### ISSUE TITLE
No way to add query parameters without a value

### ISSUE THREAD

**Issue by wichert** [Pylons/pyramid#1119]
I occasionally need to put a hint in the query string for a URL, which is essentially a parameter without a value. This can be important to provide information to javascript or as a hint to GA. For example I may need to use ``http://localhost/dashboard?new-user`` as URL when I redirect a new user to the dashboard after completing registration.

Intuitively I expected this to work:
```python
return HTTPFound(request.route_url('dashboard', _query={'new-user': None}))
```

but that returns ``/dashboard?new-user=None`` which is not very pretty.

**Comment by bertjwregeer** [comment]
This issue has been resolved in #1183. `request.route_url('main', _query='new-user')` will render the URL appropriately.
