### ISSUE TITLE
Authentication cookie is randomly disappearing on Chrome

### ISSUE THREAD

**Issue by mastergberry** [Pylons/pyramid#1151]
Hi.  I am experiencing a bug on my website (production) where the cookie for authentication (auth_tkt) in Chrome is randomly disappearing after a few hours.  I can say that this is not happening on my local dev environment though, it might have something to do with the way uwsgi/nginx is creating the cookie. I find it odd that this is only happening on Chrome though.  I am on Version 30.0.1599.69 of Chrome for debugging purposes.  The website in question is www.badlion.net  I should also mention that other users have reported this to me as well.

I have attached what I am currently using for login/authentication to provide as much detail as to what I am doing as possible.

```python
# In __init__.py

 authn_policy = AuthTktAuthenticationPolicy(
        settings['password_secret'], callback=getUserRole, reissue_time=3600)
authz_policy = ACLAuthorizationPolicy()

    my_session_factory = UnencryptedCookieSessionFactoryConfig(settings['session_secret'])
config = Configurator(settings=settings, session_factory=my_session_factory,
                          root_factory='.security.auth.RootFactory')

config.set_authentication_policy(authn_policy)
config.set_authorization_policy(authz_policy)
```

```python
# In my login view

@view_config(route_name='login')
    def view_login(self):
        self.title = "Login | Badlion Network"
        # Already logged in
        if self.loggedIn:
            return HTTPFound(location='/')

        params = self.request.params
        loginForm = LoginForm(params)
        if 'form.submitted' not in params:
            previousURL = self.getPreviousRoute('login')
            return HTTPFound(location=previousURL)

        user = getUserByUsername(params['username'])
        if user is None:
            self.session['error'] = "Invalid login."
            previousURL = self.getPreviousRoute('login')
            return HTTPFound(location=previousURL)
        if not user.active:
            self.session['error'] = "Account not activated yet."
            previousURL = self.getPreviousRoute('login')
            return HTTPFound(location=previousURL)

        if checkUserPassword(user, params['password']):
            maxAge = 86400 * 365 if 'remember_me' in params else None
            headers = remember(self.request, params['username'], max_age=maxAge)
            import pdb; pdb.set_trace()
            user.last_login = int(time. time())
            user.logins += 1
            previousURL = self.getPreviousRoute('login')
            # First time logging in, go to home page. TODO: Fix to be nicer system?
            if user.logins == 1:
                return HTTPFound(location=self.request.route_url('home'), headers=headers)
            return HTTPFound(location=previousURL, headers=headers)

        self.session['error'] = "Invalid login, try again."
        previousURL = self.getPreviousRoute('login')
        return HTTPFound(location=self.request.route_url('home'))
```

```python
# In my views/__init__.py

attemptToLogin = authenticated_userid(self.request)
        if attemptToLogin is not None:
            self.loggedIn = True
            self.user = getUserByUsername(attemptToLogin)
            self.username = self.user.username
            self.uid = self.user.id
```

I hope that this is a bug on Chrome's or my end and not the Pyramid side, so please feel free to yell at me if I am doing something dumb that is breaking it.  As previously mentioned it works on dev, not on production, safari/firefox don't have issues on production.

Thanks.

**Comment by bertjwregeer** [comment]
Have you been able to figure out anything more regarding this issue?

**Comment by mastergberry** [comment]
Nope sadly. Still have the issue on each reboot.

**Comment by bertjwregeer** [comment]
Are you sure that the cookie you are setting is not a session based cookie? If you fully close Chrome and restart it does the same thing happen?

**Comment by mastergberry** [comment]
Yeah if i fully close Chrome it seems to happen also. I guess it is a session based cookie? The code above is still accurate as to what I am doing (with a few small tweaks because of the newer versions)

**Comment by bertjwregeer** [comment]
Alright, mystery solved:

http://docs.pylonsproject.org/projects/pyramid/en/latest/api/authentication.html

`max_age`.

Without that it becomes a session cookie.

**Comment by mastergberry** [comment]
`max_age = 86400 * 365 if remember_me else None
headers = remember(self.request, user.uuid, max_age=max_age)
return HTTPFound(location=self.request.route_url('home'), headers=headers)`

I did add the max_age to the Authentication Policy as you suggested. Did not affect it. I already had the above code also in the login section of my website setting the max_age. Using the "Edit cookie" plugin on Chrome it shows that the cookie is set for a year. As mentioned though it dies when the browser is reset.

**Comment by bertjwregeer** [comment]
At that point it is out of the hands of Pyramid. The cookie is set for a year, it should be good to go.

**Comment by mastergberry** [comment]
Where would it be then?

**Comment by bertjwregeer** [comment]
Your cookie gets set for a year, so that should mean Chrome should store it for that long. However I noticed another snag, you have reissue_time set to 3600 seconds, without max_age.

While the original cookie is set or a year (because you set the max_age for a year when the user logs in) any cookies that are re-issued after the reissue_timeout (1 hour basically) are going to be set with max_age set to the default (i.e. None):

https://github.com/Pylons/pyramid/blob/master/pyramid/authentication.py#L935

I bet if you log in, verify that a cookie has been set for a year, and then close your browser and restart your browser immediately and browse back to the site you'll still be logged in. However if you wait a hour that won't be the case.

If that is not what happens, and your site is actually correctly setting the cookie to a year from now, something else is going on with your browser.

**Comment by bertjwregeer** [comment]
I'd check your site myself, however I don't have MineCraft. Feel free to send me a message on IRC with a test account if you'd like me to verify for you.

**Comment by mastergberry** [comment]
With my above testing I was logging in with remember_me enabled and then closing browser right after and restarting it. Then I was no longer logged in (not waiting the hour).

I also am in the IRC and made a test account for you to toy around with. Send me a message.

**Comment by bertjwregeer** [comment]
This is not an issue with Pyramid.
