### ISSUE TITLE
Image missing on Traversal Docs on versions except 1.4

### ISSUE THREAD

**Issue by chungwong** [Pylons/pyramid#1194]
just a minor thing. 
http://docs.pylonsproject.org/projects/pyramid/en/1.5-branch/narr/traversal.html#a-description-of-the-traversal-algorithm

the image tag on versions !1.4 is 
img alt="narr/resourcetreetraverser.png" src="narr/resourcetreetraverser.png"
while 1.4 is pointing to 
img alt="../_images/resourcetreetraverser.png" src="../_images/resourcetreetraverser.png"

**Comment by mcdonc** [comment]
This appears to have been fixed in 1.5 and later.
