### ISSUE TITLE
Make class of Localizer configurable

### ISSUE THREAD

**Issue by t-8ch** [Pylons/pyramid#1203]
`pyramid.i18n.make_localizer()` uses a old version of a `Translations` class extracted from babel.
The new version of babel also added support for `pgettext()` and related methods.

It would be nice to be able to specify a custom `Translations` class which is to be used by `make_localizer()`.
This would also allow subclassing to overwrite the default domain.

**Comment by psyclip-r** [comment]
Actually it should be important for i18n. There's no way to pass the context at all. Which is as important as pluralization.
Flask-Babel normally provides pgettext too.

**Comment by mmerickel** [comment]
Improvements to the localizer class would probably be accepted but we'd need to see similar PRs to improve translationstring's support for these methods as well.
