### ISSUE TITLE
pyramid should have a MANIFEST.in

### ISSUE THREAD

**Issue by mgedmin** [Pylons/pyramid#121]
Today a user on IRC was complaining that he installed Pyramid, but all the paster templates were missing.  Further investigation lead to the discovery that he downloaded a tarball of 1.0 directly from github rather than PyPI.  This tarball has no package metadata.  Compare

```
cd /tmp
wget http://pypi.python.org/packages/source/p/pyramid/pyramid-1.0.tar.gz
tar xvzf pyramid-1.0.tar.gz
wget https://github.com/Pylons/pyramid/tarball/1.0 --no-check-certificate -O pyramid-github-export.tar.gz
tar xvzf pyramid-github-export.tar.gz
diff -ur pyramid-1.0 Pylons-pyramid-699da1d | diffstat
```

You'll see that pyramid.egg-info is missing in the github export.  Without it, and without a .git/ folder, and without a MANIFEST.in, setuptools has no clue what files it should include, so if you attempt something like

```
cd Pylons-pyramid-699da1d
python setup.py install
```

(as the original user did), you'll end up without paster_templates (and a few test support files).  You can see which files would be missing with

```
cd /tmp/Pylons-pyramid-699da1d
python setup.py sdist
cd dist
tar xvzf pyramid-1.0.tar.gz
cd /tmp
diff -ur pyramid-1.0 Pylons-pyramid-699da1d/dist/pyramid-1.0 | diffstat
```

It'd be nice to have a MANIFEST.in to prevent this mind of misunderstandings.

**Comment by tisdall** [comment]
as per @mmerickel request to bring the conversation back here:
```
# if a git repo then add setuptools-git as a setup_requires
if os.path.isdir(os.path.join(here, '.git')):
    setupkw['setup_requires'] = ['setuptools_git']
```

Taken from my PR on deform (obviously the setup() call needs to be changed to setup(**setupkw) for this to work, but hopefully you get the concept).

**Comment by tisdall** [comment]
It seems like a manifest template kind of solves this issue too, no?  A list of wildcards to generate a MANIFEST when its needed?  Tell it to include everything and prune out just the files we don't want to include...  Then new files of any type will be added by default.

**Comment by tisdall** [comment]
What's wrong with the following MANIFEST.in:
```
include *
recursive-include * *
```

That seems to include everything except hidden "." files.

**Comment by tisdall** [comment]
Okay, I see the issue now... You end up including `__pycache__` `.pyc` etc.

Still, I think the patch I mentioned is a good compromise to allow people to install straight from github.  At the very least, it avoids yet another person from getting stung by this re-occurring issue.

**Comment by stevepiercy** [comment]
Per https://github.com/Pylons/pyramid/issues/121#issuecomment-3510076 there is now a better presentation of the process in https://github.com/Pylons/pylonshq/pull/72

This should also push users to officially supported channels.

**Comment by mmerickel** [comment]
Just since I found @mgedmin's https://github.com/mgedmin/check-manifest that it might be worthwhile to revisit this issue. There are real annoyances with not including a MANIFEST.in such as requiring the guards around the README/CHANGES files in the setup.py which mean that tox fails to build a correct sdist. We could add the check to our tox configuration along with our flake8 (and possibly a check to verify our readme syntax in the future) and enable it on travis. The idea would be that anything not included in the MANIFEST or in the ignore configuration would error and we would need to decide whether to ignore it or include it.

**Comment by mmerickel** [comment]
Whelp Pyramid has a `MANIFEST.in` now... thanks for the `check-manifest` tool @mgedmin.
