### ISSUE TITLE
Memory leak per request with add_request_method and resource_url

### ISSUE THREAD

**Issue by murrayreadccdc** [Pylons/pyramid#1212]
I am finding a continuous memory growth in my Pyramid application when I make repeated requests to it. This is happening both with pserve on windows and apache on linux.

A test pserve process died due to memory exhaustion after 85 minutes with 1871MB allocated under a load of up to 40 requests per second.

I have managed to reproduce the issue in a minimal pyramid application, based on the standard hello world app. There are two key lines added to this, which cause the problem. First "config.add_request_method(db, property=True)" - if this is used with either property=True or reify=True, you get the leak, otherwise not. Second "url = request.resource_url(request.context)" - without this call to get a resource url, there is no leak. Here is the full test app:

```
from wsgiref.simple_server import make_server
from pyramid.config import Configurator
from pyramid.response import Response

def hello_world(request):
    url = request.resource_url(request.context)
    return Response('Hello world! ' + url)

def db(request):
    return None

if __name__ == '__main__':
    config = Configurator()
    config.add_route('hello', '/')
    config.add_view(hello_world, route_name='hello')
    config.add_request_method(db, property=True)
    app = config.make_wsgi_app()
    server = make_server('0.0.0.0', 8080, app)
    server.serve_forever()
```

I am using the following test client app to drive the server:

```
import urllib2
import sys
import time

uri = sys.argv[1]

count = 0
while True:
    f = urllib2.urlopen(uri)
    print count, len(f.read())
    f.close()
    count += 1
    time.sleep(0.01)
```

Monitoring the memory use in the pyramid app, it increases by 1MB every few seconds. This rate stays approximately constant.

**Comment by bertjwregeer** [comment]
@murrayreadccdc Could you provide more information on your memory leak?

**Comment by murrayreadccdc** [comment]
@bertjwregeer - it's been a year since I look at this, but my last note on this issue was "Using Pyramid 1.5b1 on Linux, I am not seeing significant evidence of memory leak now."
