### ISSUE TITLE
FileResponse deadlocks with gunicorn WSGI server (eventlet/greenlets)

### ISSUE THREAD

**Issue by bkeroack** [Pylons/pyramid#1214]
Using gunicorn 18.0 as the WSGI server (Python 2.7.4), serving large files (>~800kB) with pyramid.response.FileResponse does not work.

The content-length is sent correctly along with the first ~800 kB of the file, but then transfer stops and sits until the client times out. I'm guessing the sending thread deadlocks somehow on I/O after the initial buffer is sent and never finishes.

Switching to waitress makes everything work normally.

```
@view_config(name="myview", renderer='json')
def MyView(request):
    return pyramid.response.FileResponse(FILENAME, request=request, cache_max_age=0)
```

development.ini:
```
[server:main]
use = egg:gunicorn#main
host = 0.0.0.0
port = 6543
worker_class = eventlet
timeout = 600
workers = 5
```

**Comment by mmerickel** [comment]
This sounds like an eventlet bug more than anything. The `FileIter` being used underneath the hood is a very simple shim around opening a file and reading chunks.
