### ISSUE TITLE
pserve --stop-daemon does not work with --monitor-restart

### ISSUE THREAD

**Issue by arobinson** [Pylons/pyramid#1216]
If pserve is started with --monitor-restart, the command is restarted when pserve --stop-daemon is run and the pid file's process ID is not updated. The only way to seem to stop it is using kill on the process ID instead of relying on pserve.

**Comment by piotr-dobrogost** [comment]
Just a note that you also use --reload which according to issue #912 is not supported when using --daemon.

**Comment by bertjwregeer** [comment]
@mmerickel and I have fixed the use of `--monitor-restart` with `--daemon`. Don't think it will work with `--reload`.

Either way, this feature is being deprecated.
