### ISSUE TITLE
1.4 installation documention not current on docs site, but current on github

### ISSUE THREAD

**Issue by keresian** [Pylons/pyramid#1217]
The 1.4 installation file specifically says: $ bin/easy_install "pyramid==|release|"

the ==|release|" portion of the document is not pulling through to http://docs.pylonsproject.org/projects/pyramid/en/1.4-branch/narr/install.html#installing-pyramid-on-a-unix-system

Without that == section, you end up installing 1.5 by default.

**Comment by mmerickel** [comment]
This is rendering properly on the supported 1.5/1.6 branches as well as latest and master.

**Comment by stevepiercy** [comment]
...and 1.4 branch renders fine, too.
http://docs.pylonsproject.org/projects/pyramid/en/1.4-branch/narr/install.html#installing-pyramid-into-the-virtual-python-environment
