### ISSUE TITLE
Memory leak when logging in Pyramid app

### ISSUE THREAD

**Issue by murrayreadccdc** [Pylons/pyramid#1234]
We are seeing a memory leak when we use logging in a Pyramid app. It happens when a view writes to a log file after logging has been configured from settings. I've created a minimal test case based on the starter scaffold, with the following modified version of __ init __.py

```
from pyramid.config import Configurator
from pyramid.response import Response
import logging

def hello_world(request):
    logging.warning('Watch out!')
    return Response('Hello world! ')

def main(global_config, **settings):
    """ This function returns a Pyramid WSGI application.
    """

    config = Configurator(settings=settings)
    config.add_route('hello', '/')
    config.add_view(hello_world, route_name='hello')
    app = config.make_wsgi_app()

    return app
```

No other change is needed (development.ini is unchanged).

The client app driving the test is the same as for 1212

```
import urllib2
import sys
import time

uri = sys.argv[1]

count = 0
while True:
    f = urllib2.urlopen(uri)
    print count, len(f.read())
    f.close()
    count += 1
    time.sleep(0.01)
```

I have integrated gctween to this, which reports the following per request:

```
GC report for /
===============
LogRecord                      1 +
Response                       1 +
dict                           1 +
instance                       1 +
list                           2 +
```

We've told Chris about this, but I raised this issue to track it.

**Comment by dfroger** [comment]
Is there any news about this bug? Is it now fixed?

It seems that `LogRecord`s are accumulated and never handled, does Pyramid do something special with log handlers? Any place I can start to investigate from?

**Comment by dfroger** [comment]
I can reproduce like this (using Python 2.7 or 3.6):

``` bash
pip install objgraph pyramid pyramid_debugtoolbar==1.0.9 pyramid_tm==0.7
```

and the script:

``` python
import sys
import logging 
from pyramid.config import Configurator
import objgraph

settings = {
    'pyramid.includes': 'pyramid_debugtoolbar',
}

logger = logging.getLogger('memleak')

config = Configurator(settings=settings)
config.scan()

for k in range(10): 
    for i in range(1000):
        logger.error('error msg')
    print(len(objgraph.by_type('LogRecord')))
```

The output is:

```
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
```

**Comment by miohtama** [comment]
I think, by definition, pyramid_debugtoolbar retains all log messages so that you can show them in the debug toolbar web interface.

Does the leak occur without pyramid_debugtoolbar? If not then this is no issue.

**Comment by dfroger** [comment]
The leak does not occur without `pyramid_debutoolbar`, however, with the lastest versions of `pyramid_debubtoolbar` and/or `pyramid_tm`, the leak does not occurs too. (ie, the script always output `0`).

So the bug, if there is any, is fixed in recent versions. It would be interesting to know where, and why a combination of specific versions `pyramid_debugtoolbar` and `pyramid_tm` that trigger the bug.

**Comment by dfroger** [comment]
Maybe [this](https://github.com/Pylons/pyramid_debugtoolbar/blob/master/CHANGES.txt#L120-L127) was the fix on `pyramid_debugtoolbar` side.

**Comment by dfroger** [comment]
If confirm the bug occur with `pyramid_debugtoolbar==2.4.1`, but no more with `2.4.2`.

**Comment by dfroger** [comment]
So I my case, the issue can be closed.
