### ISSUE TITLE
tilde (~) is encoded on AppendSlashNotFoundViewFactory 

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#1235]
a tilde is encoded on AppendSlashNotFoundViewFactory

if you visit:

```
http://127.0.0.1/~one
```

you are redirected to

```
http://127.0.0.1/%7Eone/
```

instead of

```
http://127.0.0.1/~one/
```

The two urls remain functionally equivalent.

Looking at the chain of imports, it seems that this is happening due to how webob handles BaseRequest.path , wrapping it in a call to `compat.url_quote` (which imports from the appropriate urlparse module under python 2 or 3 )

I'm not sure why ~ is quoted by urlparse. based on rfc3986, it should.  ( it wasn't according to earlier rfcs )

RFC 3398 states ( http://tools.ietf.org/html/rfc3986.html )

```
2.3.  Unreserved Characters

Characters that are allowed in a URI but do not have a reserved
purpose are called unreserved.  These include uppercase and lowercase
letters, decimal digits, hyphen, period, underscore, and tilde.

unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"

URIs that differ in the replacement of an unreserved character with
its corresponding percent-encoded US-ASCII octet are equivalent: they
identify the same resource.  However, URI comparison implementations
do not always perform normalization prior to comparison (see Section
6).  For consistency, percent-encoded octets in the ranges of ALPHA
(%41-%5A and %61-%7A), DIGIT (%30-%39), hyphen (%2D), period (%2E),
underscore (%5F), or tilde (%7E) should not be created by URI
producers and, when found in a URI, should be decoded to their
corresponding unreserved characters by URI normalizers.
```

the ~ remains normal in the environment ( PATH_INFO ) and some other webob places.  its just the encoding that has this behavior

**Comment by bertjwregeer** [comment]
This was fixed in https://github.com/Pylons/webob/pull/291
