### ISSUE TITLE
No public way to change the response factory

### ISSUE THREAD

**Issue by eevee** [Pylons/pyramid#1256]
`Request` has a `ResponseClass` class attribute, but it's not actually used by `Request.response`.  That uses the registered `IResponseFactory`.  I can change _that_ directly, but it seems like there should be a `config.set_response_factory`?

**Comment by sontek** [comment]
In #1499 we've opted to ignore `ResponseClass` and introduce `config.set_response_factory`

**Comment by mmerickel** [comment]
Fixed in #1499.
