### ISSUE TITLE
Extra concatenation in Deform usage example

### ISSUE THREAD

**Issue by sbivol** [Pylons/pyramid#1266]
The Quick Tutorial for Pyramid v1.5b1 contains a mistake when giving the contents for file forms/tutorial/wikipage_addedit.pt on lines 7 and 10.

``` python
        <link rel="stylesheet" type="text/css"
              href="${request.static_url('deform:static/' + reqt)}"/>
```

Specifically, the call to request.static_url() contains an extra concatenation. It should instead look like 

``` python
        <link rel="stylesheet" type="text/css"
              href="${request.static_url(reqt)}"/>
```

because reqt already has the form "deform:static/scripts/jquery.form-3.09.js".

**Comment by henry808** [comment]
For me this did not work without the "'deform:static/' +" before reqt in line 7 and line 10.  Maybe it is because I am using Python 2.7.6.

**Comment by stevepiercy** [comment]
@henry808 See https://github.com/Pylons/pyramid/issues/1857#issuecomment-121639164

**Comment by henry808** [comment]
Thanks for the clarification.
