### ISSUE TITLE
add PYTHONSTARTUP support to pshell

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#1299]
Currently pshell does not source any `.pystartup` file pointed to by the `PYTHONSTARTUP` environment variable. It'd be nice to support this.

https://docs.python.org/2/tutorial/interpreter.html#the-interactive-startup-file

**Comment by jessedhillon** [comment]
@pacopablo did you ever figure out why only keywords and built-ins were tab completing in pshell?
