### ISSUE TITLE
response callbacks and tweens

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#1336]
Currently response callbacks (`request.add_response_callback`) are executed after tweens.

Maybe this issue is specific to pyramid_tm, but it seems to mess with the encapsulation of the request pipeline. Let's say that a callback is added and then a retryable error occurs, and the the request is retried and the callback is added again. Now we have 2 callbacks and one is from a cancelled pipeline, yet they will both be executed right now. Can it be said that pyramid_tm should be clearing the list of callbacks?

I'm marking this as recreational because I don't have a good answer right now but wanted to talk about it.

**Comment by mmerickel** [comment]
related issues https://github.com/Pylons/pyramid_tm/issues/40 and https://github.com/Pylons/pyramid_tm/issues/41

**Comment by bertjwregeer** [comment]
For a retryable exception I would state that the request/responses should be entirely new ones, with nothing from the previous attempt attached.

**Comment by mmerickel** [comment]
Replaced by #2622.
