### ISSUE TITLE
Cannot nest dispatch applications below traversal application

### ISSUE THREAD

**Issue by dwt** [Pylons/pyramid#1350]
http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hybrid.html#hybrid-chapter lays out how to nest a traversal based application inside a dispatch based application.

However the reverse seems to be missing (or is completely undocumented).

That is, I want to mount a dispatch based application inside a traversal application.

For this to work transparently, request.route_url() and request.route_path() need to be aware of this nesting and let part of the url generation be controlled by the parent application.

Now for some use cases: In our app we have a simple dispatch based admin interface that we now would like to extend with multi language editing capabilities. Switching the admin interface over to a traversal based approach seems sensible, but is not something we would like to commit to in one run before we understand dispatch better.

Thus we had the idea that if we are able to mount the dispatch base admin application below a traversal based layer that allows choosing the language, we will not have to change much in the existing application if we can handle the internationalized access at the model layer. This could work if the traversal based language chooser sets a thread local with the currently selected language, which is then used by the model layer to bring up the right translation.

This seemed like a great first step to get our feet wet with traversal while having a quite natural and small extension to our app.

However, according to the docs this doesn't seem to be possible.

Are the docs incomplete? Is this actually possible? If not, is there a reason why this is not arbitrarily composable? It seems natural that different applications might want to be mounted in arbitrary places into each other and should not need to be aware where and how they are mounted when generating urls.

**Comment by mmerickel** [comment]
It's possible to mount wsgi applications at traversal or dispatch endpoints using `pyramid.views.wsgiapp2`. URL generation does not and never has been supported well across the WSGI app boundaries, however.

Perhaps `request.invoke_subrequest` would be helpful here for invoking another lookup step from within a view.
