### ISSUE TITLE
pcreate creates project named pyramid

### ISSUE THREAD

**Issue by sirex** [Pylons/pyramid#1357]
I just tried Pyramid using `pcreate`. `pcreate --help` says:

> Usage: pcreate [options] output_directory

So I decided to use `.` as my `output_directory`, and `pcreate` assumed, that my project name is same as name of `.` directory, which happens to be `pyramid`.

It would be great if `pcreate` would be smart enough to avoid creating project with name `pyramid`. Or at lease there should be option, to specify different project name.

How to reproduce:

    $ virtualenv pyramid
    $ cd pyramid
    $ . bin/activate
    $ pip install pyramid
    $ pcreate -s starter .
    $ python setup.py develop
    Installed /tmp/pyramid/lib/python2.7/site-packages/pyramid_mako-1.0.2-py2.7.egg
    error: Installed distribution pyramid 0.0 conflicts with requirement pyramid>=1.2dev

I think this scenario is quite common for all, who just trying Pyramid and for some of these newcomers, this can be show stopper.

**Comment by mmerickel** [comment]
Fixed by https://github.com/Pylons/pyramid/pull/1837
