### ISSUE TITLE
Tainted mode to prevent handling of unsafe User input

### ISSUE THREAD

**Issue by florianpilz** [Pylons/pyramid#1358]
Some languages, like Perl, have a tainted mode. I Python there is a scientific solution presented, but I think it's much better to incorporate a tainted mode into a web framework, since the framework knows about User input and can add some handlers "to make it clean".

I just wanted to start the discussion what you think about a tainted mode, where all user input is marked as untrusted initially and only marked methods can be used to parse the input -- all other methods will brake due to untrusted input. After the input was parsed by such a marked method it is assumed as safe and can be used anywere.

What do you think?

**Comment by mmerickel** [comment]
There's not enough info here in order to consider how this would work in Pyramid. Please be more clear about how changes to Pyramid could help here.
