### ISSUE TITLE
@view_defaults inheritance

### ISSUE THREAD

**Issue by drarmstr** [Pylons/pyramid#1382]
Currently, options specified in a @view_defaults decorator are inherited by any child classes.  However, if a @view_defaults decorator is applied to the child class, then it cancels any options from the parent class, even if a particular option was not specifically overridden in the child.  It would be nice if there was some way to specify that the parent's options should still apply, unless individually overridden, as well as the new ones specified in the child class.  Sort of like a "super" for @view_defaults.

For example:

@view_defaults(route_name='foo', context=Resource)
class Parent:
...

@view_defaults(context=OtherResource)
class Child:
...

In class Child then view configuration for context would be overridden to be OtherResource, but the route_name would be inherited from Parent.  The current default behaviour doesn't need to change if there is an additional way to specify this "super" inheritance behaviour.

**Comment by miohtama** [comment]
As related work, I created a `@view_overrides` decorator for partial overriding of parent class `view_config`.  It's basically `venusian.lift` with the optional setting overrides blended in.

You can find it here: https://bitbucket.org/websauna/websauna.viewconfig

**Comment by mmerickel** [comment]
@miohtama I'm impressed, that code is insane. I'm worried about how something like view overrides works for things like package-relative template lookups. It looks like it's overriding it to be the subclass's package instead of the parent which isn't always correct! This is a problem in general with doing these subscriptions in a base class though.

Anyway, if someone wants to implement `inherit_defaults=True` with docs please submit a PR. It should be a very simple patch.

**Comment by miohtama** [comment]
Ok, I'll look `inherit_defaults` patch, but not sure if it's going to be simple.

**Comment by bertjwregeer** [comment]
@miohtama This is what the patch should do: https://github.com/Pylons/pyramid/issues/1382#issuecomment-49190933

**Comment by mmerickel** [comment]
Yeah I think it's as simple as:

```
defaults = parent.__view_defaults__.copy()
defaults.update(child.__view_defaults__)
child.__view_defaults__ = defaults
```

**Comment by mmerickel** [comment]
Any movement on this? I might close the issue if no one wants to work on it.

**Comment by miohtama** [comment]
@mmerickel Feel free to close by me.

**Comment by bertjwregeer** [comment]
I haven't needed this myself in more recent projects.
