### ISSUE TITLE
add_request_method's name parameter must be of type str

### ISSUE THREAD

**Issue by Javex** [Pylons/pyramid#1387]
The documentation of [add_request_method](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator.add_request_method) does not state that the `name` argument must be of type `str` because it will be set as `fn.__name__`. When passing a `unicode` on Python 2 (and I suppose `byte` as Py3) as a parameter, it will raise an exception.

Probably a good idea to document this.

**Comment by mmerickel** [comment]
Fixed via #1520.
