### ISSUE TITLE
`not_` fails on `accept` predicate

### ISSUE THREAD

**Issue by Treora** [Pylons/pyramid#1391]
Not sure if it's important, but the `not_` operator does not work on the `accept` predicate for a view configuration:
```AttributeError: 'not_' object has no attribute 'lower'```
([here] is the culprit)
I haven't checked other functions or predicates, just encountered this one.

[here]: https://github.com/Pylons/pyramid/blob/3587a53dc28b8f6411816ccd7fd8fdee0d88acb4/pyramid/config/views.py#L1122

**Comment by mmerickel** [comment]
Yep, #1487 explicitly removes `not` support from accept, as it's not labelled as a predicate now.
