### ISSUE TITLE
Allow alternatives to Paste ini files to work with pshell/pserve

### ISSUE THREAD

**Issue by inklesspen** [Pylons/pyramid#1394]
At my workplace, we've "standardized" on [an alternate configuration file format](http://axialcorps.com/2014/02/06/betterconfig/). Other workplaces may want to use JSON or YAML or some such. These can basically be turned into a dict the same way ConfigParser ini files are, so why not allow specifying a config parser function? Perhaps via a prefix, the same way asset specifications can reference a different package's assets. So I could do myfile.ini for the standard functionality, or json:myfile.json to specify that it's a json file. That way I can still use all the nice Pyramid tooling.

(Somewhat related to issue #560.)

**Comment by mmerickel** [comment]
related #2419

**Comment by mmerickel** [comment]
Closed via https://github.com/Pylons/pyramid/pull/2985
