### ISSUE TITLE
using Accept-Language in the default locale negotiator

### ISSUE THREAD

**Issue by tisdall** [Pylons/pyramid#1398]
Is there a rational behind not using the `Accept-Language` values in a HTTP request as a fallback in the `default_locale_negotiator`?  I understand the preference of using a `_LOCALE_` value over the `Accept-Language` as there seems to be issues with people properly setting that value, but why not use that value when there's no `_LOCALE_` set?  I think a lot of browsers set that browser's language automatically on install based on the OS's settings so it typically defaults to a reasonable value.

I wanted to see if there was some reason for this before submitting any sort of pull request.

**Comment by ztane** [comment]
We did the language list approach exactly like that (available_languages in .ini); however there is a problem with the matching that for example Chinese locales have complicated names, and we needed to match everything that could possibly come from the client with whatever our locale names were and it wasn't eventually pretty at all.

**Comment by mmerickel** [comment]
This definitely belongs in a recipe instead of in core but it'd be really nice if someone could write up an example for the cookbook or even as part of the i18n chapter. For example update  http://docs.pylonsproject.org/projects/pyramid/en/1.6-branch/narr/i18n.html#detecting-available-languages

with a snippet negotiator that used `request.accept_language.best_match()` as you're describing and then fallback to `default_locale_negotiator` if no match was found.

**Comment by ztane** [comment]
I do not have time now, but here is a starter for someone:

```
#: Mapping of language codes send by browsers to supported dialects.
BROWSER_LANGUAGES = {
    'en-ca': 'en_GB',
    'en-gb': 'en_GB',
    'en-us': 'en_US',
    'fi':    'fi_FI',
    'fi-fi': 'fi_FI',
    'en':    'en_GB',
    'zh':    'zh_CN',
    'zh-cn': 'zh_CN',
    'zh-hk': 'zh_HK',
    'zh-tw': 'zh_TW'
}


def locale_negotiator(request):
    """Locale negotiator for pyramid views.

This version differs from Pyramid's :py:func:`default_locale_negotiator
<pyramid.i18n.default_locale_negotiator>` in that it prefers the preferred
locale of the currently authenticated user, and has a fallback to the
preferred languages from browser.
"""
    locale = default_locale_negotiator(request)
    if locale is None and request.accept_language:
        locale = request.accept_language.best_match(BROWSER_LANGUAGES.keys()).lower()

        # default to en_GB as it does not have silly units etc...
        locale = BROWSER_LANGUAGES.get(locale, 'en_GB')
        request._LOCALE_ = locale

    return locale
```

**Comment by mmerickel** [comment]
It's been a while but I think that adding support for `pyramid.available_languages` is a fine idea. The PR would need to support the current behavior when this setting is not configured and would need to come with appropriate docs and tests. If there's no one interested in implementing this I'll probably just close this issue.
