### ISSUE TITLE
invoke_subrequest fails when SCRIPT_NAME is set

### ISSUE THREAD

**Issue by lieryan** [Pylons/pyramid#1434]
First, a refresher on WSGI. SCRIPT_NAME is used in situations where an application server lives under a URL subpath in a set up with a reverse proxy. This is set in waitress by [specifying url_prefix](http://waitress.readthedocs.org/en/latest/#using-url-prefix-to-influence-script-name-and-path-info):

> Setting this to any value except the empty string will cause the WSGI SCRIPT_NAME
> value to be that value, minus any trailing slashes you add, and it will cause the
> PATH_INFO of any request which is prefixed with this value to be stripped of the
> prefix. This is useful in proxying scenarios where you wish to forward all traffic to
> a Waitress server but need URLs generated by downstream applications to be
> prefixed with a particular path segment.

When a Pyramid app that can be used as both a standalone app and a reusable app invoke_subrequest the following Pyramid app produces a 404 instead of the expected result because route_url generates an absolute with the prefix path but invoke_subrequest expects a path without the prefix:

``` python
from pyramid.config import Configurator
from pyramid.response import Response
from pyramid.request import Request
from waitress import serve

def root(request):
    location = request.route_url('other')
    subrequest = Request.blank(location, base_url=request.script_name)
    resp = request.invoke_subrequest(subrequest)
    return resp


def other(request):
    return Response('hello world')


def main():
    config = Configurator()

    config.add_route('root', '/')
    config.add_view(root, route_name='root')

    config.add_route('other', '/other')
    config.add_view(other, route_name='other')

    return config.make_wsgi_app()

application = main()
serve(application, host='0.0.0.0', port=8080, url_prefix='prfx')
```

The workaround is fairly simple but I believe this probably should be in Pyramid itself:

``` python
subrequest.script_name = request.script_name
subrequest.path_info = subrequest.path_info[len(request.script_name):]
```

There are several other ways I can think of this can be fixed:
1. Have a parameter in `request.route_url('viewname', _script_name=False)` to generate route without SCRIPT_NAME
2. Have a parameter in `Request.blank(url, script_name=request.script_name)` to strip the prefix from the request or (should base_url= be changed to do this?)
3. Have invoke_subrequest strip SCRIPT_NAME from PATH_INFO before making the subrequest

**Comment by slomo** [comment]
The suggested solution doesn't work if the path comes from outside the application. In my case I have a JS-Frontend which hands back in urls generated by other requests. I then want to perform a subrequest with those urls, which works until is set the Script-Name header.
