### ISSUE TITLE
Document caching headers that should be implemented when using cookies

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid#1443]
As discussed in #1342 and #1348 users should probably implement the "Vary:" header so that caches that sit between Pyramid and the user knows that it should return the cached result based upon the value of the cookie.

This should be documented and possibly some cookbook entries should be added so that users can do the right thing.

**Comment by mcdonc** [comment]
Should we defer this one until we add better support to WebOb?

**Comment by bertjwregeer** [comment]
I'd be okay with that.

**Comment by mmerickel** [comment]
Closing in favor of https://github.com/Pylons/pyramid/issues/1845.
