### ISSUE TITLE
mod_wsgi deployment should be updated to use pip and verified

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid#1454]
http://docs.pylonsproject.org/projects/pyramid/en/latest/tutorials/modwsgi/index.html

Is in need of an overhaul, and verification that it works. Ran across a couple of questions online on how to accomplish this, and most of them ended up switching to proxying directly to waitress or using uWSGI with nginx.

**Comment by pauleveritt** [comment]
It looks like this ticket started as simplifying the modwsgi install and turned into a pip discussion. On the former, perhaps the introduction of mod_wsgi-express can give the needed entry point. I'll give it a look.

On the latter, I need to read a little more on switching to pip. packaging.python.org (which is 503 at the moment) claims that, if you are *making* a package, put your dependencies in setup.py. The quick tutorial's approach requires a package which thus requires setup.py. However, the examples outside of the tutorial can look at switching.

I think we should make a new ticket focused on pip, assigned to me, and talk about it there. I recognize that I'm signing myself up for some Windows joy.

**Comment by stevepiercy** [comment]
Closed by #2438.
