### ISSUE TITLE
404 errors in the docs

### ISSUE THREAD

**Issue by schmilblick** [Pylons/pyramid#1476]
You should be able to reproduce it by retracing my steps:
* Google for: pyramid render_to_response, click the first link that should be: http://docs.pylonsproject.org/docs/pyramid/en/latest/api/renderers.html 
* Use the version changer popup thing in the lower right corner: https://www.dropbox.com/s/b7349p3co1xm66w/Screenshot%202014-11-27%2008.39.52.png?dl=0 I clicked on the 1.4-branch which results in a 404 on this URL: http://docs.pylonsproject.org/en/1.4-branch/api/renderers.html 

* Tried to remedy it by clicking the "The Pyramid Web Framework v1.5.2"-breadcrumb to get to the docs front page, but using the version changer popup there renders the same error: http://docs.pylonsproject.org/en/1.4-branch/

If I prefix the URL paths with /projects/pyramid/ it works as expected: http://docs.pylonsproject.org/projects/pyramid/en/1.4-branch/api/renderers.html

**Comment by mmerickel** [comment]
The issue on RTD was fixed, but it appears this is a separate bug on RTD.

**Comment by bertjwregeer** [comment]
If this is still an issue please respond, otherwise I'm closing this ticket.
