### ISSUE TITLE
add_static_view does not accept decorator argument

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid#1486]
It could be handy to use the same `decorator`'s that can be used on `add_view` with `add_static_view`, for example for custom handling of adding headers after a response has been rendered.

For example, this came up in this StackOverflow question: http://stackoverflow.com/questions/24854300/is-it-possible-аdd-http-header-x-accel-expires-in-add-view-add-static-view-from/27467911#27467911

I wonder though if maybe there is a better way to set headers for specific views only (I would have thought NewResponse, but that is not nearly as good as a location as a view decorator that can be applied just for some views).

The static view gets turned into an `add_view` here: https://github.com/Pylons/pyramid/blob/master/pyramid/config/views.py#L2020 and does not seem to take into account any of the `**extra` arguments that may have been passed.

**Comment by wjehenddher** [comment]
Thank you. 

We ran into this issue when switched to nginx and https proxying our pyramid server.

It seems like replacing `request.static_url(...` with `request.static_path(` within the chameleon templates solved the problem. Although, we still need to test .css files including `url(` directives.

**Comment by mmerickel** [comment]
@wjehenddher your issues sound like a misconfiguration in your stack if your app is generating the wrong urls. You need to look at some options for telling pyramid more about the non-proxied request by having nginx and your wsgi app work together.

http://docs.pylonsproject.org/projects/waitress/en/latest/#using-behind-a-reverse-proxy

**Comment by wjehenddher** [comment]
Thank you, @mmerickel 

We will take a look.  Our system is only meant to support https. Our config is pretty much the following:
    
    http://pyramid-cookbook.readthedocs.org/en/latest/deployment/nginx.html

I do see that we are using `proxy_set_header Host $http_host;` instead of `proxy_set_header Host $host;` as recommended by your citation. 

Thanks again.

**Comment by mmerickel** [comment]
@bertjwregeer if you want to submit a PR that pops `decorator` from the stack and passes it to `add_view` that's fine but I think it has very limited use.

**Comment by bertjwregeer** [comment]
No, instead I am going to use view derivations, and I'll make sure that `add_static_view` takes those into account.

**Comment by bertjwregeer** [comment]
Closing in favour of #2021
