### ISSUE TITLE
Add canonical_url to docs

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#1514]
In IRC, we discovered that RTD does not correctly insert a canonical URL html link tag. @mmerickel filed a ticket with RTD https://github.com/rtfd/readthedocs.org/issues/1108. When that issue is fixed, then we can close this placeholder issue.

If we get impatient, we can insert `canonical_url` and its value:
https://github.com/Pylons/pyramid/blob/master/docs/conf.py#L160

...but we would rather not maintain that. Backporting is not fun.

**Comment by mmerickel** [comment]
This has been fixed in RTD.
