### ISSUE TITLE
add_request_method should work in unit tests

### ISSUE THREAD

**Issue by rightaway** [Pylons/pyramid#1521]
I've got request.user calls scattered throughout my views as described in http://pyramid-cookbook.readthedocs.org/en/latest/auth/user_object.html. Unit tests fail since DummyRequest doesn't have a user attribute. So I tried calling `self.config.add_request_method(get_user, 'user', reify=True)` after `self.config = testing.setUp()` in the setUp method of the test classes (to initialize it for every test function), but I still get errors saying that DummyRequest doesn't contain user. Making this possible would make writing tests cleaner.

**Comment by mmerickel** [comment]
There's no magic here, the `DummyRequest` is a dumb object with no relationship or knowledge of the config, and doesn't support many of those methods. If you'd like the `DummyRequest` to have a `user` then give it one.

```python
req = DummyRequest()
req.user = User()
```

**Comment by mardiros** [comment]
Because google has indexed this page for "pyramid add_request_method DummyRequest"
and actually it helps a lot to no that there is no magic.

Here is  a way to inject properties that come from the configurator.

```
@pytest.fixture
def dummy_request(config: Configurator, params=None):
    params = params or {}
    req = DummyRequest(config=config, **params.get('request', {}))
    ext = config.registry.queryUtility(IRequestExtensions)
    for key, val in ext.descriptors.items():
        setattr(req.__class__, key, val)
    yield req
    testing.tearDown()
```

from commit https://github.com/mardiros/pyramid-blacksmith/commit/997765c3311bc4f5b9ede3b021d5c7a0880757cb

**Comment by mmerickel** [comment]
There is an api for this already called ‘apply_request_exrensions(req, registry=config.registry)’

**Comment by mardiros** [comment]
https://github.com/mardiros/pyramid-blacksmith/commit/4f5fad6d220b7988c6763defe3096010f044e1dd

Didn't aware. Nice tips, thanks
