### ISSUE TITLE
invoke_subrequest not available on DummyRequest

### ISSUE THREAD

**Issue by ismail-s** [Pylons/pyramid#1527]
I'm running a blog atm using pyramid. I have a homepage that displays the contents of the latest post, but without redirecting to that page. The code for that is:

```python
@view_config(route_name = 'home', renderer = 'templates/post.mako')
def home(request):
    postname = DBSession.query(Post).\
                order_by(desc(Post.created)).first().name
    request.matchdict['postname'] = postname
    return view_post(request)
```

This is tested by the following code:

```python
@pytest.fixture
def pyramid_req():
    return testing.DummyRequest()

@pytest.fixture
def pyramid_config(mydb, request):
    # mydb is a DBSession object (see sqlalchemy docs)
    config = testing.setUp()
    add_routes(config)
    mydb.begin(subtransactions = True)
    def fin():
        testing.tearDown()
        mydb.rollback()
    request.addfinalizer(fin)
    return config

class Test_home:
    def test_success(self, pyramid_config, pyramid_req):
        response = views.home(pyramid_req)
        # And then there's a few asserts to make sure the response is correct
```

If I change the view to use subrequests as so:

```python
from pyramid.request import Request
@view_config(route_name = 'home')
#, renderer = 'templates/post.mako')
def home(request):
    # Get the most recent post. This maybe should use invoke_subrequest,
    # but for the moment it works fine.
    postname = DBSession.query(Post).\
                order_by(desc(Post.created)).first().name
    #request.matchdict['postname'] = postname
    subrequest = Request.blank('/{}'.format(postname))
    return request.invoke_subrequest(subrequest)
```

then this test fails with:

```python
self = <myblog.tests.Test_home object at 0x00000000047AADA0>
pyramid_config = <pyramid.config.Configurator object at 0x00000000048CEA90>
pyramid_req = <pyramid.testing.DummyRequest object at 0x0000000004BEDC18>

    def test_success(self, pyramid_config, pyramid_req):
>       response = views.home(pyramid_req)

myblog\tests.py:79:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

request = <pyramid.testing.DummyRequest object at 0x0000000004BEDC18>

    @view_config(route_name = 'home')
    #, renderer = 'templates/post.mako')
    def home(request):
        # Get the most recent post. This maybe should use invoke_subrequest,
        # but for the moment it works fine.
        postname = DBSession.query(Post).\
                    order_by(desc(Post.created)).first().name
        #request.matchdict['postname'] = postname
        subrequest = Request.blank('/{}'.format(postname))
>       return request.invoke_subrequest(subrequest)
E       AttributeError: 'DummyRequest' object has no attribute 'invoke_subrequest'
```

Is there a way of getting a dummy request object with invoke_subrequest on it?

And before you ask: I also have functional tests that work fine, but there are definitely reasons for having unit tests eg testing a function that isn't a view but receives a request object and uses invoke_subrequest.

**Comment by tseaver** [comment]
If returning the result of `view_post` works, that is actually preferred over using a subrequest.  The [subrequest docs](http://docs.pylonsproject.org/docs/pyramid/en/latest/narr/subrequest.html) say:

> Being able to unconditionally obtain a response object by invoking a view callable indirectly is the main advantage to using pyramid.request.Request.invoke_subrequest() instead of simply importing a view callable and executing it directly. Note that there's not much advantage to invoking a view using a subrequest if you can invoke a view callable directly. Subrequests are slower and are less convenient if you actually do want just the literal information returned by a function that happens to be a view callable.

At the implementation level, `invoke_subrequest` is not defined on the `Request` class at all:  instead, the `Router` copies its own bound `invoke_subrequest` method to the request *instance* during routing.  So, you could do the same in your test (or even a dummy implementation).
