### ISSUE TITLE
invoke_subrequest seems to get rid of port in url

### ISSUE THREAD

**Issue by ismail-s** [Pylons/pyramid#1528]
This follows on from #1527.

I have a view setup as in that issue:

```python
from pyramid.request import Request
@view_config(route_name = 'home')
#, renderer = 'templates/post.mako')
def home(request):
    # Get the most recent post. This maybe should use invoke_subrequest,
    # but for the moment it works fine.
    postname = DBSession.query(Post).\
                order_by(desc(Post.created)).first().name
    #request.matchdict['postname'] = postname
    subrequest = Request.blank('/{}'.format(postname))
    return request.invoke_subrequest(subrequest)
```

but when I serve it on localhost:6545, then all the links generated in the subrequest by requst.route_url calls are of the format localhost/some_text_here as opposed to localhost:6545/some_text_here.

Needless to say, this means the links don't work. This isn't an issue on my production site, but is still an issue when serving on non-standard ports. If there is a way of solving this, it would also serve well to update the example code in the docs with this.

## Additional info

From using debug toolbar and inspecting variables, the request object within the view called by the subrequest looks like:

```<Request at 0x614a080 GET http://localhost/new%20page>```

whereas just before calling the subrequest, the request object looks like:
```<Request at 0x6120cf8 GET http://localhost:6545/>```
and the subrequest object:
```<Request at 0x614a080 GET http://localhost/new%20page>```

So maybe I need to configure the port during Request.blank() . But how? And shouldn't the docs be updated with this?

**Comment by tseaver** [comment]
You need to pass in the `environ` of the source request when creating the new one, e.g.:

    subrequest = Request.blank('/{}'.format(postname), environ=request.environ)

**Comment by ismail-s** [comment]
Ok, thanks. Especially for the quick reply too.
