### ISSUE TITLE
Provide clarity around HTTPNotFound and the Not Found view

### ISSUE THREAD

**Issue by inklesspen** [Pylons/pyramid#1531]
Users can either raise the HTTPNotFound exception, or return it, since it's also a Response subclass. However, returning it does not interact with the Not Found view machinery. If it's impractical to let returning it trigger the Not Found View, I think the Hooks docs should be explicit that only raised HTTPNotFoundViews are handled through that machinery.
# pyramid IRC log:

```
< FreqLabs> Hi, I'm trying to render a custom 404 page. Defined a vew callable with @notfound_view_config but it doesn't seem to have any effect. How can I figure out what's going on?
<inklesspen> FreqLabs: recommend you use pviews
< FreqLabs> oh that sorta helped
< FreqLabs> turns out 404 works if I request a url that doesn't route, but I'm returning HTTPNotFound() from views and thats when my callable is skipped
< FreqLabs> is it better to raise HTTPNotFound() instead of returning it?
<inklesspen> probably.
<inklesspen> it's possible to return it; in that case it acts as a response.
<inklesspen> i think it ought to be detected anyway, though
< FreqLabs> wooo, raising instead of returning hooks my callable
```

**Comment by mmerickel** [comment]
It seems reasonable to me to update the docs, but having this behavior only upon exceptions is intended. If you need a global hook for any 404 response then consider a tween or middleware.
