### ISSUE TITLE
narrative docs on Predicate Factories are incorrect

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#1549]
see https://groups.google.com/forum/#!topic/pylons-discuss/eBnFBw6fqp0

**Comment by stevepiercy** [comment]
@jvanasco a summary would be better, or a PR would be best. I have a hard time parsing the discussion thread to extract which file needs to be corrected, and what would correct it.

**Comment by jvanasco** [comment]
I'm only stubbing this for tracking.

The issue is in regards to Predicate Factories and these lines:

> The __call__ method of a predicate factory must accept a resource (context) and a request, and must return True or False. It is the "meat" of the predicate.
> You can use the same predicate factory as both a view predicate and as a route predicate, but you'll need to call add_view_predicate and add_route_predicate separately with the same factory.

Michael Merickel states:

> Basically, the docs are wrong about this and what I said is correct. I  hope that helps. My explanation should make sense as well. There is no  context when matching a route because traversal has not occurred yet,  and the default predicates available on routes and views are not the 
same. They are documented in their respective apis (config.add_view vs  config.add_route).
