### ISSUE TITLE
pserve --daemon fails with "Bad file descriptor on the use of os.urandom()"

### ISSUE THREAD

**Issue by zart** [Pylons/pyramid#1554]
From IRC discussion:

    <oyse> I have a problem with running pserve --daemon. It fails with Bad file
           descriptor on the use of os.urandom()
    <oyse> Is this a known problem?
    <oyse> I am running Pyramid 1.5.2 on Python 3.4.0
    <oyse> From what I found on internet it could be related to closing of
           filedescriptor, but I would assume that would have been taken care of a
           long time ago if that was the problem
     * Zart ran python2 and python3, and looked at /proc/<pid>/fd/
    <Zart> 2.7 used socket, 3.4 opens /dev/urandom. since pserve closes every fd
           after double fork() this breaks os.urandom() on py3k..
    <Zart> https://docs.python.org/3/whatsnew/3.4.html#significant-optimizations
           seems like it's 3.4 specific optimizations
    <Zart> https://github.com/Pylons/pyramid/blob/master/pyramid/scripts/pserve.py#L412

So it seems that lazy-init optimizations in 3.4 might be a culprit here.

**Comment by zart** [comment]
This might have been fixed in 3.4.1 or later: http://bugs.python.org/issue21207

**Comment by bertjwregeer** [comment]
Downside to trying to be too smart ...

**Comment by mcdonc** [comment]
TBH I'd rather remove the ``--daemon`` feature than add a hack for versions of Python earlier then 3.4.1.  So many good process managers exist; ``pserve`` should not try to be one.

**Comment by hpfmn** [comment]
so what would you recommend to daemonize pserve?

**Comment by tseaver** [comment]
http://supervisord.org/

**Comment by mmerickel** [comment]
@hpfmn yes supervisord works well or every computer comes with its own init system for running services such as sysvinit, upstart or systemd.

**Comment by bertjwregeer** [comment]
the --daemon feature has been deprecated.
