### ISSUE TITLE
Protect against session fixation attacks with SessionAuthenticationPolicy

### ISSUE THREAD

**Issue by dstufft** [Pylons/pyramid#1569]
Currently any attempt to use ``SessionAuthenticationPolicy`` with server side sessions results in a session fixation attack by default. In order to securely handle sessions any session identifiers *must* be regenerated when crossing any authentication boundaries. Currently this relies on the person implementing the login view to ensure that they copy the data from the session, call the ``Session().invalidate()`` method, and then restore all of the data onto the session. I think that it would be a good idea for the ``SessionAuthenticationPolicy`` to do the dance itself so that people get protection against this by default. 

It might make sense to add a method on ``ISession`` called something like ``ISession().cycle()`` which will encapsulate this copy, invalidate, restore dance.

See [OWASP](https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Renew_the_Session_ID_After_Any_Privilege_Level_Change) for more information.

**Comment by mmerickel** [comment]
I'm not on board with copying the session data. Whenever my apps have needed to escalate privileges they've called invalidate on the session after calling remember and that's it. It requires me to make sure that I don't push flash messages and such into the session for the current request until *after* calling `invalidate` but that's always worked well for me to avoid bringing over any unexpected data from the previous session. Can you comment on this?

**Comment by dstufft** [comment]
Copying the session data is basically a tradeoff, it's *more* secure to not copy the data over, however it's not uncommon for an application to expect to be able to use the session to store stuff when going from anonymous -> authenticated. For example a shopping website may allow users to start filling up their cart while logged out and anonymous and then ask them to login/register before actually successfully making the order.

The tradeoff makes the assumption that anonymous data is, in the general case, not particularly sensitive since there's no authentication or logged in user specific data in it. That assumption *may* not hold true for every application of course, though it's likely those applications are in the minority and they can still get that behavior by calling invalidate() themselves.

The tradeoff also makes this a lower impact change on end users, if they were relying on going from unauthenticated -> authenticated and storing data this will more or less be invisible to them other than a new session id (where applicable) will be generated.

Pyramid may decide that it doesn't feel that tradeoff is worth it, in which case the ``remember()`` method can just call invalidate and be done with it.

**Comment by mmerickel** [comment]
Ok thank you for your thoughts. I agree with you. If we changed it to simply `invalidate` it would be a real bw-incompat change for users, as well as likely being unnecessary because the actual *content* in the sessions is supposed to be untamperable in either scenario. Thus an attacker should not be able to inject data into the session themselves and the real concern is just someone tracking the identifier.

**Comment by dstufft** [comment]
One option, which Django uses, is to clear the session data if there is already an authenticated user in the session *and* this user does not match the one we're trying to remember. This will ensure that sensitive data doesn't leak between users while still making things work when going from anonymous to authenticated. This is a backwards incompatibility but I feel like it's probably an edge case that most people aren't relying on?

Another thing that Django does which is a good idea is clearing the session upon logout. It does this because users generally expect that "logout" is a destructive action that removes all of their user specific information from the session. However if you're storing something user specific in one and the user logs out, then another user comes in and logs in they'll get that users data in their authenticated session.

**Comment by mmerickel** [comment]
Yeah, we could check if the `authenticated_userid` is the same one which we are remembering. I'm not familiar with how django stores auth data, but in pyramid it isn't necessarily stored in the session. However I'm not sure that distinction is important here.

I'm also big on clearing data upon logout. Again, bw-incompat in the case someone does something like set a flash message prior to invoking logout but I think we can justify that in the release notes.

**Comment by dstufft** [comment]
Ok, I'll push that change to my PR then!

**Comment by mmerickel** [comment]
Linking this to #1845 where we should document session fixation attacks and what to do when logging in and out.
