### ISSUE TITLE
ICacheBuster interface leaks some implementation details

### ISSUE THREAD

**Issue by dstufft** [Pylons/pyramid#1582]
The ``ICacheBuster`` interface has a method, ``token(pathspec)`` which is used to generate a token for the given ``pathspec``. As far as I can tell the only place this method is used is for calling code to generate a token and then to immediate pass it into ``ICacheBuster.pregenerate``.

I feel like baking this ``token()`` method into the ``ICacheBuster`` interface is leaking the implementation details of the built in cache busting methods into the interface. Conceptually what you need in the cache busting interface is a way to convert and URL back and forth between the non-cachebusting and the cachebusting form. However this API assumes that Pyramid is the tool that is generating the token or the cache buster URLs. This doesn't always hold true though, for instance you might have a static asset pipeline outside of Pyramid that generates a manifest file and then your ``ICacheBuster`` simply needs to look up the path in that manifest file, but since the ``token()`` method is mandatory, you're forced to write a no-op method when you don't need this method.

Suggested on IRC was, I think, a better way of expressing this:

* Drop the ``ICacheBuster.token(pathspec)`` method.
* Modify ``ICacheBuster.pregenerate(token, subpath, kw)`` to ``ICacheBuster.pregenerate(pathspec, subpath, kw)``.
* Modify ``PathSegmentMd5CacheBuster`` so that they can accept a token generating function (e.g. ``PathSegmentMd5CacheBuster(tokenizer=Md5AssetTokenGenerator())`` and they'll simply call that inside of their ``pregenerate`` function.

Since this API hasn't been released yet it may be a good idea to review it before there are backwards compatibility considerations to take into account.

**Comment by mmerickel** [comment]
I think it'd be nice to have generic `PathSegmentCacheBuster` and `QueryStringCacheBuster` objects that are not coupled to md5. We can do this pretty easily via composition + mixins with very minimal changes to the current codebase.

```python
class PathSegmentCacheBuster(object):
    def __init__(self, tokenizer=None):
        self.tokenize = tokenizer

    def pregenerate(self, pathspec, subpath, kw):
        token = self.tokenize(pathspec)
        return (token,) + subpath, kw

    def match(self, subpath):
        return subpath[1:]

class MD5AssetTokenGenerator(object):
    def tokenize(self, pathspec):
        return hashlib.md5(pathspec).hexdigest()

class PathSegmentMD5CacheBuster(PathSegmentCacheBuster, MD5AssetTokenGenerator):
    pass
```

**Comment by dstufft** [comment]
I really like the above, composition is great and it gives all of niceties of the current API without forcing people who aren't generating tokens in Pyramid to have a no-op ``token()`` method.
