### ISSUE TITLE
chameleon: i18n:target has no effect

### ISSUE THREAD

**Issue by voxspox** [Pylons/pyramid#1590]
Hi,

I use chameleon as template engine with pyramid 1.4 in a multi-language application.
I want to use i18n:target to always switch to a certain language in a certain part of the template.
Using set_locale_negotiator() of pyramid.Configurator works to switch the global locale, thus everything seems to be set-up right.
But when I use i18n:target in the template nothing happens. Even not for 'default' or 'nothing'.

knut

chameleon bug tracker: https://github.com/malthe/chameleon/issues/198

**Comment by mmerickel** [comment]
Looks like this is an issue in chameleon. I'm going to close this report and let it be dealt with there.

**Comment by malthe** [comment]
Chameleon now does support `i18n:target`.
