### ISSUE TITLE
Package version 1.5.4 installed as Pyramid-1.6.dev0

### ISSUE THREAD

**Issue by keitheis** [Pylons/pyramid#1595]
`pip install --upgrade Pyramid` (on 1.5.3) doing nothing since it looks like latest stable version.

`pip install Pyramid==1.5.4` got:

```
...
Requirement already satisfied (use --upgrade to upgrade): translationstring>=0.4 in .virtualenvs/34/lib/python3.4/site-packages (from Pyramid==1.5.4)
Installing collected packages: Pyramid
  Found existing installation: pyramid 1.6.dev0
    Uninstalling pyramid-1.6.dev0:
      Successfully uninstalled pyramid-1.6.dev0

Successfully installed Pyramid-1.6.dev0
```

**Comment by tseaver** [comment]
[I cannot reproduce this report](https://gist.github.com/tseaver/e9090b4b61689c98fbf7)

**Comment by mmerickel** [comment]
I just downloaded the wheel and the tar.gz from PyPI and neither of them contains the string "1.6.dev0" anywhere in them. What you're suggesting is something I cannot verify so far.

**Comment by sontek** [comment]
Doing:

'''
pip freeze
pip --version
'''

And pasting results here might help us narrow it down.

**Comment by mmerickel** [comment]
@keitheis Please re-open this issue if you're able to reproduce what's going on.
