### ISSUE TITLE
Purpose: Alembic in scaffold Alchemy

### ISSUE THREAD

**Issue by marioidival** [Pylons/pyramid#1597]
Nowadays various frameworks is standard with some kind of database migration tool together. In alchemy scaffold, use SQLAlchemy and we have a migration framework for it when downloaded.

I know that the Pyramid is agnostic, but I believe we should think about migrations that scaffold.

**Comment by robertlagrant** [comment]
+1

**Comment by marioidival** [comment]
https://github.com/Pylons/pyramid/pull/2024

**Comment by bertjwregeer** [comment]
See pull requests #2024 and #1625. I think this would be a great addition to #2024.

**Comment by mmerickel** [comment]
related https://github.com/Pylons/pyramid-cookiecutter-alchemy/pull/7

**Comment by stevepiercy** [comment]
https://github.com/Pylons/pyramid-cookiecutter-alchemy/pull/7 was merged.

I'll be doing some work on the docs wherever the alchemy cookiecutter is used. I'll create a new branch off of `master` and push that up for ease of collaboration.

**Comment by stevepiercy** [comment]
I've started work in a PR #3307 on a new branch `alembic-cookiecutter-alchemy` in Pyramid.

**Comment by mmerickel** [comment]
Fixed via #3307 and https://github.com/Pylons/pyramid-cookiecutter-alchemy/pull/7. Thanks for the hard work everyone involved!

**Comment by marioidival** [comment]
<3
