### ISSUE TITLE
Custom traverser with find_resource()

### ISSUE THREAD

**Issue by drarmstr** [Pylons/pyramid#1598]
I'm using a custom traverser added via Configurator.add_traverser() which seems to mostly work fine for normal routing.  However, it does not appear to work with pyramid.traversal.find_resource().  Looking into the problem find_resource() calls pyramid.traversal.traverse() which looks up the custom traverser via a queryAdapter() lookup in the registry.  The issue appears to be that it gets the registry from a pyramid.threadlocal.get_current_registry() call and this call returns some global registry instead of my app's registry.  If I hack it to return my app's registry then it finds the traverser and works alright.

Is there some user error here or is there a bug with the approach of traverse() using get_current_registry()?

**Comment by mmerickel** [comment]
When are you calling `find_resource`? Is it in the same thread as an active request?

**Comment by drarmstr** [comment]
I am calling find_resource from a worker thread that was spawned by a view callable.  So, that would explain why the threadlocal storage is providing the wrong registry.  What is the best practice then for calling `find_resource` from a worker thread?

**Comment by mcdonc** [comment]
You might pass the value ``pyramid.registry.global_registry`` into the Configurator e.g.:

````
config = Configurator(registry=global_registry)
config.setup_registry(settings=settings, ....)
````
This way get_current_registry() will return the global registry when there isn't a threadlocal registry, and the threadlocal registry will be the global registry when there is.

The call to ``config.setup_registry()`` is necessary when you explicitly pass a registry argument and want the registry to be useful in a Pyramid app.  See ``pyramid.config.__init__`` the Configurator constructor for what to pass into it.

**Comment by mcdonc** [comment]
All that said, you might reconsider your app's design and instead of spawning a thread from a view callable, use some messaging queue thing like celery or retools or whatever the favored messaging queue app du jour is to communicate with a separate process pool which processes that queue.

**Comment by mmerickel** [comment]
@drarmstr Pyramid has a chapter on scripting, and you'll see that it advocates the use of the `pyramid.paster.boostrap()` api. It is almost always a mistake in design to require those workers to be spawned inside of your wsgi application which is why it doesn't really match with what Pyramid does.

**Comment by drarmstr** [comment]
Setting up the registry with the Configurator as you describe seems to have done the trick for getting my custom traverser called, thank you!!  I'm not sure how using a process pool instead of a thread pool would have helped the threadlocal context, though?

I've used `pyramid.paste.get_appsettings` before, but it was to be able to use my app's functionality from a console script.  Are you saying that I should somehow use `pyramid.paster.bootstrap()` to properly prepare worker thread pool threads?  Where is the documentation you refer to for this?

**Comment by mmerickel** [comment]
I'm saying that if you think of your workers in a way that is not coupled to the wsgi process it should become clear how to use something like `bootstrap` to accomplish your goals for your worker threads. It's something you do for each worker irrespective of whether it is thread-based or process-based.

If you are worried about the efficiency of invoking `bootstrap` per thread, it's possible to pass the registry around and invoke the `pyramid.scripting.prepare` api inside of each thread. This allows you to share a single registry everywhere just the way the wsgi app works.

**Comment by mcdonc** [comment]
I'm closing this because I think a solution has been found.
