### ISSUE TITLE
callback inside tween (before tween egress)

### ISSUE THREAD

**Issue by flibustenet** [Pylons/pyramid#1599]
We have now a very clean diagram of request possessing :
http://pyramid.readthedocs.org/en/master/narr/router.html
It show that all the callbacks (response_callback, NewResponse and finished_callback) are executed after tweens egress. They cannot benefit of all the tweens features like debutoolbar, pyramid_tm...
I think it miss a callback between view and tween egress.
We spoke a little about that on the ml and irc but in the end i don't know if it's a feature that will not be accepted or if it just wait for somebody to work on this (me if i can but not sure to can do it the right way).

**Comment by stevepiercy** [comment]
Is there anything that needs to be changed in the diagram at this time?

**Comment by mmerickel** [comment]
@stevepiercy he's asking for us to introduce a new event into Pyramid between view execution and tween egress. For what purpose, I'm not sure.

**Comment by flibustenet** [comment]
Nothing as to be changed in the diagram.
I would like to have callback that benefit of tween. For example if my callback raise an error it will be catched by debugtoobar. I can use this callback to write to the database for example, send an email and everything that need to be executed before tween egress.

**Comment by f0rk** [comment]
I just ran into this same issue. In my case, I would like to reset some session state after the request is over. Unfortunately, this is after the previous transaction has ended causes a new transaction to begin, which isn't desirable. This resulted in a number of connections to remain (unexpectedly, until @flibustenet pointed out the router diagram above) idle in transaction.

**Comment by flibustenet** [comment]
My solution before a standard Pyramid's one it to make my own event and then notify it in egress of my own tween.

**Comment by mmerickel** [comment]
I'm closing this as I can't think of any good use-cases for an event between views and tween egress. If transactions are an issue those should be solved by the tweens (they are almost always active at the spot in the pipeline we are discussing so I'm not sure how this would help @f0rk's use-case.)
