### ISSUE TITLE
Add `authenticated` view predicate

### ISSUE THREAD

**Issue by ztane** [Pylons/pyramid#1602]
`authenticated=bool` view predicate could be nice - essentially the same in function as 

```
effective_principals=pyramid.security.Authenticated 
effective_principals=not_(pyramid.security.Authenticated)
```

except not that much PITA to remember how to write correctly or what to import from where.

---

It would also make [this @mmerickel's pattern](https://github.com/Pylons/pyramid/issues/436#issuecomment-3965530) slightly more readable:

```
@view_config(context=HTTPForbidden, authenticated=False)
def unauthenticated_forbidden_view(request):
    location = request.route_url('login', _query={'came_from': request.path})
    return HTTPSeeOther(location)

@view_config(context=HTTPForbidden, authenticated=True, renderer='forbidden.mako')
def forbidden_view(request):
    request.response.status = 403
    return {
        # params required for rendering mytemplate.mako
    }
```

**Comment by mmerickel** [comment]
I am having a hard time figuring a way to justify adding this over the already-existing sugar of `effective_principals`. Too many ways to accomplish the same thing here. I'm not a fan of `effective_principals` since it allows ambiguous lookups, but it exists already.

**Comment by ztane** [comment]
the point would be the newbie-friendliness and no import for something for which no import should be needed.

**Comment by bertjwregeer** [comment]
effective_principals='system.Authenticated'

One less import, and remembering system.Authenticated isn't difficult. That being said, if the value ever changes, there are going to be issues...

**Comment by ztane** [comment]
Ok, I looked at how EffectivePrincipals are implemented, and let's state it this way:

`authenticated=arg` should do `return arg == (authenticated_userid(request) is not None)`; because it has less overhead it is preferable over `effective_principals` over a constant set. (and I can provide PR).

**Comment by robertlagrant** [comment]
Coming at Pyramid from other web frameworks, this would be a nice addition for someone learning the framework and still half-assessing whether I should stick with it.  I'm still not sure how `effective_principals` works, or what that phrase even means in terms of English :) Although possibly those problems are related.

A way to easily select views based on authentication, group membership and permissions (at class and object level) would cover a lot of use cases I've come across, although that's obviously a small sample size. @ztane's suggestion (the first in my list), small/pointless though it is to someone who's very familiar with Pyramid permissions, would be a big step, I think.

**Comment by mmerickel** [comment]
If someone wants to submit a PR, docs (narrative as well, as your entire justification for this feature is to make it easier for newcomers who probably want a nice example) and tests for this feature where `authenticated=True` is equivalent to `pyramid.security.Authenticated in request.effective_principals` and `authenticated=False` is `not in` then I don't have a problem with it.

**Comment by bertjwregeer** [comment]
Predicate vs non-predicate is still going to be an issue, unless we don't want to tackle that here.

**Comment by mmerickel** [comment]
This feature is explicitly a predicate as it's being billed in the description above... 2 views, one for authenticated and one for not. If you think this is confusing then we should just scrap it.

**Comment by mmerickel** [comment]
It looks like no one wants to implement this. I'm going to close the request.

**Comment by merwok** [comment]
@mmerickel now that `effective_principals` is deprecated, is there any interest in this?  I have implemented a version in a project so that I could have different view configs for «not authenticated» vs «not allowed»:

```python
def includeme(config):
    config.add_view_predicate("is_authenticated", IsAuthenticatedPredicate)


class IsAuthenticatedPredicate:
    def __init__(self, val, config):
        self.val = val

    def text(self):
        return f"is_authenticated = {self.val}"

    phash = text

    def __call__(self, context, request):
        return request.authenticated_userid is not None
```

**Comment by mmerickel** [comment]
Sorry to leave you hanging @merwok, I think it's probably a worthwhile addition alongside potentially a `request.is_authenticated`. There's definitely precedent in other frameworks and I think it'd be useful.

**Comment by merwok** [comment]
No worry!  One PR with both changes, or should they be separate?

**Comment by mmerickel** [comment]
I think together is fine.

I'm not sure why they would be added to the response objects.

**Comment by merwok** [comment]
Edited my message, I meant Request and IRequest :facepalm: 

Can you reopen this issue?

**Comment by mmerickel** [comment]
yes it goes on IRequest as well. Thanks for noting authenticated_identity which also needs to be added.

**Comment by merwok** [comment]
I have also noticed that the whatsnew-2.0 document is mostly empty.
Should I not add anything to it for now, or is it useful to put some info and let someone complete the whole doc in another PR?

**Comment by mmerickel** [comment]
no need to update whatsnew

**Comment by merwok** [comment]
I see now the changelog is in CHANGES.rst!
