### ISSUE TITLE
Problem generating HTML documentation (master branch)

### ISSUE THREAD

**Issue by ericpar** [Pylons/pyramid#1604]
Hello,

I've created a fresh virtual environment (```mkvirtualenv```) which uses Python 2.7.
I installed the requirements found in ```rtd.txt```.
I cloned the present repo.
I switched in the ```<pyramid-repo>/docs``` directory and issued ```make html```.

I got this error after a few tens of seconds of processing:

```
...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 132 source files that are out of date
updating environment: 132 added, 0 changed, 0 removed
reading sources... [100%] whatsnew-1.5                                          

Warning, treated as error:
/home/eric/sandbox/pyramid/docs/api/interfaces.rst:92: WARNING: autodoc: failed to import interface u'ICacheBuster' from module u'pyramid.interfaces'; the following exception was raised:
Traceback (most recent call last):
  File "/home/eric/Envs/pyramid/lib/python2.7/site-packages/Sphinx-1.3-py2.7.egg/sphinx/ext/autodoc.py", line 392, in import_object
    obj = self.get_attr(obj, part)
  File "/home/eric/Envs/pyramid/lib/python2.7/site-packages/Sphinx-1.3-py2.7.egg/sphinx/ext/autodoc.py", line 288, in get_attr
    return safe_getattr(obj, name, *defargs)
  File "/home/eric/Envs/pyramid/lib/python2.7/site-packages/Sphinx-1.3-py2.7.egg/sphinx/util/inspect.py", line 115, in safe_getattr
    raise AttributeError(name)
AttributeError: ICacheBuster

make: *** [html] Error 1
```

Is there a missing dependency ?

**Comment by mcdonc** [comment]
I think you need the SPHINXBUILD envvar when running make if you have Pyramid installed in a venv:

```
cd pyramid/docs
make html SPHINXBUILD=/home/eric/Envs/pyramid/bin/sphinx-build
```

**Comment by mcdonc** [comment]
You probably need to do "/home/eric/Envs/pyramid/bin/python setup.py develop" within the pyramid checkout too, if that isnt obvious.

**Comment by mmerickel** [comment]
As a fun alternative, the `tox.ini` now builds the documentation, so you can just run `tox -e py2-docs` if you want.

**Comment by mcdonc** [comment]
tox -e py2-docs is a better idea yup.. then cd to .tox/py2-docs/docs/html for the result

**Comment by mcdonc** [comment]
Going to close this because I know both solutions above work; if you have further difficulty please use the pylons-discuss maillist at https://groups.google.com/forum/#!forum/pylons-discuss

**Comment by mmerickel** [comment]
Actually `py2-docs` and `py3-docs` clobber eachother in `<toxinidir>/_build/html`. We'd have to pass some extra stuff into get it to build to another location.
