### ISSUE TITLE
Allow specifying the type of redirect for append_slash=True

### ISSUE THREAD

**Issue by dstufft** [Pylons/pyramid#1609]
It would be great to allow specifying the type of redirect to be used when using the ``append_slash`` parameter to ``notfound_view_config``. Maybe the API could be ``append_slash=True`` gives you the current behavior, and ``append_slash=HTTPMovedPermanently`` for instance could be used to use ``HTTPMovedPermanently`` to do the redirect?

**Comment by mcdonc** [comment]
I'd be fine with that personally.  Do you think you could provide a PR with the impl and tests Donald?

**Comment by dstufft** [comment]
Yup, just wanted to see if there was any interest before I did :)

**Comment by dstufft** [comment]
Okay, implemented in #1610.
