### ISSUE TITLE
Replace git submodules with git subrepo

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#1614]
Thanks to a tip from Zart in #pyramid, here's a nice write up of [git subrepo](https://github.com/ingydotnet/git-subrepo/blob/master/Intro.pod).

**Comment by mmerickel** [comment]
+1, git subrepo looks very nice.

**Comment by bertjwregeer** [comment]
subrepo is a pain in the ass to correctly maintain, especially if you accidentally for example forget the squash flag you get this entirely new history grafted onto your current repo's history.

I've used it in the past, and I would definitely not recommend it.

**Comment by blaflamme** [comment]
What I propose until we are set on pylons ui and redo the docs theme is to convert the current docs theme into an installable package and make releases as we fix it. So that way anytime you rebuild any project docs it'll pull the latest version without to have to worry about this wrong repo stuff approach IMHO, and in fact that was from me o_O

**Comment by stevepiercy** [comment]
If someone would like to show me how to do what @blaflamme proposes, and grant me sufficient access to do so, I will gladly do this during sprints.

**Comment by blaflamme** [comment]
@stevepiercy look at the new docs theme repo and you'll see how it's done.

https://github.com/Pylons/pyramid-sphinx-themes/blob/master/src/pyramid_sphinx_themes/__init__.py#L8

then to make it works it looks like that in the conf.py file

```python
# At the top.
import pylons_sphinx_theme

# ...

# Activate the theme.
html_theme = 'pyramid'
html_theme_path = pylons_sphinx_theme.get_html_themes_path()
```

**Comment by bertjwregeer** [comment]
So apparently I was thinking of git subtree, which is not git subrepo. So ignore my comment.

**Comment by stevepiercy** [comment]
Closing through multiple PRs as noted above. If any older branches fail to build on RTD, then I just repeat the steps documented in our new package and repo:
https://github.com/Pylons/pylons-sphinx-themes
