### ISSUE TITLE
Create a way to run scaffold functests via tox 

### ISSUE THREAD

**Issue by mcdonc** [Pylons/pyramid#1623]
Something like (doesn't yet work):

```
[testenv:scaffolds]
commands =
    {envbindir}/python pyramid/scaffolds/tests.py
```

**Comment by mmerickel** [comment]
This should be added to the travis.yml as well somehow.

**Comment by mcdonc** [comment]
I added a "scaffoldtests.sh" script.  I'm sure John will soon create a pull req to remove the shell script and to toxception.
