### ISSUE TITLE
JSONP renderer not compatible with AngularJS (400 Invalid JSONP callback function name)

### ISSUE THREAD

**Issue by katzlbt** [Pylons/pyramid#1644]
The pyramid web framework (V1.5.6) disallows angular callbacks since newer versions, throwing the error '400 Invalid JSONP callback function name.' when used with AngularJS (V1.2.28), which passes the callback like this: ptth://example/?callback=angular.callbacks._0

What would be a workaround?
There seem to be no good options to fix this on either the AngularJS or the Pyramid side.

https://pyramid.readthedocs.org/en/master/_modules/pyramid/renderers.html
JSONP_VALID_CALLBACK = re.compile(r"^[a-zA-Z_$][0-9a-zA-Z_$]+$")

    from pyramid.renderers import JSONP
    config.add_renderer('jsonp',JSONP(param_name='callback'))

https://github.com/angular/angular.js/pull/3073
http://stackoverflow.com/questions/29818947/pyramid-framework-disallows-jsonp-callback-format-of-angularjs

**Comment by bertjwregeer** [comment]
Sorry :-(

**Comment by mmerickel** [comment]
@katzlbt can you please confirm that #1648 handles angular?

**Comment by mmerickel** [comment]
Ok this is fixed and released in v1.5.7.
