### ISSUE TITLE
Template override to different templating system doesn't use correct renderer

### ISSUE THREAD

**Issue by robertlagrant** [Pylons/pyramid#1658]
My situation: I'm using [fullauth](https://github.com/fizyk/pyramid_fullauth) to get logins and user registration up and running. Fullauth uses Mako templates, but I'm using Jinja2. I've started making Jinja2 equivalents of fullauth's templates.  I've got `pyramid_jinja2` installed, and my other screens are working fine with Jinja2.

The problem is that while I can see the content of my new template (i.e. the override is finding the right template) it doesn't seem to be being pushed through the Jinja2 renderer, even though the overriding template's filename ends with `jinja2`.  

Am I missing something? How is this situation supposed to work? Or is it a bug?

**Comment by stevepiercy** [comment]
It sounds like you want support first, so please see our guidelines for doing so: http://www.pylonsproject.org/community/get-support

You'll have a larger audience and better chance of a response on the mail list or in IRC than here on the issue tracker. This is really more for reporting bugs, making feature requests, and submitting pull requests than support.

**Comment by robertlagrant** [comment]
Thanks for the response. I sort of meant it to be a driver towards a new feature (or a correction of a bug) based on the use case, but as it's not that clear-cut then I'll try those other avenues.

Thanks again!
