### ISSUE TITLE
Parameters included in a DELETE body request are not included in the parameters dictionary

### ISSUE THREAD

**Issue by Hunsu** [Pylons/pyramid#1685]
When I send the below request the `request.params` is empty even though there are parameters in the request body.  

    curl 'myurl' -X DELETE -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.6.0' -H 'Accept: */*' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8'  --data 'key=value'

**Comment by mmerickel** [comment]
This is going to be an issue with webob and not pyramid. You should open your issue there.
