### ISSUE TITLE
HTTP redirections don't work well with apache rewrite rule

### ISSUE THREAD

**Issue by dlax** [Pylons/pyramid#1698]
I'm trying to get the following adapted hello world example with a HTTP redirection working where the application is behind a Apache rewrite rule `http://hostname.example.com:8080 -> http://subdomain.example.com`.  

```python
from wsgiref.simple_server import make_server
from pyramid.config import Configurator
from pyramid.response import Response
from pyramid.httpexceptions import HTTPSeeOther

def hello_world(request):
    return Response('Hello %(name)s!' % request.matchdict)

def ahah(request):
    raise HTTPSeeOther('/hello/word')

if __name__ == '__main__':
    config = Configurator()
    config.add_route('hello', '/hello/{name}')
    config.add_view(hello_world, route_name='hello')
    config.add_route('ahah', '/ahah')
    config.add_view(ahah, route_name='ahah')
    app = config.make_wsgi_app()
    server = make_server('0.0.0.0', 8080, app)
    server.serve_forever()
```

The issue is that getting `http://subdomain.example.com/ahah` redirects to `http://hostname.example.com:8080/hello/world` so that apparently the X-Forwarded-Host information (present in request) is not taken into account.

Am I missing something? Thanks!

**Comment by mmerickel** [comment]
When you're running pyramid behind a proxy you need to do something to fix up the wsgi environ. Pyramid itself is just a wsgi app that generates urls relative to what was given to it (in this case from your wsgi server which is serving a request from apache).

The options are somewhat well documented here[1]. Most of them are not actually specific to waitress at all. I personally use the PasteDeploy PrefixMiddleware in my ini file in production to fix things up.

[1] http://waitress.readthedocs.org/en/latest/#using-behind-a-reverse-proxy
