### ISSUE TITLE
resource_url adapter

### ISSUE THREAD

**Issue by davidemoro** [Pylons/pyramid#1789]
You can modify how pyramid generate resource urls via:
1- implementing a `__resource_url__(self, request, info)` method on the model. See http://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.resource_url
2- registering a custom `ResourceURL` with `config.add_resource_url_adapter` providing a custom `virtual_path` for example. See http://pyramid.readthedocs.org/en/master/narr/hooks.html#changing-how-pyramid-request-request-resource-url-generates-a-url

The first way is not optimal because it requires you to add a method on a model, it is not always possible if you want to avoid monkey patches (third party models).
The second, it only let you provide `virtual_path[_tuple]` and `physical_path[_tuple]`. So if you want to generate something of different (for example an external url with a different structure you cannot do it. For example for a `/doc/collapsabledocument` with `id=315`, obtaining something like `/doc#id-315`) it is not possible because this adapter provides virtual/physical paths and not urls.

I assume that there is a framework that calls resource_url, in my case the Kotti's kotti_tinymce plugin.

I solved this particular use case with a custom local `__resource_url__`:

```
    def __resource_url__(self, request, conf):
        """ Change the resource url of
            CollapsableDocuments when you link them in a rich text field.

            If we are going to link a collapsable document (not publishable by the frontend)
            /doc/collapsable with id 315,
            we want to generate the following url
            /doc#id-315

            This way the frontend will be able to use anchors to collapsable
            documents.

            The url saved on the rich text field will be /doc#id-315

            See http://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.resource_url
        """
        result = None
        kottibrowser_view = '@@kottibrowser'
        request_url = request.url
        if request_url.endswith(kottibrowser_view):
            url = request_url[:-len(kottibrowser_view)]
            if url.endswith(self.path):
                virtual_path = conf['virtual_path'].endswith('/') and \
                    conf['virtual_path'][:-1] or conf['virtual_path']
                result = "%s%s#id-%d" % (conf['app_url'],
                                         '/'.join(virtual_path.split('/')[:-1]),
                                         self.id)

        if result is None:
            result = "%s%s" % (conf['app_url'], conf['virtual_path'])
        return result 
```

because it is not possible implementing it with a custom `ResourceURL`. 
This way I'm able to navigate properly the pyramid/kotti backend (I'm using a decoupled frontend vs backend architecture), but if I'm going to link on a richtext widget a not publishable object I can save the right custom url.

Anyway this is not a bug, I would be happy to know your opinion. My questions are:
- is there another hook that can be used? Just in case I've missed something in the Pyramid doc
- probably `ResourceURL` (just a semantic note) is not the best name, it reminds me a full url like `__resource_url__`already does and not an adapter that provides traversal info. Do you agree?
- am I the only one that need this kind of flexibility? If not, could be interesting adding in `Pyramid` an overridable `resource_url` adapter avoiding the `__resource_url__` local method? Since it is the second time I had to change `resource_urls` I can implement this feature.

**Comment by mmerickel** [comment]
It doesn't look to me like there's any interest in returning full urls here. I'm going to close this for now but we can always reopen it if there's a strong argument as to why we would want allow a resource to point external to the application root.
