### ISSUE TITLE
Quick Tutorial - 19: Databases Using SQLAlchemy  (modify tests so there is no session warning/collision)

### ISSUE THREAD

**Issue by kilodalton** [Pylons/pyramid#1813]
On: http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/databases.html

In the WikiFunctionalTests section in databases/tutorial/tests.py, `self.session = _initTestingDB()` doesn't need to be set in WikiFunctionalTests setUp method...and in fact when `app = get_app('development.ini')` is subsequently called it generates a `SAWarning: At least one scoped session is already present.` because a session is already defined.

In order to avoid this SA "one scoped session is already present" warning when the test is run:
--Remove `self.session = _initTestingDB()` from WikiFunctionalTests setUp()
--Remove `self.session.remove()` from WikiFunctionalTests tearDown()
--Add to WikiFunctionalTests tearDown()
       `from .models import DBSession`
        `DBSession.remove()`

**Comment by stevepiercy** [comment]
@kilodalton said she would submit a PR on Monday with the fix as well the removal of the output from `$VENV/bin/initialize_tutorial_db development.ini` because there is none.

**Comment by kilodalton** [comment]
Pull request submitted: "Quick Tutorial Database: Logging configs for db script output + fix scoped session warning" #1823

**Comment by stevepiercy** [comment]
Closed via #1823. Thank you!
