### ISSUE TITLE
Can we make ACLAuthorizationPolicy flexible regarding the '__acl__' attribute name?

### ISSUE THREAD

**Issue by ctheune** [Pylons/pyramid#1839]
I have an application that is provided to various users (multiple API endpoints and multiple UI endpoints). Each of those are configured as separate applications. It would be nice if I could add multiple __acl_*__ attributes to each content class that I use for permission checking and still leverage the ACL functionality.

I'm currently copying the class - I'll provide a link to my version as soon as I push it.

**Comment by mcdonc** [comment]
I'd much prefer not adding any knobs to policies.  Instead, I'd suggest creating a custom policy.  Sorry christian, I'll close this, and if there's a case to be made it should be on mail list but I'm a -1 on it.

**Comment by ctheune** [comment]
*headsovertomailinglist*

:)
