### ISSUE TITLE
Narrative docs for request/response contain some out of date info regarding unicode and str_* properties

### ISSUE THREAD

**Issue by lambacck** [Pylons/pyramid#1846]
The [unicode section of the request/response narrative docs](https://github.com/Pylons/pyramid/blob/master/docs/narr/webob.rst#unicode) contain some out of date information. At the very least it looks like the str_GET, str_POST MultiDicts no longer exist or generate deprecation warnings. I'm not fully up on what the new state of the world is on this so I'm not sure I'm the best person to provide a documentation update. Perhaps the only thing that needs to happen is the removal of the last sentence?
```text
Each has a corresponding req.str_* (e.g., req.str_POST) that is always a str, and never unicode.
```

It looks like this is the relevant webob code: https://github.com/Pylons/webob/blob/master/webob/request.py#L1736

**Comment by mcdonc** [comment]
This was fixed via https://github.com/Pylons/pyramid/commit/8447260de970629be01de821e43e9ea33e4405a0 .  Thank you!
