### ISSUE TITLE
Allow view_default to be applied to a class imperatively

### ISSUE THREAD

**Issue by robertlagrant** [Pylons/pyramid#1853]
***Context:*** I might be finding some local maximum and maybe there's a better way to do this, but I'm helping rewrite a plugin so it uses imperative config, as then templates with different renderers can override its built in templates (because even overridden templates use the renderer of the original template, and because you can't have config inside a `view_config` decorator to change the template that way).

The problem is that the thing is written with `view_config` and `view_defaults`, and it seems we're going to have to write a lot of repetitive config code to replicate it. Is there a way to allow `view_default` to be applied imperatively, the way `view_config` can be?

**Comment by ztane** [comment]
I guess you mean that `add_view` could be instructed to use view_defaults?

**Comment by robertlagrant** [comment]
@ztane yes, that's a good way of looking at it.

**Comment by mmerickel** [comment]
It's a decorator, can't you just do:

```python
apply_defaults = view_defaults(route_name='foo')
config.add_view(apply_defaults(my_view), ...)
```

Only drawback I see is that you can't use a string/dotted-name for `my_view`.

**Comment by robertlagrant** [comment]
@mmerickel I'll do my best :)

Just to make the case for adding it: I was a bit surprised by it because then if I want to add views imperatively, some custom code needs to be written for this plugin, for any other plugins, and for my main webapp as well, when it seems to be acknowledged (by the decorator syntax) as a useful built in way to apply view config. To put it a different way: why have the `view_default` decorator syntax when you can let a 1000 implementations bloom, e.g. wrap the `view_config` decorator?

**Comment by mmerickel** [comment]
Hmm, I'm not sure I see where you're going yet but I think `view_defaults` was added to scratch an itch more than as an attempt to prevent you from building a wrapper around `view_config`. :-)

**Comment by robertlagrant** [comment]
Ah okay that makes sense; I basically mean that the logic to add it declaratively is the same as that to add it imperatively. Coming at Pyramid not from a Pylons etc background, and not knowing all the history, it seems strangely asymmetric, as though the declarative method is the preferred method.

Which, if so, is a problem, as I don't think there's any other way to achieve my actual goal, which is to allow the overriding of a view's template (and its renderer) through config.

**Comment by mmerickel** [comment]
Okay sure. We advocate the declarative mechanisms because they look nicer and are less verbose, but they are also more limited for certain cases like what you're describing.

On a side note, I never considered that you cannot switch renderers when overriding assets. That's too bad it works that way but we do currently leave it up to the renderer to resolve the paths so there's not much we can do about it. :-(

**Comment by robertlagrant** [comment]
Alright, thanks for the information.
