### ISSUE TITLE
Docs - the "code" tag is covering neighboring text in my browser

### ISSUE THREAD

**Issue by machado2** [Pylons/pyramid#1859]
This picture was taken on a Chrome 43 browser / Linux
Browsing at this URL:
http://docs.pylonsproject.org/projects/pyramid/en/1.0-branch/narr/views.html#view-callables

All the docs are looking like this in my browser.

![image](https://cloud.githubusercontent.com/assets/10177157/8763442/1e8045ea-2d72-11e5-82dc-522f2b5b9706.png)

**Comment by stevepiercy** [comment]
You are viewing docs for version 1.0 of Pyramid which is no longer supported. Please use the [latest version](http://docs.pylonsproject.org/projects/pyramid/en/latest/).
