### ISSUE TITLE
Pyramid tests set invalid status on Response() objects

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid#1864]
Due to changes in WebOb 1.5.0 (specifically: https://github.com/Pylons/webob/blob/master/docs/news.txt#L14) when Pyramid uses `_HTTPMove()` in tests, it doesn't set the appropriate `code` and `title` this passing `None None` as the Response()'s status.

In WebOb 1.5.0 this has become more strict, so that rather than blowing up at time of use (for example when the `Response` object is actually used to `start_response`, it now blows up when the status is being set. This makes for a better API whereby you are not left guessing why WebOb blew up at a later time, and instead it is done at the call site.

This breaks Pyramid's tests as seen on Travis CI: https://travis-ci.org/Pylons/pyramid/jobs/73282779

**Comment by mmerickel** [comment]
Fixed via #1865.
