### ISSUE TITLE
quick_tutorial/forms issue with python 2.7.10 on reqts property

### ISSUE THREAD

**Issue by VicenteIranzoMaestre** [Pylons/pyramid#1867]
When running http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/forms.html with python 2.7.10 I get  the following error when trying to edit an item:
ValueError: No static URL definition matching __main__:css/form.css

The reason is that reqts in the property of WikiViews returns self.wiki_form.get_widget_resources() which doesn't include the complete path.

I solved it by adding the following code:
    @property
    def reqts(self):
        resources = self.wiki_form.get_widget_resources()
        css_resources = resources['css']
        js_resources = resources['js']
        css_links = [ 'deform:static/%s' % r for r in css_resources ]
        js_links = [ 'deform:static/%s' % r for r in js_resources ]
        resources['css'] = css_links
        resources['js'] = js_links
        return resource

Additionaly, in the forms/tutorial/wikipage_addedit.pt template, "deform:static/scripts/jquery-2.0.3.min.js" is loaded, but this file is not present in the deform for python 2.7.10 package. I solved it   substituing by jquery-1.7.2.min.js

I apologyse myself if this is not the place to comunicate it and I would apreciate any help to contact the right group/place to comunicate this issue.

**Comment by stevepiercy** [comment]
See https://github.com/Pylons/pyramid/issues/1857 and if it resolves your issue, then please close this one.

p.s. -- Always check for closed issues before opening a new one.

**Comment by VicenteIranzoMaestre** [comment]
I tryed to but I didn't find it.

**Comment by stevepiercy** [comment]
Did you use pip? If you used pip, then you did not follow the tutorial instructions. We explain why we use setuptools and easy_install instead of pip early on.

http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/requirements.html#install-pyramid

> Why easy_install and not pip? Pyramid encourages use of namespace packages, for which pip's support is less-than-optimal. Also, Pyramid's dependencies use some optional C extensions for performance: with easy_install, Windows users can get these extensions without needing a C compiler (pip does not support installing binary Windows distributions, except for wheels, which are not yet available for all dependencies).

As far as finding issues, by default, GitHub filters issues with `is:issue is:open`. You can change that to include PRs and all issues by [deleting those filters and searching for your issue](https://github.com/Pylons/pyramid/issues?utf8=%E2%9C%93&q=).

**Comment by VicenteIranzoMaestre** [comment]
As I don't use Windows, when I read this part I didn't give all the importance it allready has. Yes, I use pip. And when I read your message I remembered it. I'm a beginner and it's still hard to deal with easy_install and pip.

Thank you for your attention.

**Comment by stevepiercy** [comment]
To avoid package installation issues, it's better to use only one method, pip or easy_install, until you become more familiar with their differences. "[Don't cross the streams!](https://www.youtube.com/watch?v=jyaLZHiJJnE)"

**Comment by VicenteIranzoMaestre** [comment]
I tried with easy_install and this is the result:
./bin/easy_install deform
Searching for deform
Best match: deform 0.9.9
Adding deform 0.9.9 to easy-install.pth file

I had to force the version to 2.0a2 by specifying it. Then everithing is OK and the changes I proposed are useless, they even generate an error.

Do you think that this is because of the python version 2..7.10?

**Comment by stevepiercy** [comment]
`./bin/easy_install deform` is relative to the current directory and not necessarily your virtual environment. If you followed the Quick Tutorial instructions from the beginning, this time setting an environment variable equivalent to the path of your virtual environment, then the command would not be ambiguous.

```bash
$VENV/bin/easy_install "deform== 2.0a2"
```

Nonetheless, that is not the right way to install deform in the tutorial. That command does not exist anywhere in the Quick Tutorial, nor does its pattern.

Use `setup.py` as indicated in [Step 18](http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/forms.html).

3. We can now install our project in development mode:
```bash
$ $VENV/bin/python setup.py develop
```

So once more, this time with feeling: follow the instructions. Don't go off the beaten path and make up your own commands to install stuff unless you understand the implications.
