### ISSUE TITLE
suggestion- config argument to allow unregistered routes under pserve

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#1872]
I'd like to suggest a configuration option (.ini, pserve, etc) that would suppress pyramid.exceptions.ConfigurationExecutionError when a view is registered to a route that does not exist.

This request is for development work with the `--reload` pserve option.  Editing files in the wrong order will stop the server, instead of restarting it.

**Comment by mmerickel** [comment]
This bug is a symptom of a larger problem with any exception when saving a file via `--reload`. It should be solved at a higher level inside `pserve --reload` somehow.
