### ISSUE TITLE
suggestion: rename `includeme`

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#1874]
I've been doing some maintenance, and realized that `includeme` looks a little weird -- it's essentially a pyramid API hook that is tied to the Configurator, but has a very generic name.

I think it make make more sense as `pyramid_includeme` or `pyramid_configurator_hook`

**Comment by bertjwregeer** [comment]
:-1:

**Comment by mcdonc** [comment]
No, sorry, it's an API at this point.  While it might be idiosyncratic, it's not worth changing.
