### ISSUE TITLE
dot files not copied over from scaffold

### ISSUE THREAD

**Issue by aconrad** [Pylons/pyramid#1877]
I created a custom Pyramid scaffold that includes a `.env` file but this file doesn't get copied over to the final directory; probably because considered as a hidden file on Linux which is the platform I work on.

Shouldn't we consider copying *every* file from the scaffold directory, even the ones with leading dots? Especially since dotenv files are very common with services such as Heroku.

**Comment by mmerickel** [comment]
Yeah that doesn't sound right. I'd guess that's an artifact of some old pastescript behavior where it was avoiding .svn folders and the like.

**Comment by cguardia** [comment]
All dot files are avoided, in fact:

https://github.com/Pylons/pyramid/blob/master/pyramid/scaffolds/copydir.py#L158

Carlos de la Guardia

**Comment by sontek** [comment]
If you name it +dot+env the template engine should pick it up properly, they are special cased so you don't get things in there that you don't want

**Comment by sudarkoff** [comment]
Seems like this should be configurable.

**Comment by aconrad** [comment]
I moved `.env` to `+dot+env` and it worked. This should be documented at http://docs.pylonsproject.org/projects/pyramid//en/latest/narr/scaffolding.html

**Comment by stevepiercy** [comment]
How about adding a third bullet point as follows?

As you create files and directories within the template directory, note that:
...
- By default the template engine excludes files that begin with a period
  (e.g., `.env`) from being copied. To copy a dotted file, rename it in the
  source by replacing "." with "+dot+". For example, rename `.env` as
  `+dot+env` and the template engine will copy that file to its destination
  as `.env`.

**Comment by aconrad** [comment]
I just submitted https://github.com/Pylons/pyramid/pull/1878 -- @stevepiercy I just saw your suggestion, I'm happy to use your text if you prefer.

**Comment by stevepiercy** [comment]
Yours was more concise than mine. Thank you!
