### ISSUE TITLE
docs suggestion: testing and json

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#1881]
Some tests kept failing when I split some code out of a pyramid app into a new scaffold, and realized the both the docs on JSON and testing could probably use a decent tip--

If you're doing any sort of testing, you need to configure your json renderer as `sort_keys=True` to ensure you get repeatable strings.  (my issue was that i didn't register my custom renderer).

**Comment by mmerickel** [comment]
Or you could deserialize the json and compare the dictionaries. Ordering should not matter!
