### ISSUE TITLE
Cleanup old and stale branches

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid#1896]
Searching through the branches in the drop down to find the ones that are still active is getting harder and harder the more branches exist. Would it be possible for someone to go through and clean up all of the old stale branches?

**Comment by mmerickel** [comment]
I cleaned up a bunch that were merged into master but the rest will need to be case-by-case if you want to start a list of candidates. Some are good to keep for historical purposes probably.

**Comment by davisagli** [comment]
If in doubt you could rename to archive/[original branch name]
