### ISSUE TITLE
Pyramid quick tutorial teaches outdated Python package installation practices

### ISSUE THREAD

**Issue by miohtama** [Pylons/pyramid#1897]
Tutorial [here](http://docs.pylonsproject.org/projects/pyramid//en/latest/quick_tutorial/requirements.html) shows practices of

* Manually setting $VENV environment variable

* Using  `easy_install` instead of `pip`

Today there exist an [official and maintained Python package installation guide](https://packaging.python.org/en/latest/installing.html). The preferred package installation method is creating a virtualenv, activating it and then using `pip` to install the package.

Is there any particular reason why Pyramid tutorial differs from this or is it due to legacy?

See confusion e.g. here:

* http://stackoverflow.com/questions/32710376/unable-to-use-easy-install

**Comment by miohtama** [comment]
Ah found the mention at the very end of the page:

* Why easy_install and not pip? Pyramid encourages use of namespace packages, for which pip's support is less-than-optimal. Also, Pyramid's dependencies use some optional C extensions for performance: with easy_install, Windows users can get these extensions without needing a C compiler (pip does not support installing binary Windows distributions, except for wheels, which are not yet available for all dependencies).

I'll check if Windows installation have wheels in place yet.

**Comment by pauleveritt** [comment]
I keep promising everybody that I'll dig in deep on switching the tutorial to pip, testing on Windows, etc. Unfortunately each time I think about it, I expand the scope..."Oh, and I'll take on the work to generate wheels..." "Oh, I'll test across a bunch of Windows versions..." etc.

When you do the matrix of Python versions and operating systems, it balloons to being more than just some .rst edits.

**Comment by miohtama** [comment]
@pauleveritt: Do you remember out of your head which were the problematic packages?

**Comment by pauleveritt** [comment]
> On Sep 22, 2015, at 9:02 AM, Mikko Ohtamaa <notifications@github.com> wrote:
> 
> @pauleveritt <https://github.com/pauleveritt>: Do you remember out of your head which were the problematic packages?
> 
Sorry, no. If you’d like to work together on it this week, I can make some time. I just need a push. [wink]

—Paul
