### ISSUE TITLE
scaffold do not pin dependencies versions

### ISSUE THREAD

**Issue by gotcha** [Pylons/pyramid#1908]
Is there a reason why scaffolds do not pin dependencies versions through requirements.txt or through a buildout ?

**Comment by mcdonc** [comment]
Gotta turn it around on you and ask why they would.

**Comment by gotcha** [comment]
If I run `setup.py develop` today, I get pyramid 1.6a3 which is maybe not what I want.

**Comment by mcdonc** [comment]
But maybe is?

**Comment by bertjwregeer** [comment]
That's an issue with `easy_install` more-so than anything else. It shouldn't be installing alpha/beta software automatically.

If you run:

    pip install -e .

It will not install alpha/beta software.

**Comment by gotcha** [comment]
@bertjwregeer 

pyramid documentation recommends running `setup.py develop`. 
http://docs.pylonsproject.org/projects/pyramid//en/latest/tutorials/wiki/installation.html

**Comment by gotcha** [comment]
@mcdonc If scaffold pins latest stable version and I want sthing else like alpha or beta, I would pin it myself.

**Comment by bertjwregeer** [comment]
Yep. There's an open issue about that sort of stuff where we discuss whether to move toward showing pip or not: https://github.com/Pylons/pyramid/issues/1454.

Honestly Pyramid alpha releases might as well be release quality.

**Comment by mcdonc** [comment]
I'm going to close this, apologies.  This is a situation that won't be solved in the context of this issue.

**Comment by gotcha** [comment]
The point is not the quality of Pyramid releases, it is also to teach users that pinning versions make sense.

**Comment by stevepiercy** [comment]
If anything, this is merely a documentation clarity issue.

> pyramid documentation recommends running setup.py develop. http://docs.pylonsproject.org/projects/pyramid//en/latest/tutorials/wiki/installation.html

Not exactly. At the top of this wiki tutorial, note the [following statement](http://docs.pylonsproject.org/projects/pyramid/en/latest/tutorials/wiki/installation.html#before-you-begin)

> This tutorial assumes that you have already followed the steps in [Installing Pyramid](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/install.html), except do not create a virtualenv or install Pyramid.

This statement implies that the instructions to install Pyramid in this wiki tutorial apply only within the context of this wiki tutorial, and not in a general, all-purpose context. For the latter context, follow the appropriate documentation, [Installing Pyramid](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/install.html).
