### ISSUE TITLE
Python 3.5 test failures on master

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid#1973]
======================================================================
    FAIL: test_commit_conflict_with_two_includes (pyramid.tests.test_config.test_init.ConfiguratorTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/xistence/Projects/pyramid/pyramid/tests/test_config/test_init.py", line 1112, in test_commit_conflict_with_two_includes
        config.commit()
    pyramid.exceptions.ConfigurationConflictError: Conflicting configuration actions
      For: ('view', None, '', None, 'd41d8cd98f00b204e9800998ecf8427e')
        Line 526 of file /Users/xistence/Projects/pyramid/pyramid/util.py:
            return wrapped(self, *arg, **defaults)
        Line 526 of file /Users/xistence/Projects/pyramid/pyramid/util.py:
            return wrapped(self, *arg, **defaults)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/xistence/Projects/pyramid/pyramid/tests/test_config/test_init.py", line 1116, in test_commit_conflict_with_two_includes
        self.assertEqual(c1, 'includeme1')
    AssertionError: 'wrapper' != 'includeme1'
    - wrapper
    + includeme1
    
    
    ======================================================================
    FAIL: test_conflict_set_forbidden_view (pyramid.tests.test_config.test_init.ConfiguratorTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/xistence/Projects/pyramid/pyramid/tests/test_config/test_init.py", line 1172, in test_conflict_set_forbidden_view
        config.commit()
    pyramid.exceptions.ConfigurationConflictError: Conflicting configuration actions
      For: ('view', <class 'pyramid.httpexceptions.HTTPForbidden'>, '', None, 'd41d8cd98f00b204e9800998ecf8427e')
        Line 526 of file /Users/xistence/Projects/pyramid/pyramid/util.py:
            return wrapped(self, *arg, **defaults)
        Line 526 of file /Users/xistence/Projects/pyramid/pyramid/util.py:
            return wrapped(self, *arg, **defaults)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/xistence/Projects/pyramid/pyramid/tests/test_config/test_init.py", line 1175, in test_conflict_set_forbidden_view
        self.assertEqual(c1, 'test_conflict_set_forbidden_view')
    AssertionError: 'wrapper' != 'test_conflict_set_forbidden_view'
    - wrapper
    + test_conflict_set_forbidden_view
    
    
    ======================================================================
    FAIL: test_conflict_set_notfound_view (pyramid.tests.test_config.test_init.ConfiguratorTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/xistence/Projects/pyramid/pyramid/tests/test_config/test_init.py", line 1157, in test_conflict_set_notfound_view
        config.commit()
    pyramid.exceptions.ConfigurationConflictError: Conflicting configuration actions
      For: ('view', <class 'pyramid.httpexceptions.HTTPNotFound'>, '', None, 'd41d8cd98f00b204e9800998ecf8427e')
        Line 526 of file /Users/xistence/Projects/pyramid/pyramid/util.py:
            return wrapped(self, *arg, **defaults)
        Line 526 of file /Users/xistence/Projects/pyramid/pyramid/util.py:
            return wrapped(self, *arg, **defaults)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/xistence/Projects/pyramid/pyramid/tests/test_config/test_init.py", line 1160, in test_conflict_set_notfound_view
        self.assertEqual(c1, 'test_conflict_set_notfound_view')
    AssertionError: 'wrapper' != 'test_conflict_set_notfound_view'
    - wrapper
    + test_conflict_set_notfound_view
    
    
    ----------------------------------------------------------------------
    Ran 2467 tests in 6.874s
    
    FAILED (failures=3)

This will fix Python 3.5, but break all other Python versions:

    diff --git a/pyramid/util.py b/pyramid/util.py
    index 1ae7e6a..828f0d8 100644
    --- a/pyramid/util.py
    +++ b/pyramid/util.py
    @@ -548,13 +548,13 @@ def action_method(wrapped):
                 self._ainfo = []
             info = kw.pop('_info', None)
             # backframes for outer decorators to actionmethods
    -        backframes = kw.pop('_backframes', 0) + 2
    +        backframes = kw.pop('_backframes', 0) + 3
             if is_nonstr_iter(info) and len(info) == 4:
                 # _info permitted as extract_stack tuple
                 info = ActionInfo(*info)
             if info is None:
                 try:
    -                f = traceback.extract_stack(limit=3)
    +                f = traceback.extract_stack(limit=4)
                     info = ActionInfo(*f[-backframes])
                 except: # pragma: no cover
                     info = ActionInfo(None, 0, '', '')

**Comment by bertjwregeer** [comment]
Doing some "print()" style debugging:

    /Users/xistence/Projects/pyramid/pyramid/tests/test_config/test_init.py 1108 includeme2 config.add_view(view2)
    /Users/xistence/Projects/pyramid/pyramid/util.py 526 wrapper return wrapped(self, *arg, **defaults)
    /Users/xistence/Projects/pyramid/pyramid/util.py 557 wrapper f = traceback.extract_stack(limit=4)
    /Users/xistence/.pyenv/versions/3.5.0/lib/python3.5/traceback.py 201 extract_stack stack = StackSummary.extract(walk_stack(f), limit=limit)

Is the stack on Python 3.5

    /Users/xistence/Projects/pyramid/pyramid/config/__init__.py 798 include c(configurator)
    /Users/xistence/Projects/pyramid/pyramid/tests/test_config/test_init.py 1108 includeme2 config.add_view(view2)
    /Users/xistence/Projects/pyramid/pyramid/util.py 526 wrapper return wrapped(self, *arg, **defaults)
    /Users/xistence/Projects/pyramid/pyramid/util.py 557 wrapper f = traceback.extract_stack(limit=4)

Is the stack on Python 3.4

**Comment by mmerickel** [comment]
dup of #1899 afaict, but I'll leave it open since you're working on it

**Comment by bertjwregeer** [comment]
Kind of a dup, there are more test errors on 1.5.7 than there are on HEAD on master, hence why I didn't add stuff to that issue.

**Comment by bertjwregeer** [comment]
Python 3.5's whats new does list traceback changes: https://docs.python.org/3/whatsnew/3.5.html#whatsnew-traceback

**Comment by bertjwregeer** [comment]
Created an issue on the Python bug tracker: http://bugs.python.org/issue25379

**Comment by bertjwregeer** [comment]
@sontek dug this up: https://bugs.python.org/issue25108
