### ISSUE TITLE
show permission in pviews output

### ISSUE THREAD

**Issue by sontek** [Pylons/pyramid#1974]
It would be nice to be able to print what permission a view has declared on it in proutes/pviews and just in general when inspecting routes or views.   Right now there isn't a good way to know if you have all your permissions set properly.

**Comment by mmerickel** [comment]
I'm not saying this is perfect but there is a permission introspectable related to the view. Is this good enough or can you explain what is wrong with it?

https://github.com/Pylons/pyramid/blob/90cda8d937f40e83760683271622868b211eb819/pyramid/config/views.py#L1422-L1432

**Comment by stevepiercy** [comment]
While reviewing docs, I found this relevant passage where the permission of a View is displayed when given a URL.
http://docs.pylonsproject.org/projects/pyramid/en/master/narr/commandline.html#displaying-matching-views-for-a-given-url

But that is for a single URL, not all URLs as I think @sontek had in mind.

**Comment by mmerickel** [comment]
I guess this is a feature request to extend `pviews` with permission info. That seems reasonable to me.

**Comment by zupo** [comment]
I started looking into this by running ``pview`` locally and got the following

```bash
URL = /

    context: <ebn.acl.BlogFactory object at 0x10db18410>
    view name: 

    Route:
    ------
    route name: blog_list
    route pattern: /
    route path: /
    subpath: 

        View:
        -----
        foo.views.blog.BlogView.blog_list
        required permission = foo.view
        view predicates (layout = default)
```

See the ``required permission`` at the bottom? I guess this is already done then?

**Comment by mmerickel** [comment]
You're right. I think we could optionally add it to proutes as well (it only shows the first / highest rank view it finds for a given route). However I don't think it's very important. If you wanted to work on that though I could reopen it.
