### ISSUE TITLE
Reorder docs pages

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#2029]
The Pyramid docs pages have a peculiar flow that is more suited to a book than a website.

For example from the main docs page:
http://docs.pylonsproject.org/projects/pyramid/en/latest/

The Next page is:
http://docs.pylonsproject.org/projects/pyramid/en/latest/copyright.html

and so on.

I propose to reorder pages in `docs/index.rst` to:

* Give users a quicker entry point to tutorials and documentation, moving meta stuff to the end.
* Promote tutorials over narrative docs, because newbs want tutorials first (don't really know what they want), and experienced devs know how to find the information they need (know exactly what they want).

Thoughts?

**Comment by pauleveritt** [comment]
I think you have identified the main tension in trying to improve the organization of the artifacts: book versus website. Each attempt to rethink the space in between the entry point and an actual artifact (e.g. a tutorial) has run up against “yeh, but for the book…”

One possible alternative: consider the website generation a special case and override index.html using Sphinx’s html_additional_pages. Other formats (pdf, etc.) will continue using the status quo.

Alternatively, wait for TPC to be the web-based entry point.

—Paul

**Comment by stevepiercy** [comment]
FYI, we no longer produce a Pyramid documentation in PDF on RTD. We produce only HTML and epub versions on RTD. There were too many problems with generating the PDF via RTD, and because we don't have the people who know how to fix the issues, we abandoned support for generating PDF.

Is a book feasible, given our current situation? Regrettably, I don't think so. We have barely enough contributors to maintain the current documentation for HTML and epub outputs.

As far as waiting for TPC as the web entry point: let's say you enter the docs through a search engine. TPC as an entry point won't help in this scenario. I would hope that organizing the docs, as well as having a better site-wide navigation for the docs via its new Sphinx theme, would allow better navigation through the docs.

**Comment by mmerickel** [comment]
I can't actually tell you to do anything one way or the other here as I didn't write the vast majority of the docs but my opinion is that the book is unimportant versus a better web presence. In ever situation where I've seen a book published about a tech it was done by a third party and not the main source of information in the project.

**Comment by bertjwregeer** [comment]
I think docs re-order would be a good idea. Yeah, it'll make it less possible to build a book in PDF form, but as steve mentioned, we no longer build the PDF, and the last book that was published from the PDF was Pyramid 1.0: http://www.amazon.com/gp/product/0615445675

**Comment by ismail-s** [comment]
I did use the pdf when learning to use pyramid, but that was more to save mobile data. But tbh I would expect things like https://play.google.com/store/apps/details?id=com.ideashower.readitlater.pro&hl=en would have sufficed.

**Comment by stevepiercy** [comment]
@ismail-s HTML (zipped) and ePub formats are available on RTD for users who wish to save on mobile data:
http://readthedocs.org/projects/pyramid/downloads/

This feature is provided out of the box by RTD.

**Comment by pauleveritt** [comment]
Steve, do you think we have enough conversation to make the decision? (Namely, that the core docs are no longer limited to what can render to a book.)

Or, do you think we need to broadcast the intention, e.g. on the mailing list, and let it simmer a bit?

—Paul

**Comment by bertjwregeer** [comment]
@pauleveritt I have a bad feeling this is going to become a bike shed painting moment if we do that.

**Comment by stevepiercy** [comment]
@pauleveritt I don't think this Issue merits discussion on pylons-discuss. I'll start a punchlist of tasks to propose changes, and keep the conversation going here.

**Comment by ismail-s** [comment]
I tried the ePub files but preferred the pdf as I could pinch and zoom.
With the ePub in Google play books app, I couldn't. Ie just my choice of
apps

**Comment by stevepiercy** [comment]
@ismail-s You can generate a PDF locally. Clone the repo, follow instructions in [HACKING.txt](https://github.com/Pylons/pyramid/blob/master/HACKING.txt), then cd into `docs` to issue the following:

``` bash
make latexpdf SPHINXBUILD=$VENV/bin/sphinx-build
```

We don't maintain it on RTD because the [maintenance burden to keep up with PDFs on RTD](https://github.com/rtfd/readthedocs.org/issues?utf8=%E2%9C%93&q=is%3Aissue+pdf+) exceeds the meager benefit.

**Comment by stevepiercy** [comment]
I decided that a punch list would be counterproductive compared to PR #2086 on a new branch so folks could build the docs locally and see for themselves how it would flow. Please send feedback.

**Comment by stevepiercy** [comment]
Closed by #2086
