### ISSUE TITLE
latin encoded urls raise 500

### ISSUE THREAD

**Issue by shredding** [Pylons/pyramid#2047]
Please double check with this ticket: https://code.djangoproject.com/ticket/25623

I testet on a pyramid app as well and it raises "URLDecodeError: 'utf8' codec can't decode byte 0xf6 in position 11: invalid start byte" (urldispatch.py, line 86)

http://www.pylonsproject.org/Raumh%F6he.htm

**Comment by shredding** [comment]
For clarification, just add `Raumh%F6he` to any url of a pyramid powered app and it will raise a server error.

**Comment by bertjwregeer** [comment]
Yeah, this is an issue in WebOb: https://github.com/Pylons/webob/issues/161

**Comment by bertjwregeer** [comment]
Also see: https://github.com/Pylons/pyramid/issues/1374

**Comment by mmerickel** [comment]
Closed as a dup of #1374.
