### ISSUE TITLE
Ability to introspect calls to config.include() for auditing purpose

### ISSUE THREAD

**Issue by aconrad** [Pylons/pyramid#2048]
From IRC log:

> 09:40 (aconrad) hi, is there a way I can query Pyramid via its API to know how config.include() was called? This would be meant for auditing purpose. For example, if I require all my Pyramid apps to include a anti-csrf library, checking the output of "pip freeze" to see if the library is installed in the virtualenv isn't enough, I also need to ensure that is has been properly included via
> 09:40 (aconrad) config.include("anti-csrf-lib"). Of course, I could try to grep the source for each of the projects, but that feels cumbersome / error-prone. If I could just write a little pshell-like script to query the Pyramid API, that would be much more elegant.
> 09:41 raydeo: if your lib adds some data to the introspector then you can pull that out after config time... otherwise there's not many options
> 09:42 raydeo: pyramid doesn't keep track of any info right now about what was included
> 09:43 raydeo: except data added to the introspector
> 09:43 inklesspen: hm. a mode in the configurator that logs all method calls would be pretty cool
> 09:44 raydeo: well config.include could _probably_ be updated to record an introspectable about what was included as well
> 09:45 raydeo: logging commit cycles might be cool though

**Comment by mmerickel** [comment]
I think it's worth adding an introspectable to the introspector that mentions what modules were included.

HOWEVER

The real solution here is to make a proper conforming module in pyramid where you register your own introspectable in the introspector. Then you can introspect and make sure it's there.

```
def includeme(config):
    intr = config.introspectable('sm-anti-csrf', None, 'sm-anti-csrf', 'sm-anti-csrf')
    def register():
        # do stuff here to register your csrf
    config.register(None, register, introspectables=[intr])
```

**Comment by mmerickel** [comment]
I've been thinking about this a bit. There are some quirks in the configurator such as only the first time per-commit-cycle that a function is included will it actually be executed. However, we could easily build an introspectables for each function that is included.

**Comment by mmerickel** [comment]
The right answer here is to add an introspectable for the library or action you want to query.
