### ISSUE TITLE
In effective_principals, the userid should be tagged

### ISSUE THREAD

**Issue by olemoign** [Pylons/pyramid#2060]
In pyramid.authentication.CallbackAuthenticationPolicy.effective_principals, the userid should not be copied as is but tagged to make sure that it cannot collide with a permission.

In the example of ACL on http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html a user calling himself 'group:editors' would gain access to all parts of the app allowed by this permission. Instead of having to sanitise all ids corresponding to a permission, it would be nice if Pyramid tagged the userid (could be 'userid:' + userid).

**Comment by mmerickel** [comment]
Yes, this has come up before. The docs were updated to be clear the userid was added to the effective principals in each policy. We, however, can't change the current behavior as it'd be a severe incompatibility. It's easy to define your own entire principals list by simply subclassing the policy and overriding the effective principals with your own. See the new example added to 1.6 documentation: http://docs.pylonsproject.org/projects/pyramid/en/1.6-branch/narr/security.html#extending-default-authentication-policies

**Comment by olemoign** [comment]
Yes, that's what I'm going to do. Maybe we could change the behaviour for version 2.0 ? I fear people not thinking this through, most of them using the standard AuthTktAuthenticationPolicy, will have problems.
Thank you for your super quick answer.

**Comment by mmerickel** [comment]
I'd consider changing it in 2.0 but that isn't even on the roadmap right now. :-) I added a note to the TODO.txt.

I'll close this with the following suggestion: don't use user-input-based attributes in the actual userid. Rather use a server-generated number or prefix the result from authenticated_userid.
