### ISSUE TITLE
Docs remove section from hybrid: registering default view

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#2067]
Should this deprecated section be removed in 1.6/master, per the warning?

Registering a Default View for a Route That Has a view Attribute
http://docs.pylonsproject.org/projects/pyramid/en/master/narr/hybrid.html#registering-a-default-view-for-a-route-that-has-a-view-attribute

If not, then what version? Suggest adding this issue to a future milestone.

**Comment by bertjwregeer** [comment]
It's not listed here: https://github.com/Pylons/pyramid/blob/master/TODO.txt#L114

Is there a future version where this will be changed in the code?

**Comment by stevepiercy** [comment]
It actually appears to have already been done. I found a couple of references in HISTORY.txt:

* https://github.com/Pylons/pyramid/blob/master/HISTORY.txt#L3258-L3281 <-- Looks like it was already removed from Pyramid, but not from the docs.
* https://github.com/Pylons/pyramid/blob/master/HISTORY.txt#L3258-L3281

Which led me to compare the source on 1.5 vs. 1.4:

* https://github.com/Pylons/pyramid/blob/1.5-branch/pyramid/config/routes.py#L25-L43
* https://github.com/Pylons/pyramid/blob/1.4-branch/pyramid/config/routes.py#L24-L49

So it looks like the section in the docs should be removed from branches 1.5, 1.6, and master.

Can someone can verify my findings?

**Comment by mmerickel** [comment]
Yes those parameters are no longer supported on `config.add_route`.

**Comment by stevepiercy** [comment]
Thanks for confirming @mmerickel. This is done.
