### ISSUE TITLE
Tox tests for python 2.6 fail due to WebTest requiring OrderedDict

### ISSUE THREAD

**Issue by RaHus** [Pylons/pyramid#2071]
OrderedDict was included in python 2.7 and WebTest requires it, so tests in python 2.6 fail with ImportError. We should include a backported version of OrderedDict in setup.tests_require when py_version is 2.6

**Comment by stevepiercy** [comment]
@RaHus thanks for the explanation, and I agree. FWIW, I noticed TravisCI errors that recently cropped up on the branches master and 1.6-branch:
https://travis-ci.org/Pylons/pyramid/branches

Would you please submit a PR? You can use tox locally or watch TravisCI after submitting a PR to see results.

**Comment by RaHus** [comment]
@stevepiercy Sure, i am on it

**Comment by RaHus** [comment]
@stevepiercy Looks like its working now, should i touch CHANGES.txt also?

**Comment by stevepiercy** [comment]
LGTM. I'd like one more core contributor to review.

Touching CHANGES.txt under "Bug Fixes" would be appropriate.

**Comment by RaHus** [comment]
tseaver mentioned in the [PR](https://github.com/Pylons/pyramid/pull/2075#issuecomment-153348455) that this is actually a WebTest [packaging bug](https://github.com/Pylons/webtest/issues/143) and it should be fixed upstream.
