### ISSUE TITLE
framework should support non html exception responses

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#2136]
Let's reference the starter template:

    @view_config(route_name='home', renderer='templates/mytemplate.pt')
    def my_view(request):
        return {'project': 'ExceptionsTest'}

And add a JSON route to /json

    config.add_route('json', '/json')

    @view_config(route_name='json', renderer='json')
    def my_view(request):
        if request.params.get('fail', False):        
            raise HTTPNotFound()
        return {'success': True, }

So now this will return a JSON document:

    http://0.0.0.0:6543/json

But this will return an HTML error document

    http://0.0.0.0:6543/json?fail=1

I think in an ideal world, one should at-least be able to do something like this:

     raise HTTPNotFound(response_dict)

Where `response_dict` (could be kwarg) is info that is JSON encoded for the client.

Ideally, one would be able to override this in the exception handling view. (ie, someone might want to nest the `response_dict` into a dict that aggregates other info, or the exception view otherwise operates on headers).

As an example of this, on an Error the Facebook and Twitter API's will may either return a JSON encoded dict and/or have some errors in the headers. 

It currently takes a decent understand of Pyramid to make applications work like this.  From discussions on the archives, many people seem to just return a dict that contains "error" in a  HTTP 200 OK response.  That will get awkward and creates technical debt.

(Not sure how to best handle this, bringing it up for discussion here)

**Comment by bertjwregeer** [comment]
`HTTPNotFound()` are all sub-classed from `Response` in WebOb, and the `**kw` arguments are already passed through, so this is completely valid:

```
resp  = HTTPNotFound(json_body={})
assert(resp.body, b'{}')
```

I have in various places `raise HTTPBadRequest(json_body={'error': 'Invalid X, Y, or Z'})`:

    xistence$ curl -v -H "Accept: application/json" -H 'Content-Type: application/json' -X PUT -d '{}' http://alexandra.local:6543/api/v1.0/devices/
    *   Trying 10.10.10.205...
    * Connected to alexandra.local (10.10.10.205) port 6543 (#0)
    > PUT /api/v1.0/devices/ HTTP/1.1
    > Host: alexandra.local:6543
    > User-Agent: curl/7.43.0
    > Accept: application/json
    > Content-Type: application/json
    > Content-Length: 2
    > 
    * upload completely sent off: 2 out of 2 bytes
    < HTTP/1.1 400 Bad Request
    < Content-Length: 38
    < Content-Type: application/json; charset=UTF-8
    < Date: Sun, 15 Nov 2015 23:34:32 GMT
    < Server: waitress
    < 
    * Connection #0 to host alexandra.local left intact
    {"error":"Device could not be saved."}

**Comment by mmerickel** [comment]
The proper way to do any error handling in pyramid is to raise exceptions and convert those exceptions into responses. You can then return json responses using json renderer from those exception views. You can use `json_body` for this but in my apps I prefer to be a bit more abstract about it, using a custom error class with a status code, error and description. The exception view then translates that into a response. I find this to be much simpler than using the custom HTTP* subclasses and leaves you less-coupled to the actual response that will be generated.

**Comment by bertjwregeer** [comment]
Interesting tidbit, what @jvanasco is proposing can almost be done. `detail` is the first `kwarg` on an HTTPException, and thus calling `HTTPNotFound(some_dict)` will simply set `.detail` on the object.

Now if you use a custom exception view to capture all exceptions, he can pull `.detail` from the `context` that is passed in to the exception view. Since `context` in this case is a full on Response object, he can use the information in `detail` to modify the response however necessary.

    @view_config(context=HTTPException)
    def exception_view(context, request):
        error_details = context.detail

        if error_details:
            context.json_body = error_details
        else:
            context.body = b'Party on!'

        return context

**Comment by jvanasco** [comment]
It's great that this seems to be more of a docs deficiency than framework problem.  This is something I've seen pop up on the list and stack-overflow a few times, and most people solve it with a HTTPOK response (which IMHO is very wrong).  

I personally do something closer to what @mmerickel does.  My concern is really for the people who often ask questions like this, and the trend/concept of using multiple renderers in Pyramid (like this edited example from the cookbook):

    @view_config(route_name="info", renderer="info.mak")
    @view-config(route_name="info_json", renderer="json")
    def info(request):
        raise HTTPUnauthorized()
        return {}

Looking at @bertjwregeer's great example directly above, it seems like one would need to catch everything in a single exception view, and then examine the `context` to handle it best.   This seems like a harder task for new Pyramid users.

Could Pyramid this be handled with multiple exception views, with one specialized for json in it's `view_config`?

**Comment by bertjwregeer** [comment]
The `view_config` for the exception view can have predicates just like any other other view.

**Comment by jvanasco** [comment]
Sounds like the docs just need to expand the "Exceptions" section to cover more some more common "in the wild" usage patterns.

**Comment by mmerickel** [comment]
In addition to http://docs.pylonsproject.org/projects/pyramid/en/1.6-branch/narr/views.html#custom-exception-views ? I think the example there is fairly straightforward and even shows using a predicate `route_name` in the exception view.

**Comment by jvanasco** [comment]
@mmerickel Yeah. I've read that a few times.  I think we still need something that explicitly shows "How to handle exceptions for JSON views"...  and perhaps some best-practices that illustrate "why" and "when" -- not just "how".  Issues like this come up a lot.

Remember, the audience of people who are looking at this have little knowledge of Pyramid and are apt to interpret things incorrectly, using their own experiences as a framework for understanding.  When you read that, your familiarity lets you instantly know how to connect the dots.  When people who are new to Pyramid read it (or even those who have a lot of experience, just not with the internals) -- they simply don't see the bigger picture.

@bertjwregeer I'd be happy to give it a stab once I understand more (or someone more familiar with me can set me straight on anything).

**Comment by stevepiercy** [comment]
PRs for docs? om nom nom!

As an aside, I agree that there should be more "why" and "when" throughout the docs. For example, [should our tutorials use single files or subpackages](https://github.com/Pylons/pyramid/pull/2024#issuecomment-156689931)? It might be personal preference, but there might be advantages or disadvantages, too.

**Comment by mmerickel** [comment]
Maybe you just need to write a json-based api tutorial similar to the pyramid_blogr if you want to address a bunch of issues with getting started at once?

**Comment by bertjwregeer** [comment]
@mmerickel ++

@jvanasco I am not sure what more there is to understand. You have used Pyramid for a while now, how do you do your view matching?

**Comment by jvanasco** [comment]
Ok.  I'm going to backtrack for a second.

Let's take the example from the cookbook on a view that handles JSON+Template view

I've mocked it up below.

There doesn't seem to be an obvious way to raise an error in that code block and have it adapt to the right rendering method.   

I've spent a bit of time working on this using pdb, and I can't seem to find any info on the invoked renderer when we get to the exception view.

see below.

---

    from pyramid.view import view_config
    from pyramid.httpexceptions import HTTPNotFound, HTTPUnauthorized
    from pyramid.renderers import render_to_response


    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

    #
    # image we have 2 urls handled by the same view_config
    #
    #    config.add_route('info', '/info')
    #    config.add_route('info_json', '/info.json')

    @view_config(route_name="info", renderer="templates/info.pt")
    @view_config(route_name="info_json", renderer="json")
    def info(request):
        if request.params.get('fail', False):        
            raise HTTPUnauthorized()
        return {}


    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

    #
    # We can't set up different exception views.
    # This won't work, because the view_config sets up by the `context`
    # if enabled, this will raise:
    #       pyramid.exceptions.ConfigurationConflictError: Conflicting configuration actions

    # @view_config(context=HTTPUnauthorized, renderer='json')
    def unauthorized_json(context, request):
       return {'success': False}

    # @view_config(context=HTTPUnauthorized, renderer="templates/exception/unauthorized.pt")
    def unauthorized_default(context, request):
       return {'success': False}


    # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

    #
    # so let's try to set up a singular exception view.  like @bertjwregeer suggested
    # 

    @view_config(context=HTTPUnauthorized)
    def central_exception_view(context, request):
        """
        we're in a valid configurator
        BUT
        we don't have a way to tell what the renderer is.

            `request.matched_route`
        """    
        print "central_exception_view"
        print "request.matched_route"
        print dir(request.matched_route)
        print request.matched_route.__dict__
        print "context"
        print dir(context)
        print context.__dict__

        return context

**Comment by davisagli** [comment]
On 11/16/15 3:33 PM, Jonathan Vanasco wrote:
>
> Ok. I'm going to backtrack for a second.
>
> Let's take the example from the cookbook on a view that handles 
> JSON+Template view
>
> I've mocked it up below.
>
> There doesn't seem to be an obvious way to raise an error in that code 
> block and have it adapt to the right rendering method.
>
> I've spent a bit of time working on this using pdb, and I can't seem 
> to find any info on the invoked renderer when we get to the exception 
> view.
>
> see below.
>
> ------------------------------------------------------------------------
> |from pyramid.view import view_config from pyramid.httpexceptions 
> import HTTPNotFound, HTTPUnauthorized from pyramid.renderers import 
> render_to_response # 
> =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- 
> # # image we have 2 urls handled by the same view_config # # 
> config.add_route('info', '/info') # config.add_route('info_json', 
> '/info.json') @view_config(route_name="info", 
> renderer="templates/info.pt") @view_config(route_name="info_json", 
> renderer="json") def info(request): if request.params.get('fail', 
> False): raise HTTPUnauthorized() return {} # 
> =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- 
> # # We can't set up different exception views. # This won't work, 
> because the view_config sets up by the `context` # if enabled, this 
> will raise: # pyramid.exceptions.ConfigurationConflictError: 
> Conflicting configuration actions # 
> @view_config(context=HTTPUnauthorized, renderer='json') def 
> unauthorized_json(context, request): return {'success': False}|

Try putting accept='text/json' in the view_config params for this one...

> |# @view_config(context=HTTPUnauthorized, 
> renderer="templates/exception/unauthorized.pt") def 
> unauthorized_default(context, request): return {'success': False} |

...and accept='text/html' in the view_config params for this one. The 
renderer doesn't affect which view is chosen, it just affects what 
pyramid does with the return value of the view.

**Comment by mmerickel** [comment]
There is no renderer info... the renderer is implied by the predicates. Your exception view must have appropriate predicates to select the type of response. Exception views are not dependent on the original view selected... they are their own view.

**Comment by bertjwregeer** [comment]
Your exception view can use `route_name` as well... then again, I have a single route, and use accept to decide between json/HTML.

**Comment by bertjwregeer** [comment]
Also, your example has the exception view returning a dict() which turns the whole thing into a 200 OK.

**Comment by jvanasco** [comment]
I totally understand what you are saying (@mmerickel  and @bertjwregeer).

My frame of reference is coming from someone who has used many frameworks in many languages, and a tendency over recent years for multi-format views (such as the mako+jason example) to be able to adapt errors.    What I'm trying to illustrate is that Pyramid isn't making this convention easy.  While a Pyramid view can support handling a mako or json renderer by simply returning a dict on success, if there is an Error/Exception we are now dealing with something incredibly more complicated.

**Comment by bertjwregeer** [comment]
@jvanasco Have you looked at this PR: https://github.com/Pylons/pyramid/pull/1378

It allows Pyramid to return JSON if the client accepts it.

**Comment by mmerickel** [comment]
I think this issue will be closed by https://github.com/Pylons/pyramid/issues/2406
