### ISSUE TITLE
Possibly out-of-date docs -- custom renderers

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#2142]
The following docs all reference `system`:

* http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/renderers.html
* http://docs.pylonsproject.org/projects/pyramid/en/latest/api/renderers.html
* https://pyramid-cookbook.readthedocs.org/en/latest/templates/customrenderers.html

In practice, this seems to actually be a pyramid event, and specifically a  `BeforeRender` instance.

Should the docs be updated to that?

**Comment by mmerickel** [comment]
I'm sorry I don't follow. Are you referring to the use of the `value, system` signature? In that context the `system` is not a `BeforeRender` instance. It's a dict with documented properties.

http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/templates.html#system-values-used-during-rendering

**Comment by jvanasco** [comment]
Yep -- the `system` in the renderers.  

I stuck this example from the docs into the starter template, and added a few lines of debugging:

    import pdb

    class RendererFactory:
        def __init__(self, info):
            """ Constructor: info will be an object having the
            following attributes: name (the renderer name), package
            (the package that was 'current' at the time the
            renderer was registered), type (the renderer type
            name), registry (the current application registry) and
            settings (the deployment settings dictionary). """

        def __call__(self, value, system):
            """ Call the renderer implementation with the value
            and the system value passed in as arguments and return
            the result (a string or unicode object).  The value is
            the return value of a view.  The system value is a
            dictionary containing available system values
            (e.g., view, context, and request). """
            print "-------------------"
            print type(system)
            print system
            print "-------------------"
            pdb.set_trace()

    def includeme(config):
        config.add_renderer(name='amf', factory= RendererFactory)

This is the output:

    -------------------
    <class 'pyramid.events.BeforeRender'>
    {'renderer_info': <pyramid.renderers.RendererHelper object at 0x106691b50>, 'renderer_name': 'amf', 'context': <pyramid.traversal.DefaultRootFactory instance at 0x1066c38c0>, 'req': <Request at 0x1066ad510 GET http://0.0.0.0:6543/>, 'request': <Request at 0x1066ad510 GET http://0.0.0.0:6543/>, 'view': <function my_view at 0x106693320>}
    -------------------

I was working on a custom render factory and slipped into pdb to figure out what "system" was.  I found an event, which makes the name `system` seem odd.  I checked the docs, and it has all the same attributes.

Were these 2 objects consolidated at some point?

I also feel like this is familiar, but there's no history in github so maybe I'm having a stroke.

**Comment by mmerickel** [comment]
The fact that it's an instance of `BeforeRender` is an implementation detail. Pyramid is pretty clear on the keys you should expect in the system dictionary.
