### ISSUE TITLE
pshell does not seem to detect ipython or bpython anymore

### ISSUE THREAD

**Issue by russellballestrini** [Pylons/pyramid#2163]
http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/commandline.html#ipython-or-bpython

**Comment by stevepiercy** [comment]
Please include the steps to reproduce, including how you installed Pyramid.

This smells like you install Pyramid 1.6. See https://github.com/Pylons/pyramid/blob/master/CHANGES.txt and http://stackoverflow.com/questions/33872009/pshell-cant-detect-bpython-or-ipython

Also view the docs on `master` or `1.6-branch` (`latest` infers "stable release", or 1.5.7).
http://docs.pylonsproject.org/projects/pyramid/en/master/narr/commandline.html#ipython-or-bpython

**Comment by russellballestrini** [comment]
Thank you for the fast reply, I didn't know it was removed.  I see now that I need to teach Pyramid about  alternative shells:

http://docs.pylonsproject.org/projects/pyramid/en/master/narr/commandline.html#alternative-shells

My project is old and was started from sqlalchemy scaffold from an older version before this new package / binding was needed.

Closing as invalid.
