### ISSUE TITLE
Should production.ini in starter scaffold use 127.0.0.1 vs. 0.0.0.0?

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#2170]
The starter scaffold uses 127.0.0.1 as the default IP in development.ini, which was a recent change from 0.0.0.0. Should production.ini use 127.0.0.1 as well?

**Comment by mmerickel** [comment]
That depends on the setup, but by default none of the tutorials are running behind a proxy so the server needs to be exposed to the outside. In development most people are working on their local computer so `127.0.0.1` is more secure.
