### ISSUE TITLE
AssetResolver.resolve() returns relative path

### ISSUE THREAD

**Issue by jenstroeger** [Pylons/pyramid#2184]
Given an asset resolver `resolver = pyramid.path.AssetResolver(None)` and trying to resolve an asset path like `srv:path/to/resource` results in a relative path `./srv/path/to/resource`. I would have expected an absolute path like `/path/to/srv/path/to/resource`.

The current workaround for this problems on the caller side is `os.path.abspath(resolver.abspath())` which returns the file system's real absolute path of the resource.

Looking at [the source](https://github.com/Pylons/pyramid/blob/master/pyramid/path.py#L199) the package name is split from the path, but not actually resolved into an absolute host path. I'm not familiar enough with the code to fix this, but a `os.path.abspath()` would be needed either in AssetResolver or the PkgResourcesAssetDescriptor of this module.

**Comment by mmerickel** [comment]
yes, the `PkgResourcesAssetDescriptor.abspath` needs to actually return an `abspath`. For some reason the tests doesn't confirm this so we need to update that as well.
