### ISSUE TITLE
HACKING.txt omits 3.4, 3.5, pypy3

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#2192]
Is this an oversight or deliberate? Missing 3.4, 3.5, and pypy3:
https://github.com/Pylons/pyramid/blob/master/HACKING.txt#L127-L130

If an oversight, for what versions of Pyramid are compatible with various versions of Python?

I presume tox.ini is the official guide of Python compatibility for each version of Pyramid:

* https://github.com/Pylons/pyramid/blob/master/tox.ini
* https://github.com/Pylons/pyramid/blob/1.6-branch/tox.ini
* https://github.com/Pylons/pyramid/blob/1.5-branch/tox.ini
* https://github.com/Pylons/pyramid/blob/1.4-branch/tox.ini

Also there isn't much in the way of announcing the latest Python compatibility in changes. This is the most recent mention I found:

https://github.com/Pylons/pyramid/blob/1.3-branch/CHANGES.txt#L677

**Comment by mmerickel** [comment]
Yes the tox is the official support. We also keep the trove classifiers up to date in the `setup.py`.

**Comment by stevepiercy** [comment]
Fixed in #2193, #2195, #2197.
