### ISSUE TITLE
Update whatsnew-1.6 to include PR 1498

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid#2211]
A user on the #pyramid channel had code such as the following:

```
@view_config(context=HTTPNotFound, renderer='/templates/404.jinja2')
def http_not_found(self, request):
    request.response.status = 404
    return  {}
```

Granted that is unpythonic, but it was raising the unbound method error, and there was no good information into what changed to cause the error.

**Comment by mmerickel** [comment]
Sorry, what? Is the title relevant to the body of this issue?

**Comment by bertjwregeer** [comment]
Yes, the whatsnew didn't include the changes made in PR 1498, and a user that had the function listed above which caused the error that was added in PR 1498 due to the function checking to see if the first argument to the function is "self".

**Comment by bertjwregeer** [comment]
Read from: https://botbot.me/freenode/pyramid/2016-01-04/?msg=57243380&page=7 down for more information.

**Comment by bertjwregeer** [comment]
Thank you @mmerickel
