### ISSUE TITLE
Update glossary in docs to point to correct location for docs

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid#2215]
See http://docs.pylonsproject.org/projects/pyramid/en/latest/glossary.html#term-pyramid-cookbook

It seems that RTD no longer supports underscores in their matching for project names, so we have to replace _ with -.

http://docs.pylonsproject.org/projects/pyramid_cookbook/en/latest/

becomes

http://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/

Although pyramid_debugtoolbar's link works fine. WTF?

**Comment by mmerickel** [comment]
RTD actually does redirect things properly. The issue is that the link you pointed at is missing a trailing slash which is apparently necessary.

**Comment by bertjwregeer** [comment]
Listen to @mmerickel and not me =)

**Comment by stevepiercy** [comment]
hehe. OK, I got this one in my queue. Thanks for finding it.
