### ISSUE TITLE
pserve: don't serve a valid webpage, if there's a syntax error

### ISSUE THREAD

**Issue by kengruven** [Pylons/pyramid#2249]
#2044 makes a neat improvement: if there's a SyntaxError, pserve won't reload the app.

This is great for development, because it means when I temporarily break something, I don't have to go back and restart the server.

But it's also bad for development, because if I accidentally break something and don't realize it (e.g., by running my tests), then I could hit "reload" in my browser, and it seems like everything is fine, when in fact my app is completely broken.

I would like the best of both of these worlds.  Like #2044, the `pserve --reload` process should never crash.  But like Pyramid 1.5.6, if I do mess something up, it should be visible.  For example, while `syntax_error_files` is non-empty, every request could return an error code like HTTP 500.

**Comment by mmerickel** [comment]
Yes, this is on the roadmap for pyramid 1.8 once the current pserve deprecation period is over. The plan is to rewrite things such that the monitor does not crash but to allow the underlying app to crash. It's deemed too complicated to do right now with all the forking that's going on already.

**Comment by mmerickel** [comment]
Closing this issue and adding #2250 to the roadmap.
