### ISSUE TITLE
fix pserve --reload to avoid crashing the monitor

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#2250]
In Pyramid 1.6 we deprecated the daemon functionality in pserve to simplify the codebase. As a result it should be easier to rewrite the reloading functionality into a master-slave such that the monitor keeps running and forks the app, restarting it when it crashes.
- [x] Remove daemon functionality.
- [x] Rewrite loader to use multiprocessing.
- [x] Update reloader to avoid crashing the monitor.
- [x] Remove syntax error checking in favor of crashing.
- [x] Get all of this working on windows (https://github.com/Pylons/hupper/issues/4).
- [x] Merge the `pserve-reloader-revamp` [1] branch (#2805).

Removing syntax error checking is debatable but I'm in favor of some more user-facing error reporting instead of the current message in the console without actually crashing (#2249).

[1] https://github.com/mmerickel/pyramid/tree/pserve-reloader-revamp

**Comment by mmerickel** [comment]
So there is some precedent for this in wsgiwatcher [1] and reloadwsgi [2].

Carl Meyer was nice enough to basically give me full control of wsgiwatcher to do with what we'd like. If nothing else it shows an excellent approach to using multiprocessing alongside watchdog to support inotify-based reloading. I don't really have any issue with adding a dependency on watchdog if we wish as it appears to fallback gracefully on alternate platforms.

It feels a little heavy to add a new dependency to pyramid just for handling `pserve --reload` (as production uses of `pserve` do not require this library, but it'd also be better to just work than to require users to install a new dependency in development via `pip install pyramid[debug]` or something.

There are 2 approaches available to us that I think are both viable:

1. Copy wsgiwatcher into pserve and make pserve work!

2. Update wsgiwatcher to support some hooks that pserve can use to pass it a callable that loads the wsgi app and leave all the reloading logic inside wsgiwatcher. Then release a version of wsgiwatcher that pyramid depends on.

I'd like to hear some ideas here because I've gone back and forth about 10 times in the last week deciding whether the new dependency is worthwhile (I think pip makes extra deps mostly a non-issue so right now I'm leaning toward option 2).

[1] https://github.com/carljm/wsgiwatcher/blob/master/wsgiwatcher/watcher.py

[2] https://bitbucket.org/dholth/reloadwsgi/src/7a251ecd21b517a1a3bffd98a2e5ae090e7d6640/reloadwsgi.py?at=default&fileviewer=file-view-default

**Comment by mmerickel** [comment]
@davisagli do you have any thoughts on this? I saw that you're listed as an author on wsgiwatcher.

**Comment by mmerickel** [comment]
I went ahead and made a WIP branch [1] to mess around with this just to verify some assumptions. Fortunately it was really really easy. A couple notes:

- watchdog has a pretty large number of open issues in its tracker and hasn't had a release in 1.5 years. This concerns me as it compiles C extensions (including pyyaml for use with its cli, but also stuff for inotify event tracking). I'm -1 on adding this to Pyramid's dependency chain in its current state.

- wsgiwatcher actually has nothing to do with wsgi and it'd be cool if it could be improved as just a great package for performing monitoring (I know I would like to use this myself in some other non-wsgi packages like my worker queue runner).

- rewrite wsgiwatcher or just write something new that follows the same idea but goes back to using stupid polling like pserve currently does. Also add support for waiting for saves before restarting (currently wsgiwatcher will continually and quickly restart until the error is fixed).

[1] https://github.com/mmerickel/pyramid/tree/pserve-reloader-revamp

**Comment by davisagli** [comment]
I worked on wsgiwatcher with Carl at the PyCon 2015 sprint, but haven't thought about it since so would need to reevaluate where it's at. That's a pity that watchdog isn't maintained; the cross-platform support for event-based approaches looks like a big can of worms, but polling seems to makes my CPU and fan run hard when there are a lot of files to watch.

**Comment by mmerickel** [comment]
Just FYI I've basically merged wsgiwatcher with the old pserve code and come up with hupper [1]. The pserve-reloader-revamp branch [2] is using hupper.

Hupper is suffering from a couple issues that wsgiwatcher also suffers from and I could really use some help resolving them.

1) I'm using a pipe between the parent and the child process in order to allow the child to detect when the parent dies. From what I can tell it's the only way to do this reliably on non-posix platforms (windows). However, it's not working and I can't figure out why.

2) hupper is using multiprocessing and it closes stdin on the subprocess. This means that pdb does not work in the subprocess. I think I need to forward stdin to the subprocess somehow but I could use some help figuring that out.

[1] https://github.com/mmerickel/hupper
[2] https://github.com/mmerickel/pyramid/tree/pserve-reloader-revamp

**Comment by mmerickel** [comment]
Got those issues fixed thanks to @bertjwregeer but they are not working on windows. No idea why, but could use some help from anyone interested!

**Comment by mmerickel** [comment]
Closed via #2805.

**Comment by SowingSadness** [comment]
@mmerickel 
![image](https://cloud.githubusercontent.com/assets/576443/21332211/049df9b2-c658-11e6-92ef-4e25aeb07390.png)
nice fix )

**Comment by mmerickel** [comment]
@SowingSadness What are you trying to tell me here? What are you using to test this? Have you actually read this issue or tried out the master branch of pyramid?

**Comment by SowingSadness** [comment]
@mmerickel sorr. I did not spent enough time to read all comments.
In my humble opinion this bug come from this changes.
But I can wrong, cos used search by "pserver" keyword
![image](https://cloud.githubusercontent.com/assets/576443/21334165/431c0d60-c666-11e6-8432-edcefaf9ab54.png)

**Comment by mmerickel** [comment]
The changes discussed in this issue are unreleased. Perhaps you want to try the master branch of pyramid and see if it fixes your problems.
