### ISSUE TITLE
pip no longer installs in Python 3.2

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid#2255]
This is currently breaking tox test runs. Dropping Python 3.2 support may be required.

**Comment by bertjwregeer** [comment]
https://travis-ci.org/Pylons/pyramid/jobs/103424405

**Comment by mmerickel** [comment]
yes, I'm +1 on dropping python versions as the PSF does as well

**Comment by mmerickel** [comment]
I'll say I'm not interested in backporting this change to older Pyramid versions however. I think we should be stuck figuring out how to handle 1.5/1.6 (extra motivation to release 1.7/1.8).

**Comment by stevepiercy** [comment]
@mmerickel which versions do you consider to be "older Pyramid versions"?

**Comment by mmerickel** [comment]
Currently 1.5/1.6 like I said. We consider the last 2 releases supported.

**Comment by mmerickel** [comment]
Fixed via #2256, #2269, #2270, #2271.
