### ISSUE TITLE
proposal - extend `_HTTPMove` with location_queryargs kwarg

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#2306]
I end up doing a handful of redirects, and must stuff information into the querystring. 

unfortunately, this means i have code that looks a bit unsightly.

my proposal is to add an argument to `_HTTPMove.__init__`, named something like "location_queryargs", which expects a `dict` or `None`.  If provided, the dict is encoded into a string via `urllib.urlencode` (or similar), and then added to the `location`.

**Comment by mmerickel** [comment]
Sorry, no. You're responsible for passing a full URL to the `location` argument. You're free to write your own wrapper around `HTTPSeeOther` or whatnot that passes in a valid `location` but this feature request adds minimal value and maximum confusion in several corner cases like when the `location` already contains a partial query string, etc. I see no way this would be worthwhile to have in core.

**Comment by bertjwregeer** [comment]
If you are using Pyramid to generate the URL's, you can pass query parameters into `resource_url`/`route_url`. See documentation: http://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.route_url

**Comment by jvanasco** [comment]
thanks, @bertjwregeer.

I had actually already implemented this before filing. This was more of a "I can easily make a PR if interested" type of ticket.  

The code, fyi, is below:

    class HTTPFound(pyramid.httpexceptions.HTTPFound):

        def __init__(self, location='', detail=None, headers=None, comment=None,
                     body_template=None, location_queryargs=None, **kw):
            if location is None:
                raise ValueError("HTTP redirects need a location to redirect to.")
            if location_queryargs is not None:
                q_encoded = urllib.urlencode(location_queryargs)
                q_joiner = '&' if '?' in location else '?'
                location += q_joiner + q_encoded
            super(HTTPFound, self).__init__(
                detail=detail, headers=headers, comment=comment,
                body_template=body_template, location=location, **kw)
        
I subclassed HTTPFound, and just imported the override to maintain compatibility.

The 3 approaches seemed to be:

1. Extend HTTPFound

    raise HTTPFound(location='string', location_queryargs={})

2. Use a "string generator" that accepts url+kwargs in one of the following ways:

    raise HTTPFound(location=url_generator('string', queryargs))

or
   
    location = url_generator('string', queryargs))
    raise HTTPFound(location=location)

The first version read cleaner on code audits and reported better in stack traces.
