### ISSUE TITLE
json_body does not raise an exception when body is a simple string

### ISSUE THREAD

**Issue by fpuga** [Pylons/pyramid#2356]
The [doc says](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.json_body) that when the body is not well formed or is not a valid json an exception is raised when accessing `request.json_body`.

I'm generating an invalid json with:

```
import requests
r = requests.post('http://localhost:6543/', json= 'not valid json')
```

That generates this request (`print request`)

> POST / HTTP/1.1
> Accept: */*
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> Content-Length: 16
> Content-Type: application/json
> Host: localhost:6543
> User-Agent: python-requests/2.4.3 CPython/2.7.9 Linux/3.19.0-16-generic
> 
> "not valid json"

And this is my view

```
@view_config(
    route_name='home',
    request_method='POST',
    renderer='json')
def test_post(request):
    print request
    try:
        body = request.json_body
    except (ValueError):
        print 'ValueError exception'
    print body
```

I expect that the ValueError exception  was raised, but no exception is raised. Not sure why this is happening as `json.load("not valid json")` that is pretty similar to the [implementation of json_body](https://github.com/Pylons/pyramid/blob/master/pyramid/request.py#L233) launches a ValueError exception.

**Comment by fpuga** [comment]
Well i make a unit test on pyramid testing my case and seems correct, so maybe the problem is in the _requests_ library or how i'm making the request

https://github.com/fpuga/pyramid/commit/02156f71f453bcc960ca8a557f55eee16d1ae8d0

**Comment by mmerickel** [comment]
I'm pretty sure the issue is that you used the `json=` arg on the request, which serializes the string into a json-encoded string so the data over the wire *is* json.
