### ISSUE TITLE
Drop Python 2.6 support

### ISSUE THREAD

**Issue by tseaver** [Pylons/pyramid#2368]
Per [Nick Coghlan's blog post](http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html).

tl;dr: folks still running Python 2.6 can't reasonably expect to be updating to latest-and-greatest of everything else, especially if they aren't paying for it with blood or treasure.

**Comment by bertjwregeer** [comment]
For 1.7 we could totally just drop it.

**Comment by mmerickel** [comment]
I have no problem dropping 2.6 considering it was EOL 2 years ago. The only argument against that I know are 1) according to @dstufft's numbers there are still tons of installations of 2.6 using PyPI 2) it's not hard to support - at least so far.

Next question: soft or hard drop? The current `setup.py` raises a `RuntimeError` on < 2.6 because Pyramid uses things like the `with` statement that don't work on 2.5 whereas 2.6 feels more like "it may work or it may not, but we aren't testing it anymore".

**Comment by mmerickel** [comment]
Actually I think the `with` statement is 2.5+... Maybe byte strings are a better example. Point remains.

**Comment by bertjwregeer** [comment]
We should remove it from setup.py, besides that, let's keep testing on Python 2.6 until we decide it's time to drop it.

**Comment by mmerickel** [comment]
Sorry what do you mean "remove it from setup.py" ? The trove classifier? A hard fail?

**Comment by bertjwregeer** [comment]
Remove it from the trove classifier.

**Comment by tseaver** [comment]
ISTM that dropping it from tox/Travis should go hand-in-hand with dropping it from Trove:  we get quicker turnarounds for builds, plus we can start using [2.7-only features / syntax](https://docs.python.org/2/whatsnew/2.7.html), e.g. improved unittest assertions, set literals, dict comprehensions, etc.  I'm +0 to dropping it for 1.7 (since we haven't deprecated it ahead) and +1 for whatever release comes afterward (1.8 or 2.0).

**Comment by dstufft** [comment]
I personally think Pyramid can probably ditch Python 2.6, but I'll let y'all make that decision. However, data is cool, so here is the downloads for Pyramid from 2016-02-22:

| python_version | download_count |
|----------------|----------------|
| 2.7            | 1855           |
| 3.4            | 270            |
| 3.5            | 175            |
| 2.6            | 123            |
| Unknown  | 75             |
| 3.3            | 67             |
| 3.2            | 8              |

**Comment by dstufft** [comment]
I also think you can ditch support for Python <3.4 as well, and make it just 2.7, and 3.4+. In general the web world seems to be the best at getting to newer versions of Python quicker.

**Comment by stevepiercy** [comment]
I would very much like to drop 3.3 because it will make writing docs to transition from setuptools to pip a wee bit easier, due to [pip being available by default in most installations of Python 3.4 or later](https://packaging.python.org/en/latest/current/#id3).

**Comment by bertjwregeer** [comment]
Wish Github had a way to vote on things:

Thumbsup on this comment means remove Python 2.6 for Pyramid 1.7
Thumbsdown on this comment means deprecate Python 2.6 and remove for Pyramid 1.8

**Comment by bertjwregeer** [comment]
Thumbsup on this comment means remove Python 3.3 for Pyramid 1.7
Thumbsdown on this comment means deprecate Python 3.3 and remove at a later time

**Comment by stevepiercy** [comment]
Python 2.6 was EOLed Oct 29, 2013. We let that one slip by.
https://www.python.org/dev/peps/pep-0361/

Python 3.3 is EOLed for September 2017. I vote a definitive Pyramid 1.8 for its removal, instead of "later time".
https://www.python.org/dev/peps/pep-0398/#lifespan

**Comment by bertjwregeer** [comment]
I mentioned later time so that we could have a discussion around it. I am okay with 1.8 being that time.

**Comment by mmerickel** [comment]
One very subtle concern I have about dropping 2.6 is that it currently acts as a very solid sanity check against bugs in older versions of 2.7. For example the `hmac.compare_digest` which was introduced in 2.7.11 or something. 2.6 exercises the codepath that older versions of 2.7 will execute, keeping us honest.
