### ISSUE TITLE
Tween configuration is limited

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid#2412]
See this comment:

https://github.com/Pylons/pyramid/pull/2021#issuecomment-196669080

> [...] add_tween(tween). The difference between these apis [new view derivations/old tween] is an issue I want to discuss further because it has been bugging me for some time now - mostly regarding tweens. There is currently a restriction on tweens that they be an importable object and their name is always the Python dotted name. I think this is done to ensure the tween has a consistent name but it also limits the api in some ways. For example, the tween can't be a product of some other computation. It must come directly from the top-level code that exposes it. It can't be used twice with different options in the pipeline by specifying different names and possibly options. Finally, it can only receive options from the registry and settings.

This is something we definitely want to change and or solve so that it becomes more flexible.

**Comment by mcdonc** [comment]
Mike and I talked today about adding support for an alias argument to add_tween (or possibly "aliases").

**Comment by mmerickel** [comment]
@sawdog did you make any progress on the aliases after the pycon sprints? I'm just trying to see where things are at such that I know what work needs to be done.

**Comment by mmerickel** [comment]
I'm going to drop this from 1.8 as there seems to be no immediate interest in working on it.

To summarize the change request, we basically would like to add a `name` argument to `config.add_tween` which could be a string or a list of strings. When new tweens are added they would ensure they do not conflict with any previously added names, and they would resolve over/under against all names, linking back to their core importable string. Finally, we could relax the constraint that the tween is globally importable by requiring a `name` argument when it is an object and this would be a path forward for `config.add_tween(obj, name='foo')`.
