### ISSUE TITLE
running pytest on wiki2 yields 1 pytest-warnings

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#2450]
After updating the docs for wiki2 to use pytest, I stumbled across this warning.

```bash
$VENV/bin/py.test -r w -q
......................
======================================================================== pytest-warning summary =========================================================================
WC1 /Users/stevepiercy/projects/hack-on-pyramid/pyramidtut/tutorial/tutorial/tests/test_functional.py cannot collect test class 'TestApp' because it has a __init__ constructor
22 passed, 1 pytest-warnings in 5.81 seconds
```

If it can be ignored, then the docs need to be updated in the subsequent note with an explanation.

See #2104.

**Comment by bertjwregeer** [comment]
Looks like we need to remove `__init__` on that `TestApp` and then py.test can do it's thing.

**Comment by stevepiercy** [comment]
@bertjwregeer that's what I didn't grok. I saw no `__init__`, unless it is something implicit. See:
https://github.com/Pylons/pyramid/blob/docs/easy-install-to-pip.2104/docs/tutorials/wiki2/src/tests/tutorial/tests/test_functional.py#L3

**Comment by bertjwregeer** [comment]
Ah... py.test shouldn't attempt to collect that in the first place. I should have looked before answering.

**Comment by bertjwregeer** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1223883

Will a from webtest import TestApp as WebtestApp?

Perhaps?

**Comment by stevepiercy** [comment]
Very clever. That worked. Thank you! PR coming soon.

**Comment by stevepiercy** [comment]
closed by #2457

**Comment by mmerickel** [comment]
I think I would have used `import webtest` and `app = webtest.TestApp(app)` instead of renaming the import. Just my 2cents.

**Comment by bertjwregeer** [comment]
I didn't think about that. Either one works.

**Comment by stevepiercy** [comment]
Oh, I like the succinctness of that. Thanks!
