### ISSUE TITLE
package scanning doesn't work when .egg is built with --exclude-source-files

### ISSUE THREAD

**Issue by sayap** [Pylons/pyramid#246]
Let's say I have 2 pyramid projects, p1 and p2, with p2 overriding p1's functionality.

This is p1's configure.zcml:

``` xml
<configure xmlns="http://pylonshq.com/pyramid">

  <!-- this must be included for the view declarations to work -->
  <include package="pyramid_zcml" />

  <view
     context=".resources.Root"
     view=".views.TestView"
     attr="test_view"
     renderer="string"
     />

</configure>
```

This is p1/views.py:

``` python
from p1.validators.test import TestSchema


class TestView(object):

    schema = TestSchema

    def __init__(self, context, request):
        self.context = context
        self.request = request

    def __call__(self):
        return {}

    def test_view(self):
        return ', '.join(sorted(self.schema.fields.keys()))
```

And this is p1/validators/test.py:

``` python
from formencode.schema import Schema
from formencode.validators import UnicodeString


class TestSchema(Schema):
    allow_extra_fields = True
    filter_extra_fields = True

    field1 = UnicodeString()
```

Thus, when running p1, the home page should return just "field1".

Next, I have p2 which overrides p1 by returning "field1, field2".

This is p2's configure.zcml:

``` xml
<configure xmlns="http://pylonshq.com/pyramid">

  <!-- this must be included for the view declarations to work -->
  <include package="pyramid_zcml" />

  <include package="p1" file="configure.zcml"/>

  <scan package=".validators"/>

</configure>
```

And this is p2/validators/test.py:

``` python
from formencode.validators import UnicodeString

from p1.validators.test import TestSchema


TestSchema.add_field('field2', UnicodeString())
```

It works as expected during development (`setup.py develop`). It also works fine with normal .egg packages (built with `setup.py bdist_egg`). However, with stripped down .egg packages (built with `setup.py bdist_egg --exclude-source-files`), the home page of p2 only show "field1" instead of "field1, field2".

This is tested against pyramid 1.0 + venusian 0.6 + FormEncode 1.2.3dev, as well as pyramid 1.1 + venusian 0.9 + FormEncode 1.2.4, running under both paster serve and apache. I am not sure where the problem is, so I log it against pyramid.

**Comment by kiranmsn** [comment]
@tseaver 
We have a enterprise product which uses pyramid and we are shipping egg file which is bdist_egg with exclude-source-files. We are getting **py file expecting instead of orphan .pyc file** error. Pyramid config.scan() is not the scanning cornice @resource decorator which we use for routes. @resource decorator works fine if we it is used in __init__.py but not in other .py files. Can we maintain the routing logic in __init__.py and business logic in other files so that we need not ship py files in the eggs. Please suggest if there is any other approach or solution.

**Comment by kiranmsn** [comment]
> @kiranmsn All the seven-year-old logic posted above is still in force. You can:
> 
> * Add [ZCML directives which set up your routes](https://docs.pylonsproject.org/projects/pyramid_zcml/en/latest/narr.html) (requires the [`pyramid_zcml`](https://pypi.org/project/pyramid_zcml/) add-on).
> * Fork the [`venusian` repository](https://github.com/Pylons/venusian) and add support for using `.pyc` files.

@tseaver 
Does Python3.x support ZCML

**Comment by bertjwregeer** [comment]
@kiranmsn at the time that release was made Python 3.6 was the latest version, so we only have it tested for up to Python 3.6. Is there a failure in Python 3.7?

**Comment by tseaver** [comment]
Things will almost certainly work with 3.7:  the package just hasn't been updated to test that.

**Comment by tseaver** [comment]
There is one test failure on 3.7, but it is a trivial testing-only issue.

**Comment by Hariprasad1600** [comment]
Are there any disadvantages of using declarative zcml directives compared to imperative view configuration in python code?

**Comment by bertjwregeer** [comment]
No.
