### ISSUE TITLE
Suggestion: compatibility matrix for docs

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#2485]
I wanted to suggest a compatibility matrix file for the docs/source.

Something like the following:

	Pyramid is compatible with the following versions of Python.

	The recommended Python version is denoted with an asterisk, when available.
	
	It is always recommended to use the latest version of Python and Pyramid.

	This chart is only provided to help people maintain legacy projects.
	
	Pyramid Version | Python 3    | Python 2
	--------------- | ----------  | --------
	1.7             | 3.3 - 3.4*  | 2.7+
	1.6             | 3.2 - 3.4   | 2.7+

The reason is because there are a lot of changes going on right now regarding:

• dropping support for various versions of Python
• docs migrating to python 3.x
• existing docs and web materials show all sorts of versions (such as 1.3.x referenced on http://www.pylonsproject.org/projects/pyramid/faq )

**Comment by bertjwregeer** [comment]
Patches will be gladly reviewed and accepted :-).

**Comment by stevepiercy** [comment]
Skip http://www.pylonsproject.org/projects/pyramid/faq as it is loosely true in its current state. This site is also only updated for clearly erroneous information, and the preferred repos are Pylons/trypyramid.com and Pylons/pylonsproject.org (which will also be their URLs).

The appropriate page is `docs/narr/install.rst`. The sidebar could be killed in place of the table. I would only backport this change from `master` to `1.6-branch`.

**Comment by jvanasco** [comment]
`docs/narr/install.rst` install is aimed at first-time users; and the docs are encouraged to be opinionated on what they recommended.  

The use-case I'm thinking of are developers who have existing Pyramid installs.  

I think the best place for something like this would be in the source code; perhaps the README or an UPGRADING.txt; or perhaps an "Installing/Upgrading" section on the README that links to a paragraph on the docs/narr/install ?

I brought up the FAQ because that was one of the top hits on search engines, and it has the outdated info.

**Comment by stevepiercy** [comment]
@jvanasco this is the direction for `install.rst`:
http://docs.pylonsproject.org/projects/pyramid/en/docs-easy-install-to-pip.2104/narr/install.html#installing-chapter

It targets all users who install or have installed Pyramid.

Ultimately, be the change, else it won't.

**Comment by mmerickel** [comment]
The place for anyone upgrading is the whatsnew/changelog documents for every version between where you're at and where you want to be. There is no other place that we want to maintain this list of changes.
