### ISSUE TITLE
Quick Tutorial - 18: Forms and Validation With Deform - Missing assets path

### ISSUE THREAD

**Issue by arianmaykon** [Pylons/pyramid#2493]
In step 18 of quick tutorial, the root path of CSS/JS assets is missing in the `wikipage_addedit.pt` file, which causes a error.

It should be:
```
    <tal:block tal:repeat="reqt view.reqts['css']">
        <link rel="stylesheet" type="text/css"
              href="${request.static_url('deform:static/' + reqt)}"/>
    </tal:block>
    <script src="${request.static_url('deform:static/scripts/jquery-2.0.3.min.js')}"
        type="text/javascript"></script>
    <tal:block tal:repeat="reqt view.reqts['js']">
        <script src="${request.static_url('deform:static/' + reqt)}"
                type="text/javascript"></script>
    </tal:block>
```

instead of:

```
    <tal:block tal:repeat="reqt view.reqts['css']">
        <link rel="stylesheet" type="text/css"
              href="${request.static_url(reqt)}"/>
    </tal:block>
    <script src="${request.static_url('deform:static/scripts/jquery-2.0.3.min.js')}"
        type="text/javascript"></script>
    <tal:block tal:repeat="reqt view.reqts['js']">
        <script src="${request.static_url(reqt)}"
                type="text/javascript"></script>
    </tal:block>
```

And the `jquery-2.0.3.min.js` file is missing.

**Comment by arianmaykon** [comment]
https://github.com/Pylons/pyramid/pull/2494#issuecomment-209804654 fixed this issue, closing it

**Comment by stevepiercy** [comment]
Fixed by #2494 and #2497

**Comment by arianmaykon** [comment]
Guys, first, i'm sorry for taking more of your time, i'm very ashamed to ask that, but something changed or i think my PR did't fixed the problem.

I have checked out the master branch on a new machine (Linux Mint 17, with pyenv and python 3.5.1), and when running the tutorial step 18 again, none of the assets are loaded, printing the reqts property this is what is shown:

`{'css': [], 'js': ['deform:static/scripts/jquery.form-3.09.js', 'deform:static/scripts/deform.js', 'deform:static/scripts/jquery.maskedinput-1.3.1.min.js', 'deform:static/tinymce/tinymce.min.js']}`

This time no CSS is returned, and the js assets are now with the full path, but this time, without jQuery, im not very experienced in Python, so this can be some mistake or my environment.

Can someone confirm that?

If its confirmed i can make another PR, the original file would be nice this time, but loading the missing jQuery from a CDN or something like that.

Thanks for this great software.

**Comment by arianmaykon** [comment]
Here's the output of my `pip list`

```
$VENV/bin/pip list
Chameleon (2.24)
colander (1.2)
deform (2.0a2)
iso8601 (0.1.11)
Mako (1.0.4)
MarkupSafe (0.23)
PasteDeploy (1.5.2)
peppercorn (0.5)
pip (8.1.1)
Pygments (2.1.3)
pyramid (1.6.1)
pyramid-chameleon (0.3)
pyramid-debugtoolbar (2.4.2)
pyramid-mako (1.0.2)
repoze.lru (0.6)
setuptools (18.2)
translationstring (1.3)
tutorial (0.0.0, /home/maykon/Projects/OSS/pyramid/docs/quick_tutorial/forms)
venusian (1.0)
WebOb (1.6.0)
zope.deprecation (4.1.2)
zope.interface (4.1.3)
```
