### ISSUE TITLE
Quick Tutorial - 18: Forms and Validation With Deform - Problem with assets path

### ISSUE THREAD

**Issue by arianmaykon** [Pylons/pyramid#2516]
This is related with the issue #2493 but @stevepiercy asked me to create a new issue.

Guys, first, i'm sorry for taking more of your time, i'm very ashamed to ask that, but something changed or i think my PR did't fixed the problem.

I have checked out the master branch on a new machine (Linux Mint 17, with pyenv and python 3.5.1), and when running the tutorial step 18 again, none of the assets are loaded, printing the reqts property (https://github.com/Pylons/pyramid/blob/master/docs/quick_tutorial/forms/tutorial/views.py#L31) this is what is shown:

`{'css': [], 'js': ['deform:static/scripts/jquery.form-3.09.js', 'deform:static/scripts/deform.js', 'deform:static/scripts/jquery.maskedinput-1.3.1.min.js', 'deform:static/tinymce/tinymce.min.js']}`

This time no CSS is returned, and the js assets are now with the full path, but this time, without jQuery, im not very experienced in Python, so this can be some mistake or my environment.

Can someone confirm that?

If its confirmed i can make another PR, the original file would be nice this time, but loading the missing jQuery from a CDN or something like that.

Here's the output of my `pip list`

```
$VENV/bin/pip list
Chameleon (2.24)
colander (1.2)
deform (2.0a2)
iso8601 (0.1.11)
Mako (1.0.4)
MarkupSafe (0.23)
PasteDeploy (1.5.2)
peppercorn (0.5)
pip (8.1.1)
Pygments (2.1.3)
pyramid (1.6.1)
pyramid-chameleon (0.3)
pyramid-debugtoolbar (2.4.2)
pyramid-mako (1.0.2)
repoze.lru (0.6)
setuptools (18.2)
translationstring (1.3)
tutorial (0.0.0, /home/maykon/Projects/OSS/pyramid/docs/quick_tutorial/forms)
venusian (1.0)
WebOb (1.6.0)
zope.deprecation (4.1.2)
zope.interface (4.1.3)
```

Thanks for this great software.

**Comment by stevepiercy** [comment]
@arianmaykon when you installed Pyramid, did you follow the instructions on [Requirements](http://docs.pylonsproject.org/projects/pyramid/en/1.7-branch/quick_tutorial/requirements.html#install-pyramid)?

**Comment by stevepiercy** [comment]
@arianmaykon  I followed the instructions in Requirements exactly, then copied the directory `docs/quick_tutorial/forms` from master branch (currently it is in synch with 1.7 branch), and followed the instructions to run the tutorial.

Note differing versions of deform and pyramid.

```
$VENV/bin/pip list
beautifulsoup4 (4.4.1)
Chameleon (2.24)
colander (1.2)
coverage (4.0.3)
deform (0.9.9)
iso8601 (0.1.11)
Jinja2 (2.8)
Mako (1.0.4)
MarkupSafe (0.23)
PasteDeploy (1.5.2)
peppercorn (0.5)
pip (8.1.1)
py (1.4.31)
Pygments (2.1.3)
pyramid (1.7a1)
pyramid-chameleon (0.3)
pyramid-debugtoolbar (2.4.2)
pyramid-jinja2 (2.6.2)
pyramid-mako (1.0.2)
pyramid-tm (0.12.1)
pytest (2.9.1)
pytest-cov (2.2.1)
repoze.lru (0.6)
setuptools (20.9.0)
six (1.10.0)
SQLAlchemy (1.0.12)
transaction (1.4.4)
translationstring (1.3)
tutorial (0.0.0, /Users/stevepiercy/projects/quick_tutorial/forms)
venusian (1.0)
waitress (0.9.0)
WebOb (1.6.0)
WebTest (2.0.21)
zope.deprecation (4.1.2)
zope.interface (4.1.3)
zope.sqlalchemy (0.7.6)
```

**Comment by arianmaykon** [comment]
@stevepiercy yes, my fault, sorry, with my version of deform the error occurs, following the requirements steps it's ok, sorry for the time waste.

Thanks.
