### ISSUE TITLE
Wheels for 1.7a1 and 1.7a2 contain wrong contents

### ISSUE THREAD

**Issue by ergo** [Pylons/pyramid#2525]
Hi,

I've tried using new scaffolds today and it turns out that wheel files contain old files in scaffold modules.
If you download the wheels and check the contents of `/pyramid/scaffolds/alchemy/+package+/`
you will find that there are files there like `views.py_tmpl` and `models.py_tmpl` they are not supposed to be there as this is 1.6 version content - essentially this means that all scaffolds generated are in broken state.

The tar.gz sdist files seem to be unaffected by this bug.

**Comment by mmerickel** [comment]
It looks like the build folder on my machine isn't getting properly cleaned up between builds for some reason? I removed the build folder and now things look correct. Uploading 1.7b1 soon.

**Comment by mmerickel** [comment]
@ergo can you please close this once you confirm 1.7b1 fixes the issue?

**Comment by krysros** [comment]
I noticed the same problem with 1.7a1 and 1.7a2 installing Pyramid on Windows using pip. 1.7b1 fixes the issue.
