### ISSUE TITLE
Remove inclusion of 'pyramid_tm' in development.ini for 'alchemy' scaffold

### ISSUE THREAD

**Issue by vincent-ferotin** [Pylons/pyramid#2538]
As of the refactoring of 'alchemy' scaffold for branch 1.7, it seems to me that there is some old configuration in 'development.ini' file requiring that 'pyramid_tm' must be here: 
https://github.com/Pylons/pyramid/blob/1.7-branch/pyramid/scaffolds/alchemy/development.ini_tmpl#L16
This is no more the case for 'production.ini': https://github.com/Pylons/pyramid/blob/1.7-branch/pyramid/scaffolds/alchemy/production.ini_tmpl#L14

It seems to me that 'production.ini' is right in not including 'pyramid_tm', as application configuration include '.models' (https://github.com/Pylons/pyramid/blob/1.7-branch/pyramid/scaffolds/alchemy/%2Bpackage%2B/__init__.py#L9) where 'pyramid_tm' is raw-included (https://github.com/Pylons/pyramid/blob/1.7-branch/pyramid/scaffolds/alchemy/%2Bpackage%2B/models/__init__.py_tmpl#L62).

If right, could you please remove the unnecessary line in 'development.ini_tmpl' file?

**Comment by mmerickel** [comment]
Yes I thought we had removed those references. Thanks for the report!

**Comment by stevepiercy** [comment]
I'll fix this tonight.

**Comment by vincent-ferotin** [comment]
Thanks for fixing this.

**Comment by stevepiercy** [comment]
@vincent-ferotin thanks for the report. Fix is available on master and 1.7-branch, and will be included in the next release of 1.7.
