### ISSUE TITLE
request.invoke_exception_view does not conform to its docs

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#2554]
Currently the docs say `request.invoke_exception_view` will return `None` but it will actually raise a `PredicateMismatch` if it attempts a view. This needs to be standardized before release. The two options:

1. Squash `PredicateMismatch` into `None` such that you always receive a valid response or `None`, or a legitimate exception raised by the invoked view itself.
2. Raise `HTTPNotFound` instead of returning `None` such that you either receive a valid response or an exception (could be `HTTPNotFound`, `PredicateMismatch` or anything raised by the exception view).

**Comment by bertjwregeer** [comment]
Number 2 would basically document the existing behaviour, no?

**Comment by mmerickel** [comment]
Existing behavior is that it raises `PredicateMismatch` if a view is registered for a matching `context_iface, request_iface` but does not match predicates. If no views match at all, then `None` is returned. The conversion of the latter case to `HTTPNotFound` is done in the router itself which is why this oddity slipped by. I think the appropriate change is to pursue option 2 instead of squashing the exceptions.
