### ISSUE TITLE
Download setuptools return 404 NOT FOUND

### ISSUE THREAD

**Issue by erichideki** [Pylons/pyramid#2555]
The tutorial in this page (http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/requirements.html) recommends install setuptools with command: `wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | $VENV/bin/python` but returns ERROR 404: NOT FOUND

So, need to change to other resource, like - https://pypi.python.org/pypi/setuptools#unix-wget

Just change the command to `wget https://bootstrap.pypa.io/ez_setup.py -O - | python`

**Comment by mmerickel** [comment]
You're correct, the url should be the one from `bootstrap.pypa.io`. This only affects 1.5-branch and 1.6-branch, as in 1.7 we've dropped these instructions in favor of pip.

**Comment by stevepiercy** [comment]
Dude, where's my setuptools?

I'll take this on tonight. Thanks for the report.

**Comment by stevepiercy** [comment]
Closed by #2556 and #2557.

**Comment by erichideki** [comment]
I appreciate the attention and the fix <3
