### ISSUE TITLE
Quick tutorial step 18: Forms and Validation With Deform not correct (Pyramid 1.7b4)

### ISSUE THREAD

**Issue by mjmare** [Pylons/pyramid#2570]
The intro mentions that Deform supports Bootstrap so that means deform 2.2a2. However installing deform will install 0.9.9. So one has to pin 2.0.a2.

In step 7 the url is generated with 
`<link rel="stylesheet" type="text/css"
              href="${request.static_url('deform:static/' + reqt)}"/>`

However deform 2 returns asset specifications (info buried somewhere in a README), so this should be:
`<link rel="stylesheet" type="text/css"
              href="${request.static_url(reqt)}"/>`

Also unmentioned in the tutorial is that one has to manually include JQuery and Bootstrap. Guessing the versions I added:

`    <script src="https://code.jquery.com/jquery-2.2.3.min.js"
            integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous"></script>`

Deform is a bit in a sorry state IMHO:

- Deform2 is in alfa since 2013?
- Pypi shows 2.0a2 but will install 0.9.9
- Docs are not updated to reflect the above. 
- The deform demo uses deform 1?
- There is a http://deform2demo.repoze.org (which looks good!), but all its links point to the deform 1 demo/docs. The 'show in context' links are broken.

**Comment by stevepiercy** [comment]
There are two ways to fix the docs.

1. Remove mention of Twitter Bootstrap.
2. @mjmare submit a PR to update the docs with a TB-ified version.

Given this is a Quick Tutorial, and design is outside the scope of generating a form and doing validation, I'll implement option 1. You're welcome to submit a PR for the TB-ified version.

**Comment by mjmare** [comment]
You might want to add that the tutorial is not compatible with Deform 2.0a2 due to the change in requirements specification.

**Comment by bertjwregeer** [comment]
@mjmare by default when you request deform as a dependency it will install the latest deform that is not alpha/beta. This will thus install the older version of deform. If the user explicitly requests deform 2.0a2 then they are themselves going to have to figure out how that changes the code in the quick tutorial, since that is a full two version jumps from the version that is installed by default.

I don't think it is necessary to add anything to let users know that alpha software is incompatible with a tutorial.

**Comment by stevepiercy** [comment]
Additionally by removing the statement about Twitter Bootstrap, the tutorial will not lead the user down the deform version rabbit hole.

@mjmare see status of deform https://github.com/Pylons/deform#status

**Comment by mjmare** [comment]
Thanks Steve for directing me to the status page. Pity about deform. Any other form libs that are blessed for pyramid?

**Comment by stevepiercy** [comment]
None are "blessed". There are other form libs that have been used by folks who use Pyramid. See https://trypyramid.com/resources-extending-pyramid.html and filter by "forms".

I don't know about assumptions. Use what works for your use case.

**Comment by mmerickel** [comment]
If you are set on doing server-side forms then I would suggest looking at wtforms.

**Comment by mjmare** [comment]
Thanks. I've used WTForms before (with Flask) but have not become a fan. Deform looked better designed.
