### ISSUE TITLE
add latexpdf to tox

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#2575]
Consider adding `latexpdf` to the list of builders in [tox](https://github.com/Pylons/pyramid/blob/master/tox.ini#L65 ), which would serve as a check that PDF should build at Read the Docs.

Any thoughts?

**Comment by bertjwregeer** [comment]
I currently have latexpdf installed on only some of my development machines. Adding it to tox means we also need to make sure that all of our builds have latexpdf available, and I speak from experience when I say that getting latex and everything installed and working correctly is a major pain in the behind.

I am a -1 on this. I wouldn't mind adding it as a non-default. There is an issue with the PDF book generation and the TOC, in that you have to run latexpdf multiple times for it to generate a correct TOC. Read the Docs doesn't do so, and thus there is no TOC or it uses an outdated TOC from a previous run (when I checked in the past, this may have been fixed).

**Comment by stevepiercy** [comment]
I agree with not a default for the reasons you cite and because the benefit is not worth the loss of time waiting for builds.

To make this optional, would I just duplicate and edit the `docs` stanza and add a line for `pdf`, or is there more to it? The following "works", but I don't know if it is in fact optional. `tox -e docs` seems to leave out pdf, so I think it's good.

```ini
#tox.ini
# ...
    docs,pdf,pep8,
# ...
[testenv:pdf]
basepython = python3.5
whitelist_externals = make
commands =
    pip install pyramid[pdf]
    make -C docs latexpdf BUILDDIR={envdir} "SPHINXOPTS=-W -E"
```

```python
#setup.py
# ...
      extras_require={
          'testing': testing_extras,
          'docs': docs_extras,
          'pdf': docs_extras,
          },
# ...
```

I haven't seen the TOC issue in RTD for a while, but I check maybe a couple times per year, and only then when someone points it out to me.

**Comment by bertjwregeer** [comment]
Don't add another `extras_require`, docs is fine here since that already installs all the needed parts.

Also, adding it to the default list is exactly what you don't want to do...

**Comment by bertjwregeer** [comment]
Sorry, let me make that clearer. The `envlist` under `[tox]` is the default environments to run when one is not explicitly provided on the command line.

**Comment by stevepiercy** [comment]
Thanks for the clarification. I reverted `setup.py`, removed `pdf` from `envlist` in `tox.ini`, and edited `tox.ini` as follows:

```ini
[testenv:pdf]
basepython = python3.5
whitelist_externals = make
commands =
    pip install pyramid[docs]
    make -C docs latexpdf BUILDDIR={envdir} "SPHINXOPTS=-W -E"
```

Invoked by `tox -e pdf` seems to work fine and makes PDF builds optional.

**Comment by bertjwregeer** [comment]
That works for me.
