### ISSUE TITLE
pcreate -s shows wrong link to tutorials

### ISSUE THREAD

**Issue by COLABORATI** [Pylons/pyramid#2604]
after a 
```
pcreate -s alchemy scaffold-alchemy
```
I see a link to tutorials, but this link is a 404: 
```
Tutorials: http://docs.pylonsproject.org/projects/pyramid_tutorials
```

**Comment by stevepiercy** [comment]
@COLABORATI, this does not appear in Pyramid 1.7. Which version are you using?

**Comment by stevepiercy** [comment]
Ah, you mean on the command line, not in the web page after you run. I'm working on this now. PR coming.
