### ISSUE TITLE
investigate what patterns from tomb_routes may be generalized into core

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#2608]
https://pypi.python.org/pypi/tomb_routes is cool and has several new features like decorator-based routes as well as supporting trailing slashes. It'd be interesting to see if any of these features can be pulled into core in a general way.

**Comment by ztane** [comment]
But the problem is that the route ordering is arbitrary, and thus this is against the design defence.

**Comment by ztane** [comment]
http://docs.pylonsproject.org/projects/pyramid/en/latest/designdefense.html#routes-need-relative-ordering
