### ISSUE TITLE
suggestion- extend prequest to support command-line PUT arguments (like curl)

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#2612]
the current POST/PUT/PATCH can only send STDIN data

i propose an alternate syntax to make `prequest` behave a bit more like `curl`
1. multiple `-F` or `--form` arguments can be invoked on the commandline.  they are appended into the optionparser
   
   parser.add_option(
       '-F', '--form',
       dest='form',
       type='string',
       action="append",
       help='HTTP formfields',
       )
2. if any formfields are submitted, instead of using STDIN an in-memory file-like object is created and assigned to environ['wsgi.input']

I already stubbed this (I needed this for testing) and can generate a PR that generally handles this with a few caveats:
- no support for file uploads
- it ignores content-type declarations on the fields

**Comment by jvanasco** [comment]
if anyone has feedback or needs '--form' functionality in the short term, this largely works.  i'm not going to generate a PR for a while.

https://github.com/jvanasco/pyramid/commit/317ec57193cf4e774e671a5c997d2946eb8f51b3

**Comment by mmerickel** [comment]
@jvanasco If you want to submit a well-formed PR then we can consider it.

**Comment by jvanasco** [comment]
great. will do.
