### ISSUE TITLE
Use tox to build documentation in contributing.md

### ISSUE THREAD

**Issue by cewing** [Pylons/pyramid#2617]
To solve a chicken/egg situation in building the documentation, tox is used to build an appropriate environment.  Make sure that this is clear in the contributing.md doc when discussing contributing documentation.

**Comment by mmerickel** [comment]
It seems to me that contributing.md already uses tox to build the docs. Does anything need to be done here or can we close this issue?

**Comment by stevepiercy** [comment]
@cewing made a lot of improvements to `contributing.md` in the just closed PR #2619. I don't know why all the other files got included in that PR.

I'd like to see @cewing submit another PR for the changes just to `contributing.md`. If he doesn't respond after a few days, I'll do it.

**Comment by mmerickel** [comment]
Okay well all of the changes from contributing.md appear to already be applied to master. They must have come from another PR.

**Comment by stevepiercy** [comment]
OK, after doing a pull from `master`, I see now that the changes are there. I'll backport this to 1.7 and 1.6 as needed this weekend, and close this issue as soon when I do so.

**Comment by stevepiercy** [comment]
Looks like the changes were backported to 1.7 and 1.6, too, so we just overlooked closing this issue at that time. Closing now.
