### ISSUE TITLE
Gitter chat as addition besides IRC

### ISSUE THREAD

**Issue by miohtama** [Pylons/pyramid#2626]
**Problem**: The world is moving forward. The popularity of IRC, the work horse of chat protocols, is declining. The new developers feel more comfortable to use services which provide modern user experience. IRC is not what they are used to and what they do not want to use.

**Solution**: To stay in tune with the times and developer community I'd propose to have Gitter as an addition to IRC for chat to have newcomer developers to have more welcoming experience.

**What I propose**
- Add Gitter chat badge to: Github page with other badges, where other community forums are mentioned with mailing lists and IRC 
- Brand the chat as unofficial and tell that for reaching out Pyramid developers official channels should be used. Make sure that IRC still the main chat medium.
- Give it 365 days and take it down if it turns out to be a bad idea (no discussion, some other sort of problems)

**Arguments**
- Gitter is specialized in open source chatting and they are actively involved in open source community and their mission is to make it easier to engage with open source authors. Here is case study of Akka https://medium.com/@gitter/building-online-communities-akka-project-c17e83c16468#.4hcmvg8rh and here are several other case studies https://medium.com/@gitter
- Several Python projects are using Gitter already: DjangoGirls, Coala. 
- Gitter offers native IRC support for those who do not wish to use desktop, web or mobile applications. I am using it with my IRC client myself.
- Gitter integrates well with Pyramid Github repository due to Gitter's use case being especially for open source Github projects like Pyramid
- Praise for Gitter from some of notable open source authors: https://twitter.com/timruffles/status/738706558687682560?ref_src=twsrc%5Etfw
- Gitter provides offline notifications: if you asked a question and closed the chat, you still get a notification if somebody replies to your question (via email). This is a problem for IRC where newcomers pop up, ask a question, but cannot stay around for getting an answer.

**Counter arguments**
-  This would split the community as I feel most of the oldtimers would not be willing to join another chat room. To balance this out, I promise to watch Gitter channel 24h myself. I am one of the most active persons in IRC.
- It's not open source. Other non-open services Pyramid project is using already: Github, Travis, Google mailing lists.

**Comment by mydigitalself** [comment]
Hey, Mike here from Gitter...

Just a couple of points with IRC. Firstly, you can also use Gitter via your favourite IRC client from https://irc.gitter.im

You can also use something like [Sameroom](https://sameroom.io) if you have an existing IRC channel and connect the two rooms together, although the experience isn't perfect. 

Completely aware that not being open source can be a hindrance, although our API is always there for you to build on top of and we always have a really open and available team in our own chat room to help you folks out.

**Comment by mmerickel** [comment]
I'm not against using gitter. There's 7 people in the pylons project channel right now and it's completely inactive. I'm not sure how to get people to use it and I'm a big fan of IRC myself.

If someone wants to do a bunch of work to make the room more popular by putting it on the website and readme, etc then we can consider it.

**Comment by ztane** [comment]
Well, at first there could be a topic  everyone in #pyramid should also connect to irc.gitter.im. Sameroom seems to be paid so I am doubtful about that.

**Comment by mmerickel** [comment]
If anyone has more suggestions we can reopen this issue but it doesn't look like there's much interest right now.
