### ISSUE TITLE
Non working code in "Quick Tour" documentation: static assets

### ISSUE THREAD

**Issue by delallea** [Pylons/pyramid#2648]
I'm on Windows 7, not sure if it makes a difference... But the code at http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tour.html#static-assets does not fully work. The problem is with this line:

    <link rel="stylesheet" href="{{ request.static_url('static/app.css') }}"/>

I'm getting this error:

    ValueError: No static URL definition matching jinja2:static/app.css

I could fix it with the following syntax instead (but since I'm super new to Pyramid I have no idea if that's the "correct" fix):

    <link rel="stylesheet" href="{{ request.static_url('__main__:static/app.css') }}"/>

**Comment by stevepiercy** [comment]
OS should make no difference.

Compare your files against those in the repo for 1.7:
https://github.com/Pylons/pyramid/tree/1.7-branch/docs/quick_tour/static_assets

I just got this to work as follows (adjust commands for Windows):

```bash
$ mkdir qtour; cd qtour
$ export VENV=${PWD}
$ python3 -m venv $VENV
$ $VENV/bin/pip install --upgrade pip setuptools
$ $VENV/bin/pip install "pyramid==1.7"
$ $VENV/bin/pip install pyramid_jinja2
# copy the source directory from https://github.com/Pylons/pyramid/tree/1.7-branch/docs/quick_tour/static_assets into the qtour directory
$ cd static_assets
$ $VENV/bin/python ./app.py
# visit http://127.0.0.1/howdy/steve
127.0.0.1 - - [15/Jun/2016 20:51:19] "GET /howdy/steve HTTP/1.1" 200 175
127.0.0.1 - - [15/Jun/2016 20:51:19] "GET /static/app.css HTTP/1.1" 200 54
```

Please let us know whether that works for you or not.

**Comment by delallea** [comment]
Indeed it works with the default code, the problem occurs when using the version in ``hello_world_static.jinja2``: on my machine I need to prefix the link with ``__main__:`` to make it work.

**Comment by stevepiercy** [comment]
Please paste the entire stack trace.

**Comment by blaflamme** [comment]
@stevepiercy you have to switch the renderer to see the error `renderer='hello_world_static.jinja2` and it also fails on unixes.

@delallea you're right, the problem is because the project is not installed as a package into the environnement so you have to specify the package name, in this case `__main__`. Thanks for the catch!

Would you like to contribute the fix?

**Comment by stevepiercy** [comment]
OK, now I see it. `docs/quick_tour/jinja2/views.py` uses the correct template filename, but the content of the two jinja2 templates needs to be swapped and `__main__:` added. `hello_world_static.jinja2` should be used only for rendering code in the docs.

This one is a little tricky to fix, so I'll take this on. @delallea thanks for the report, and @blaflamme thanks for pointing me in the right direction.
