### ISSUE TITLE
Errors in code examples in documentation of resource_url() method

### ISSUE THREAD

**Issue by piotr-dobrogost** [Pylons/pyramid#2658]
At http://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.resource_url there are a couple of similar code examples. Below is one of them:

```
remainder_path = request.resource_path(someobject)
url = request.route_url(
          'blogentry',
          'element1',
          'element2',
          _query={'a':'1'},
          traverse=traversal_path,
          )
```

It looks like `remainder_path` should be called `traversal_path` or the other way around.

**Comment by stevepiercy** [comment]
Here is the source for that for a PR:
https://github.com/Pylons/pyramid/blob/master/pyramid/url.py#L457-L464
