### ISSUE TITLE
Provide 'current_route_name' as request member

### ISSUE THREAD

**Issue by stephanarts** [Pylons/pyramid#2663]
I've been scavenging the docs for a while, and couldn't find it. I think it would be nice if the request object would get a current_route_name member that holds the name of the route provided.

This would make it easy to create an internal 'bookmark' function to an app that stores the route_name and the parameters. This way you can generate the urls using the existing route_path functions. This way the bookmarks remain valid even if the url_prefix of waitress changes.

Ofcourse, a workaround is available by adding the a variable in the view-response and hard-coding the route-name, but this would mean a lot of duplicate code.

**Comment by piotr-dobrogost** [comment]
The first result in Google when searching for *pyramid get current route* has answer – http://stackoverflow.com/q/13552992/95735

**Comment by stephanarts** [comment]
Seriously... I have lost my google foo... I've spent several evenings looking for this. 

Sorry for the noise...

`request.matched_route` is what I need. Thanks. :)
