### ISSUE TITLE
reify docstring doesn't render properly

### ISSUE THREAD

**Issue by inklesspen** [Pylons/pyramid#2670]
The testsetup section is omitted from the rendered docs at http://pyramid.readthedocs.io/en/latest/api/decorator.html#pyramid.decorator.reify

Unfortunately this section is essential for understanding the example.

**Comment by stevepiercy** [comment]
Thanks for the report. Fixed on master in #2671, and I will backport to other versions tonight.

I also filed an issue with Sphinx: https://github.com/sphinx-doc/sphinx/issues/2747
