### ISSUE TITLE
pyramid/docs/quick_tutorial/forms.rst

### ISSUE THREAD

**Issue by sevillalarry** [Pylons/pyramid#2673]
$VENV/bin/py.test tutorial/tests.py

gives error msgs
1. ImportError: cannot import name 'TutorialViews'
2. KeyError: 'howdy'

**Comment by stevepiercy** [comment]
@sevillalarry check your steps to make sure you didn't miss something. The Quick Tutorial is written such that you must follow all steps in order. My guess is that you skipped over a step.

FWIW, the docs for the Quick Tutorial have been thoroughly tested, and I was able to run the tests successfully for this step just now.

```bash
stevepi-mbp:forms stevepiercy$ $VENV/bin/py.test tutorial/tests.py -q
..
2 passed in 0.48 seconds
```

You can also grab the source code from the repo to make sure that your local version matches that which passes tests:
https://github.com/Pylons/pyramid/tree/master/docs/quick_tutorial/forms

**Comment by sevillalarry** [comment]
As per tutorial:

directory 'view_classes' was copied to a new directory 'forms'

then, there was a major revision in 'tutorial/views.py', notably

'class TutorialViews' was changed into 'class WikiViews'

but there was no revision in 'tutorial/tests.py' in the tutorial page.

(I just downloaded the one from github, and everything's fine)

**Comment by stevepiercy** [comment]
OK. Thanks. I see there is a step missing in between steps 8 and 9:
http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/forms.html

A step needs to be inserted, where the user updates the file `tests.py` accordingly.

**Comment by stevepiercy** [comment]
@sevillalarry p.s., if you notice any other omissions in other steps, please do let us know.

**Comment by sevillalarry** [comment]
Welcome and thanks also...
