### ISSUE TITLE
JSON is not text and has no charset (upcoming WebOb changes)

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid#2691]
Due to changes in WebOb (https://github.com/Pylons/webob/pull/261) to fix content type/charset handling, various tests within Pyramid are failing because the JSON renderer returns `str` objects and then the `RenderHelper` attempts to set `Response.text` which fails if there is no `charset`.

All none-text types (so anything that does not match mime type `text/*`, `application/xml` or `*/*+xml`) no longer automatically have a charset set, this means they are treated as bytes objects only.

https://github.com/Pylons/pyramid/blob/master/pyramid/renderers.py#L275
https://github.com/Pylons/pyramid/blob/master/pyramid/renderers.py#L382

Should both have a `.encode('UTF-8')` added, to correctly encode it's rendering into a bytes object.

Extra protection could also be added here:

https://github.com/Pylons/pyramid/blob/master/pyramid/renderers.py#L468-476

It should verify that a `charset` is set, before attempting to set the `response.text`.

With the addition of the call to `encode()` in the JSON renderers, the test suite would have to be appropriately updated to use `b''` wherever there are string literals that are being compared, currently there are 12 tests that fail with the `encode()` fix in place.

**Comment by mmerickel** [comment]
If we add the two fixes proposed we can release a bugfix to 1.7 and 1.6 in preparation for people upgrading webob prior to pyramid.

As far as the "verify that a `charset` is set" I'm not clear what the end game is there. If it is not set do we just encode to utf-8?

**Comment by bertjwregeer** [comment]
@mmerickel I am going to implement the change in WebOb whereby there is a `default_encoding`. If no `charset` is set or there is no valid `charset` for the `Content-Type` then accessing `resp.text` will use `default_encoding` instead.

`default_encoding` is going to be set to `UTF-8` by default.

---

My comment regarding checking for a `charset`, if there is none, then the data is technically binary so if a renderer returns a text type, it should either raise, or one could just encode it to "utf-8" and call it good (but I wonder if that would allow for subtle errors).

Either way with the fix I am proposing in WebOb before I make the changes, that becomes entirely moot since `resp.text` will just work (albeit with an implicit encode using `default_encoding`, which in this case will be 'UTF-8').

**Comment by bertjwregeer** [comment]
@mmerickel 

I've added a `default_encoding` on `Response`, but it does have backwards incompatibility changes as a side-effect:

https://github.com/Pylons/webob/pull/261/commits/22bd28178d126946f86a4db6ba9e1917c7e5ad52#diff-bb3c4deeba77c2bbfd893f2e90fecc77R28

Would definitely like your input on whether this is a good idea, or if this should get fixed in Pyramid instead for 1.6/1.7.

Only reason I am attempting to fix it is due to Pyramid using `.text`, and I am not sure it is worth the backwards incompatible change. Would like your feedback.

**Comment by bertjwregeer** [comment]
I've removed the whole `default_encoding` thing from that WebOb PR. Didn't like it.
