### ISSUE TITLE
`etag_cache` function?

### ISSUE THREAD

**Issue by tsauerwein** [Pylons/pyramid#2726]
Pylons used to have a [etag_cache](http://docs.pylonsproject.org/projects/pylons-webframework/en/latest/caching.html#e-tag-caching) helper function. For my use-case this function seems to be convenient.

I am wondering if there is now a better way to set/check ETag headers, or would a PR adding this function again be welcome?

**Comment by bertjwregeer** [comment]
WebOb already has support for etags:

http://docs.webob.org/en/stable/api/response.html#webob.response.Response.etag

If you set the etag on a response, and build a response that has conditional_response set to True (http://docs.webob.org/en/stable/api/response.html#webob.response.Response) WebOb will take the environment from the original request and return a 304 or other conditional response as needed.

**Comment by tsauerwein** [comment]
`etag_cache` allows me do the following:

```
def view(request):
    key = get_key(...)
    etag_cache(key)
    // ... do heavy work
    return result
```

If the current etag matches the provided etag, the part with the "heavy work" is skipped. Can I do the same with `Response.etag` and `conditional_response`?

**Comment by bertjwregeer** [comment]
No. You'd still have to generate the content in case the etag does not match, and the conditional response has to send a full response.

You could potentially get away with providing a generator as the app_iter for the response and not do any heavy lifting until it actually needs to send a body.

**Comment by tsauerwein** [comment]
Ok, thanks for the info!

**Comment by mmerickel** [comment]
You can generate the etag yourself and compare it to the one in `request.if_none_match` for example.

```python
etag = gen_etag(key)
if etag in request.if_none_match:
    # skip work
else:
    # do work
```

**Comment by mmerickel** [comment]
I don't see an actual issue here so closing.
