### ISSUE TITLE
Can I log out of a session in Pyramid using Curl Http Post?

### ISSUE THREAD

**Issue by anouar99pac** [Pylons/pyramid#2731]
I have two frameworks Pyramid and Zope. For the login sessions, I use a CAS server connection.

However, when either services (Pyramid and Zope) is logged out, the CAS server will send an HTTP request using a Curl Post.

There seems to be no problem when sending this HTTP request. I have checked that I receive it correctly and am able to debug the code for the logout command.

```
""" Invalid ticket log out """
if request.get('<samlp:LogoutRequest    xmlns'):
     headers = forget(request)
     request.session.clear()
     return HTTPFound(location=CAS.get_logout_url(request), headers=headers)
```

The problem is that when the above code is executed, the session does not log out.

Is it possible that the above code is well executed and kills the session on this service, but the framework prevents the log-out by retrieving the session cookie from the user's browser?

Do you have any idea how to solve this problem? Is it possible to log out using Curl or not?

Thanks a bunch.

**Comment by mmerickel** [comment]
What? What do you mean the "session does not log out"? Are you using the `SessionAuthenticationPolicy`? Otherwise what does the session have to do with authentication?
