### ISSUE TITLE
support Same-site cookies

### ISSUE THREAD

**Issue by philtay** [Pylons/pyramid#2733]
Please support [Same-site cookies](https://tools.ietf.org/html/draft-west-first-party-cookies-07) in `pyramid.response.set_cookie`. This new standard provides protection against CSRF attacks and Google Chrome has [already implemented it](https://developer.chrome.com/extensions/cookies).

**Comment by mmerickel** [comment]
This is actually an issue for webob and a duplciate of https://github.com/Pylons/webob/pull/255. However I'm going to leave this open and rephrase it.

Pyramid should add support for `same_site=True` on `AuthTktAuthenticationPolicy` and `SignedCookieSessionFactory` once webob supports it in its `CookieProfile` API.

**Comment by bertjwregeer** [comment]
Is this actually RFC yet? Or is it still experimental? I need to write some docs with the experimental stuff so that rapid changes can be made as the standard evolves rather than having to worry about backwards compatibility.

**Comment by ztane** [comment]
Actually now that I read it, there is no `same_site=True` but there are 2 distinct behaviours, strict and lax; strict would mean that even a GET request wouldn't send the cookie if it originates from a link on another site, so if you Google something and it directs to your site, then open the link, you are *not* logged in to your site in that tab.

**Comment by AvnerCohen** [comment]
@mmerickel @ztane Any ideas if this planned any time soon?

**Comment by bertjwregeer** [comment]
I have merged support for it into WebOb, but it is not yet in a release.

**Comment by alex** [comment]
What is the next step here, now that this is landed in webob. Is this something that I could help with?

**Comment by ztane** [comment]
Well, `pyramid.response` is a WebOb response so it supports it.

**Comment by alex** [comment]
Should this bug be closed then? Or is there more work to do?

**Comment by mmerickel** [comment]
@alex thanks for checking! This bug relates to Pyramid's usage / support of same-site cookies in APIs that wrap or use cookies. This means adding relevant support to `BaseCookieSessionFactory`, `SignedCookieSessionFactory`, `AuthTktAuthenticationPolicy` and probably `CookieCSRFStoragePolicy`. This basically entails adding an option to each policy, docs for the option, and tests to each object to ensure they support the option.

**Comment by mmerickel** [comment]
Sessions were updated via https://github.com/Pylons/pyramid/pull/3300.

- [X] BaseCookieSessionFactory
- [X] SignedCookieSessionFactory
- [ ] AuthTktAuthenticationPolicy
- [ ] CookieCSRFStoragePolicy

**Comment by persho** [comment]
@bertjwregeer @mmerickel I am using Pyramid 1.10.4 and I had issues setting samesite=None like 
`AuthTktAuthenticationPolicy(settings['auth.secret'], hashalg='sha512', max_age=3600 * 24, samesite=None, http_only=True, secure=True)`

it never came to cookie, so the cookie always used default samesite='Lax'. We tried to find a reason, and finally got it to work using 'None' as a string.

`AuthTktAuthenticationPolicy(settings['auth.secret'], hashalg='sha512', max_age=3600 * 24, samesite='None', http_only=True, secure=True)`

I am not sure this is expected, but it works. 

Thanks
Gabrijel

**Comment by mmerickel** [comment]
The string `None` is the correct usage. The `None` sentinel in Python would normally indicate to not set samesite at all on the cookie, but may also trigger the default `Lax` like you mentioned. If you think we should improve the docs could you submit a PR or point out specific locations?

**Comment by persho** [comment]
Hey @mmerickel yes actually I think docs are misleading https://docs.pylonsproject.org/projects/pyramid/en/latest/api/authentication.html

check samesite section. It talks about 'Lax' and None as a non string. It would be awesome to mention explicitly that None has to be passed as a string. Hope it is not just me who got confused :)

**Comment by mmerickel** [comment]
I'm more concerned that it sounds like you're saying `samesite=None` is triggering a `SameSite=Lax` header, which is counter to the current docs that say it should not add a `SameSite` directive to the cookie at all. This would be a bug.

**Comment by bertjwregeer** [comment]
`samesite=None` currently tells the code that you don't want to send a `SameSite` flag in the cookie that is being sent to the remote user.

The browser then converts that to `Lax` or whatever Chrome has decided today by default... the docs should be updated to use the string, and it looks like @stevepiercy did so.
