### ISSUE TITLE
pyramid/docs/quick_tutorial/ authentication and authorization

### ISSUE THREAD

**Issue by sevillalarry** [Pylons/pyramid#2735]
Please be informed that:

tutorial/security.py in the quick tutorial document and github are different.

Got error in authorization when following the quick tutorial document.

**Comment by stevepiercy** [comment]
Can you be more specific? Which branch?

The Quick Tutorial does a `literalinclude`, so it pulls in the source file directly, at least on the master branch.

```rst
   .. literalinclude:: authentication/tutorial/security.py
```

**Comment by sevillalarry** [comment]
there was an update on "20 logins in authentication". mine was old page.
there were days gap in my tutorial.

"21 protecting resources with authorization" was new page.


you can close this one.
