### ISSUE TITLE
No module name 'bcrypt'

### ISSUE THREAD

**Issue by sevillalarry** [Pylons/pyramid#2736]
I got "No module name 'bcrypt'" error on quick tutorial document, number 21 protecting resources with authorization when I copied tutorial/security.py from github.

Did I missed something?

**Comment by ztane** [comment]
bcrypt is a separate installable module from PyPI. Perhaps the tutorials missed adding that to `setup.py` or saying that you need to reinstall requirements?

**Comment by ztane** [comment]
No, at least this one http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/authentication.html spells it out, perhaps it should stress a bit more that you need to pip install -e again, or did pip fail to recheck dependencies? setup.py develop would work

**Comment by ztane** [comment]
Ah by happenstance, are you reading *old* documentation? The docs are now for 1.7 and so is the git tip. And Chapter 21 says it builds on Chapter 20.

**Comment by stevepiercy** [comment]
The most common problems:

1. User fails to include URL of page in docs when reporting issue with docs.
1. User fails to use latest release of docs, following outdated versions.
1. User jumps in to a step without following preceding steps.
1. User fails to install project in development mode, using `$VENV/bin/pip install -e .`, or forgets to set an environment variable `$VENV` as instructed in the introduction.

@sevillalarry verify you made none of the above mistakes first. If you can reproduce the issue, then please provide explicit steps to reproduce, and we will investigate further and correct documentation as needed.

**Comment by sevillalarry** [comment]
there was an update on "20 logins in authentication". mine was old page.
there were days gap in my tutorial.

"21 protecting resources with authorization" was new page.


you can close this one.
