### ISSUE TITLE
1.7.1 changed the json renderer to return bytes instead of unicode

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#2744]
```
result = pyramid.renderers.render('json', {}, request=request)
```

``result`` is now ``bytes`` instead of ``unicode``. This is a regression in 1.6.2 and 1.7.1.

This is not a problem with `render_to_response` or `view_config(..., renderer=json)` because they are using the response object.

**Comment by mmerickel** [comment]
related: https://github.com/Pylons/pyramid/pull/2706

**Comment by bertjwregeer** [comment]
:-/

Sorry :-(
