### ISSUE TITLE
zope.interface 4.3 breaks pyramid registry

### ISSUE THREAD

**Issue by MarcSchmitzer** [Pylons/pyramid#2758]
[A change introduced in zope.interface 4.3.0](https://github.com/zopefoundation/zope.interface/commit/58ef4872922803fac3429d88fb3c58ae509b17c5) breaks the pyramid registry because the `Components` class (which `Registry` derives from) now assumes that its instances are hashable. Pyramid `Registry` instances are not hashable because it derives from `dict`.

Example stack trace:

    .tox/py27/local/lib/python2.7/site-packages/pyramid/testing.py:470: in setUp
        config._set_settings(settings)
    .tox/py27/local/lib/python2.7/site-packages/pyramid/config/settings.py:15: in _set_settings
        self.registry.settings = settings
    .tox/py27/local/lib/python2.7/site-packages/pyramid/registry.py:99: in _set_settings
        self.registerUtility(settings, ISettings)
    .tox/py27/local/lib/python2.7/site-packages/zope/interface/registry.py:227: in registerUtility
        _UtilityRegistrations.for_components(self).registerUtility(provided, name, component, info, factory)
    .tox/py27/local/lib/python2.7/site-packages/zope/interface/registry.py:82: in for_components
        regs = cls._regs_for_components[components]
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    self = <WeakKeyDictionary at 140605312576040>, key = <Registry testing>

    def __getitem__(self, key):
    >       return self.data[ref(key)]
    E       TypeError: unhashable type: 'Registry'`

**Comment by tseaver** [comment]
https://github.com/zopefoundation/zope.interface/pull/54 fixes it in `zope.interface` 4.3.1

**Comment by bertjwregeer** [comment]
Pyramid once again builds on Travis using the updated `zope.interface` too.
