### ISSUE TITLE
2.0 Feature Suggestion: ability to persist set_cookie on redirects

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#2763]
This has been bugging me for a few years now, so I wanted to bring it up on the 2.0 discussion.  It is a variant of this old ticket - https://github.com/Pylons/pyramid/issues/691

Pyramid's design makes it rather hard to set cookies on a redirect:

1. A HTTPFound exception must be returned by a view; it can not be raised (unless you specify the headers in the raise).  Raising the redirect exception will clear out existing the `request.response` objects (which the set_cookie was registered onto)
2. If you return the exception, you then need to catch it in a `pyramid.events.NewResponse` event and translate the headers from the `event.request.response` to the `event.response`.  

It would be really great if there were a simpler way to register cookies to unconditionally set via the request object - sort of like how `request.add_finished_callback` works.

A common use-case for this is a form-submission redirecting on success.

**Comment by bertjwregeer** [comment]
A HTTPFound is a perfectly good response, and can thus have `set_cookie` be called on it.

```
response = HTTPFound(location='mylocation')
response.set_cookie(...)

return response
```

or

```
request.response.status_code = HTTPFound.code
request.response.location = 'http://google.com/'
request.response.set_cookie(...)

return {}
```

or

```
response = HTTPFound(location='mylocation', headers=[('Set-Cookie', webob.cookies.make_cookie(...)), ('Set-Cookie', webob.cookies.make_cookie(...))])
return response
```

or

```
response = HTTPFound(location='mylocation', headers=request.response.headers)
return response
```

**Comment by bertjwregeer** [comment]
Of course, you could use:

http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hooks.html#using-response-callbacks

```
def add_cookies(request, response):
    response.set_cookie(...)
request.add_response_callback(add_cookies)
```

**Comment by jvanasco** [comment]
Yes, all (or most of) the pyramid.httpexceptions are valid Response objects and can be instantiated or augmented with headers.

The approaches you first described are all convenient for simple test cases, but become incredibly unwieldy in larger applications that can have hundreds of httpexceptions -- which might be created within native views or 3rd party libraries.  As developers use different libraries within the pyramid ecosystem and people build re-usable frameworks, this becomes a limiting and annoying design choice.   If you use a library or create a module that raises a pyramid.httpexception, it can write out any cookies set by your application or other modules (in the main logic, a tween, etc).  At that point one must rely on subscribers or similar -- and pay careful attention to how exceptions are managed to try and catch a cookie.

It's certainly possible for a single application to use `add_response_callback` or even `add_finished_callback` to get around this (or most things).  pyramid's sessions use that exact approach too.

But this is all configuration needed to have sessions create a cookie on exceptions (in an environment.ini, or as a kwarg)

	session.cookie_on_exception = true

That's a much more elegant and maintainable syntax.

Since the only interface to do a set_cookie is on the Response, and not the request, this can't be done with a simple option.  instead, developers must pay careful attention to how/when cookies are set and exceptions are handled.

creating a hook that allows cookies to set on redirects/exceptions would make it a lot easier to leverage cookies in 3rd party modules and re-use code.  it would be much better for the ecosystem.

**Comment by mmerickel** [comment]
> session.cookie_on_exception = true

You realize that the session factory is using `add_response_callback` under the hood to set that cookie, right?

`request.response` is not meant to be a global response object shared and merged across different response workflows. It solves one specific workflow, and if your view doesn't use it then you pass it your response object around as you see fit. If you want something to affect **any** response object in your app then that's the purpose of response callbacks and subscribers.

**Comment by mmerickel** [comment]
To be clear, Pylons had a global response object and it was explicitly avoided in Pyramid because of how crazy it was merging 2 arbitrary response objects together. Being explicit about under what conditions you want these properties to actually go on the wire is very important. This is why things like the response callbacks/subscribers let you see if they are affecting a normal response or an exception response (by checking `request.exception`).

**Comment by jvanasco** [comment]
> You realize that the session factory is using add_response_callback under the hood to set that cookie, right?

Yes. I noted it above.

> request.response is not meant to be a global response object shared and merged across different response workflows.

I understand that and would not challenge it.  The current behavior of the response object is important and necessary.  I came from pylons, and know the problems created by a global_response all too well.

My concern is over the `set_cookie` functionality (though it generally applies to headers) and the behaviors resulting from it being supported on the Response object.  As pyramid's ecosystem grows, I see a lot of utility in providing support for registering cookies via the Request object.  A set_cookie coordinated by the request might preserve existing behavior by default, but accept a kwarg/config-option to still set the cookie on exceptions (via a similar callback).  This would be better implemented on the framework level than a package, because it would allow for 3rd party libraries to leverage it it.

Consider an application that exposes an API and uses 3rd party libraries to handle Authentication and Throttling.  A cookie could be set by the application or either plugin, but an HTTPException raised on any level would obliterate the data -- unless it is caught and transferred.  

If pyramid offered a set_cookie functionality via the Request, which could be configured for 'cookie_on_exception', the Authentication and Throttling modules might be configured to use them instead of the response.

**Comment by mmerickel** [comment]
This is **exactly** what `request.add_response_callback` is for. It seems like you just want some sugar on it that is less general than the solution provided. I just can't justify that.

**Comment by bertjwregeer** [comment]
Exceptions are meant to be exceptional. In almost all cases you don't want to actually send any of the data that was created on the response, including cookies and other header types.

Raising an exception for HTTPFound to me just seems weird.

**Comment by tseaver** [comment]
> Raising an exception for HTTPFound to me just seems weird.

The only reason I can think of for doing that is that the app is structured such that it can't detect the need for the redirect at / near the actual view function / method, but nested way down a call chain:  in that case, raising the HTTPFound avoids needing to code the intermediate layers to return it all the way to the view.  Maybe some kind of recursive search consuming elements from the query string to compute the redirect?

In any case, having the response callback set the cookie before pushing it across the wire seems like the Right Thing(TM).

**Comment by jvanasco** [comment]
Jumping back to this a few years later...

I'm sorry for being so adamant about this earlier. Pyramid was doing everything right for many years.

The cause of my concerns was supported a library that was no longer needed, but seemed to be - due to some bad unit tests:

* A much earlier version of Pyramid required special help to handle a `raise` vs `return`. This looks to have been changed in at least 1.1 - but my tests never caught that.

* A bug in Safari (finally closed in 2012 but enough legacy versions were still out until 2018) did not respect Set-Cookie on 302 and 303 responses.  The workaround was to grab the SetCookie, stash it in an existing serverside session, then set the cookies on the next http200 request.

Again, apologies for being annoying on this issue .
