### ISSUE TITLE
Add nose-selecttests to setup.py or fix HACKING.txt?

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#2781]
[HACKING.txt](https://github.com/Pylons/pyramid/blob/master/HACKING.txt#L167-L172) has the following:

```rest
- To run individual tests (i.e. during development) you can use a regular
  expression with the ``-t`` parameter courtesy of the `nose-selecttests
  <https://pypi.python.org/pypi/nose-selecttests/>`_ plugin that's been
  installed (along with nose itself) via ``python setup.py dev``. 
```

But nose-selecttests is not in [setup.py](https://github.com/Pylons/pyramid/blob/master/setup.py#L67-L71):

```python
testing_extras = tests_require + [
    'nose',
    'coverage',
    'virtualenv', # for scaffolding tests
    ]
```

Should I add the plugin to setup.py, or fix HACKING.txt to tell the user to install the plugin manually?

ping @mmerickel @bertjwregeer @tseaver

**Comment by stevepiercy** [comment]
Some notes to possibly add to HACKING.txt.

```bash
# manually install nose-selecttests
$ $VENV/bin/pip install nose-selecttests

# run one specific test "mytestname"
$ $VENV/bin/nosetests -t mytestname

# run one specific test "mytestname" in a class in a module at a path
$ $VENV/bin/nosetests tests/path/to/module.py:ClassName.test_mytestname

# run tests in a class in a module at a path
$ $VENV/bin/nosetests tests/path/to/module.py:ClassName.test_mytestname
```

**Comment by bertjwregeer** [comment]
I can honestly say that I have never used anything to run just a single test. IMHO tests should run fast enough to complete within a minute and running the whole test suite means that if you are making changes you don't accidentally break something.

Also, I run tox with -e py27,py35 so that I make sure not to break any Py2 stuff.

**Comment by mmerickel** [comment]
I regularly run a single test using nose's default syntax. I do not see the point of nose-selecttests being packaged here. Someone could install it if they want to use it, but otherwise what's the point of pyramid depending on it?

```
# run a single test
$ $VENV/bin/nosetests pyramid.tests.test_module:ClassName.test_mytestname`
```
