### ISSUE TITLE
Replace sphinxcontrib-programoutput with another package

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#2804]
sphinxcontrib-programoutput is no longer maintained and may cause future builds of the documentation to fail.

Replacement candidates include:
* https://pythonhosted.org/sphinxcontrib-autoprogram/
* http://sphinxcontrib-argdoc.readthedocs.io/en/latest/

See #2803

**Comment by stevepiercy** [comment]
pcreate and other p* scripts use `optparse`. Neither of the above options are possible solutions because they require `argparse`.

`optparse` is [deprecated as of Python 2.7](https://docs.python.org/2/library/optparse.html).

@mmerickel what do you think about updating p* scripts to use `argparse`? I found [some code](https://github.com/apple/swift-package-manager/commit/c2138c25ce48d799ea9dfb693b86cda996d6a68c) that might serve as a pattern to do so.

Our options include:
1. Do nothing. Continue using `sphinxcontrib-programoutput`.
1. Update p* scripts to use `argparse`.
1. Remove documentation that generates the output of the p* scripts.
1. Something else?

**Comment by mmerickel** [comment]
I can't find any examples of rendered output for http://sphinxcontrib-argdoc.readthedocs.io/en/latest/.

https://pythonhosted.org/sphinxcontrib-autoprogram/ looks fine. Switching to argparse shouldn't be a big deal because they are not extensible commands - no one should be depending on their internal parsing format.

**Comment by stevepiercy** [comment]
This issue is being worked in #2864

**Comment by stevepiercy** [comment]
Closed by #2864
