### ISSUE TITLE
Deprecation Warnings are not displayed by default

### ISSUE THREAD

**Issue by hyperknot** [Pylons/pyramid#2808]
Deprecation Warnings are not displayed by default, at least on Python 2.7.

There is a hidden [section](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/upgrading.html#my-application-doesn-t-have-any-tests-or-has-few-tests) in the docs, mentioning that it can be manually enabled by

```
PYTHONWARNINGS=default $VENV/bin/pserve development.ini
```

There are two problems with this:

1. As it's silenced by default, this is not functioning as a warning. The user would actively need to look and seek for clues how to manually enable those warnings, which I guess results in 99% of the users not seeing any of those warnings.

2. The following 3 lines are always displayed when warnings are enabled, 2x when using `--reload`:

```
/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/Users/user/.virtualenvs/gigamacro_web/lib/python2.7/site-packages/zope': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/Users/user/.virtualenvs/gigamacro_web/lib/python2.7/site-packages/repoze': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/Users/user/.virtualenvs/gigamacro_web/lib/python2.7/site-packages/paste': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
```

I _think_ Django has the warnings enabled by default in Python 2.7, but I didn't find the code, only the result (it is displayed for all users on all platforms by default).

**Comment by mmerickel** [comment]
I don't see anything about warnings being on by default in Django. I see some docs suggesting you turn them on yourself. https://github.com/django/django/blob/3c447b108ac70757001171f7a4791f493880bf5b/docs/howto/upgrade-version.txt#L45

**Comment by hyperknot** [comment]
I couldn't find anything either, but I've just double checked, and the default `./manage.py runserver` prints lines like

```
/Users/user/.virtualenvs/kek/lib/python2.7/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)
```

**Comment by mmerickel** [comment]
If I start a new django project and add `import django.contrib.admin.util` to a file in that project I do not see the warning unless I run with the `-Wd` cli flag. I tried this using Django 1.8.16 as that module is removed in 1.9.

**Comment by hyperknot** [comment]
It seems it's not initialised early on, but only after some kind of setup process has completed.

```
pip install "django<1.9"
django-admin startproject project

cd project
./manage.py startapp app
echo "import django.contrib.admin.util" > app/__init__.py
echo "INSTALLED_APPS += ('app',)" >> project/settings.py

./manage.py runserver
```

**Comment by mmerickel** [comment]
I just went through all of these steps and don't see a warning. What python are you using? Are you sure you don't have a `PYTHONWARNINGS` env variable set?

**Comment by mmerickel** [comment]
I tracked down how this works and it's a little clever. Basically, if the user doesn't override the warnings from the command-line/environment, django will configure `logging.captureWarnings(True)` and defines a `py.warnings` logger that emits messages to the console. This is nice for several reasons but not the issue at hand.

The reason you're seeing the warnings is that django specifically registers `django.utils.deprecation.RemovedInNextVersionWarning` as a default-on warning via `warnings.simplefilter('default', RemovedInNextVersionWarning)`.

If Pyramid defined such a warning we could also enable it by default. I think this approach of redirecting warnings to the logging module is also nice.

**Comment by hyperknot** [comment]
Great findings! Also, I think it'd solve the problem of only displaying warnings we consider important (that is Pyramid core deprecations), while keeping quiet about missing __init__.py files for example.

**Comment by mmerickel** [comment]
I propose the following changes:

1. Modify `pyramid.paster.setup_logging(...)` to invoke `logging.captureWarnings(True)`, piping warnings into the logging subsystem.

2. Modify the scaffold config to output warnings to the console without timestamps.

3. Define `pyramid.deprecations.RemovedInNextVersionWarning` as an alias for `pyramid.deprecations.DeprecatedIn17Warning`. (As we'd release this as part of 1.8, we would be talking about removing features deprecated in 1.7 when 1.9 is released).

4. Modify `pyramid.paster.setup_logging(...)` to invoke `warnings.simplefilter('default', pyramid.deprecations.RemovedInNextVersionWarning)` if `sys.warnoptions` is not already defined.

The end result would be that all warnings would go through the logging system instead of straight to the console and that warnings for features that are scheduled to be removed in the next version of pyramid would emit warnings by default. Any other deprecations would still be hidden.

@tseaver Do you see have objections to this?

**Comment by mmerickel** [comment]
The biggest downside I see is that this is specific to Pyramid and other libraries wouldn't have this benefit. For example we're quite dependent on webob APIs and would want people to see deprecations there. If webob adopted such a warning we could opt into it automatically as well. A slippery slope but probably good for users.

**Comment by bertjwregeer** [comment]
WebOb emits just standard warnings at the moment, I wouldn't be opposed to doing something similar in WebOb that makes it easier for consumers to opt-in to warnings specifically from WebOb.

**Comment by mmerickel** [comment]
I started working on this and dove in a bit, then I discovered that Django has actually backtracked on this, actually removing the on-by-default warnings [1].

If they decided it was a bad idea, I'm much less compelled to worry about this for our users. We already have pretty decent documentation about testing pyramid with new releases to find such warnings [2].

[1] https://code.djangoproject.com/ticket/25999
[2] http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/upgrading.html
