### ISSUE TITLE
add 3.6 support to documentation

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#2835]
We've been running 3.6 tests for a while with no issues and it will be stable on 2016-12-16. We should update the docs and trove classifiers to indicate full support prior to the 1.8 release.

**Comment by stevepiercy** [comment]
I can take on this task, to free up senior developer time to work on harder tasks.

**Comment by stevepiercy** [comment]
I did not update the following, assuming that Python 3.6 needs to out of dev status before these can be changed.

* /.travis.yml
* /tox.ini

**Comment by mmerickel** [comment]
Appveyor doesn't support 3.6 yet. I opened #2885 to track this.

For the record it appears as if readthedocs is using Python 3.4 so I'm in no hurry to update the python we're using in tox.ini for docs.
