### ISSUE TITLE
Create a DuckDuckGo cheatsheet

### ISSUE THREAD

**Issue by JanLikar** [Pylons/pyramid#2844]
It is possible to create cheat sheets that are displayed when DuckDuckGo is used to search for eg. 'python cheatsheet'. @zupo suggested it would be nice to also have a Pyramid cheat sheet available.

https://docs.duckduckhack.com/walkthroughs/programming-syntax.html

**Comment by stevepiercy** [comment]
How would the proposed cheat sheet stay up to date with the official docs?

Would this increase the documentation maintenance burden?

I found a Django cheat sheet. I have no idea if it is useful to developers or if it helps with marketing of Django.
https://duckduckgo.com/?q=django+cheatsheet&ia=cheatsheet&iax=1
