### ISSUE TITLE
Update Hello World example to align with TryPyramid.com

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#2856]
We've updated the Hello World example on https://trypyramid.com per https://github.com/Pylons/trypyramid.com/pull/205 so we should update it on our official docs.

Verify that line numbers and narrative still align in docs whenever a `literalinclude` of Python files occurs.

- [x] README.rst
- [x] docs/designdefense.rst
- [x] docs/index.rst
- [x] docs/narr/helloworld.py
- [x] docs/narr/hellotraversal.py (take care to adapt code)
- [x] docs/narr/configuration.rst ("Declarative Configuration" section only)
- [x] docs/narr/firstapp.rst
- [x] docs/narr/hellotraversal.rst
- [x] docs/quick_tour/hello_world/app.py
- [x] docs/quick_tour.rst ("Hello World" section only)

Note that I excluded `docs/quick_tutorial/*` because it deliberately starts with imperative configuration, then introduces declarative configuration in [Step 7](http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/views.html).

**Comment by zupo** [comment]
Will completing the list above also include whatever source file used to generate text on https://pypi.python.org/pypi/pyramid? Or is there another file that needs modifying?

**Comment by stevepiercy** [comment]
Good catch. I've added `README.rst` to the list.

**Comment by stevepiercy** [comment]
I wanted to get some opinions before working on this issue. Below are two examples where the differences are:

1. **usage of the `request` object** - I think using the `request` object in the README.rst example is interesting and educational, but it's not "minimal". I'm leaning toward using the `request` object.
2. **port number** - I'd like to change the port number from 8080 to 6543 throughout examples because that's what is used by the cookiecutters and most of the documentation and for consistency.

# TryPyramid.com

```python
from wsgiref.simple_server import make_server
from pyramid.config import Configurator
from pyramid.response import Response

def hello_world(request):
    return Response('Hello World!')  # does NOT make use of the request object

if __name__ == '__main__':
    with Configurator() as config:
        config.add_route('hello', '/')
        config.add_view(hello_world, route_name='hello')
        app = config.make_wsgi_app()
    server = make_server('0.0.0.0', 6543, app)
    server.serve_forever()
```

# README.rst
```python
from wsgiref.simple_server import make_server
from pyramid.config import Configurator
from pyramid.response import Response

def hello_world(request):
    return Response('Hello %(name)s!' % request.matchdict)  # makes use of the request object

if __name__ == '__main__':
    with Configurator() as config:
        config.add_route('hello', '/hello/{name}')
        config.add_view(hello_world, route_name='hello')
        app = config.make_wsgi_app()
    server = make_server('0.0.0.0', 8080, app)
    server.serve_forever()
```

**Comment by stevepiercy** [comment]
TryPyramid.com has the authoritative version. It's simpler and requires fewer changes to the port number throughout our documentation.
