### ISSUE TITLE
Create a Style Guide for documentation

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#2880]
## Introduction and history

There is no style guide for documentation in any Pylons Project project. Since Pyramid has the largest and most comprehensive documentation of any Pylons Project project, it's the best candidate from which standards can be derived and documented.

An effort was put forth and merged into Pyramid `master`, but it was not adequately discussed beforehand and it became apparent that more discussion, corrections, and revisions were needed. It was moved onto a separate branch [Pylons/style-guide](https://github.com/Pylons/pyramid/tree/style-guide).

## Proposal and implementation

Ultimately the Style Guide shall reside in its own repository under the Pylons Project. However, to get more exposure, reviewers, and contributors, work on the Style Guide will reside in the Pyramid repository on the branch [Pylons/style-guide](https://github.com/Pylons/pyramid/tree/style-guide) with a pull request to master that **shall not be merged**, but merely present for performing diffs and requesting reviews. Upon final approval and consensus amongst the core developers:

1. the Style Guide shall be moved into its own repository,
1. the branch [Pylons/style-guide](https://github.com/Pylons/pyramid/tree/style-guide) shall be deleted, and
1. references to the Style Guide from the Pyramid documentation, https://pylonsproject.org/, and https://trypyramid.com/ shall be made.

For all projects, wherever contributing, writing documentation, or standards is mentioned, such as each project's `contributing.md`, a reference should be made to the new Style Guide project's documentation.

It is understood that rewriting documentation for the sake of adhering to policy is a massive undertaking and mostly tedious busy work. A comprehensive rewrite would also interfere with git blame history. For this reason, incremental changes to documentation, instead of comprehensive rewrites, are preferred.

Because it serves as a guide for documentation, it is easier to use Sphinx to render its reST source code to verify that code gets rendered as one expects.

**Comment by blaflamme** [comment]
I think its own project would make sense.

**Comment by stevepiercy** [comment]
Closing in favor of #3362
