### ISSUE TITLE
Document that registry can be used as dictionary

### ISSUE THREAD

**Issue by PavloKapyshin** [Pylons/pyramid#2891]
Currently ability to use `Registry` as a `dict` is only implied: for example, it is used in such way in alchemy scaffold to store and retrieve DB session factory. Maybe it is a good idea to explicitly document that `Registry` is a `dict` subclass?

**Comment by stevepiercy** [comment]
@PavloKapyshin do you mean like this?
http://docs.pylonsproject.org/projects/pyramid/en/latest/api/registry.html

Or something else?

**Comment by PavloKapyshin** [comment]
In retrospective, I admit title and text may be a bit misleading :) Basically, I suggest to make `__getitem__` and `__setitem__` methods (minimal set of methods to avoid relying on implementation details) of `Registry` part of its documented API.

Why: `alchemy` scaffolding generates code that relies on `config.registry[...]`. Generated code is part of an application, so it is nice to have benefits of documented API.

Or maybe I misunderstand something, and that aspect of application registry is documented?

**Comment by PavloKapyshin** [comment]
Thank you, @mmerickel!
