### ISSUE TITLE
Tutorial #18 example fails

### ISSUE THREAD

**Issue by stenci** [Pylons/pyramid#2897]
The test pyramid/docs/quick_tutorial/forms/tutorial/tests.py succeeds, but when I run the server and browse to http://localhost:6543/100/edit I get a bunch of 404.

Here is the server's output:

> 127.0.0.1 - - [08/Jan/2017 16:54:06] "GET /100/edit HTTP/1.1" 200 3714
> 127.0.0.1 - - [08/Jan/2017 16:54:07] "GET /deform_static/deform%3Astatic/scripts/jquery.form-3.09.js HTTP/1.1" 404 603
> 127.0.0.1 - - [08/Jan/2017 16:54:07] "GET /deform_static/deform%3Astatic/scripts/deform.js HTTP/1.1" 404 593
> 127.0.0.1 - - [08/Jan/2017 16:54:07] "GET /deform_static/deform%3Astatic/scripts/jquery.maskedinput-1.3.1.min.js HTTP/1.1" 404 615
> 127.0.0.1 - - [08/Jan/2017 16:54:07] "GET /deform_static/deform%3Astatic/tinymce/tinymce.min.js HTTP/1.1" 404 598

**Comment by miohtama** [comment]
I am the deform maintainer. Let me take a look on this.

**Comment by stevepiercy** [comment]
@miohtama the source files for this step are:
* https://github.com/Pylons/pyramid/blob/master/docs/quick_tutorial/forms/tutorial/wikipage_addedit.pt
* https://github.com/Pylons/pyramid/blob/master/docs/quick_tutorial/forms/tutorial/views.py

Looks like a RichTextWidget.

**Comment by Yepoleb** [comment]
The additional `deform:static` in the URL seems to be the problem.
http://localhost:6543/deform_static/deform:static/scripts/deform.js should be http://localhost:6543/deform_static/scripts/deform.js.

https://github.com/Pylons/pyramid/blob/master/docs/quick_tutorial/forms/tutorial/__init__.py may be relevant as well, because that's where the route is defined.

**Comment by Yepoleb** [comment]
I changed `${request.static_url('deform:static/' + reqt)}` to `${request.static_url(reqt)}` in `wikipage_addedit.pt` and it loads properly now.

**Comment by stevepiercy** [comment]
@Yepoleb along with that change, I needed to add some lines from the [rich text widget demo](https://github.com/Pylons/deformdemo/blob/master/deformdemo/templates/mini.pt#L17-L35) such that the CSS and JS would all load in the proper order. If you want to see a pretty rich text widget, try copying those lines into your `wikipage_addedit.pt`.

I'll submit a PR later tonight.

**Comment by stevepiercy** [comment]
Yup, this is a change in Deform 2.0 which we didn't catch in Pyramid tutorials:
http://docs.pylonsproject.org/projects/deform/en/latest/changes.html

> ### MIGRATION NOTES:
> ...
> deform 2.0 requires users to manually load TB 3.0 and jquery 2.0
