### ISSUE TITLE
Missing TOC on some quick_tutorial pages

### ISSUE THREAD

**Issue by stenci** [Pylons/pyramid#2898]
From the [first page](http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/requirements.html) to page [11](http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/routing.html) and on page [20](http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/authentication.html) the toc is on the left as expected.

From page [12](http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/jinja2.html) to [19](http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/databases.html) and on page [21](http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/authorization.html) the toc on the left is missing.

**Comment by stevepiercy** [comment]
Thanks for the report. I initiated a rebuild of the docs, and the issue is resolved. If it appears to persist, force reload the page or clear the browser cache.
http://readthedocs.org/projects/pyramid/builds/4875608/
