### ISSUE TITLE
Restore the Registry(*args, **kw) API

### ISSUE THREAD

**Issue by tlotze** [Pylons/pyramid#2916]
In the course of #2891, the Registry API was changed in a backwards-incompatible way. While the author of the change (PR 2893) couldn't imagine anyone using the keywords API, I immediately ran into the incompatibility with a number of customer projects. Since the change back to the old API shouldn't introduce another backwards incompatibility, I suggest reverting that change as soon as possible.

**Comment by bertjwregeer** [comment]
How were you using the API?

**Comment by mmerickel** [comment]
It looks like you can configure the registry to delegate lookup to another registry (probably the global one). I will patch this for 1.8.1. I should have done more research on what the `bases` argument was prior to removing it.

https://github.com/zopefoundation/zope.interface/blob/b8a36f1b6aa2c4d4470c08b84bb6f5031e33ab30/src/zope/interface/registry.py#L180

https://docs.zope.org/zope.component/api/utility.html#delegated-utility-lookup

**Comment by tlotze** [comment]
I'm using code like this to make Pyramid use the global ZCA registry:
```
        registry = pyramid.registry.Registry(
            bases=(zope.component.getGlobalSiteManager(),))
        config = pyramid.config.Configurator(
            settings=self.settings,
            registry=registry)
        config.setup_registry(settings=self.settings)
```
There are documented ways to do something similiar without using the `bases` parameter, but I'm not aware of another way to have Pyramid use a registry that delegates, but is not identical, to the same ZCA global registry that has been in use during process start-up before Pyramid came into play, while being a full `pyramid.registry.Registry` (as opposed to a `zope.interface.registry.Component`, which the Pyramid registry expands upon).

In addition to this technical reason for wanting the `bases` parameter back, I consider it a matter of principle that a backwards-incompatible change like this should not go into a release without some research (and without even being documented in the change log). I'm happy to see that we agree on that, so I'd like to reinforce my suggestion to just restore the old `*arg, **kw` API in 1.8.1 and bring up simplification as a feature for a future release, so it may be discussed by the users of the API.

**Comment by tlotze** [comment]
Thank you!

**Comment by russellballestrini** [comment]
@mmerickel you rock, thank you for resolving this so quickly.
