### ISSUE TITLE
pserve does not start when not connected to internet

### ISSUE THREAD

**Issue by abhijithb21** [Pylons/pyramid#2940]
Three people reported to me that pserve does not run on their machine when not connected to internet. All three of them are using Ubuntu 16.04 on Dell laptops.

It is still working in my Debian Testing on a Dell laptop.

**Comment by bertjwregeer** [comment]
What error message do you get?

Most likely it is related to:

https://github.com/Pylons/waitress/pull/153
https://github.com/Pylons/waitress/issues/149

Will get a release out tomorrow (it's midnight, don't want to mess something up)

To fix the issue for the next 24 hours till I get a new release out:

    pip install "waitress<=0.9"

**Comment by abhijithb21** [comment]
Thank you for the quick response. I'll ask them to do the same and reply here.

**Comment by bertjwregeer** [comment]
I have released waitress 1.0.2 which should hopefully fix the issues you were seeing: https://pypi.python.org/pypi/waitress/1.0.2

`pip install -U waitress`

Thanks!
