### ISSUE TITLE
pserve --reload call hupper which call pserve with sys.argv instead of the parameters

### ISSUE THREAD

**Issue by Natim** [Pylons/pyramid#2961]
If you are calling `pserve.main(argv)` and `argv` contains `--reload` it will call upper with `sys.argv` instead of `argv`.

**Comment by mmerickel** [comment]
This main function is not actually an API. What are you using it for? I'm inclined to not fix this as you're apparently relying on some implementation details of the CLI scripts.

**Comment by Natim** [comment]
We are using it in the kinto command to run the server: `kinto --ini config.ini start --reload`

**Comment by Natim** [comment]
> This main function is not actually an API.

Even if it is not an API, the fact that you can pass argv to it and that hupper doesn't care about them is a problem.

**Comment by mmerickel** [comment]
Just FYI I'm not sure why I didn't mention this before but it's possible to embed pserve without forwarding the `--reload` option. You can simply import and run `hupper.start_reloader` yourself and pserve will pick up on it and pass the ini files to the watcher process. Regardless 1.8.3 is out now with the fix from #2962.

**Comment by Natim** [comment]
Thanks :)
