### ISSUE TITLE
pserve disables existing loggers

### ISSUE THREAD

**Issue by leplatrem** [Pylons/pyramid#2975]
`pserve` calls [logging.config.fileConfig()](https://docs.python.org/3/library/logging.config.html#logging.config.fileConfig) but [leaving the default value of `disable_existing_loggers`](https://github.com/Pylons/pyramid/blob/c151adb1ee83eb34005a9883e748831e2b79de21/pyramid/scripts/common.py#L42) to True.

In some situations, this prevents the `root` logger to catch certain loggers defined on top of modules (import time). Adding `disable_existing_loggers=False` solves the issue. 

Would you consider setting that flag (I can open a PR), or does anybody have specific recommendations that we could emphasize in the logging documentation to avoid such pitfalls?

I would appreciate your feedback, especially if this is completely expected.

Thanks!

> Note: I'm a bit embarrassed 'cause I can't reproduce in a minimalist project. Proof that I haven't fully understood the deep implications of that `fileConfig()` option.

**Comment by mmerickel** [comment]
This usually means that you imported modules that configured loggers *before* configuring logging. That's usually pretty difficult to do when using pserve because it configures logging before importing your app or server.

I'm not against changing the default but I'd need a more reproducible example of what's going wrong to consider fixing it so that we could consider the implications.

**Comment by leplatrem** [comment]
You gave me a hint!

We have a logging formatter in a submodule of our application, whose parent is imported when specified in the `.ini`. The [`_resolve()` ](https://github.com/python/cpython/blob/v3.5.3/Lib/logging/config.py#L90-L102) function used by `logging.config.fileConfig()` seems to be responsible of importing parents.

I could reproduce (without the nested submodules) using that simple example: 

```ini
[loggers]
keys = root

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = DEBUG
handlers = console

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
class = logtest.utils.Formatter
```

```py
# __init__.py
from pyramid.config import Configurator

def main(global_config, **settings):
    config = Configurator(settings=settings)
    config.include("logtest.utils")
    return config.make_wsgi_app()
```

```py
# utils.py
import logging

from pyramid.events import NewResponse

logger = logging.getLogger(__name__)
summary_logger = logging.getLogger("request.summary")

def includeme(config):
    logger.info("Setup")

    def on_new_response(event):
        summary_logger.info("Hit {}".format(event.request.path))

    config.add_subscriber(on_new_response, NewResponse)

class Formatter(logging.Formatter):
    pass
```

When specifying the formatter class in the `.ini`, the `root` won't catch the loggers.

Again, I could fix our code, but I would like to at least help others devs avoid that pitfall :) As you said, since this is very specific situation, we may want to consider using `disable_existing_loggers=False`

Your call! Thanks for your light-speed answer :)

**Comment by mmerickel** [comment]
I'm inclined to switch this default as you suggest. I'd like to hear what other people think though.

**Comment by mmerickel** [comment]
From the docs on `disable_existing_loggers`:

> This behaviour is to disable any existing loggers unless they or their ancestors are explicitly named in the logging configuration.

I will say that the docs certainly suggest it's old broken behavior to rely on that setting and that you can fix loggers by defining them in the config file but then you need to know which ones are being disabled.

**Comment by mmerickel** [comment]
This issue belongs in plaster_pastedeploy if we want to switch this behavior.
