### ISSUE TITLE
Non-deterministic renderer selection with no 'Accept' header

### ISSUE THREAD

**Issue by bjmc** [Pylons/pyramid#2986]
Hello, I'm not sure if this is properly a bug, but it's certainly somewhat confusing behavior. If it's expected, I think it should be documented more prominently.

As far as I can tell, if you register multiple renderers for the same view callable, and differentiate between them using the HTTP `Accept` header, then in situations where the client doesn't send an `Accept` header, Pyramid chooses one in a non-deterministic fashion.

Here's a small example to demonstrate:

```python
from pyramid.config import Configurator
from pyramid.view import view_config
from pyramid.renderers import JSON
from webtest import TestApp

class Renderer1(JSON):

    def __call__(self, info):
        """ Returns a plain JSON-encoded string with content-type
        ``application/json``. The content-type may be overridden by
        setting ``request.response.content_type``."""
        def _render(value, system):
            request = system.get('request')
            if request is not None:
                response = request.response
                ct = response.content_type
                if ct == response.default_content_type:
                    response.content_type = 'application/vnd.api+json'
            default = self._make_default(request)
            return self.serializer(value, default=default, **self.kw)

        return _render

class Renderer2(JSON):
    pass

@view_config(route_name='hello', accept='application/vnd.api+json', renderer='renderer1')
@view_config(route_name='hello', accept='application/json', renderer='renderer2')
@view_config(route_name='hello', accept=None, renderer='renderer2')
def hello_world(request):
    return {'Hello': 'World'}

def make_app():
    config = Configurator()
    config.add_route('hello', '/')
    config.add_renderer(name='renderer1', factory=Renderer1())
    config.add_renderer(name='renderer2', factory=Renderer2())
    config.scan()
    app = config.make_wsgi_app()
    return app

def main():
    app = make_app()
    testapp = TestApp(app)
    resp = testapp.get('/', headers={})
    assert resp.content_type == 'application/json'

if __name__ == '__main__':
    main()
```

If you run this script multiple times, for example:

`for i in {1..5}; do python example.py; done`

you will see that an `AssertionError` is triggered only about half the time. I've observed this behavior with Pyramid 1.8.3 under Python 3.4 on Ubuntu.

My expectation was that by doing `@view_config(route_name='hello', accept=None, renderer='renderer2')` then when the `Accept` header was absent, `renderer2` would always be used.

**Comment by mmerickel** [comment]
Hello @bjmc and thanks for the nice reproducible example. Your issue is related to the fact that the `TestApp` is not passing an accept header which means that it is declaring that it doesn't care what content type it gets back. This is parsed into a `webob.acceptparse.NilAccept` accept object which matches any possible content type.

You can see https://github.com/Pylons/pyramid/issues/1264 for a bit more info but we have not yet implemented any changes to the accept system. Anything you wish to contribute in this space would be appreciated but accept handling in general is a very complex topic due to the horribleness of the RFC versus what people *think* it is.
