### ISSUE TITLE
Unbond methods

### ISSUE THREAD

**Issue by alexfalcucc** [Pylons/pyramid#2997]
Exploring pyramid and your changes I didn't find any issue that talks about why unbond method calls are not supported anymore since pyramid 1.7, that for me could keep this feature as it was before. It means that you are able to use decorators only on pyramid class views and not if your view is a function, that repectively it will break.

```python
@view_config(...)
@decorator1('arg1', 'arg2')
def my_view(request):
```

```python
ConfigurationExecutionError: <class 'pyramid.exceptions.ConfigurationError'>: 
Unbound method calls are not supported, please set the class as your `view`
and the method as your `attr`
```
So [here](https://github.com/Pylons/pyramid/blob/1.7b3/pyramid/viewderivers.py#L63-L68), we are checking the method is bond/unbond and their attributes, but if it's a class and attributes are `None` everything is [fixed](https://github.com/Pylons/pyramid/blob/1.7b3/pyramid/view.py#L218-L223).

Firstly I am using a lot of decorators on my view methods and everything works fine with pyramid 1.6 but I don't want to use class views for every view that I will create til it may be really necessary, but this error sucks me on pyramid 1.8 and I want keep pyramid with the latest version.

So, I did some changes to fix this and just making this little change:
```python
if info.scope in [ 'class', 'module']:
```
Everything works great.

There's another way to add our custom decorators but it don't accept parameter for itself:
```python
@view_config(..., decorator=(decorator1('arg1', 'arg2'), decorator2('arg1', 'arg2')))
def my_view(request):
```
It breaks. So in theory still just as unbound as the first method but with no parameters.

**Comment by mmerickel** [comment]
So I'll take the last part first. 

> There's another way to add our custom decorators but it don't accept parameter for itself:

This should work fine. The only reason it might not is because your decorator is not expecting the `(context, request)` signature which is the biggest advantage of using `decorator=`. Even if you're decorating a class method that doesn't take request, the decorator still will use the same signature.

Finally... I don't know how your decorators are defined as you don't provide a reproducible example but things work fine for me on functions. Can you tweak this example such that it doesn't work? The view is the one from a pyramid-cookiecutter-starter project.

```python
def mydecorator(*args):
    def decorator(wrapped):
        def wrapper(request):
            print('wrapping request', request.url, args)
            return wrapped(request)
        return wrapper
    return decorator

class mydecorator2(object):
    def __init__(self, *args):
        self.args = args

    def __call__(self, wrapped):
        def wrapper(request):
            print('wrapping request', request, self.args)
            return wrapped(request)
        return wrapper

@view_config(route_name='home', renderer='templates/mytemplate.jinja2')
@mydecorator('foo', 'bar')
@mydecorator2('baz')
def my_view(request):
    return {'project': 'Pyramid Scaffold'}
```

You really shouldn't be hitting this unbound method error unless your decorators are defined in some weird way.

**Comment by mmerickel** [comment]
If someone can give me a reproducible example I'll be happy to reopen the issue.

**Comment by alexfalcucc** [comment]
Fortunately everything works fine with the decorator attribute in the view_config just adding the context into it.

```python
class mydecorator(object):
    def __init__(self, *args):
        self.args = args

    def __call__(self, wrapped):
        def wrapper(context, request):
            return wrapped(context, request)
        return wrapper

@view_config(..., decorator=(mydecorator('foo', 'bar')))
def my_view(request):
```

But the first way doesn't work getting the ConfigurationExecutionError:
```python
@view_config(route_name='home', renderer='templates/mytemplate.jinja2')
@mydecorator('foo', 'bar')
def my_view(request):
```
```
'Unbound method calls are not supported, please set the class '
ConfigurationExecutionError: <class 'pyramid.exceptions.ConfigurationError'>: Unbound method calls are not supported, please set the class as your `view` and the method as your `attr`
```



Anyway, I will do this changes to upgrade pyramid. Thank you for the support, I really appreciate it!

**Comment by mmerickel** [comment]
I'm glad you have it working. I'm sorry I'm unable to reproduce the unbound method error with a function myself.

**Comment by mmerickel** [comment]
On a side note.. view derivers were added to Pyramid 1.7 which allow a declarative way to decorate your views. You may want to look into it. It'll allow you to avoid importing the decorator everywhere and simply doing something like `@view_config(..., use_my_decorator=True)`.

http://docs.pylonsproject.org/projects/pyramid/en/1.8-branch/narr/hooks.html#view-derivers

**Comment by alexfalcucc** [comment]
Pretty good! I didn't see that. It'll absolutely useful for me. thanks again!

**Comment by alexfalcucc** [comment]
Good news for me, It works fine with the `@decorator('foo', 'bar')` just adding the context into the view as well:
```python
class mydecorator(object):
    def __init__(self, *args):
        self.args = args

    def __call__(self, wrapped):
        def wrapper(context, request):
            return wrapped(context, request)
        return wrapper

@view_config(route_name='home', renderer='templates/mytemplate.jinja2')
@mydecorator('foo', 'bar')
def my_view(context, request):
```
Ugh! :)
