### ISSUE TITLE
Redirect DeprecationWarnings to output

### ISSUE THREAD

**Issue by hyperknot** [Pylons/pyramid#3009]
There was a discussion over IRC about this and I believe someone (possibly @mmerickel) implemented it in core for 1.8. I couldn't find an issue about it so I thought it's good to record this here as well.

The issue is about this not really working, or I'm forgetting something. I've upgraded an old project to Pyramid 1.8 and I don't see any warnings when running `pserve <inifile>` .

If I manually start it with `PYTHONWARNINGS=default pserve development.ini` the warnings are displayed.

// Note, also strange to read "It will be removed in Pyramid 1.8" lines for unauthenticated_userid in 1.8. Is that removed so it's actually an error and not a warning, or it's been pushed to 1.9+? 

Py 2.7

**Comment by mmerickel** [comment]
Yes, the explanation is in your other issue that was closed.

https://github.com/Pylons/pyramid/issues/2808#issuecomment-260549752
