### ISSUE TITLE
Pyramid's bad publicity - what is missing ?

### ISSUE THREAD

**Issue by corehack** [Pylons/pyramid#3015]
Did you notice how much is Pyramid unknown by the general public ? Whenever there's a discussion on web frameworks, there's Django, there's Flask, but very often, sadly, no mention of Pyramid.
I see a huge problem here, that Pyramid looks like hobbyist project that is not largely relevant in the web.

**Comment by bertjwregeer** [comment]
When does it not become a hobbyist project? When big companies use it? How big does the company need to be to call it a professional project?

https://trypyramid.com/community-powered-by-pyramid.html

Do any of those count?

Yeah, sadly Pyramid is not mentioned in the same breath as Flask or Django, but it is very far from a hobbyist project.

**Comment by corehack** [comment]
I'm just talking about the image. I do not myself consider Pyramid hobbyist or inferior in any way.
In the end its all less developers, jobs and projects for us - people who use it.
I'm just wondering what has to be done to have this upgrade, for people to take Pyramid as a big player.
Coming from Drupal world, people always tried to do all kind of things with Drupal like social networks, even if it was technically a bad idea - just how good Drupal's PR was. Can we achieve something similar ? Now I understand that Drupal's idea was about pleasing everyone - even people who can't program and obviously we are not on the same level since we are talking about a framework. But I hope you get the idea.

**Comment by russellballestrini** [comment]
@corehack yes, I understand where you are coming from and agree.  It would be nice if Pyramid was more popular with the masses but I've also grown to love and appreciate that its still a small group of very committed community members doing a lot of the work.

Some ways to make Pyramid more popular is to use it for bigger and bigger projects and blog about it.  Every couple of months I try to write a Pyramid centric blog post / guide.  

Its really down to marketshare. Flask and Django for whatever reason captured a large share of Python developers.  Its not that much different then a company capturing a large share of a market.  Its really hard to displace the people on top, and even more tricky when all of the time and energy to work on the project (in this case Pyramid) is 100% donated time.

It would be pretty cool if we could have a PR team, or a marketing team, or a sales team to promote Pyramid, but I don't see that happening anytime soon, unless a large consultancy or agency started building Pyramid apps and marketing it.

Pyramid is really flexible and not really opinionated which makes it really powerful.  It also means developers need to typically think quiet a bit more about which parts they want to use.  I think this also causes friction for the on-boarding of new developers. The Pyramid project has tried to solve this by supplying scaffolds and cookie cutter skeleton projects.

**Comment by stevepiercy** [comment]
The appropriate repository for marketing Pyramid is https://github.com/pylons/trypyramid.com.

For organization-wide marketing efforts of the Pylons Proejct, see https://github.com/pylons/pylonsproject.org/.

We have many open issues just *waiting* for a champion with free time or a sponsor with a large grant to hand out. New issues can also be created.

Finally we are doing some work about how to either create a legal entity or go under the umbrella of an established legal entity that will allow the Pylons Project to:

1. Form a legal entity with a board and advisors
2. Operate as a non-profit organization, if unable to attain a 501(c)(3) status from the IRS
3. Inure the entity and its members
4. Manage intellectual property
5. Manage licensing
6. Manage contributor agreements
7. Receive grants and donations, both in-kind and monetary
8. Disburse funds
9. Establish independent contractor agreements to avoid employee/employer entanglements and legal requirements

There are probably a few other organizational details, depending on whether we remain independent or go under and umbrella organization.

**Comment by cs0sor** [comment]
Flask/Django are the VHS of python frameworks, Pyramid is Betamax.

**Comment by mmerickel** [comment]
This issue belongs on the community mailing list and not the issue tracker. Thank you.

https://groups.google.com/forum/#!forum/pylons-discuss

**Comment by corehack** [comment]
I just read CONTRIBUTORS agreement...wow, an eye opening experience. Until its fixed, I don't think contributing to this project could be exciting for many people. The agreement sounds like a proprietary software license.
I understand @stevepiercy mentioned that it will be fixed, however as far as I imagine this is not easy and the timelines can't be estimated.

**Comment by stevepiercy** [comment]
Nope. I discussed the Pylons Project becoming a legal entity or going under the umbrella of an existing legal entity. The contributor agreement could be adapted to that entity, or we could adopt what the entity already has. That does not mean the existing contributor agreement is broken or needs fixing. It merely is.

**Comment by corehack** [comment]
Have you tried https://sfconservancy.org/ umbrella btw ? I had impression that they not only provide umbrella like financial stuff, but they also consult for free on how to run your project and give legal advice

**Comment by stevepiercy** [comment]
Yes, it is one of about a dozen entities under consideration.

**Comment by corehack** [comment]
Regarding
> That does not mean the existing contributor agreement is broken or needs fixing

I can just give you an example.
https://groups.google.com/forum/#!msg/sqlalchemy-devel/Meqew810H4w/YPiE3CrGObEJ

> OK just scratch the whole pylons agreement, as copyright assignment is a non-starter in any case.(Mike Bayer, author of SQLAlchemy)

So people may not, and will not like it. And you may never know, because instead of complaining they will just keep a private fork of the software.

**Comment by bertjwregeer** [comment]
As mentioned 17 days ago by @mmerickel this belongs on the mailing list: https://github.com/Pylons/pyramid/issues/3015#issuecomment-297796291
