### ISSUE TITLE
add pyramid_ipython to the cookiecutters

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#3028]
Maybe this is controversial but I think it'd be worthwhile to add `pyramid_ipython` to the cookiecutters so that pshell is fancier by default. People can remove it if they want. It's useful to me and I think it's probably not very discoverable right now so enabling it by default would be good.

**Comment by bertjwregeer** [comment]
IPython 6.0 only runs on Python 3.x

**Comment by mmerickel** [comment]
IPython uses `python_requires` on releases and so current versions of pip will autonegotiate the right version for 2.x vs 3.x.

**Comment by mmerickel** [comment]
Anyway if there's no interest we won't do it. No big deal. We should close this if we get through the Pycon sprints without anyone wanting to do it.

**Comment by mmerickel** [comment]
Closing from lack of interest.
