### ISSUE TITLE
Provided cookie session/auth implementations don't support OWASP "Absolute Timeout" best practice

### ISSUE THREAD

**Issue by corehack** [Pylons/pyramid#3032]
Pyramid provides cookie implementations, that do not separate session timers from the cookie timers. The end result is that every time we renew cookie, we essentially update session also. This makes impossible to configure (login) session timeout features, such as https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Absolute_Timeout

Of course developer can implement his own session factory, but I think framework-provided implementation should also support best security practices by default. I am not sure, is "security by default" a policy of Pyramid ?

Note: the described flaw also maybe present in the `AuthTktAuthenticationPolicy`, since they apparently share the cookie logics. In Pyramid session and authentication are separate, but in OWASP session means both things together.

**Comment by corehack** [comment]
Since OWASP session mean different thing, I think its more correct to say the issue is about authentication policies, rather than session factories. OWASP don't require "pyramid sessions" to have timeout, but rather "pyramid logins".

**Comment by mmerickel** [comment]
Both session and authentication policies implement absolute timeouts by using signed cookies with an embedded timestamp, if you choose to set it. See the timeout option versus the max_age option of the policy.

As far as coordinating the session with your backend to support deletion, this is the point of the `unauthenticated_userid` versus `authenticated_userid` and should be clear in the docs that you are intended to override the latter to verify that the authentication token is actually valid.

It is true that Pyramid does not assist you in invalidating sessions around privilege escalation boundaries and that it is up to the user to do this. You should invoke `request.session.invalidate()` when performing remember/forget operations.

**Comment by corehack** [comment]
`timeout` option affects idle (inactivity) timeout, not "absolute timeout". If you check the code, it actually compares timeout with "renewed time" of the cookie. Its even mentioned in some of the docs

**Comment by mmerickel** [comment]
If you set `reissue_time` to `None` or greater than `timeout` then `timeout` is an "absolute timeout" as the cookie will never be renewed.

**Comment by corehack** [comment]
That is not true. Properly implemented "Absolute timeout" would work all the time. Your proposed solution would only work if you don't touch session at all, cause once you put something there, the cookie will be reissued even with "reissue time" disabled.

**Comment by corehack** [comment]
Also, disabling "reissue" is not a good idea. Note that "Idle timeout" is also a feature recommended by OWASP. The fact is, these are 2 features, both important - even if it's both possible to implement simply by configuration (which is not true), the fact that they are incompatible with each other would be bad.

**Comment by mmerickel** [comment]
This conversation belongs on the mailing list, not here. Setting `0 > reissue_time < timeout < ∞` effectively satisfies both the idle timeout and renewal timeout clauses of OWASP and you'll note that absolute and renewal timeouts are not both required. If you have an issue with this you need to convince more people before I will jump on board. Especially without any code.

**Comment by corehack** [comment]
I don't know what "OWASP renewal timeout" you are talking. I was talking about "Absolute timeout".
Your proposed setting would not implement proper "Absolute timeout": when you have reissue, the cookie timer is reset, thus it's impossible to enforce the session timer cause there's no session timer at all.
I have no problem with implementing my own security policy, and also "security by default" is not a requirement. If it's an "opinion" and Pyramid is non-opinionated for me it's also perfectly acceptable. Just would be nice to add a note in the docs that provided implementations are just examples and do not provide the best security by default.

**Comment by mmerickel** [comment]
Renewal timeout is literally the next section in the document you linked. Note the first word is "alternatively" with respect to absolute timeout. Again, I encourage you to engage more people in the conversation than the relatively fewer that will read the issue tracker. I will absolutely not put a note in the docs saying that it does not provide the best security by default until this is proven... not from one person's reading of the OWASP recommendations. This code has been in use for over a decade (counting its inception in the paste library) and has been vetted many times over to satisfy the requirements of many users.

**Comment by corehack** [comment]
Sorry I will try to use the mailing list

**Comment by corehack** [comment]
Btw, renewal policy is not possible to implement using settings described above. I'm not even sure its possible to implement without backend at all, because you have to track 2 session ids and invalidate the old one (not possible without backend) when user starts to use the new one.
