### ISSUE TITLE
Specify cwd at shell prompt in Quick Tutorial

### ISSUE THREAD

**Issue by okc0mputer** [Pylons/pyramid#3033]
I'm probably newer to Python web development than most, but I have suggestion for the readability of the Quick Tutorial.  I found the directory structure to be slightly ambiguous, and was a little unsure if I was placing files in the proper directories.  Perhaps using a more explicit directory in the tutorial would be more helpful to beginners such as myself would make things slightly easier, for example:
Change references such as 
`$ cd ..; mkdir package; cd package`
to something like
`hello_world $ cd ..; mkdir package; cd package`

While this may not be a major issue, it becomes confusing once getting further into the tutorial where more of the directory structure changes.  Once the tutorial reaches a point where the directories aren't being created and deleted with every step it's not so important, but in the beginning it would surely clarify exactly where to place new files/directories as well as which ones to remove or change.

**Comment by mmerickel** [comment]
Good suggestion. Maybe even add a `tree` output every time the structure changes to show what the whole thing should look like.

**Comment by stevepiercy** [comment]
Although we never plan to rearrange the steps of the Quick Tutorial, if someone were crazy enough to do so, then this would add a maintenance burden. When Paul and I moved it from the Community Cookbook to official docs, we went through just that, checking the current step as well as the preceding and subsequent steps to maintain continuity and consistency.

I'm a -0 for both suggestions.

**Comment by okc0mputer** [comment]
I can see your point, however I just finished part 4 wondering for each step if i'm placing my files in their intended directories, mostly due to the copying of directories and changing the content of the files within them.  Pyramid has a higher level of entry than just about all frameworks in any language, and clarifying the documentation can change that.  Regardless of the quality of the project code,  there is no reason for documentation not to be even better.  I believe "explicit is better than implicit" should apply to all aspects of a python project.

**Comment by stevepiercy** [comment]
There's always a trade-off. For example, if someone were to be so kind as to create the pull request and shoulder the maintenance burden and become a contributor, then, well, who am I to argue against it?

**Comment by okc0mputer** [comment]
A few more days with pyramid I will gladly take responsibility for making the docs a little more beginner-friendly and possibly more concise, starting with the Quick Tutorial.  I was under the assumption there was someone dedicated to keeping up the documentation, making changes, and adding to them.  If that is not the case then my apologies for expecting these changes to be made by developers dedicating their time just to keep the project alive and current.

**Comment by stevepiercy** [comment]
As with most open source projects, anyone can contribute to Pyramid, and any other Pylons Project project, whether with code, tests, or documentation. No one person owns the duty, although there are *core* contributors—those who hold a keen and enduring interest—who review suggestions and contributions and provide guidance.

Hopefully our [contributing guidelines](https://github.com/Pylons/pyramid/blob/master/contributing.md) explain how to contribute. If not, just ask.

**Comment by mmerickel** [comment]
@stevepiercy can we close this?
