### ISSUE TITLE
"ImportError: No module named 'hupper'" - with pserve --reload

### ISSUE THREAD

**Issue by keipaglows** [Pylons/pyramid#3043]
Yesterday I was trying to upgrade pyramid to the last version (1.8.3) on one project. However, when I run usual "pserve --reload" I got this message:

    Starting monitor for PID 16676.
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    ImportError: No module named 'hupper'
    Server with PID 16676 exited with code 1.
    Waiting for changes before reloading.

And I get 502 when I try to access app locally, so it doesn't work, despite being in a "run state", I guess.

If I drop --reload key it works just fine, so something goes wrong with hupper module. Unfortunately, I wasn't able to fix this problem for me, and I was forced to downgrade to 1.7, which doesn't use hupper for reloading needs.

**Comment by frispete** [comment]
hupper is a new package, that is used, when you invoke pserve with --reload.

**Comment by keipaglows** [comment]
Yes, it is used. Problem is that something doesn't work. I have hupper installed in the project environment.

**Comment by stevepiercy** [comment]
The import error indicates you do not have hupper installed for your project where you think it is. If possible, I suggest blowing away the virtual environment and reinstalling your project via `pip install -e .`. Make notes of steps to reproduce the issue if it recurs so we can assist further, including OS.

**Comment by keipaglows** [comment]
We use python buildout in order to to get all needed packages. I double checked that hupper was in the eggs folder.

I was tinkering around, and turns out, hupper 0.5.0 was released a few days ago. I've tried the version before (0.4.4), and application starts as usual now. --reload also works. Can you check if --reload works with hupper 0.5.0? If it doesn't, do I need to create a new issue redarding hupper 0.5.0, or just edit this one?

**Comment by tseaver** [comment]
I can't reproduce with a virtualenv:

```bash
$ /opt/Python-3.6.0/bin/virtualenv /tmp/py36-pyramid
Using base prefix '/opt/Python-3.6.0'
New python executable in /tmp/py36-pyramid/bin/python3.6
Also creating executable in /tmp/py36-pyramid/bin/python
Installing setuptools, pip, wheel...done.
$ cd /tmp/py36-pyramid/
$ bin/pip install pyramid
Collecting pyramid
  Using cached pyramid-1.8.3-py2.py3-none-any.whl
Collecting PasteDeploy>=1.5.0 (from pyramid)
  Using cached PasteDeploy-1.5.2-py2.py3-none-any.whl
Collecting hupper (from pyramid)
  Downloading hupper-0.5-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./lib/python3.6/site-packages (from pyramid)
Collecting zope.interface>=3.8.0 (from pyramid)
  Using cached zope.interface-4.4.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting repoze.lru>=0.4 (from pyramid)
Collecting zope.deprecation>=3.5.0 (from pyramid)
  Using cached zope.deprecation-4.2.0-py2.py3-none-any.whl
Collecting WebOb>=1.7.0rc2 (from pyramid)
  Using cached WebOb-1.7.2-py2.py3-none-any.whl
Collecting translationstring>=0.4 (from pyramid)
  Using cached translationstring-1.3-py2.py3-none-any.whl
Collecting venusian>=1.0a3 (from pyramid)
  Downloading venusian-1.1.0-py2.py3-none-any.whl
Requirement already satisfied: appdirs>=1.4.0 in ./lib/python3.6/site-packages (from setuptools->pyramid)
Requirement already satisfied: six>=1.6.0 in ./lib/python3.6/site-packages (from setuptools->pyramid)
Requirement already satisfied: packaging>=16.8 in ./lib/python3.6/site-packages (from setuptools->pyramid)
Requirement already satisfied: pyparsing in ./lib/python3.6/site-packages (from packaging>=16.8->setuptools->pyramid)
Installing collected packages: PasteDeploy, hupper, zope.interface, repoze.lru, zope.deprecation, WebOb, translationstring, venusian, pyramid
Successfully installed PasteDeploy-1.5.2 WebOb-1.7.2 hupper-0.5 pyramid-1.8.3 repoze.lru-0.6 translationstring-1.3 venusian-1.1.0 zope.deprecation-4.2.0 zope.interface-4.4.1
$ bin/python
Python 3.6.0 (default, Dec 28 2016, 01:07:21) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hupper
>>> print(hupper.__path__)
['/tmp/py36-pyramid/lib/python3.6/site-packages/hupper']
```

Maybe something weird about your `buildout.cfg` flie?  Is the egg included in the generated `pserve` script's path?

**Comment by mmerickel** [comment]
Interesting error. It's failing to import hupper in the worker but it did load it into the master process. This indicates a `sys.path` issue inside the worker. I think I may need to take steps to copy the current `sys.path` down into the worker as it's something buildout is setting directly in the parent process and not as a `PYTHONPATH` env var.

**Comment by mmerickel** [comment]
@keipaglows can you confirm that Pylons/hupper#27 works for you?

**Comment by keipaglows** [comment]
@mmerickel I've tried to manually add changes from Pylons/hupper#27 into hupper egg. However, it doesn't fix the issue for me.

I tried to debug a little, and it appears that "prepare" method doesn't get called, as well as "spawn_main" method, in which former method is used.

**Comment by mmerickel** [comment]
Oh because the path isn't set until after python tries to import hupper. Crap. This makes the change more complex. I'm open to suggestions but I will need to think on this some more.

**Comment by keipaglows** [comment]
No problem! Unfortunately I don't have any suggestions on the possible fix. Seems like it takes a much closer look, or good knowledge of module internals, or probably even both, to come up with a fix.

**Comment by mmerickel** [comment]
Well fundamentally the issue is that buildout does not properly prepare subprocesses to use the same python path as their parent. It only enhances the original process's `sys.path` but this is not inherited.

I could take `sys.path` and set it as the `PYTHONPATH` of the subprocess, or more simply just add hupper to the `PYTHONPATH` since the rest of the path is passed down via my fix in Pylons/hupper#27 already. I would certainly like to avoid messing with the `PYTHONPATH` in a cross-platform way but there may not be a choice here.

**Comment by mmerickel** [comment]
@keipaglows I pushed an update that I think will work. Wanna give it another shot? Thanks!

**Comment by keipaglows** [comment]
@mmerickel Everything is fine and dandy now, works like a charm. Thanks for fixing this!

**Comment by mmerickel** [comment]
Great to hear! I will cut a new release later today.
