### ISSUE TITLE
Quick tour of pyramid windows installation instructions

### ISSUE THREAD

**Issue by rustybox** [Pylons/pyramid#3044]
It seems unlikely that python would live at c:\env\Scripts\python this will probably confuse someone.

https://github.com/Pylons/pyramid/blob/master/docs/quick_tour.rst

```
c:\> set VENV=c:\env
# create the virtual environment
c:\> %VENV%\Scripts\python -m venv %VENV%
```

**Comment by stevepiercy** [comment]
Thank you!
