### ISSUE TITLE
add plaster_pastedeploy to the cookiecutters

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#3048]
The cookiecutters should be updated to depend on `plaster_pastedeploy` explicitly as the config file format they require, just as new apps should in the future be explicit about the format they need. There is no compatibility issue here... if `plaster_pastedeploy` is installed on old apps using pyramid < 1.9 things will work fine.

**Comment by stevepiercy** [comment]
There are a lot of docs that also need to be updated. A quick search with a regex `literalinclude.*setup.py` returns 21 matches in 16 files in the `docs/` directory.

**Comment by stevepiercy** [comment]
@goodwillcoding thanks for the updates. It would be great if you would update the Pyramid docs along with the 3 Pyramid-specific cookiecutters (I don't think there is any documentation of the Substance-D cookiecutter). Specifically, the source files referenced in the tutorials and narrative docs, and any .rst files that refer to those sources files, would need to be updated. Two searches of the `docs/` directory should locate all the files:

1. 
```
requires = [
    'pyramid',
```
2. regex of `literalinclude.*setup.py`.

**Comment by stevepiercy** [comment]
Here's my plan:

- [ ] Merge the 4 open PRs, one for each cookiecutter.
- [ ] Backport the PRs from `master` to each of the other three branches, `latest`, `1.9-branch`, and `1.8-branch`.
- [ ] Complete tasks for #3059.
- [ ] Update Pyramid docs one time only for both Pyramid issues #3048 and #3059, on Pyramid's `master` branch
- [ ] Backport/cherrypick relevant commits in docs from `master` to `1.8-branch`.

@mmerickel does that sound about right?

**Comment by mmerickel** [comment]
Just focus on the master branches.

**Comment by mmerickel** [comment]
Fixed in #3082 and related cookiecutter issues.
