### ISSUE TITLE
Why is BasicAuthenticationPolicy not included?

### ISSUE THREAD

**Issue by vog** [Pylons/pyramid#3049]
Why does Pyramid provide no native support for HTTP Basic Auth?

It seems that there is already a quite mature `BasicAuthenticationPolicy` provided in the documentation, which is at least 5 years old (perhaps older):

* http://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/auth/basic.html

However, why is that code maintained in the docs? What is the benefit of not including it directly?

The huge drawback of maintaining code in the docs is that every applications will have a separate copy of it,  so bugfixes and security fixes to that code will not make it directly into these applications.

Is this on purpose? If so, why? If not, what are the necessary steps to improve this situations.

**Comment by mmerickel** [comment]
We do have the `BasicAuthAuthenticationPolicy` inside `Pyramid`. If you're interested you could submit a PR to update the cookbook entry to point to this one as the better option, or even better would be to update the entry to use the new policy. I've opened #3050 to talk about this.

http://docs.pylonsproject.org/projects/pyramid/en/1.8-branch/api/authentication.html#pyramid.authentication.BasicAuthAuthenticationPolicy
