### ISSUE TITLE
Update the HTTP Basic cookbook documentation to show how to use the pyramid.authentication.BasicAuthAuthenticationPolicy.

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#3050]
http://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/auth/basic.html

http://docs.pylonsproject.org/projects/pyramid/en/1.8-branch/api/authentication.html#pyramid.authentication.BasicAuthAuthenticationPolicy

replaces: #3049

**Comment by fangpenlin** [comment]
handling this

**Comment by fangpenlin** [comment]
Created a PR here https://github.com/Pylons/pyramid_cookbook/pull/181
