### ISSUE TITLE
Add a cookbook example of using aiopyramid with an asyncio server.

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#3051]
https://github.com/housleyjk/aiopyramid looks like a pretty exciting and simple addon for Pyramid which supports some features such as views operating as coroutines. This requires running with a compatible server and marking certain features as `@aiopyramid.synchronize` in order to execute them in a threadpool while awaiting on the future.

I think it would be great if we had some blog posts of cookbook entry which showed how to build a server and discussed various tradeoffs. This would help a lot of people understand what's going on and how we may further work toward supporting async in Pyramid.

**Comment by ergo** [comment]
OOB support or via extension would be a killer feature for pyramid.
