### ISSUE TITLE
Improve forbidden_view for BasicAuthAuthenticationPolicy

### ISSUE THREAD

**Issue by vog** [Pylons/pyramid#3066]
The recommended `forbidden_view` of `BasicAuthAuthenticationPolicy` is slightly flawed:

* http://docs.pylonsproject.org/projects/pyramid/en/latest/api/authentication.html#pyramid.authentication.BasicAuthAuthenticationPolicy

The manual currently recommends:

```python
from pyramid.httpexceptions import HTTPUnauthorized
from pyramid.security import forget
from pyramid.view import forbidden_view_config

@forbidden_view_config()
def basic_challenge(request):
    response = HTTPUnauthorized()
    response.headers.update(forget(request))
    return response
```

This implementation has the huge drawback that it does not distinguish between authentication issues (nonexisting user, wrong password) and authorization issues (missing permissions). In particular, if a user is successfully logged in via HTTP Auth and clicks on a forbidden resource, the user will be asked to re-login again and again. That doesn't make any sense because the user can login as often as they want - nothing will ever change as the resource is forbidden to the user.

It makes more sense to ask for login (401) only on authentication failure (nonexisting user, wrong password), while an authorization failure (missing permissions) should lead to a plain classic "forbidden" page (403).

I propose the following `forbidden_view` instead:

```python
from pyramid.httpexceptions import HTTPForbidden, HTTPUnauthorized
from pyramid.security import forget
from pyramid.view import forbidden_view_config

@forbidden_view_config()
def forbidden_view(request):
    if request.authenticated_userid is None:
        response = HTTPUnauthorized()
        response.headers.update(forget(request))
        return response
    return HTTPForbidden()
```

Some more ideas:

* The cookbook should mention this forbidden_view as well: https://pyramid-cookbook.readthedocs.io/en/latest/auth/basic.html
* Since this view is a bit more involved, doesn't it make sense to provide that as a helper function by the framework, instead of having it just as example code in the docs?
  * Perhaps that helper could be automatically installed when BasicAuthAuthenticationPolicy in set in the config?

**Comment by mmerickel** [comment]
I'd be very happy if you wanted to add this example to the cookbook as well as the `BasicAuthAuthenticationPolicy` docs. However, adding a mechanism to automatically register this view is a -1 from me... the example is dead simple but most apps want to customize these error views in some way and are unlikely to use this default implementation so the effort to register it automatically would not be worthwhile.

**Comment by vog** [comment]
Would it make sense to split the concept of the `forbidden_view` into two separate concepts, such as `forbidden_view` and `unauthorized_view`? It doesn't look "sane" to me that one view is forced to handle two entirely separate topics.

**Comment by mmerickel** [comment]
It might be more sane but it'd also be a bw-incompatibility that I'm not really interested in considering at this time without seeing a more detailed proposal. I'd be happy to evaluate a PR that did all of the necessary work to make that happen, but otherwise it doesn't sound very interesting / worthwhile.

Again if you want to submit improvements to the docs they would be greatly appreciated to help future users.

**Comment by piotr-dobrogost** [comment]
> It doesn't look "sane" to me that one view is forced to handle two entirely separate topics.

Just wanted to say I totally agree. It would be awesome if Pyramid reflected its otherwise clear separation of authorization and authentication in the area of handling authorization and authentication errors.

**Comment by mmerickel** [comment]
In a very pedantic sense there are only ever authorization errors and it's up to the policy why it refused to authorize a request to perform an operation. Pyramid itself will never raise an error because the user is not authenticated or has no principals... only when the authorization policy decides it can't do anything with that information.

**Comment by vog** [comment]
I created a pull request for the docs regarding the improved `forbidden_view`:

* #3079 Fix forbidden_view for BasicAuthAuthenticationPolicy

I also created some related pull requests for the cookbook:

* https://github.com/Pylons/pyramid_cookbook/pull/183 Add link to BasicAuthAuthenticationPolicy manual 
* https://github.com/Pylons/pyramid_cookbook/pull/185 Fix parameters of BasicAuthenticationPolicy check function
* https://github.com/Pylons/pyramid_cookbook/pull/186 Fix typo in BasicAuthAuthenticationPolicy class name

**Comment by vog** [comment]
>>> It doesn't look "sane" to me that one view is forced to handle two entirely separate topics.
>>
>> Just wanted to say I totally agree. It would be awesome if Pyramid reflected its otherwise clear separation of authorization and authentication in the area of handling authorization and authentication errors.
>
> It might be more sane but it'd also be a bw-incompatibility that I'm not really interested in considering at this time without seeing a more detailed proposal. I'd be happy to evaluate a PR that did all of the necessary work to make that happen, but otherwise it doesn't sound very interesting / worthwhile.

Please find my rough proposal (no tests, etc.) in the following pull request:

* #3080 Proposal for optional split between HTTPForbidden and HTTPUnauthorized

Reasoning behind this design:

* The Pyramid framework does not have separate exceptions for auth failure and HTTP results. The HTTPForbidden exception is used for both purposes. This design does have its merits (simplicity), but also reduces our solution space.
* This means that we can't simply introduce a new internal exception for authentication failure. Instead we must use one of the `HTTP...` exceptions.
* The obvious choice for authentication failure is the HTTP exception corresponding to 401, i.e. `HTTPUnauthorized`.
** (This means that authentication errors lead to `HTTPUnauthorized` and authorization errors lead to HTTPForbidden. This sounds a bit strange, but that terminology issue exists purely in the HTTP standard, independently from the Pyramid framework, so let's stick with it.)
* For backwards compatibility, and since most applications don't want to distinguish between HTTPForbidden and HTTPUnauthorized, this split must be optional and disabled by default.
* Given we are using this split primarily for the `BasicAuthAuthenticationPolicy`, the `AuthenticationPolicy` is the natural place to decide whether this split occurs or not. So the AuthenticationPolicy gets a new property `use_http_unauthorized_exception`, which is optional for backwards compatibility.
* The `HTTPUnauthorized` response can already be customized through `@exception_view_config(HTTPUnauthorized)`, no need to introduce a new decorator like `@unauthorized_view_config`.

Additional ideas which I rejected for this design:

* One could perform `response.headers.update(forget(request))` automatically instead of mentioning this only in the recipe. I'm not sure whether this should be done by the framework or not.
* One could make the `use_http_unauthorized_exception` property mandatory and add it to `IAuthorizationPolicy` and consequently all other AuthorizationPolicy classes. That would make it more explicit, and simplify the `getattr()` call to a trivial property access. However, that would be backwards incompatible to custom AuthorizationPolicy classes in existing applications.
* One could add an `add_unauthorized_view()` method and an `@unauthorized_view_config` decorator in the same way as for `forbidden_view`. However, this might cause confusion to new users, because most authentication policies will not set `use_http_unauthorized_exception` to `True`, and hence those views will practically never be called. Also, `@exception_view_config(HTTPUnauthorized)` is reasonably short, so we don't need a shortcut for that.
* One could provide `use_http_unauthorized_exception` as optional constructor argument to all AuthenticationPolicy classes, so it can be easily enabled by anyone who wants that separation. Of course, this should only be used by applications which want to implement their custom `@exception_view_config(HTTPUnauthorized)`, and they should not forget to enforce a different HTTP return code (403 instead of 401) in that view. Note that I didn't reject this idea because I think it is bad, but because I don't have a use case for that, so this should be discussed and implemented later on.

**Comment by vog** [comment]
Too bad #3080 was not accepted, but thanks for evaluating my PR anyway! At least I provided some starting point for discussion. I guess it's up to somebody else to address the issues with a different approach.

**Comment by bertjwregeer** [comment]
There are always trade-offs with how systems work. The fact that currently an authorization raises an `HTTPForbidden` is a shame, but the HTTP standard (other than for basic authentication) doesn't really define a better HTTP error code when not using Basic Auth (or a challenge the browser natively understands).

We understand that the little extra code you have to write to capture a `HTTPForbidden` to check and see if it is due to a user not being authenticated or not having permission, however even that can be made into a separate view configuration using `effective_principals` so that you don't have an explicit if statement to verify whether the user is authenticated or not.

```
# Fallback for all other HTTPForbidden's that are raised and there is no authenticated user, thus they need to authenticate
@view_config(
    context=HTTPForbidden,
    exception_only=True,
    )
def retunauthorized(context, request):
    response = HTTPUnauthorized()
    response.headers.update(forget(request))
    return response

# User is authenticated, but they are actually forbidden due to authz
@view_config(
    context=HTTPForbidden,
    exception_only=True,
    effective_principals=pyramid.security.Authenticated
)
def retforbidden(context, request):
    return context
```

This may also work (but not recommended, `not_` just feels wrong):

```
# If the user is not authenticated, present them with authentication request
@view_config(
    context=HTTPForbidden,
    exception_only=True,
    effective_principal=pyramid.config.not_(pyramid.security.Authenticated)
    )
def retunauthorized(context, request):
    response = HTTPUnauthorized()
    response.headers.update(forget(request))
    return response
```

Then you won't even need the secondary `@view_config`. Although I personally recommend against using `not_`.

**Comment by piotr-dobrogost** [comment]
@bertjwregeer 
Thanks for presenting available options to handle this nicely.
