### ISSUE TITLE
Use context manager for Configurator in code and narrative references

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3069]
RE: https://github.com/Pylons/pyramid/commit/134ef7e8d17842e286528aeb8d2936579ed81053#diff-88b99bb28683bd5b7e3a204826ead112R34

For Pyramid 1.9 release:

* Search the docs for instances of `config = Configurator()` in both tutorial source files and narrative documentation.
* Do a replacement where it makes sense to do so. Skip one-line examples.
* Update narrative documentation that references updated code.

**Comment by stevepiercy** [comment]
Would it be a good idea to apply a context manager in the cookiecutters and tutorials that use them as well?

**Comment by mmerickel** [comment]
@stevepiercy can we close this?

**Comment by stevepiercy** [comment]
@mmerickel yes, it's complete. I kept it open to discuss the question above. Would like your thoughts.

**Comment by mmerickel** [comment]
I'm not opposed to updating the cookiecutters.

**Comment by stevepiercy** [comment]
Seems like a "best practice" to me, and I learned something new while reading its history. Issues created.
