### ISSUE TITLE
Need clarity about True/False vs. ACLAllowed/ACLDenied in custom AuthorizationPolicy

### ISSUE THREAD

**Issue by vog** [Pylons/pyramid#3078]
This is a request for clarification in the documentation:

The documentation about [Creating Your Own Authorization Policy](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#creating-your-own-authorization-policy) states that `permits(...)` shall return `True` or `False`. However, the [ACLAuthorizationPolicy documentation](http://docs.pylonsproject.org/projects/pyramid/en/latest/api/authorization.html) states that it returns instead instances of `ACLAllowed` or `ACLDenied`, which are only compatible to `True` or `False`, but not the same.

Roughly speaking, the only implementation of `IAuthorizationPolicy` violates that interface, which is confusing.

So what is a custom AuthorizationPolicy supposed to do? Should it return instances of `ACLAllowed`/`ACLDenied`, or should it return plain booleans (`True`/`False`)?

Another question: If the framework only evaluates the boolean value of `ACLAllowed`/`ACLDenied`, what are the additional fields in those objects good for? Where are these used or shown?

**Comment by mmerickel** [comment]
The interface requires truthy/falsey return types. It could do better to explain this and it is not very consistent with `request.has_permission` documentation which states a `pyramid.security.PermitsResult` object which is a subclass of `int` and is more practically implemented as `pyramid.security.Allowed` and `pyramid.security.Denied`.

Practically you can return `Allowed` and `Denied` or the more specific `ACLAllowed` and `ACLDenied` if they work in your policy. They can carry along more information about exactly why things were allowed or denied. The underlying system, however, only cares about how they compare to boolean values. The advantage of adding more information to the values is that they can be used in a forbidden exception view to deduce what happened and explain things to the user if that's a goal of yours.

If you're interested in turning any of this into improvements to the documentation they would be greatly appreciated.

**Comment by mmerickel** [comment]
After re-reading my comment the immediate action items would be:

1) Fix `request.has_permission` documentation to mention that the expected return type is something that can be truthy/falsey. I'm blanking on a good term for that right now.

2) Fix the `IAuthorizationPolicy` documentation to mention the same thing. It could mention `Allowed` and `Denied` as well as possible return types.
