### ISSUE TITLE
DummyBootstrap doesn't support context manager mode

### ISSUE THREAD

**Issue by corehack** [Pylons/pyramid#3096]
Since #1822 bootstrap can return a context manager, but DummyBootstrap hasn't been converted to support the new mode.

**Comment by mmerickel** [comment]
`pyramid.tests.test_scripts.dummy.DummyBootstrap` is not a public API.

**Comment by corehack** [comment]
Really ? But it could be useful for anyone unit testing new pyramid scripts

**Comment by mmerickel** [comment]
Nothing in `pyramid.tests` is public. You can see public APIs by viewing the API docs at http://docs.pylonsproject.org/projects/pyramid/en/1.8-branch/#api-documentation

`pyramid.testing` is public but does not include a `DummyBootstrap` object and I see no reason why anyone would need that fixture.

**Comment by corehack** [comment]
>I see no reason why anyone would need that fixture.

As I already said, it's useful to test new scripts. For pyramid add-ons, for example. Any script using bootstrap could use a DummyBootstrap fixture. Why is it surprising ?

**Comment by corehack** [comment]
I don't understand why would you make these fixtures public. It's very useful outside of testing Pyramid itself and I see it's just a bunch of generic mocks, nothing restricting it to the Pyramid itself. Perhaps you could reconsider the decision to make this private API later. I see no problem using it and I will not blame you if it breaks, but I can't see why would it break at all: if a fixture is made for pyramid, it will work for any software using pyramid also, because pyramid as a framework has lowest expectations.
