### ISSUE TITLE
How do I add font-awesome to pyramid? 

### ISSUE THREAD

**Issue by jorge90mtz** [Pylons/pyramid#3102]
I tried to use font-awesome to my project. I added the font types to the Manifest.in and I call it like:
`<link href="${request.static_url('project:static/font-awesome/css/font-awesome.min.css')}" rel="stylesheet" type="text/css">`  and in that file the url is as follows:
`url('../fonts/fontawesome-webfont.woff?v=4.2.0') `
but I still get the 404 not found when I run it with **pserve**. What else can I do? Do I add it as a static view, if so, how would I do it? 
I also added the line:
`config.add_static_view('static', 'static', cache_max_age=3600)` to my file.

I would **IMMENSELY** appreciate any pointers or any help with this. Thank you very much to all.

**Comment by mmerickel** [comment]
Is the 404 on the CSS file or the woff request? Does the folder structure have a fonts folder next to the css folder?

**Comment by jorge90mtz** [comment]
Yes, the 404 is on the woff request.
The structure in static is:
----Static
- css
- other stuff
- font-awesome

            -    css
            -    fonts
            -    less
            -    scss

- fonts
- images
- js

**Comment by mmerickel** [comment]
Did you try requesting the woff file directly in the browser or with curl? Common problems with woff files include CORS errors and missing mime type configurations for the file type on your system so you should use your browser console to see if there is an error about CORS and you can use curl directly to see if the mime type is correct.

**Comment by jorge90mtz** [comment]
How can I see if its a CORS error?

**Comment by rustybox** [comment]
It's not going to be a CORS error, you're  not making a cross origin request, the css just references the font file with a relative URL.

The advice about making a direct request for the font file makes a lot of sense though, see what the server responds with when you make an absolute request, if it is served correctly by the web app server it is possible the font file is in the wrong location relative to the css.

**Comment by mmerickel** [comment]
@rustybox is right I was giving more general advice about woff issues there. It could also be a file permission error on the python process being unable to read it.

**Comment by rustybox** [comment]
Presumably app server should 500 in such a case, I can only assume the static route is misconfigured or that the file doesn't exist at the expected path.

**Comment by rustybox** [comment]
Here's a minimal example https://github.com/rustybox/font-awesome-pyramid-demo

I'd pay particular attention to the line

    # server.py

    config.add_static_view(name='static', path='my_cool_package:static')

cloning this repo and running the following will result in some fa glyphs showing at http://localhost:8080/

    pip install -r requirements.txt
    python server.py

**Comment by jorge90mtz** [comment]
Thank you very much! I will try it and let you know
