### ISSUE TITLE
Please tag the 1.9 release on GitHub

### ISSUE THREAD

**Issue by bowlofeggs** [Pylons/pyramid#3114]
Hello!

I am working on [packaging 1.9 for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1465428), and we currently use your git tags to pull the source code for your releases. Could you make a ```1.9``` tag in git that corresponds to the [build found in PyPI](https://pypi.python.org/pypi/pyramid/1.9)? Thanks!

**Comment by mmerickel** [comment]
Is there a reason you rely on the git tag instead of packaging the official sdist we upload to PyPI?

Anyway I pushed the tag just now.

**Comment by bowlofeggs** [comment]
On Sat, 2017-07-01 at 14:09 -0700, Michael Merickel wrote:
> Is there a reason you rely on the git tag instead of packaging the
> official sdist we upload to PyPI?

No particularly strong reason. I'd say it's a preference. The sdist is
made from a developer's laptop, and in some cases (I've not analyzed
Pyramid for this so it may not apply) the PyPI package doesn't contain
the full sources that can be found in source control. For example, I've
seen projects drop the test suite (since users don't need it) or other
files that I find useful as a packager. Due to this, I've formed a
habit of looking for tags in source control since that will always have
the full source tree that I expect.

> Anyway I pushed the tag just now.

Thanks so much!

**Comment by mmerickel** [comment]
Our sdists contain tests and docs but I understand most projects on PyPI are not quite as mature. :-)
