### ISSUE TITLE
URLDecodeError should produce 404 instead of server error in production

### ISSUE THREAD

**Issue by lambacck** [Pylons/pyramid#312]
Either by badly behaved bot or accidental paste by a user, you can generate internal server errors by putting invalid utf8 characters in the url:

2011-09-28 10:48:40,736 http://localhost:6543/sF0%9C%FEF%DC
Traceback (most recent call last):
  File "D:\ciocenv\Lib\site-packages\pyramid_exclog__init__.py", line 31, in exclog_tween
    return handler(request)
  File "D:\ciocenv\Lib\site-packages\pyramid\router.py", line 116, in handle_request
    tdict = traverser(request)
  File "D:\ciocenv\Lib\site-packages\pyramid\traversal.py", line 606, in **call**
    vpath_tuple = traversal_path(vpath)
  File "D:\ciocenv\Lib\site-packages\repoze\lru__init__.py", line 96, in lru_cached
    val = f(*arg)
  File "D:\ciocenv\Lib\site-packages\pyramid\traversal.py", line 482, in traversal_path
    raise URLDecodeError(e.encoding, e.object, e.start, e.end, e.reason)
URLDecodeError: 'utf8' codec can't decode byte 0x9c in position 3: invalid start byte

In production environments this should generate a 404 instead of a 500 internal server error.

**Comment by benhoyt** [comment]
I had to add this exception view too, as some bots or hacker was sending me URLs like `foo.com/%80` (and we have our server send us an error email on every internal server error, as they're usually bugs in our code). A bad request (bad URL in this case) should return 400 Bad Request rather than 500 Internal Server Error almost by definition, right?

**Comment by bertjwregeer** [comment]
It's an uncaught exception, so by definition it is a 500 Internal Server Error.

There is work being done to make it easier to catch these exceptions and make it easier to turn it into a 400 Bad Request for example.

**Comment by benhoyt** [comment]
Well, yes, it's an uncaught exception (and not hard to work around per above), but I guess I'm arguing that it shouldn't be an uncaught exception. It's a bad request (bad character in the URL), and there's already a standard response for that (400 Bad Request), so it seems to me something the web framework should handle by default.

Related question: when would you *not* want a badly-formed URL to return 400 Bad Request?
