### ISSUE TITLE
Object persistence issue

### ISSUE THREAD

**Issue by TWry** [Pylons/pyramid#3137]
See code below. I'd expect that the `add_event` method would automatically persist new events. That is not the case. I have to add a call to transaction.commit in order for this to work. The project has been set up from the cookiecutter template, pyramid version is 1.9.1. Any ideas what's going wrong here, please?
    

    from repoze.folder import Folder
    
    
    class FooRoot(Folder):
        __name__ = None
        __parent__ = None
    
        def add_event(self, **kwargs):
            title = kwargs.get('title')
            event = Event(**kwargs)
            self[title] = event
            return event
    
        
    class Event(Folder):
        def __init__(self, **kwargs):
            super().__init__()
            for key, val in kwargs.items():
                setattr(self, key, val)
    
    
    def appmaker(zodb_root):
        if 'app_root' not in zodb_root:
            app_root = FooRoot()
            zodb_root['app_root'] = app_root
            import transaction
            transaction.commit()
        return zodb_root['app_root']

**Comment by tseaver** [comment]
I haven't used the cookiecutter, but it looks as though its [development.ini](https://github.com/Pylons/pyramid-cookiecutter-zodb/blob/latest/%7B%7Bcookiecutter.repo_name%7D%7D/development.ini#L14-L15) is lacking the [zodb / tm configuration of the older scaffold](https://github.com/Pylons/pyramid/blob/master/pyramid/scaffolds/zodb/development.ini_tmpl#L16-L17).

**Comment by tseaver** [comment]
Never mind, those packages get [pulled in via `config.include`](https://github.com/Pylons/pyramid-cookiecutter-zodb/blob/latest/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/__init__.py#L18-L20).

**Comment by TWry** [comment]
Right, Here's the __init__.py:

    from pyramid.config import Configurator
    from pyramid_zodbconn import get_connection
    from .models import appmaker
    
    
    def root_factory(request):
        conn = get_connection(request)
        return appmaker(conn.root())
    
    
    def main(global_config, **settings):
        """ This function returns a Pyramid WSGI application.
        """
        config = Configurator(root_factory=root_factory, settings=settings)
        settings = config.get_settings()
        settings['tm.manager_hook'] = 'pyramid_tm.explicit_manager'
        config.include('pyramid_chameleon')
        config.include('pyramid_tm')
        config.include('pyramid_retry')
        config.include('pyramid_zodbconn')
        config.add_static_view('static', 'static', cache_max_age=3600)
        config.scan()
        return config.make_wsgi_app()

**Comment by tseaver** [comment]
That configuration looks right:  the`pyramid_tm` tween starts a transaction when the request begins, and commits it when it ends unless the view raises an exception, in which case it aborts the transaction.

Can you show the view code which invokes your `FooRoot.add_event` method?

**Comment by TWry** [comment]
Sure thing: 

    @view_defaults(renderer='json')
    class BaseView:
        def __init__(self, context, request):
            self.context = context
            self.request = request
    
        @view_config(context=FooRoot)
        def events(self):
            '''GET all events'''
            return self.context
    
        @view_config(context=FooRoot, request_method='POST')
        def post_event(self):
            'POST a new event'
            return self.context.add_event(**self.request.json_body)

The object is getting created ok as far as I can see. But it is never persisted. Changing ._p_changed on it or the root does also not help. (Note: Event init code in my first post corrected)

**Comment by mmerickel** [comment]
One thing to note is that the scaffold is not using the threadlocal transaction manager so anytime you `import transaction; transaction.commit()` this is effectively a no-op. You need to grab `request.tm` and use it instead. As far as your `add_event` issue it's still not clear what the issue is but presumably the `self[title] = event` should be enough to persist it if the `FooRoot` itself is being persisted - which is probably not the case. My guess would be that the scaffold has not taken the necessary steps to attach the connection to the appropriate transaction manager - a quick look at pyramid_zodbconn indicates there is no such way to do it easily right now. If you drop the `   settings['tm.manager_hook'] = 'pyramid_tm.explicit_manager'` line from your `main` I expect things to work.

**Comment by TWry** [comment]
I confirm that it's working without the `settings['tm.manager_hook'] = 'pyramid_tm.explicit_manager'` line and without calling `transaction.commit` in the `add_event` method. Thanks for the help!

**Comment by mmerickel** [comment]
Thanks @TWry - we should be able to release an updated version of pyramid_zodbconn that works with the non-threadlocal transaction managers but until then you'll need to use the global one.

I'm moved this issue into https://github.com/Pylons/pyramid_zodbconn/issues/6
