### ISSUE TITLE
Make it possible to set serializer for cookies

### ISSUE THREAD

**Issue by piotr-dobrogost** [Pylons/pyramid#3143]
It would be handy if one could set serializer used to serialize/deserialize cookies being set/read. This could probably be implemented using cookie profiles from WebOb which store such serializer.

**Comment by mmerickel** [comment]
I'm willing to review a patch for this but until that time I don't think it's a goal of the project to add a framework for cookies. You can easily add helper functions to your app to deal with specific cookies/profiles without adding this to Pyramid.

**Comment by piotr-dobrogost** [comment]
I still think that direct support for non-text values of cookies in the framework itself would be valuable addition. The fact that the existing requirement – WebOb – already supports this feature when using CookieProfile class should make the task pretty easy. I'm willing to write a patch and would like to receive some guidelines as to possible API for this feature. I envision there should be a method (of which Pyramid's class?) to register serializer/deserializer (of the form supported by WebOb's CookieProfile) for specific cookie names.
