### ISSUE TITLE
AuthTktAuthenticationPolicy: wild_domain option not working

### ISSUE THREAD

**Issue by toirl** [Pylons/pyramid#3144]
I'm using AuthTktAuthenticationPolicy for cookie-based authentification on a site hosted under "my-app.foo.example.com"

As described in the [documentation](https://docs.pylonsproject.org/projects/pyramid/en/1.5-branch/api/authentication.html) I receive two cookies after authentification on default configuration:

1. my-app.foo.example.com (host-only)
2. .my-app.foo.example.com (wilddomain)

I expect to get only one cookie (host-only) when setting the "wild_domain" option to False. But the wild_domain option has no effect. I always get those two cookies.
I do not use any of the interferring option like "domain" or "parent_domain".

**Comment by mmerickel** [comment]
Actually with `wild_domain` you should see 3 cookies. You can see from the code that by default you should receive 2. One for the current domain and one that is unpinned, allowing the browser to define it.

https://github.com/Pylons/pyramid/blob/e83f2aa50917cf1ed07f8bcfb146a6c1b5759e5b/pyramid/authentication.py#L833-L836
