### ISSUE TITLE
Pyramid CORS doest not serve PUT AND DELETE

### ISSUE THREAD

**Issue by adouani** [Pylons/pyramid#3145]
I have a serious problem with pyramid framework. I add this function to pyramid

```
add_cors_headers_response_callback(event):
    def cors_headers(request, response):
        response.headers.update({
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST,GET,DELETE,PUT,OPTIONS',
        # 'Access-Control-Allow-Methods': 'DELETE, OPTIONS',
        'Access-Control-Allow-Headers': 'Origin, Content-Type, Accept, Authorization',
        'Access-Control-Allow-Credentials': 'true',
        'Access-Control-Max-Age': '1728000',
        })
    event.request.add_response_callback(cors_headers)

from pyramid.events import NewRequest
config.add_subscriber(add_cors_headers_response_callback, NewRequest)

```

```
@view_config(route_name='gm', renderer='json',request_method="GET")
def get(request):
    return dict(hello="GET")


@view_config(route_name='gm', renderer='json',request_method="POST")
def post(request):
    return dict(hello="POST")


@view_config(route_name='gm', renderer='json',request_method="PUT")
def put(request):
    return dict(hello="PUT")


@view_config(route_name='gm', renderer='json',request_method="DELETE")
def delete(request):
    return dict(hello="DELETE")

```
And I can make request to my server using GET, POST methods. The problem is when I use PUT AND DELETE methods the server sends HTTP status 404, but when I curl the route I get the answer (or using POSTMAN).

I use the same Angular http query with Node.JS and it accepts my request. I don't know why pyramid refuse to serve the view

```
import { Injectable } from '@angular/core';
import {Http} from "@angular/http";

import "rxjs/add/operator/map"

@Injectable()
export class AppService {
  baseUrl : string = "http://10.0.0.34:8880"
  constructor(public http:Http) { }

  getData(url) {
    console.log('hi');
    let full_url= this.baseUrl + url;
    return this.http.get(full_url)
      .map(response => response.json());
  }
  postData(url) {
    console.log('hello');
    let full_url= this.baseUrl + url;
    return this.http.post(full_url,null)
      .map(response => response.json());
  }
  putData(url) {
    console.log('hello');
    let full_url= this.baseUrl + url;
    return this.http.put(full_url,null)
      .map(response => response.json());
  }
  deleteData(url) {
    console.log('hello');
    let full_url= this.baseUrl + url;
    return this.http.delete(full_url)
      .map(response => response.json());
  }

}
```

**Comment by bertjwregeer** [comment]
There is not enough information here to understand or replicate the issue you are having. CORS only comes into play when the request is cross origin, if the JavaScript application is served from the same domain then CORS doesn't even matter.

Nowhere in this code does the server run HTTP 404.

You do not have a OPTIONS handler, so there is no way for the client to do a pre-flight request, is that an issue.

**Comment by adouani** [comment]
The Java server runs on another server so, it's CORS app.
What information do you need to understand the issue?
I post the question in stackoverflow too, and I put pictures to clarify the problem. 
Cordially

**Comment by adouani** [comment]
It's solved thanks! The problem is there is no view that handle OPTIONS method so I create a view with this method


@view_config(route_name='gm', renderer='json',request_method="OPTIONS")
def options(context, request):
    request.response.headers.update({
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST,GET,DELETE,PUT,OPTIONS',
        'Access-Control-Allow-Headers': 'Origin, Content-Type, Accept, Authorization',
        'Access-Control-Allow-Credentials': 'true',
        'Access-Control-Max-Age': '1728000',
    })
    return dict()

**Comment by bertjwregeer** [comment]
You could also return an empty dict() from that function and let your NewRequest subscriber take care of things for you.

Glad it's resolved.
