### ISSUE TITLE
pserve --reload needs an option to force polling

### ISSUE THREAD

**Issue by dpopowich** [Pylons/pyramid#3147]
This is slightly different than #2920...

I am part of a team developing a single-page webapp.  Server-side is pyramid, client-side is a javascript app built into a one-file bundle with browserify.

I have a development setup where I'm running my pyramid server in a vagrant vm (virtualbox, ubuntu 16.04), accessing the running application via port-forwarding from host computer to vm. I edit my files on my host.  With pyramid 1.7 running `pserve --reload` worked fine.  

Meanwhile I have watchdog installed in my vm for use with the non-python code: when js files are modified, watchdog (*using polling*) kicks off browserify to rebuild the client-side app. Note how I said using watchdog with polling. There is an issue with virtualbox, inotify, and modifying files from the host computer...inotify in the vm does not recognize the file updates. So I *have* to use polling.

I updated pyramid to 1.9 and now `pserve --reload` no longer works because it detects watchdog and uses it and **there is no way to tell pserve (or, rather, hupper) not to use watchdog if it exists.** Uninstalling watchdog is not an option as I need it elsewhere.

In a nutshell: **I need an option to force polling regardless of the existence of watchdog in the virtualenv.**

Meanwhile, this is my hack script to get around the issue:

```python
#!/usr/bin/env python

import sys
import builtins
from pyramid.scripts.pserve import main

def no_watchdog():
   """We have watchdog installed for client-side watching of file changes
   via polling. Meanwhile, pyramid (since 1.8) will use watchdog, if it is
   installed, for file watching and use inotify which doesn't work
   well when watching within a vm and files are edited on the host.
   We need polling.  HOWEVER, there is no way to force polling from
   the pserve commandline: if it can import watchdog it uses it with
   inotify.  Herein we force the importing of watchdog to raise an
   ImportError which will force the use of polling.
   """
   
   def prevent_watchdog_import(name, *args, **kwargs):
      """Force ImportError when importing watchdog.
      """
      if name.split('.')[0] == 'watchdog':
         raise ImportError
      # call out to real builtin importer
      return real_import(name, *args, **kwargs)
   
   # get handle to __import__ builtin
   real_import = builtins.__import__
   # replace  __import__ with our custom importer
   builtins.__import__ = prevent_watchdog_import

if __name__ == '__main__':
   no_watchdog()
   sys.exit(main())
```

**Comment by mmerickel** [comment]
So it sounds like your virtualenv has watchdog in it even though you don't want to use it? Could you just install it into a different virtualenv?

I've considered things like `HUPPER_DEFAULT_MONITOR=poll` which would kick in if `start_reloader` was not passed an explicit `monitor_factory` [1] but in general I'm not a big fan of environment variables controlling library behavior - however controlling a default doesn't sound too bad.

As far as an explicit option to pserve, I'm probably -1 on that because then I would be inclined to add it to any other CLI that uses hupper which would be much worse than making it controllable from one location (I think).

[1] https://github.com/Pylons/hupper/blob/cd6c27cdb176799995cea65999183e4e1775e23e/src/hupper/reloader.py#L261.

**Comment by dpopowich** [comment]
Regarding watchdog in my virtualenv: yes it needs to be there, but for a different purpose and we use it in polling mode when we do (for the same reason: a disconnect between file modification on the host and inotify within the vm).

Regarding -1 on option to pserve: pserve has an explicit option to turn on file monitoring. Should it not then offer options related to how that works?

Regarding not being a fan of environment variables not controlling library behaviour: it's one of the reasons they exist, no?  And this could be the perfect solution if you don't want to litter ever utility that uses hupper with a command line option. A way to pass user preferences deep into the library. 

IMHO, -1 on hupper's use of magic: "ooh, this exists, I'll use it even if the user doesn't want to and do so in this fixed manner without offering any config options to the user." One size does not fit all.

**Comment by mmerickel** [comment]
> IMHO, -1 on hupper's use of magic: "ooh, this exists, I'll use it even if the user doesn't want to and do so in this fixed manner without offering any config options to the user." One size does not fit all.

https://github.com/pallets/werkzeug/blob/368ccb07d097660156eb19a0ec2042bc53e68238/werkzeug/_reloader.py#L239

I understand your issue, and I'm thinking about it - but just recognize this is a corner case and the world is not on fire. If you want to supply a patch to hupper I'll be happy to review it as well.

**Comment by RobAWilkinson** [comment]
I'm facing the same problem as well, havent yet figured out a solution

**Comment by mmerickel** [comment]
This is being tracked by https://github.com/Pylons/hupper/pull/29.

**Comment by mmerickel** [comment]
hupper 1.2 contains the `HUPPER_DEFAULT_MONITOR=hupper.polling.PollingFileMonitor` hook which you can use to solve this problem
