### ISSUE TITLE
request: make pyramid.session's CookieSession scoped publicly

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#3148]
the current behavior:

`pyramid.session.BaseCookieSessionFactory` is a def, which defines a privately scoped class `CookieSession(dict)`.  

`type(request.session)` will return `pyramid.session.CookieSession`, however this can not be accessed as a class for comparison due to scoping issues, since CookieSession doesn't exist on the scope.  e.g. this will raise an exception:

   if isinstance(request.session, pyramid.session.CookieSession)

The change I would like to propose, is creating a public `BaseCookieSession` (or similar) class, and having the current CookieSession inherit it.  That would allow for full backwards compatibility.

    +class BaseCookieSession(dict):
    +    "core class for inheritance"
    +    pass

    .def BaseCookieSessionFactory(
    ...
    .    @implementer(ISession)
    -    class CookieSession(dict):
    +    class CookieSession(BaseCookieSession):

**Comment by jvanasco** [comment]
edit: the point of this is to be able to test if a session is an instance of pyramid's base CookieSessions.  Right now one can only test against it being a dict, which (most-likely) all sessions subclass, and 'guess' that you have pyramid session by process-of-elimination against other known session types.

**Comment by bertjwregeer** [comment]
What problem are you trying to solve for? Every session implementation is required to implement a particular interface, ISession, so you should be testing for that, not an individual session implementation.

**Comment by jvanasco** [comment]
Short version:

ISession is great, but doesn't expose information on the Session Implementor or the generating Factory; that type of information is often needed for integrated tests.

Long version:

This is for integrated tests (but eventually, analytics reporting).  We often  use the 'wrapped session factory' technique to dynamically determine the session for a particular request.  For example, a multi-tenant app determines the session factory by active domain - a redis backend on the main domain, encrypted cookies on the whitelabel hosted domains.

I need to know what the active session implementor for a request is -- then I can ensure the correct cookie payloads make it through the stack, and if server side systems are accessed or ignored.  Having the standard ISession interface is great for portability and hot-swapping backends -- but it's a pain for writing detailed tests that can track and recreate edge cases.

Currently I just assume it is a Pyramid cookie session if all other checks fail.  Considering there are 3(soon 2) potential types of cookies, my suggestion above isn't very useful.

**Comment by mmerickel** [comment]
Can't you just annotate the session within your custom factory? I don't really see a reason for us to expose the `CookieSession` class so long as it conforms to the interface. It's not built to be reusable at all and exposing a base class for it is just a straight hack that doesn't belong.

**Comment by jvanasco** [comment]
I can/will handle it like that - thanks.

Generally speaking, it would be really nice to be able to tell what the session provider is though.

**Comment by bertjwregeer** [comment]
Pyramid provides you a way to find out what the session provider is: fetch it from the registry. That your session provider factory is a wrapper that can return one of many different session providers is a detail of your implementation.

You could for instance on the way out annotate the session with another interface, and then use z.i to interrogate the object to find out what it "implements". Or have it annotated in various other ways.
