### ISSUE TITLE
add option to create pyc/pyo files with `--reload` or exclude them from polling (hupper?)

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#3149]
The switch to hupper has created a weird issue for us with unit tests.  I finally figured it out. hupper doesn't create `.pyc` files when used to run the daemon, but will detect changes in them.

so this race condition happens during bugfixing tests:

* `pserve --reload development.ini` will start the server, but not create `.pyc` files
* developer makes a change to a file, hupper catches it, the server reloads.
* `python -munittest integrated_tests` will include some of the same `.py` files as the daemon uses, generating the `.pyc` and/or `.pyo` files
* hupper detects the new/changed `.pyc` file, as an update on the corresponding `.py` file and issues a second reload
* the testsuite then fails, because the upstream server is reloading

if hupper either only polled the `.py` files, or compiled `.pyc` files, running the test wouldn't create a secondary load.

the workaround for now is to run `python -B -munittest integrated_tests`

**Comment by bertjwregeer** [comment]
hupper explicitly polls for changes in either or: https://github.com/Pylons/hupper/blob/5c2f7122a1c1876ec7101687bdea3b69e21e519e/src/hupper/worker.py#L58

Yet bytecode compiling was explicitly disabled in version 0.3:

https://github.com/Pylons/hupper/blob/1c27910bf27a52d1768fdd466e53f5955c649e43/CHANGES.rst#03-2016-11-06

**Comment by mmerickel** [comment]
The pyc hack is solving a real problem on windows where pyc files are not handled the same as on *nix systems. Windows creates new pyc files and does not update/touch their timestamps to match the same as the py file and thus a restart is triggered when the .py changes and then when the server starts a pyc file is generated which triggers another restart. I'm open to suggestions but your comments so far don't indicate to me that you appreciate these corner cases so I can't take them and jump straight to a simple fix. Similarly you can't use *only* polled py or compiled pyc files as that just isn't how things work.

**Comment by jvanasco** [comment]
Those edge cases are definitely something I didn't know about.  I'll keep thinking of potential ways.

**Comment by ztane** [comment]
Actually I saw hupper being in limbo a couple times this week with some `.pyc`s myself on Linux.

**Comment by mmerickel** [comment]
Can you turn that into an actual bug report in hupper?

**Comment by jvanasco** [comment]
looping back onto this, I've noticed another variant that triggers a reload.  I think this behavior is dependent on watchdog (we recently started using it in our stack; it may not have been installed earlier)

* a page is served
* the page's template file is edited (e.g. "foo.mako")
* the page is reloaded to see changes
* hupper catches the compiled `foo.mako.py` in the `data` folder as it is compiled, and issues a restart

detecting this template change is unnecessary because of how the templating libraries handle caches.

**Comment by mmerickel** [comment]
> looping back onto this, I've noticed another variant that triggers a reload. I think this behavior is dependent on watchdog (we recently started using it in our stack; it may not have been installed earlier)

Is this not a problem with polling? If that's the case then presumably it's related to watchdog noticing changes much faster than polling does.

**Comment by elliot-jsq** [comment]
I'm having a similar issue using `pserve` with celery. Whenever a celery task runs, `pserve` informs me that a bunch of pyc files have changed and reboots the server. The contents of the pyc files definitely isn't changing, so it seems inappropriate that pserve is rebooting. I would love an option to disable this behavior.

**Comment by mmerickel** [comment]
this should be fixed by https://github.com/Pylons/hupper/pull/31 which tries to only track source paths
