### ISSUE TITLE
Phrasing in tutorial on views sounds broken

### ISSUE THREAD

**Issue by larsblumberg** [Pylons/pyramid#3150]
On https://github.com/Pylons/pyramid/blob/4acd85dc98fb2a43eae54d2116cc4bf383157269/docs/quick_tutorial/view_classes.rst#L15 it states:

_They may be different ways to look at or work on the same data, or be a REST API that handles multiple operations._

I'm not a native English speaker, but that phrase sounds broken to me. Since I'm not able to guess what the author intends to express, I can't provide a PR.

By the way, Pyramid's tutorial pages are an excellent help to get started.

**Comment by stevepiercy** [comment]
Thanks for the comment. It is grammatically correct, although somewhat awkward. How does this sound instead?

"They may consist of different ways..."

**Comment by larsblumberg** [comment]
Sounds good to me. Addressed in #3153

**Comment by merwok** [comment]
PR was merged, this can be closed!

**Comment by mmerickel** [comment]
Thanks for the reminder!
