### ISSUE TITLE
Should be possible to *remove* variables in pshell

### ISSUE THREAD

**Issue by ztane** [Pylons/pyramid#3166]
This is rather minor, but i.e. if traversal is not used, the `root` and `root_factory` could be gone from the injected env as the list of things after my additions is rather long already. However while a `setup` method within the `[pshell]` section *can* pop these keys, the changes are not reflected in the shell globals. Alternatively, they could be set to `None`, so remove `None`s as they'd hardly useful anyway.

**Comment by mmerickel** [comment]
I'm willing to entertain a PR for this but I don't really see the point.
