### ISSUE TITLE
create first pyramid application

### ISSUE THREAD

**Issue by Rajanani044** [Pylons/pyramid#3167]
Hi,thanks for tutorial!
create first pyramid application, i get following error in commad line
c:>%VENV%/Scripts/python helloworld.py
C:\env/Scripts/python: can't open file 'helloworld.py':[Error 2] No such file or directory
![screenshot_1](https://user-images.githubusercontent.com/31839716/30316451-e8cdd786-97c4-11e7-9954-f7481cfbaa43.png)

**Comment by rustybox** [comment]
your command prompt is currently in the folder
```bash
C:\
```
Is there a script named helloworld.py at that path? __C:\helloworld.py__

If not you need to change to the correct folder first.

e.g. if helloworld.py lived at c:\Users\Foo\helloworld.py

you would do the following

```bash
$ cd C:\Users\Foo\
$ %VENV%/Scripts/python helloworld.py
```

**Comment by Rajanani044** [comment]
Hi, Thanks

Pyramid single file application now run.

Now,i create new project, but there are some confusions in cookiecutter

1.How to install cookiecutter in windows
2.How to get cookiecutter packages

**Comment by stevepiercy** [comment]
In the future, the best channel for requesting support is to use the [pylons-discuss Google Group mailing list](https://groups.google.com/forum/#!forum/pylons-discuss). It has 2895 members with over 6000 topics and a lot of history to search through. New GitHub Issues only reach only 168 members (watchers).

In this case, a simple search on your search engine of choice will give you an immediate answer. Please follow the guidelines for [Using Support Wisely](https://pylonsproject.org/community-support.html). Thank you.
