### ISSUE TITLE
trypyramid.com typo

### ISSUE THREAD

**Issue by gomezhyuuga** [Pylons/pyramid#3176]
In the website https://trypyramid.com/, at the part of *Pyramid Features*:
> [...] curl or a browser to request http://0.0.0.0:8080

Shouldn't the port be `6543` ?

**Comment by russellballestrini** [comment]
Yes, that seems like a mismatch between the example programs and the text.

https://github.com/Pylons/trypyramid.com/blob/master/src/templates/index.ejs#L207

**Comment by stevepiercy** [comment]
Thanks for the report, and you are correct, but you reported this issue in the wrong repo. The correct one is https://github.com/Pylons/trypyramid.com/

I'll take care of it, no need to submit another report.
