### ISSUE TITLE
Remove optional installations from Quick Tutorial

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3181]
At the end of [Requirements](https://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/requirements.html#install-pyramid):

> You can optionally install some of the extra Python packages used in this tutorial.

This section should be removed because it is redundant to the instruction to install one's project via `pip install -e .`

**Comment by cewing** [comment]
Did that PR close this issue?  Can we close it?

**Comment by stevepiercy** [comment]
Was #3275 backported to 1.9-branch and 1.8-branch? If yes, then this can be closed.

**Comment by stevepiercy** [comment]
Closing time! Thank you for the backports!
