### ISSUE TITLE
add_request_method only accepts property descriptor that subclasses property

### ISSUE THREAD

**Issue by tjwudi** [Pylons/pyramid#3202]
https://github.com/Pylons/pyramid/blob/cc6a6ed60260b0391aa38f372b26311d58edf0d6/pyramid/util.py#L70

Looks like we check the type of a property descriptor by `isinstance(callable, property)`. This is not true for property descriptors subclasses from `object` which is pretty common. Maybe we should document this behavior [here](https://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator.add_request_method).

**Comment by mmerickel** [comment]
I think we'd also be open to a better approach to detecting descriptors as well. I was not aware of one at the time that I added this feature to Pyramid but perhaps we could relax the constraint if you or anyone else wanted to dive into it.
