### ISSUE TITLE
NewResponse after exception: event.request.response is not event.response

### ISSUE THREAD

**Issue by tjwudi** [Pylons/pyramid#3207]
When NewResponse event is fired, `event.request.response` is not `event.response`.

Simple test code

```py
from wsgiref.simple_server import make_server
from pyramid.config import Configurator
import pyramid.httpexceptions as exc
from pyramid.events import NewResponse

def hello_404(request):
    raise exc.HTTPNotFound()
    return {}

def handle_event(event):
    print(event.response is event.request.response)
    print(event.response.status_code == event.request.response.status_code)

if __name__ == '__main__':
    config = Configurator()
    config.add_route('404', '/404')
    config.add_view(hello_404, renderer='json', route_name='404')
    config.add_subscriber(handle_event, NewResponse)
    app = config.make_wsgi_app()
    server = make_server('0.0.0.0', 6543, app)
    server.serve_forever()
```

Both of the expressions in `print` statements yield `False`. **event.response turns out the be the correct response object because it has the correct response code.**

```bash
[pyramid-playground] $ python server.py 
False
False
```

Seems to be related to #1633. I'm using pyramid 1.9.

**Comment by bertjwregeer** [comment]
This is correct, the request always has a pristine copy of the response that would be used if you returned from the hello_404. However when you raise, the default exception view handler will return that raised exception, which is itself also a response.

Pyramid does not at any point set `request.response` to match the actual response that is being sent back to a client.

**Comment by tjwudi** [comment]
This is interesting. I can understand the incentives here. Although, things turn out to be confusing when you have both `event.request.response` and `event.response` but they are not the same and can also be somehow misleading. To many people, `request.response` looks like the actual response being returned to the client.

I see somewhere in the codebase we use `original_response` to indicate a `response` object before the exception view. I think that'll be a better name for `request.response`.

At the very least, what do you think about updating the documentation and add more clarification there?

**Comment by bertjwregeer** [comment]
https://docs.pylonsproject.org/projects/pyramid/en/latest/api/request.html#pyramid.request.Request.response

Could be updated, and potentially the documentation for the `NewResponse` event. I'm pretty sure it is documented somewhere that `request.response` does not have to equal the response sent to the client.

**Comment by tjwudi** [comment]
Documenting in `NewResponse` will be a good idea. I'd like to make a branch for that.

**Comment by mmerickel** [comment]
I'd prefer not to litter the documentation with info about `request.response` everywhere. If you wanted to improve the `request.response` documentation that'd be fine but that seems to be your main misunderstanding. The `request.response` object is the response object used when you return a non-response-object from your view. Like its documentation says - it is not a global response object and it is not used on every request.
