### ISSUE TITLE
Security - Session - Support SameSite

### ISSUE THREAD

**Issue by AvnerCohen** [Pylons/pyramid#3211]
For a while now - There is a support SameSite cookie attribute - This should help reduce CSRF concerns:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
See SameSite support:
https://caniuse.com/#search=SameSite

Are there plans to support that in the session module?

**Comment by mmerickel** [comment]
duplicate of #2733
