### ISSUE TITLE
Pyramid documentation links broken

### ISSUE THREAD

**Issue by chrismcmacken** [Pylons/pyramid#3214]
When looking through documentation many of the links seem to return broken pages. For example, on this page https://docs.pylonsproject.org/projects/pyramid/en/latest/ if you click on the Installing Pyramid documentation it links to https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/install.html#installing-chapter. Which doesn't load, it returns an empty page.

**Comment by stevepiercy** [comment]
Please see https://twitter.com/PylonsProject/status/951473982703730691
