### ISSUE TITLE
Allow setting route_prefix with a context manager

### ISSUE THREAD

**Issue by inklesspen** [Pylons/pyramid#3218]
Currently, the only way to set `route_prefix` on the configurator is with `config.include()`. If the `route_prefix` functionality were placed in a common method on the configurator, something like the below example would become possible.

```python
with config.with_route_prefix('/api') as api_config:
  api_config.add_route('enable', '/enable/{service}')
  api_config.add_route('disable', '/disable/{service}')
```

As it is, it's perfectly possible to do the same thing with `config.include()`, but only by defining a separate function for those `add_route` lines, leaving them separated in the code from the specified route_prefix.

**Comment by mmerickel** [comment]
Maybe `with_route_prefix(...)` wouldn't actually return anything to avoid any duplicate configurator instances getting bounded.

```python
with config.with_route_prefix('/api'):
  config.add_route('enable', '/enable/{service}')
  config.add_route('disable', '/disable/{service}')
```

**Comment by mmerickel** [comment]
I don't really like `with config.with...` as far as readability goes but maybe it is the best way? With the execution policy api I did something like `with router.request_context(environ)` [1] which is similar to a pattern used in flask.

https://github.com/Pylons/pyramid/blob/af689040be329909e4075bf323ea0bb826e79a68/pyramid/interfaces.py#L690

So possibly `with config.route_prefix_context(...)` would be a convention there.

**Comment by inklesspen** [comment]
I'm fine with that wording, yeah.

**Comment by mmerickel** [comment]
This will be in 1.10
