### ISSUE TITLE
NoTransaction error when using bootstrap in script

### ISSUE THREAD

**Issue by viraptor** [Pylons/pyramid#3219]
I'm trying to create a console script using bootstrap as explained in https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/commandline.html#writing-a-script

I'm running into an issue with access to the database though. The basic expected use like:
```
with bootstrap(sys.argv[1]) as env:
    dbsession = env['request'].dbsession
    with dbsession.begin_nested() as transaction:
        res = dbsession.execute('''SELECT ...''')
```
Throws a `transaction.interfaces.NoTransaction`. I should probably do something better here, but the documentation doesn't really help me :( Could you add something about the db initialisation in this use case?

**Comment by mmerickel** [comment]
`bootstrap` does not setup everything for you completely identical to a normal request and so, for example, the pyramid_tm tween doesn't run and setup a transaction manager for you. Since you are using the explicit transaction manager via `tm.manager_hook = ...` config setting, you will need to create a manager and begin it here. Using the pyramid-cookiecutter-alchemy pattern, you would want something like this:

```python
with bootstrap(sys.argv[1]) as env:
    with env['request'].tm:
        dbsession = env['request'].dbsession
        dbsession.execute(...)
```

The transaction manager then controls commit/abort for you.

**Comment by russellballestrini** [comment]
Thank you!

I feel like this needs to be documented somewhere, maybe an example script could be added to the sqlalchemy cookie cutter?

**Comment by stevepiercy** [comment]
The cookiecutter is not the best place for such docs. I think better places would be the Pyramid Community Cookbook, a new step in the [SQLAlchemy + URL dispatch wiki tutorial](https://docs.pylonsproject.org/projects/pyramid/en/latest/tutorials/wiki2/index.html), the Pyramid docs [Writing a Script](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/commandline.html#writing-a-script), or [pyramid_sqlalchemy docs](https://pyramid-sqlalchemy.readthedocs.io/en/latest/init.html).

**Comment by kayuse** [comment]
I spent a good amount of productive time on this.

**Comment by mmerickel** [comment]
@kayuse Sorry you lost time on this. The pyramid-cookiecutter-starter has a pattern for using bootstrap in the `initialize_db` script that maybe you missed, or maybe you're not using that structure for your project.
