### ISSUE TITLE
Request.copy() removes Pyramid-added attributes

### ISSUE THREAD

**Issue by rbu** [Pylons/pyramid#3247]
Pyramid's documentation [states that ```Request.copy``` can be used to make a copy of a request](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/webob.html#methods). The method returns a ```pyramid.request.Request```, but that copy is missing essential request attributes such as ```registry```.

Background:
The method is purely ```webob.copy``` which only make a copy of environment and body. Pyramid does not override it to copy attributes it sets itself.

## Expected behavior:
```py
r1 = get_current_request()
r2 = r1.copy()
assert r1.registry is r2.registry
```

## Actual behavior:
Raises ```AttributeError: 'Request' object has no attribute 'registry'``` (from ```r2.registry```)

**Comment by mmerickel** [comment]
I'd be open to extending this to copy the registry but I think I'm -1 on copying lazy request methods/properties from `config.add_request_method` and `request.set_property`. We have no protocol in place to make those actually copies versus just duplicated references which could lead to a world of hurt. It's safer to just not copy them.

**Comment by mmerickel** [comment]
`copy` is documented as a shallow copy except for wsgi.input but man it feels like a bad idea. For example copying `request.tm` to a subrequest is unlikely to be what you want.

**Comment by bertjwregeer** [comment]
What problem are you trying to solve that requires you to `copy()` the request?

**Comment by rbu** [comment]
I needed to change the locale for part of the request processing (rendering a template on another language) without interfering in the current request, like so:

```py
@contextmanager
def change_locale_on_global_request(locale):
    old_request = get_current_request()
    try:
        fake_request = old_request.copy()
        fake_request.reset_locale_to(locale, should_update_locale_cookie=False)
        set_current_request(fake_request)
        yield
    finally:
        set_current_request(old_request)
```

**Comment by mmerickel** [comment]
@rbu In this case do you expect the request to share resources with the original request? If you didn't then you could use:

```
```
