### ISSUE TITLE
Unhandled exception when returning/raising error response if request contains invalid Accept: header

### ISSUE THREAD

**Issue by dairiki** [Pylons/pyramid#3250]
As of WebOb 1.8, `webob.acceptparse.MIMEAccept` throws an exception if fed an invalid value for an Accept: header.  As part of generating an HTTP response from an HTTPException, HTTPException.prepare [constructs a MIMEAccept object](https://github.com/Pylons/pyramid/blob/309e6be0e83b5ed08f954c7dd66c5e8cf959a006/pyramid/httpexceptions.py#L253).  This means that, if a request includes a malformed Accept header, any attempt to convert an `HTTPException` (or subclass thereof) to a response will result in an unhandled exception.

I'm not completely sure whether this should be fixed in pyramid or in WebOb.  WebOb's [changelog](https://docs.pylonsproject.org/projects/webob/en/1.8-branch/whatsnew-1.8.html#backwards-incompatibilities), however, does seem to indicate that `webob.acceptparse.create_accept_header` should be used going forward, rather than constructing a `MIMEAccept` directly.

**Comment by bertjwregeer** [comment]
I've added a test so that we don't regress on this in the future! Thank you!

**Comment by mmerickel** [comment]
This issue was fixed in webob 1.8.1.
