### ISSUE TITLE
New to python, tutorial doesn't work

### ISSUE THREAD

**Issue by datatalking** [Pylons/pyramid#3252]
cookiecutter gh:Pylons/pyramid-cookiecutter-starter
bash: cookiecutter: command not found

is the error when I run your readme.md instructions

Is there supposed to be an assumption of additional code or some kind of fancy something that makes this run?

I installed cookie cutter and no command downloads or create the cookiecutter so how does it work?

**Comment by russellballestrini** [comment]
@datatalking welcome to the community! Could you please link to the document you are referencing so I may try to reproduce or further assist you?

**Comment by datatalking** [comment]
https://github.com/Pylons/pyramid-cookiecutter-starter

**Comment by stevepiercy** [comment]
Closing, wrong repo to report this issue. See https://github.com/Pylons/pyramid-cookiecutter-starter/issues/49

@datatalking please see [Get Support](https://pylonsproject.org/community-support.html).
