### ISSUE TITLE
Exceptions as json

### ISSUE THREAD

**Issue by robinharms** [Pylons/pyramid#3256]
Pyramid already has the convention that objects with the method __json__ can be handled with the json renderer.

It would be nice if all the HTTP exceptions would pass to a json renderer and simply render as json, if they have the same method.

Would this be something the framework team fancied? In that case I'd be up for the work.

**Comment by stevepiercy** [comment]
Does this SO post provide an alternative?
https://stackoverflow.com/a/49847668/2214933

If I understand the proposal correctly, changing the default renderer to json would be a breaking change to all those users who expect `text/html`. I'm a -1 on the suggestion.

**Comment by bertjwregeer** [comment]
Do note that if you want to change the default JSON exception formatter used by any sub-class of HTTPException iff the Accept header includes json, you can pass a function named `json_formatter` to the exception:

```
def exc_formatter(exc, status, body, title, environ):
    return {'status': status, 'exc': 'You dun goofed'}
```

To use:

```
raise HTTPBadRequest(json_formatter=exc_formatter)
```

And if the client has specified `Accept: application/json` they will get a JSON response that is:

```
{'status': '400 Bad Request', 'exc': 'You dun goofed'}
```

**Comment by robinharms** [comment]
Hi, thanks a lot for your responses. I didn't think of the aspect that the HTTPExceptions are responses in themselves, so that would of course not make any sense with the __json__ attr as other non-response objects may use.

I'll go with the suggestions above instead :)
Thanks a lot!
