### ISSUE TITLE
Allow context to be passed along from the permission check to the auth callback (groupfinder) and the effective_principals method

### ISSUE THREAD

**Issue by robinharms** [Pylons/pyramid#3268]
This is an issue regarding permission checks in traversal. It's only a problem in more complex setups where you might have groups stored further down the resource tree, and want to check permissions on something outside of your path.

Here's an example. I know the groupfinder method here doesn't do what's expected, but that's pretty much the way people solve things with traversal and locally assigned roles. For instance SubstanceD does this.

https://gist.github.com/robinharms/226770283995e447b13d2cf250584b15

A lot of folks have invented clever hacks to get around this, like Kotti by @dnouri and others:

https://github.com/Kotti/Kotti/blob/master/kotti/security.py

While using context managers and replace the request.context attribute does solve the problem, it would be much better if that wasn't needed.

Proposal:

* Add context=None as kwarg for AuthenticationPolicy method effective_principals.
* Make sure Reqeust.has_permission passes along the context to the effective_principals method: https://github.com/Pylons/pyramid/blob/5fce6fd72960ed0893b1d77c8db9efd64a5a81ab/pyramid/security.py#L438 (if it was specified)
* Pass along the context (if specified) to the callback (a.k.a 'groupfinder') method. https://github.com/Pylons/pyramid/blob/5fce6fd72960ed0893b1d77c8db9efd64a5a81ab/pyramid/authentication.py#L159

This would greatly help with permission checks, and also remove the need for all clever hacks in more complex permission implementations. (Kotti has solved this, but for instance SubstanceD would have the same problem)

If this would be something you could consider, I'd happily do the work. I think it could be a done in a non-intrusive way that would make all old code work and remove the need for clever hacks.

All the best,
Robin

**Comment by mmerickel** [comment]
I think https://github.com/lrowe/pyramid_localroles solves this very cleanly doesn't it?

**Comment by robinharms** [comment]
Hi,
pyramid_localroles solves the problem of having roles that shouldn't be inherited within the same resource tree. And it does a really good job at that. However, that's not what this problem is about.

If I reimplement the test i wrote and posted on gist with pyramid_localroles the second item would still fail, since it would go all thumbs up on checking permission on something outside of the resource tree. The wrong principals would be fetched, since they're fetched from request.context instead of the context passed to has_permission.

I know this API change shouldn't be taken lightly, but this is something that should have been done in Pyramid 1.5 when we changed the has_permission method to include a context. :/

It is, after all only the option to pass along a keyword that could default to None.

**Comment by mmerickel** [comment]
I need more time to digest what you're trying to say but here's a few comments that are really distracting me.

- You absolutely should not be access `request.context` inside `effective_principals`. This is by design and there is no expectation that `has_permission` would affect `request.context`.

- `request.has_permission` does not ignore the passed in context. It properly passes it to the authorization policy's `permits(...)` method, which is its only job in the world.

So far it kind of sounds like you're saying there's a bug in `has_permission` and I'm saying there is definitely not, it's working as intended. The bug is your expectation that you can use `request.context` in the groupfinder - you shouldn't be doing that **right now**.

With that in mind, sure we can talk a bit more about your use case and what you're trying to solve, but I have no experience with kotti and just linking me to a file of code with no context doesn't really help me understand what the issue is. I'm like 99% sure I can rewrite your gist to work with pyramid_localroles just by renaming `Resource.local_roles` to `Resource.__ac_local_roles__`.

**Comment by robinharms** [comment]
Of course. I’m guessing quite few people are affected by this anyway, since not many use local roles in complex setups. And all the large projects that use it that I'm aware of have overriden several of the security parts in pyramid to do exactly what I'm suggesting.

> You absolutely should not be using request.context inside effective_principals. This is by design and there is no expectation that has_permission would affect request.context.

I understand that, but that would also render the whole concept of local roles useless, since you could never assign anything that has to do with permissions to them. So a lot of projects do that anyway.

Even Substance D, which is part of Pylons and made by some of the original creators of Pyramid do this in their code. And that has to do with the design of the callback (aka groupfinder) on authorization.

https://github.com/Pylons/substanced/blob/fed5f2363fb9af1c567c3fdf95c5168e7cf4b4e5/substanced/principal/__init__.py#L519

> request.has_permission does not ignore the passed in context. It properly passes it to the authorization policy's permits(...) method along with the user-level principals from effective_principals.

Yes, but the method effective_principals only accepts the request. Within effective_principals, the callback/groupfinder will be called for CallbackAuth policies. And that policy will usually fetch local roles principals from request.context, and thus fetching the wrong principals...

https://github.com/Pylons/pyramid/blob/21a9376b6c8535432eca527598013a0fbac9a461/pyramid/security.py#L438

On the next line, authz_policy.permits(context, principals, permission) will be called with the correct context from has_permission.

So all of this goes away if has_permission passes a long it's context (that might be None):
`principals = authn_policy.effective_principals(self, context=context)`

That would make local roles work as intended.

> So far it kind of sounds like you're saying there's a bug in has_permission and I'm saying there is definitely not, it's working as intended. The bug is your expectation that you can use request.context in the groupfinder - you shouldn't be doing that right now.

No not at all, It's doing exactly what the docs says it's doing. So not a bug. The problem is that as soon as people start implementing local roles, they will cause that bug by the requirement to fetch principals with the groupfinder/authz_policy.callback And if we want to support local roles with principal assignments without bad hacks, the change I'm proposing is needed.

This is one of the most common fixes for this problem, overriding the has_permission method and then doing this before calling the effective principals:

```
@contextmanager
def authz_context(context, request):
    before = request.environ.pop('authz_context', None)
    request.environ['authz_context'] = context
    try:
        yield
    finally:
        del request.environ['authz_context']
        if before is not None:
            request.environ['authz_context'] = before
```

And then fetching request.environ['authz_context'] within the groupfinder.

So what I'm saying is that the current implementation causes people to write hacky code :/
Hence the suggestion to simply pass along the context.

Sorry for the wall of text, but hope that cleared it up a bit.

**Comment by bertjwregeer** [comment]
`groupfinder` is a terrible thing, and we should have just told people to sub-class.

As for local roles, why not just make `__acl__` dynamic based upon the `localrole`? 

See https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#assigning-acls for making your ACL's dynamic.

**Comment by mmerickel** [comment]
@robinharms thanks for your patience, I think I'm starting to see what's going on. It seems to be differing opinions on who is responsible for determining more granular principals (the authentication policy or the context). Currently pyramid would say it's the context + authorization policy and not the authentication policy. We should certainly consider this issue if we revisit the identity vs authorization apis (re: post mortem) in 2.0. A big part of the problem is that I think people feel they should not override the authorization policy right now.

**Comment by robinharms** [comment]
@bertjwregeer the problem is that you need to subclass and replace has_permission to get that to work, and replacing the policy too afterwards.

Dynamic ACL still doesn't change the fact that the wrong principas will be passed to the permits-function. (If you're using local roles as a concept where you attach roles to groups, which i very much want to do :D )

(Run the gist i attached!)

@mmerickel that's great!

About overriding the authz, we roll our own for our projects, but it would feel weird to override it and not follow the IAuthorizationPolicy interface. (I.e. sneaking in context in effective_principals) And that would still require an override of has_permission.

Thanks a lot for digging into this.

**Comment by bertjwregeer** [comment]
@robinharms The principals passed to the permits function are inconsequential if you set up your `__acl__` to dynamically return the permissions for the object based upon something you know is in the principal list, such as the username.

Your principals could be something as simple as `user:<userid>` and your `__acl__` function that would return:

```
local_roles = {'user:<userid>': ['Editors']}

def __acl__(self, user=None):
    default_permissions = [(Allowed, 'Editors', [EDIT])]
    permissions = []
    if user and local_roles and user in local_roles:
        for (access, group, permissions) in default_permissions:
            if group in local_roles[user]:
                permissions.append((access, user, permissions))
            else:
                permissions.append((access, group, permissions))
        return permissions
    return default_permissions
```

With this policy:

```
@implementer(IAuthorizationPolicy)
class ACLAuthorizationPolicyWithLocalRoles(pyramid.authorization. ACLAuthorizationPolicy):
    def permits(self, context, principals, permission):
        user = None
        for principal in principals:
            if principal.startswith('user:'):
                user = principal
                break

        acl = '<No ACL found on any object in resource lineage>'

        for location in lineage(context):
            try:
                acl = location.__acl__
            except AttributeError:
                continue

            if acl and callable(acl):
                try:
                    acl = acl(user=user)
                except Exception:
                    acl = acl()

            for ace in acl:
                ace_action, ace_principal, ace_permissions = ace
                if ace_principal in principals:
                    if not is_nonstr_iter(ace_permissions):
                        ace_permissions = [ace_permissions]
                    if permission in ace_permissions:
                        if ace_action == Allow:
                            return ACLAllowed(ace, acl, permission,
                                              principals, location)
                        else:
                            return ACLDenied(ace, acl, permission,
                                             principals, location)

        # default deny (if no ACL in lineage at all, or if none of the
        # principals were mentioned in any ACE we found)
        return ACLDenied(
            '<default deny>',
            acl,
            permission,
            principals,
            context)
```

Attack the problem from a different direction. If you also need to get the potential local_roles from parent objects, you can walk the tree in the `__acl__`.

**Comment by robinharms** [comment]
Sorry, I don't really understand why we're talking about a solution to work around this. As I said, numerous projects have already invented clever hacks to get around the problem of effective_principals and callback/groupfinder.

I don't need help solving this problem that the API looks this way, I want to help to change the API so this problem goes away completely :)

If i use your code, the method authn_policy.effective_principals() would still return the wrong principals. Please run the example code that I attached and look at the code in Pyramid. You'll notice that there's really no way to create an implementation with local roles that will work with every method implemented in IAuthorizationPolicy and IAuthenticationPolicy.

I have worked with Pyramid since it was called BFG, I just never reported this problem because I forgot about it since I've patched it in all frameworks we use. Trying to correct that now...

**Comment by robinharms** [comment]
Hi everyone, it seems like the new Security policy from #3465 will solve this issue. So as soon as that's released this will pretty much go away.

**Comment by mmerickel** [comment]
Does it solve this issue? It's not clear to me that it does.

**Comment by luhn** [comment]
With `effective_principals` on the way out, I can't see how this issue applies anymore.  Principals are now an implementation detail of `permits` (if they exist at all) and can change based on the context.

**Comment by mmerickel** [comment]
Thank you, yes I forgot this issue was specific to principals.

**Comment by bertjwregeer** [comment]
With the work in #3465 now merged, I am closing this discussion. Feel free to re-open if the new security policy doesn't allow you to do what you need.
