### ISSUE TITLE
Bump Sphinx to >=1.7.2

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3269]
Would anyone be opposed to bumping Sphinx to >=1.7.2, != 1.7.3 in `setup.py`? I really want our PDFs to have `emphasize-lines` support, at long last, and bring in support for Unicode characters in PDFs via xelatex.

Refs:
* #667
* #2572
* https://github.com/rtfd/readthedocs.org/issues/4015

**Comment by mmerickel** [comment]
That's fine but I'm -1 on backporting it to older release branches.
