### ISSUE TITLE
Backport https://github.com/Pylons/pyramid/pull/3276

### ISSUE THREAD

**Issue by bertjwregeer** [Pylons/pyramid#3277]
This change looks like it will not be difficult to back port and will make our docs look better:

https://github.com/Pylons/pyramid/pull/3276

**Comment by cewing** [comment]
I can help @radurevutchi with that if needed.

**Comment by stevepiercy** [comment]
Please see my review and subsequent comments first.
https://github.com/Pylons/pyramid/pull/3276#pullrequestreview-120027305

**Comment by stevepiercy** [comment]
@radurevutchi made the changes in #3276 and #3277, so the two PRs can be backported, if possible. There might be issues with `emphasize-lines` in `1.9-branch` and `1.8-branch`, so they need to be checked carefully, too. Please let me know if you are still sprinting and someone can take it on, and I'll assign this issue to that person. Thank you!

**Comment by stevepiercy** [comment]
Fixed in 263ba4d and d488844
