### ISSUE TITLE
Bump tox testenvs to use basepython = 3.6?

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3289]
I just noticed that our tox `testenv`s use `basepython = 3.5` for `lint`, `docs`, `pdf`, and `coverage`.
https://github.com/Pylons/pyramid/blob/master/tox.ini#L67

Should I bump them to 3.6?

**Comment by mmerickel** [comment]
Last I checked rtd still used 3.5 which is why I left them there. Feel free to check again and keep it matched up.

**Comment by stevepiercy** [comment]
OK, RTD is still on 3.5. I'll leave this open for `docs` and `pdf`. How about bumping for `lint` and `coverage`?

**Comment by mmerickel** [comment]
@stevepiercy they can be bumped, it's not really a big deal either way but go for it.

**Comment by stevepiercy** [comment]
Huh, turns out that they've supported 3.6 for about a year.
https://github.com/rtfd/readthedocs.org/issues/4434#issuecomment-408175934

We can specify that docs be built on RTD with 3.6 (default is 3.5) in order to get support for f-strings with a `readthedocs.yml` file. What do you think?

Do we have any f-strings in Pyramid code now? I reckon in v2.0 when we drop Python 2.7, we might start seeing them.

**Comment by mmerickel** [comment]
f-strings are Python 3.6 and we are supporting 3.4. They won't be getting used for a little while. There's no reason for us right now to try and force rtd to use 3.6.

**Comment by stevepiercy** [comment]
OK. I'll defer the work until necessary.

Should this issue be closed or kept open as a reminder for far into the future? I'm fine either way.

**Comment by mmerickel** [comment]
Comments were added to the steps that are pinned, others are updated in #3388.
