### ISSUE TITLE
Support Python 3.7

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3312]
With the release of Python 3.7, we should support it.

Changes on `master` should be backported to `1.9-branch` and `1.8-branch`.

Files to update:
- [x] appveyor.yml
- [x] tox.ini
- [x] .travis.yml
- [x] CHANGES.txt
- [x] HACKING.txt lines 121, 122, 214
- [x] scaffoldtests.sh
- [ ] HISTORY.rst (upon release)
- [x] RELEASING.txt line 36
- [x] setup.py, line 86
- [x] docs/narr/install.rst line 25
- [x] docs/quick_tutorial/requirements.rst lines 22, 23, 26
- [x] docs/quick_tour.rst lines 30, 721,719
- [x] docs/tutorials/wiki/installation.rst lines 114, 253, 259
- [x] docs/tutorials/wiki2/installation.rst lines 126, 263, 269

**Comment by stevepiercy** [comment]
If we can easily, temporarily insert and remove support for 3.7 in travis, then we can compromise on `tox.ini` and `.travis.yml`. Otherwise, we are testing on 3.7 now, so all other changes can be made for v1.10.

**Comment by ztane** [comment]
The workaround isn't that bad.

**Comment by mmerickel** [comment]
Did you want to submit a PR?

**Comment by stevepiercy** [comment]
Watching https://github.com/Pylons/peppercorn/pull/12#pullrequestreview-146151308 for a possible workaround, as implemented in https://github.com/zopefoundation/zope.interface/blame/bec33bef33d3d2b173f22575bf8fa3b8ae114f21/.travis.yml#L13-L16

**Comment by stevepiercy** [comment]
See #3333

**Comment by stevepiercy** [comment]
Closed by #3333

**Comment by stevepiercy** [comment]
FYI Travis now supports Xenial
https://blog.travis-ci.com/2018-11-08-xenial-release
