### ISSUE TITLE
docs for `IRequestExtensions` confusing 

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#3313]
Based on some tests from pyramid_tm, I'm using IRequestExtensions to test that a package is correctly registering request methods via the includeme.

These lines show two managed lists: descriptors and methods; most tests I've seen reference 'method'

https://github.com/Pylons/pyramid/blob/57a896f103c7378fb285f6594228578a5324d672/pyramid/interfaces.py#L577-L583

what I've noticed in practice, is that this registers under 'methods':

        self.config.add_request_method(foo, name='foo')

while specifying 'reify=True' registers under 'descriptors'

        self.config.add_request_method(bar, name='bar', reify=True)

**Comment by mmerickel** [comment]
This is not a public interface.

**Comment by tseaver** [comment]
@jvanasco FWIW, having reified "methods" show up in `descriptors` is quite normal / explicable:  the point of the `@reify` decorator is to cache the method call result, which means that such "wrapped methods" are *not* like other methods.

**Comment by jvanasco** [comment]
> This is not a public interface.

It probably should be. It's the only method I've seen projects use in test suites to ensure their `includeme` directive property sets up `add_request_method`.

> FWIW, having reified "methods" show up in descriptors is quite normal / explicable: 

that makes perfect sense.

it's just a bit confusing as the docstring reads "properties and methods" , the actual attributes are "descriptors" and "methods", and 'add_request_method' can add a descriptor or method.
