### ISSUE TITLE
Don't shadow __name__

### ISSUE THREAD

**Issue by dstufft** [Pylons/pyramid#3315]
Currently the location aware resources rely on two attributes on a class instance, one is ``__parent__``, and the other is ``__name__``. However, ``__name__`` is also the name used for the name of a class.

It's true that instances don't have a ``__name__`` attribute in normal Python, only classes do, however situations like:

```python
class Foo:
    @property
    def __parent__(self):
        ...

    @property
    def __name__(self):
        ...
```

Put the class into a weird state where ``Foo.__name__`` refers to one thing, and ``Foo.__dict__["__name__"]`` refers to another thing. 

I ran into this when I was *trying* to attempt to make a decorator that would make objects location aware, when they already have an attribute on them that ``__parent__`` and ``__name__`` should just blindly return. Thus I was looking for something like:

```python
@location_aware(parent="foo", name="bar")
class Foo:
    ...
```

Which would ultimately get translated into the same thing as:

```python
class Foo:
    @property
    def __parent__(self):
        return self.foo

    @property
    def __name__(self):
        return self.bar
```

It did this by having a small function that would just assign a property to ``Foo.__parent__``, and ``Foo.__name__``, but it turns out you can't actually assign a non string to ``Foo.__name__`` (and doing so is unlikely to actually do what I want, and on Python 3 at least, ``Foo.__dict__`` isn't mutable, so I can't work around it by setting it there. Making it impossible to mutate the class level ``__name__`` after the fact, without doing something gross like overriding ``__init__`` or something.

There are obviously ways around this, so maybe this edge case isn't worth worrying about. However, it feels like really poor form to quasi shadow a built in dunder method like this, so maybe it would make sense to deprecate (but likely never remove) support for ``__name__``, and allow it to be specified with a different name?

The location code could just simply do something like:

```python
_sentinel = object()

name = getattr(obj, "__newname__", _sentinel)
if name is _sentinel:
    name = getattr(obj, "__name__", _sentinel)
if name is _sentinel:
    raise Exception("Oh No, couldn't find a name")
```

Of course, if y'all think it's not worth it, feel free to close this issue-- I do recognize it is a bit of an edge case and might not be worth the churn, even if it's kinda undesirable to shadow like that.

**Comment by mcdonc** [comment]
Wow.  It's weird that I never thought of this; the pattern comes from Zope, and has been in place for about 15 years, and I never once thought about instance __name__ shadowing class __name__.

In general, I think I agree.  If we were to have it to do all over, we might pick a different attribute.  In this context, however, I think we just have to live with it, because it's such an ingrained pattern, and documenting the __newname__ feature would be pretty tricky (adding confusion to a concept that seems to already be confusing to newcomers).  I'm -1 on __newname__ as a result.

**Comment by russellballestrini** [comment]
Could this be something tackled when switching to Pyramid 2.0?

**Comment by mcdonc** [comment]
@russellballestrini I don't think a major version bump has any effect on this; unless we were to rename ``__name__`` to something else, and that would be a terrible idea for backwards compatibility.

**Comment by tseaver** [comment]
I don't think "shadow" is the right term here, as `__name__` is not accessible from an instance (and never has been):

```python
$ python2.7
Python 2.7.14 (default, Oct  4 2017, 16:09:27) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> class Foo: pass
... 
>>> foo = Foo()
>>> foo.__name__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: Foo instance has no attribute '__name__'
>>> Foo.__name__
'Foo'
>>> class Bar(object): pass
... 
>>> bar = Bar()
>>> bar.__name__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Bar' object has no attribute '__name__'
>>> Bar.__name__
'Bar'
$ python3.6
Python 3.6.3 (default, Oct  4 2017, 16:14:25) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> class Foo: pass
... 
>>> foo = Foo()
>>> foo.__name__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Foo' object has no attribute '__name__'
>>> Foo.__name__
'Foo'
```

**Comment by dstufft** [comment]
@tseaver Yea, I just couldn't think of a better name for it. ``__name__`` is already weird in that it only exists on classes not instances (unlike other class level attributes). It does shadow it at the class level though (since descriptors get assigned to the class not the instance).

Ultimately I'm fine either way here, I ran into it because Python 3 does not allow *any* way that I could find to dynamically assign to ``__name__`` like ``Bar.__name__ = property(...)`` while ``__parent__`` works fine for this. I was trying to do that because I was making a class decorator that would make a class location aware.

It's reasonable to say this is too big of a change to deal with too narrow of an edge case.

**Comment by mmerickel** [comment]
I guess at the end of the day there's nothing you actually need `@property` for here, as you could set a dynamic instance-level attribute in the constructor or any other time, albeit in a less satisfying syntax. I agree that it's just not worth changing at this point.
