### ISSUE TITLE
DeprecationWarning from WebOb 1.8.2 (Accept parsing uses old method)

### ISSUE THREAD

**Issue by fschulze** [Pylons/pyramid#3317]
Since WebOb 1.8.2 the AcceptPredicate (and possibly others) cause a DeprecationWarning, see https://github.com/Pylons/webob/commit/503f4f864631a7b48a1a419068fd2173baed8075

Just wanted to leave this here so it's not forgotten.

**Comment by mmerickel** [comment]
@fschulze Can you confirm that this was fixed in master via https://github.com/Pylons/pyramid/pull/3251?

**Comment by bertjwregeer** [comment]
The `AcceptPredicate` is a special case, and I likely missed it when I did my initial fixes.

/assign: bertjwregeer

**Comment by mmerickel** [comment]
this is fixed via #3326
