### ISSUE TITLE
How to distinguish ApplicationCreated during bootstrap()?

### ISSUE THREAD

**Issue by glasserc** [Pylons/pyramid#3349]
Hi! Our application uses Pyramid `pyramid.paster.bootstrap` to implement a `migrate` command which initializes databases. We also have a plugin system and a plugin that listens for the `ApplicationCreated` system to try to track the application's initial state. However, `bootstrap` calls `make_wsgi_app` which emits the `ApplicationCreated` event, so the first time the application runs, the plugin gets initialized and it tries to access the database before the actual migrate can be done.

I'm at a bit of a loss of how to address this. Should the plugin somehow check to see that migration hasn't happened and do nothing? Should the application somehow `bootstrap()` in a special "we're about to do a migration" mode, and the plugin modified to check for that and not do anything in that case? Should we not call `bootstrap` on the "real" config file but a generated-on-the-fly one that e.g. doesn't have any plugins?

I thought it would be simplest to check for what "mode" we had ApplicationCreated in, but I don't see a way to do that.

**Comment by glasserc** [comment]
Thinking about this more, probably the significant variable here is not `are we doing bootstrap()?` but `why are we doing bootstrap()? is it for a migrate?`. One approach that seems to work is to pass a `command` option as part of the `options` to `bootstrap()`, which then get passed back to the application, which can then set the `command` as part of the registry.

**Comment by mmerickel** [comment]
It'd probably be nice if `bootstrap` and `prepare` would inject something into the app settings automatically but it doesn't. I'd happily consider a PR for this.

For now, the assumption is that if you need to differentiate that state then you would pass a setting which would be available in `app.registry.settings` as part of the event.

**Comment by glasserc** [comment]
OK, I think that's the same as the approach we took. That worked well enough for us. I think even having `bootstrap` and `prepare` add extra information to the app settings is impractical because you would need to know more about `bootstrap`'s caller in order to add any information that was actually useful. I think I'll close this for now. Thanks for your thoughts!
