### ISSUE TITLE
Sphinx 1.8.0 build error: ImportError: cannot import name 'DEFAULT_SETTINGS'

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3350]
The release of Sphinx 1.8.0 brings a new build error.
https://travis-ci.org/Pylons/pyramid/jobs/428634951#L497

Reported in:
https://github.com/sphinx-doc/sphinx/issues/5433

**Comment by cdunklau** [comment]
A workaround would be to `import sphinx.builders.latex.nodes` first. This avoids the circular import:

```
--> $ venv/bin/python
Python 3.5.3 (default, Apr 11 2017, 21:55:23) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Enabled tab completion
>>> import sphinx.builders.latex.nodes
>>> from sphinx.writers.latex import LaTeXTranslator
>>> sphinx.version_info
(1, 8, 0, 'final', 0)
```

**Comment by stevepiercy** [comment]
I've pinned Sphinx to <=1.7.9 in setup.py until their team can resolve the issue and avoid workarounds.

**Comment by stevepiercy** [comment]
This was fixed in https://github.com/sphinx-doc/sphinx/pull/5445, and we're awaiting a release. I'm watching [Sphinx 1.8.1 release plan](https://github.com/sphinx-doc/sphinx/issues/5448). I'll pin the Sphinx version to exclude 1.8.0.
