### ISSUE TITLE
Copyright out of date

### ISSUE THREAD

**Issue by cdunklau** [Pylons/pyramid#3355]
Just noticed this, not sure if it's intentional:

https://github.com/Pylons/pyramid/blob/1f2bde7ac13542958f1808ee72b26b567398fd9b/COPYRIGHT.txt#L1

That's a long time ago! :)

**Comment by stevepiercy** [comment]
It's an oversight. Please submit a PR immediately before the copyright attorneys lay siege! :bowtie:
