### ISSUE TITLE
Avoid `sudo pip` suggestion in HACKING.txt

### ISSUE THREAD

**Issue by cdunklau** [Pylons/pyramid#3357]
This is worrisome advice:

https://github.com/Pylons/pyramid/blob/8cc4bf732f636abc06a2fbb72b2bd9ab0a680eb2/HACKING.txt#L181-L192

This should at the very least not suggest using `sudo` with `pip`, since it can potentially screw up your OS.

Here are some nicer alternatives:

- Don't discuss specific installation commands at all (probably link to tox's installation page)
- Directly suggest a safer way
  - Install tox itself in a virtualenv
  - `pip install --user`, although that would need a note about PATH and/or answer "where did setuptools put my executable!?"
- Point to a good blog post or docs about such workflows

**Comment by stevepiercy** [comment]
Agreed. Option 1 is best. We like punting to the authoritative sources and let the developer decide where to put their executables.
https://tox.readthedocs.io/en/latest/install.html

**Comment by cdunklau** [comment]
The virtualenv workflow is shown in [contributing.md](https://github.com/Pylons/pyramid/blob/e2110176fe0e6c6dd1891be2761fe33fc23fb650/contributing.md#building-documentation-for-a-pylons-project-project), so that could be adapted/copied/etc. Would probably be best to have one "source of truth" about it though.

Another point: HACKING.txt and contributing.md both have notes about building documentation...

**Comment by stevepiercy** [comment]
Closed by #3389
