### ISSUE TITLE
Drop support for Python 3.4 (and 3.5?) for Pyramid 2.0?

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3419]
This issue is a placeholder for discussing the drop of support for Python 3.4 and 3.5.

- Python 3.4 will be EOLed on 2019-03-16.
- Python 3.5 will be EOLed on 2020-09-13.

See [Status of Python branches in the Python Developer's Guide](https://devguide.python.org/#status-of-python-branches).

What features in Python >= 3.6 could we implement by dropping either of these earlier versions? Please comment below.

See also #2362

**Comment by bertjwregeer** [comment]
Type annotations please. f strings may be worth it too... maybe.

**Comment by hugovk** [comment]
Here's the pip installs for Pyramid from PyPI for December 2018:

| category | percent | downloads |
|----------|--------:|----------:|
|      2.7 |  47.89% |    49,041 |
|      3.6 |  32.60% |    33,379 |
|      3.5 |   9.08% |     9,299 |
|      3.7 |   5.37% |     5,498 |
|      3.4 |   4.11% |     4,204 |
| null     |   0.60% |       610 |
|      2.6 |   0.18% |       185 |
|      3.3 |   0.18% |       182 |
|      3.8 |   0.01% |         6 |
| Total    |         |   102,404 |

Source: `pypistats python_minor --last-month pyramid`

**Comment by ztane** [comment]
Type annotations are backportable. I wouldn't drop 3.5 before the EOL date for sure because there are many server OSes in existence where the 3.5 is the default

**Comment by mmerickel** [comment]
We need to drop 3.4 for sure.

**Comment by mmerickel** [comment]
fixed by #3547
