### ISSUE TITLE
Missing line in code - server will quit immediately

### ISSUE THREAD

**Issue by yackx** [Pylons/pyramid#3427]
**Describe the issue**
Missing line of code in tutorial causes the server to quit right after it has started.

**Include references**
1. Go to [02: Python Packages for Pyramid Applications](https://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/package.html)
2. Follow the instructions
3. Server terminates right after it is started

**Describe the improvement**

Add the following line to `app.py`:
```python
server.serve_forever()
```

**Comment by stevepiercy** [comment]
@yackx I'm sorry, I can't replicate the issue you describe. Follow the instructions works for me.

Please compare your files [against the source](https://github.com/Pylons/pyramid/tree/1.10-branch/docs/quick_tutorial/package).

**Comment by yackx** [comment]
You're right, I had some leftovers from a previous chapter. Sorry for the inconvenience. This tutorial is very well thought and written btw.
