### ISSUE TITLE
Feature Request: Upload into PyPi package with all Pyramid tests, e.g. `pyramid.tests`.

### ISSUE THREAD

**Issue by Cykooz** [Pylons/pyramid#3428]
How can I use in my project code form Pyramid tests after #3022 ?

I have a project with extended version of `pyramid.authorization.ACLAuthorizationPolicy`. I am using `TestACLAuthorizationPolicy` test case to testing my implementation:

```python
from pyramid.tests.test_authorization import TestACLAuthorizationPolicy

class TestRestACLAuthorizationPolicy(TestACLAuthorizationPolicy):

    def _getTargetClass(self):
        from ..authorization import RestACLAuthorizationPolicy
        return RestACLAuthorizationPolicy

    # Some addition tests for extended functionality
```

It would be cool if you upload into PyPi package with all Pyramid tests, e.g. `pyramid.tests`.

**Comment by stevepiercy** [comment]
You can clone the repository and run tests. See https://github.com/Pylons/pyramid/blob/master/HACKING.txt.

**Comment by Cykooz** [comment]
> You can clone the repository and run tests. See https://github.com/Pylons/pyramid/blob/master/HACKING.txt.

But how can I import pyramid tests from cloned repository? After #3022 the package with pyramid's tests located outside of main pyramid package, and it can not be imported without some hacks of `sys.path`

**Comment by stevepiercy** [comment]
What did you try? Following HACKING.txt is the supported method of running Pyramid's tests.

**Comment by Cykooz** [comment]
> What did you try? Following HACKING.txt is the supported method of running Pyramid's tests.

I don't need to run Pyramid's tests. I need to run tests of my project. My tests imports some code from Pyramid's test (look at the example in at the beginning of the issue)

**Comment by stevepiercy** [comment]
What does the stacktrace show you?

**Comment by stevepiercy** [comment]
Adjust your import statement so it can find the `tests` module. This is not the correct dotted Python path:

```
from pyramid.tests.test_authorization import TestACLAuthorizationPolicy
```

I don't know your project structure, but I'd guess that removing `pyramid.` would be a good start.

**Comment by Cykooz** [comment]
> Adjust your import statement so it can find the `tests` module. This is not the correct dotted Python path:
> I don't know your project structure, but I'd guess that removing `pyramid.` would be a good start.

Have you read #3022?

`pyramid.tests` was a valid python module, was a part of `Pyramid` distribution. But after release of `Pyramid 1.10` this module has been removed from `Pyramid` distribution.

**Comment by Cykooz** [comment]
> vendor in the `pyramid.tests`

Oh, it's not funny. :(

**Comment by mmerickel** [comment]
Sorry but you will need to vendor the policy’s tests if you want to use them in your project. The test suite is not public api.
