### ISSUE TITLE
Migrate content from `/narr/scaffolding.rst` to `/narr/cookiecutters.rst`

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3434]
Review content in `/narr/scaffolding.rst` from the `1.10-branch` and port relevant bits to `/narr/cookiecutters.rst` on `master`.

See also https://github.com/Pylons/trypyramid.com/issues/255

**Comment by mmerickel** [comment]
@stevepiercy any plans to make this happen? If not I'm removing the 2.0 milestone.

**Comment by stevepiercy** [comment]
Yes. Do we have a timeline for a 2.0 release?

**Comment by mmerickel** [comment]
This week I’m looking at an alpha if only docs stuff is left.

**Comment by stevepiercy** [comment]
Opened PR #3552. There wasn't a whole lot that can be migrated, but I expanded it a bit.

**Comment by stevepiercy** [comment]
Closed by #3552
