### ISSUE TITLE
pyramid.exceptions.ConfigurationConflictError: <exception str() failed>

### ISSUE THREAD

**Issue by benkawecki** [Pylons/pyramid#3453]
**Describe the bug**
While building an app I caused an error who's traceback ending the the following line:
```
pyramid.exceptions.ConfigurationConflictError: <exception str() failed>
```
What caused the error in the first place was that I copied a python package containing my views to a new package called controllers and forgot to delete the original views package. I assume that the configurator failed while trying to commit the config.scan(). Since I couldn't find any information online about the above traceback message I assume that this is probably just some internal problem with Pyramid. 
**To Reproduce**
download from: https://github.com/benkawecki/pypi/tree/error
after setting up run 
``` 
pserve development.ini
```

**Expected behavior**
I expect there to be an error message. 

**Screenshots**
Screenshot of the error message:
<img width="489" alt="screen shot 2019-01-15 at 10 02 44 pm" src="https://user-images.githubusercontent.com/39999125/51224413-c57eb800-1913-11e9-9e0f-b25878a479f5.png">
Screenshot of installed packages:
<img width="488" alt="screen shot 2019-01-15 at 10 24 42 pm" src="https://user-images.githubusercontent.com/39999125/51224563-8b61e600-1914-11e9-9b04-42936f94d4bd.png">

**Additional context**
I'm looking to help out in open-source more this year so if this is an easy fix I would love to see if I can do it!

**Comment by stloma** [comment]
I'm getting getting it on arch linux with python 3.7.2; did you maybe not checkout the error branch @mmerickel?

The error seems to stem, as you mentioned @benkawecki, from having the same view_configs.

The message `exception <str> failed` looks to be a `__str__` method that isn't able to make a string and I believe the method that's choking is at this line:

https://github.com/Pylons/pyramid/blob/7bd9da72c63124c7ca007f4fa2113633bba5c403/src/pyramid/exceptions.py#L95

When self._conflicts contains the following dictionary (specifically the HTTPNotFound object):

```
('view', None, '', 'about', 'd41d8cd98f00b204e9800998ecf8427e'):
    [
        <pyramid.config.actions.ActionInfo object at 0x7f02f0bd25c0>,
        <pyramid.config.actions.ActionInfo object at 0x7f02f0ae3128>
    ],
('view', None, '', 'home', 'd41d8cd98f00b204e9800998ecf8427e'):
    [
        <pyramid.config.actions.ActionInfo object at 0x7f02f0bd2898>,
        <pyramid.config.actions.ActionInfo object at 0x7f02f0ae3278>
    ],
('view', <class 'pyramid.httpexceptions.HTTPNotFound'>, '', None, 'd41d8cd98f00b204e9800998ecf8427e'):
    [
        <pyramid.config.actions.ActionInfo object at 0x7f02f0bd2b00>,
        <pyramid.config.actions.ActionInfo object at 0x7f02f0ae3470>
    ]
}
```

Anyway, just a cursory inspection, but maybe enough to get you started looking into or someone else can shed more insight :)

**Comment by benkawecki** [comment]
@mmerickel as @stloma said did you checkout the error branch? That was my bad for not specifying which branch in my initial post. I was able to recreate again though by just copying the controller folder in the master branch and renaming it to views.

**Comment by stloma** [comment]
This issue is the `sorted` function choking on trying to sort the `None` value against the `HTTPNotFound` object that I detailed in my previous post.

The resolution is changing however you'd like to sort the conflicts (if they need to be sorted at all?)

**Comment by mmerickel** [comment]
Ok I can repro using the error branch. The bug is in sorting the discriminators on Python 3. It's kind of amazing this hasn't come up before. I think instead of sorting the discriminators the best we can do is group by them.

**Comment by benkawecki** [comment]
@mmerickel 
The following seems to work for me:
```python
class ConfigurationConflictError(ConfigurationError):
    """ Raised when a configuration conflict is detected during action
    processing"""

    def __init__(self, conflicts):
        self._conflicts = conflicts

    def __str__(self):
        r = ["Conflicting configuration actions"]

        items = sorted(self._conflicts.items(), key=lambda x: (x[0][1] is None, x))
        for discriminator, infos in items:
            r.append("  For: %s" % (discriminator,))
            for info in infos:
                for line in str(info).rstrip().split(CR):
                    r.append("    " + line)
        return CR.join(r)
```

The output is below, please let me know if this is the expected behavior:
![image](https://user-images.githubusercontent.com/39999125/51327949-5652b200-1a40-11e9-9ada-5e7afc38fd54.png)

**Comment by benkawecki** [comment]
Fair enough, I haven't really dug much into the discriminators. Would it be worth including a timestamp when an action in made (atleast a timestamp that isn't included in the hash)? this way the order is preserved.

**Comment by mmerickel** [comment]
Nah. It’s really just sorting between different conflicts.

**Comment by benkawecki** [comment]
@mmerickel 

Do you mind if I branch and make a PR removing the sorted function?

**Comment by bertjwregeer** [comment]
@benkawecki we will always welcome PR's :-) Please make sure if you haven't yet, to read and sign CONTRIBUTORS.rst. Thanks!

**Comment by benkawecki** [comment]
Sorry @mmerickel and @bertjwregeer, for the delay, working on the PR now. I've always used pytest over unit test so making an appropriate test is taking a bit.

**Comment by mmerickel** [comment]
@benkawecki thanks for offering to do the PR but it's been a few days so I went ahead and did it so that we can get the bugfix out - you're off the hook.
