### ISSUE TITLE
render_to_response() does not use request.response

### ISSUE THREAD

**Issue by mikeckennedy** [Pylons/pyramid#3462]
## Bug Report

Hi, recently I found my site (build on Pyramid of course), was not properly reporting 404 status codes for a custom error page. After investigating I think this close to a bug, certainly an enhancement.

**Describe the bug**
A clear and concise description of the bug.

Using this function for a custom error page:

```
@notfound_view_config()
def not_found(request: Request):
    request.response.status_code = 404
    t = '...:templates/errors/404.pt'
    return render_to_response(t, {}, request)
```
Was returning 200, not 404, even though the response on the request was set. This code was needed to make it work:

```
@notfound_view_config()
def not_found(request: Request):
    request.response.status_code = 404
    t = '...:templates/errors/404.pt'
    return render_to_response(t, {}, request, response=request.response)
```

Notice `response=request.response`. 

**To Reproduce**
1. Just use the error handler above 
2. hit a nonexistant URL.

**Expected behavior**
Status code of the response is 404 (but it's actually 200)

**Additional context**
Add any other context about the issue here.

What I thought would happen was if no response was specified, request.response would be used. I would like to propose that when calling

`render_to_response(template, data, request, response=None)` that `request.response` is used.

I looked into fixing this but didn't see a good place to do this test in the test suite.

**Comment by stevepiercy** [comment]
I think you want to do this:

```python
    request.response.status = 404
```

See https://docs.pylonsproject.org/projects/webob/en/stable/api/response.html#module-webob.response and https://stackoverflow.com/a/9815676/2214933

**Comment by mikeckennedy** [comment]
Hi @stevepiercy I think you may be right. But the issue stands. I originally had status and was mucking around when it wasn't working. Although it may work either way (when explicitly passing along the response).

**Comment by mmerickel** [comment]
Hey @mikeckennedy thanks for opening the issue. This behavior was changed in 1.6 to make it a more predictable and isolated render when using `render_to_response()` or `render()`. The behavior is documented[1] as well:

> Keep in mind that any changes made to request.response prior to calling this function will not be reflected in the resulting response object. A new response object will be created for each call unless one is passed as the response argument.

[1] https://docs.pylonsproject.org/projects/pyramid/en/1.10-branch/api/renderers.html#pyramid.renderers.render_to_response

**Comment by mikeckennedy** [comment]
Oh I see. Ok, that makes sense. I guess the parameter to pass the response was throwing me off. Thank you!
