### ISSUE TITLE
userid unsecured as a base64 encoded string

### ISSUE THREAD

**Issue by AvnerCohen** [Pylons/pyramid#3484]
As far as I can see Inside https://github.com/Pylons/pyramid/blob/587fe72fae0efda3a860d37a1ea2449a41dab622/src/pyramid/authentication.py#L1020

The userid, will be base64ed and saved on the session cookie.

The output will be something like:
01f13ac1671ddd4e695c37ff27a230c10fgggg620ca0a66b73113abba4411fc2322ff425828fc64bbc3aaa3b056728e23d01bd89a7f89467329c1fa1d306275ca720ea**CREDENTIAL REDACTED**!userid_type:b64str

**To Reproduce**
Implement a Auth Policy with a Cookie.
I could be wrong and than happy to provide more info, but I suspect it's a pretty default setup.

**Expected behavior**

Any user related/session related data should be full encrypted.

Happy to provide any additional information of anything else is needed.

Thanks!

**Comment by mmerickel** [comment]
Thank you for the report but auth_tkt is a standard protocol for transporting access tokens and was not invented here. I will note that while you're correct that it's not encrypted, neither are most mechanisms used for this purpose such as even JWT. The information (the user id) encoded here is not intended to be a secret, but rather only guaranteed to be created / signed by a trusted party.
