### ISSUE TITLE
pip 19.1 breaks editable installs

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3493]
See https://github.com/pypa/pip/issues/6434 and https://discuss.python.org/t/pip-19-1-and-installing-in-editable-mode-with-pyproject-toml/1553 for reference.

As I read these threads on pip 19.1 breaking editable installs, it appears that the Pyramid tutorials need to be updated by removing any step of `pip install --upgrade pip setuptools`.  Is that correct?

Additionally, will we need to change anything else with how we use editable installs?

This will also carry over to the [starter cookiecutter](https://github.com/pylons/pyramid-cookiecutter-starter).

For searching issues, the error message with pip 19.1 installed after `pip install -e .` is the following:

> ERROR: Error installing 'user_path_to_pyramid_checkout': editable mode is not supported for pyproject.toml-style projects. pip is processing this project as pyproject.toml-style because it has a pyproject.toml file. Since the project has a setup.py and the pyproject.toml has no "build-backend" key for the "build_system" value, you may pass --no-use-pep517 to opt out of pyproject.toml-style processing. See PEP 517 for details on pyproject.toml-style projects.

**Comment by bertjwregeer** [comment]
We don't have a `pyproject.toml` that is generated in the cookie cutter, no?

**Comment by bertjwregeer** [comment]
Also, I don't recommend doing dev on pyramid itself in a editable checkoutl

**Comment by stevepiercy** [comment]
> We don't have a `pyproject.toml` that is generated in the cookie cutter, no?

Ah, you're right.
https://github.com/Pylons/pyramid-cookiecutter-starter/tree/latest/%7B%7Bcookiecutter.repo_name%7D%7D

**Comment by stevepiercy** [comment]
> Also, I don't recommend doing dev on pyramid itself in a editable checkout!

Our [HACKING.txt](https://github.com/Pylons/pyramid/blob/master/HACKING.txt) does not.

Only our docs and tutorials recommend doing it for development of a Pyramid project in 66 places across 51 files.

**Comment by bertjwregeer** [comment]
That's fine, let's not add a `pyproject.toml` until that problem is resolved in pip, and then we can worry about it.

**Comment by stevepiercy** [comment]
Some of our docs do not use the cookiecutter. For those parts, we have to wait for PyPA to resolve their breakage of editable installs before we can revise our docs. Meanwhile, we should advise users not to do `pip install --upgrade pip setuptools`, or if they do then to downgrade via `env/bin/pip install pip==19.0.3`.

**Comment by bertjwregeer** [comment]
`virtualenv` by default will download and install the latest version of pip. Ask me how I know.

**Comment by stevepiercy** [comment]
/me puts on slippers, pulls up a comfy chair, and 🍿 . Tell us a story, uncle Bert!

**Comment by mmerickel** [comment]
this was fixed in 19.1.1
