### ISSUE TITLE
Improve code used to benchmark Pyramid on the Tech Empower - Web Framework Benchmarks

### ISSUE THREAD

**Issue by rudaporto** [Pylons/pyramid#3495]
## Intro
Here are the results of the latest round of the Web Framework Benchmarks provided by Tech Empower:
- https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=json&l=zijzen-1

I was wondering about how fast is Pyramid and how it can be compared with Starlette in the basic JSON test, using a view like this in local machine:

```python
@view_config(route_name='test_1', renderer='json')
def test_1(request):
    """
    Test type 1: JSON serialization
    """
    return {"message":"Hello, World!"}
```

I've decided to test Pyramid and Starlette, each one with 4 workers and using the Python stdlib JSON module (Starlette uses JSONResponse in the benchmark).

Here some results comparing Pyramid and Starlette using Ubuntu 19.04 with Python 3.7 (no docker) on a MacBook Pro Retina Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz.

## Results:

- Pyramid:

```bash
$ pip freeze
greenlet==0.4.15
gunicorn==19.9.0
hupper==1.6.1
meinheld==1.0.1
PasteDeploy==2.0.1
pkg-resources==0.0.0
plaster==1.0
plaster-pastedeploy==0.7
pyramid==1.10.4
translationstring==1.3
ujson==1.35
venusian==1.2.0
WebOb==1.8.5
zope.deprecation==4.4.0
zope.interface==4.6.0
```

```bash
$ ab -n100000 -c 100 http://localhost:8000/
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 10000 requests
Completed 20000 requests
Completed 30000 requests
Completed 40000 requests
Completed 50000 requests
Completed 60000 requests
Completed 70000 requests
Completed 80000 requests
Completed 90000 requests
Completed 100000 requests
Finished 100000 requests


Server Software:        meinheld/1.0.1
Server Hostname:        localhost
Server Port:            8000

Document Path:          /
Document Length:        18 bytes

Concurrency Level:      100
Time taken for tests:   9.205 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      16900000 bytes
HTML transferred:       1800000 bytes
Requests per second:    10863.37 [#/sec] (mean)
Time per request:       9.205 [ms] (mean)
Time per request:       0.092 [ms] (mean, across all concurrent requests)
Transfer rate:          1792.88 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    3   1.2      3      20
Processing:     1    6   2.7      5      44
Waiting:        1    5   2.7      4      42
Total:          5    9   2.8      8      50

Percentage of the requests served within a certain time (ms)
  50%      8
  66%      9
  75%      9
  80%      9
  90%     11
  95%     14
  98%     19
  99%     23
 100%     50 (longest request)

```
- Starlette:

```bash
$ pip freeze
Click==7.0
gunicorn==19.9.0
h11==0.8.1
httptools==0.0.13
pkg-resources==0.0.0
starlette==0.12.0
ujson==1.35
uvicorn==0.7.1
uvloop==0.12.2
websockets==7.0
```

```bash
$ ab -n100000 -c 100 http://localhost:5000/
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 10000 requests
Completed 20000 requests
Completed 30000 requests
Completed 40000 requests
Completed 50000 requests
Completed 60000 requests
Completed 70000 requests
Completed 80000 requests
Completed 90000 requests
Completed 100000 requests
Finished 100000 requests


Server Software:        uvicorn
Server Hostname:        localhost
Server Port:            5000

Document Path:          /
Document Length:        17 bytes

Concurrency Level:      100
Time taken for tests:   9.480 seconds
Complete requests:      100000
Failed requests:        0
Total transferred:      14200000 bytes
HTML transferred:       1700000 bytes
Requests per second:    10548.50 [#/sec] (mean)
Time per request:       9.480 [ms] (mean)
Time per request:       0.095 [ms] (mean, across all concurrent requests)
Transfer rate:          1462.78 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    3   1.2      3      17
Processing:     0    7   3.6      6      50
Waiting:        0    5   3.1      5      49
Total:          1    9   3.8      9      53

Percentage of the requests served within a certain time (ms)
  50%      9
  66%      9
  75%     10
  80%     10
  90%     13
  95%     17
  98%     22
  99%     25
 100%     53 (longest request)
```

I know that benchmarks can be tricky but why in my local machine the result was so different from the results in the same test made by Tech Empower?

I've decided to check the code used in the benchmark and discovered that the Pyramid version along with all the other packages is very much outdated, this requirements.txt they use:

```
psycopg2==2.7.5
gunicorn==19.9.0
meinheld==0.6.1
SQLAlchemy==1.0.12
pyramid==1.6.1
pyramid_chameleon==0.3
greenlet==0.4.14
```
reference: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Python/pyramid/requirements.txt

Another interesting fact when running on my local machine is that if I use a custom Response using this `jsonify` function the performance jumps on Pyramid to 12K requests per second, code example:

```python
from json import dumps

def jsonify(payload):
    return Response(dumps(payload), content_type='application/json', charset='utf-8')

def hello_world(request):
    return jsonify({'hello': 'world'})
```

For bigger payloads being able to easily use ujson or python-rapidjson in Pyramid would also improve the performance (but this is another topic).

I would like to work on a pull request to update the version of the packages and the code (if necessary) to reflect the current state of the Pyramid framework and the best practices to create a scalable web app with Pyramid.

I think this would be also good marketing for the new Pyramid 2.0 release.

**Comment by mmerickel** [comment]
It's cool to see people doing benchmarks, thanks!

> Another interesting fact when running on my local machine is that if I use a custom Response using this jsonify function the performance jumps on Pyramid to 12K requests per second, code example:

It'd be helpful to know why the declarative renderer is so much slower than using `dumps()` directly. My guess is that it's to do with the renderer framework which is determining what to do with the dictionary returned from the view, but some profiling would be necessary.

> For bigger payloads being able to easily use ujson or python-rapidjson in Pyramid would also improve the performance (but this is another topic).

It is very easy to replace the json renderer in Pyramid with one that uses a different serializer. See https://docs.pylonsproject.org/projects/pyramid/en/1.10-branch/api/renderers.html#pyramid.renderers.JSON and https://docs.pylonsproject.org/projects/pyramid/en/1.10-branch/narr/renderers.html#adding-and-changing-renderers

> I would like to work on a pull request to update the version of the packages and the code (if necessary) to reflect the current state of the Pyramid framework and the best practices to create a scalable web app with Pyramid.

What do you want to do with this open issue? The changes you propose are nothing to do with this repository so I'm inclined to close it and encourage you to repost some this nice analysis to the mailing list and to improve the techempower benchmark.

**Comment by rudaporto** [comment]
@mmerickel first of all thanks for the quick answer.

> It's cool to see people doing benchmarks, thanks!

Thanks!

> > Another interesting fact when running on my local machine is that if I use a custom Response using this jsonify function the performance jumps on Pyramid to 12K requests per second, code example:
> 
> It'd be helpful to know why the declarative renderer is so much slower than using `dumps()` directly. My guess is that it's to do with the renderer framework which is determining what to do with the dictionary returned from the view, but some profiling would be necessary.

+1

> > For bigger payloads being able to easily use ujson or python-rapidjson in Pyramid would also improve the performance (but this is another topic).

> It is very easy to replace the json renderer in Pyramid with one that uses a different serializer. See https://docs.pylonsproject.org/projects/pyramid/en/1.10-branch/api/renderers.html#pyramid.renderers.JSON and https://docs.pylonsproject.org/projects/pyramid/en/1.10-branch/narr/renderers.html#adding-and-changing-renderers

You are right, this could be in another package.

> What do you want to do with this open issue? The changes you propose are nothing to do with this repository so I'm inclined to close it and encourage you to repost some this nice analysis to the mailing list and to improve the techempower benchmark.

I will do it anyway. The here ticket is more about how this affects Pyramid visibility as a high-performance web framework and how to coordinate efforts to help Pyramid to get better visibility.

The fact that not many people outside the bubble of Pyramid experienced developers knows about that and in the end, will never think about Pyramid when developing their services is the issue.

This may also be related to Documentation and Marketing to attract more users to Pyramid.

**Comment by rudaporto** [comment]
I've updated the version of Pyramid and other packages in the code used in the Benchmark and it was merged:

https://github.com/TechEmpower/FrameworkBenchmarks/pull/4819

I'm closing the ticket now.

**Comment by slav0nic** [comment]
i updated pyramid benchmarks, now its ~30-60% better in some tests

before (round 18) https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=json&l=zijzen-f
after (test) https://www.techempower.com/benchmarks/#section=test&runid=66ee924e-3bc2-4bd8-aaf0-2cd8443f65db&hw=ph&test=json&l=zijzen-f

but this benchs is really stupid things ;)
