### ISSUE TITLE
sqlalchemy integration & docs incorrect, upstream change coming

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#3504]
I'm posting this on the main pyramid tracker, but it concerns code in the pyramid docs and the pyramid cookiecutter.

The `naming_convention` in the starter template and pyramid docs which is sent to SqlAlchemy is "inadequate" and undergoing a change upstream.  I'm opening a ticket here now, just in case others experience this issue before the fix is released.

https://github.com/Pylons/pyramid-cookiecutter-starter/blob/latest/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/sqlalchemy_models/meta.py#L4-L13

The issue: using this setup will create errors in Sqlite and Mysql if the user declares a Boolean or Enum column. On these backends, SqlAlchemy generates a CHECK constraint to enforce the data type when the database is initialized; however the template for "ck_" requires a "constraint_name" to be provided.  Advanced users will know this can be declared in the column definition, but most users will not know this and just see an exception that is not very helpful.

A fix in SqlAlchemy and Alembic is underway

**Comment by stevepiercy** [comment]
Is there an issue in their repos to which we can add links in this issue?

**Comment by jvanasco** [comment]
sorry, @stevepiercy , I totally forgot to cross-reference.

The sqlalchemy one is here and will also cover alembic: https://github.com/sqlalchemy/sqlalchemy/issues/4784

**Comment by bertjwregeer** [comment]
When SQLAlchemy adds the updated list, we'll just have to grab it and stick it in the cookie cutter.

**Comment by stevepiercy** [comment]
...and the tutorials.

**Comment by mmerickel** [comment]
I don't think there's anything more to do here. There is a `ck_` convention defined in the template for the last few releases.
