### ISSUE TITLE
How to run Pyramid in production directly

### ISSUE THREAD

**Issue by ORESoftware** [Pylons/pyramid#3509]
Sorry for bombing the issue tracker, I have this question on SO:
https://stackoverflow.com/questions/57894461/run-python-pyramid-server-in-production-w-o-apache

basically, looking for a way to run Pyramid in production _without_ Apache.
If this is documented, I apologize, but I can't find it. Please let me know if there is a discussion forum where I can post the question instead of here since it's not really appropriate for an issue tracker, thanks.

**Comment by stevepiercy** [comment]
Please see https://trypyramid.com/documentation.html

**Comment by mmerickel** [comment]
Yep the cookbook has some recipes for various deployment options but Pyramid is just a wsgi app so almost any guide that you find can be adapted pretty easily to pyramid. I’d ask on the mailing list as well and we can help with that.

**Comment by ORESoftware** [comment]
@mmerickel @stevepiercy  conceptual speaking is there a way to run WSGI apps directly?  WSGI bindings can be invoked from within the same process right?  

I posted my question here:
https://groups.google.com/forum/#!forum/pylons-discuss
