### ISSUE TITLE
Feature Request- deprecate/remove PickleSerializer

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#3511]
This has basically already been decided to happen, but the timing is not clear.  I could not find the scheduled removal listed anywhere.

`[pyramid.session.PickleSerializer](https://github.com/Pylons/pyramid/blob/587fe72fae0efda3a860d37a1ea2449a41dab622/src/pyramid/session.py#L46-L70)` is the legacy session implementation and [not used by any actual code in Pyramid](https://github.com/Pylons/pyramid/search?q=PickleSerializer&unscoped_q=PickleSerializer).

It only exists in a test, docs and the changelog.  The code is simple enough that it could be consolidated into the narrative docs that invoke it.

If this is staying for a while to enable 3rd party libraries that require it, I suggest invoking a `warnings.warn`  on `PickleSerializer.__init__()` to have people upgrade.

If this does not need to stay, can it be removed sooner than later?   I keep nearly using it on a compatibility layer, and then I realize this will likely be gone soon.

**Comment by stevepiercy** [comment]
Did you see this?

https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/sessions.html#upcoming-changes-to-isession-in-pyramid-2-0

**Comment by jvanasco** [comment]
Yes.  The current source reflects those changes. This serializer class is only used in a test and is referenced by those docs (I actually linked to their source above).  That's why I think it could be removed is and those docs just incorporate the pickle loads.

**Comment by mmerickel** [comment]
I'd accept a PR to remove it.

I'd like to ship a 1.10 version with a few more things deprecated including pyramid.compat.

**Comment by jvanasco** [comment]
@mmerickel I am happy to generate a PR for this.  should it be against `master`, `1.10-branch` or something else?

**Comment by stevepiercy** [comment]
Please make changes to `master`. Optionally cherry-pick the same changes, if possible, to `1.10-branch` in a separate PR.

**Comment by mmerickel** [comment]
My suggestion is to just deprecate it in master and we'll remove it in a future release.
