### ISSUE TITLE
Overriding assets should provide some "fallback" feature

### ISSUE THREAD

**Issue by silenius** [Pylons/pyramid#3517]
Currently Pyramid provides the possibility to override asset(s) through `config.override_asset`, which works well. However there is no simple way to say globally _"override all templates from to_override with override_with only if template exists in override_with, otherwise fallback to to_override"_, (except by having one `config.override_asset` call per template, which is tedious).

A possible solution would be to add a `fallback=True|False`-like parameter to config.override_asset ..?

**Comment by mmerickel** [comment]
Maybe I am missing something here but when looking up an asset that falls into `config.override_asset()` does fallback properly right now. I think you'll need to paste a test case or something to prove what you're saying.
