### ISSUE TITLE
zope.sqlalchemy.ZopeTransactionExtension was deprecated and is gone in latest release

### ISSUE THREAD

**Issue by mgedmin** [Pylons/pyramid#3522]
The [latest release of zope.sqlalchemy](https://pypi.org/project/zope.sqlalchemy/1.2/#id1) (1.2) no longer has a ZopeTransactionExtension.  You're supposed to use the `register()` API instead.  See https://github.com/zopefoundation/zope.sqlalchemy/issues/31 for details.

Most of the tutorial examples in Pyramid documentation do that already, but docs/quick_tutorial/databases/tutorial/models.py is still using ZopeTransactionExtension and ought to be updated.

(It would also be very helpful if Pyramid's What's New docs were to mention this and explain to users what they should do to upgrade their existing Pyramid applications based on older tutorial versions.  Something similar to commit b30d448a0e5f42d4dc1f607158ceda52217d5cee I guess?)

**Comment by stevepiercy** [comment]
This was done in https://github.com/Pylons/pyramid/pull/3529 on `master` and backported to both `1.10-branch` and `1.9-branch` back on 11 Nov 2019.
