### ISSUE TITLE
Update docs to sync with https://github.com/Pylons/pyramid-cookiecutter-starter/pull/71

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3523]
With the PR Pylons/pyramid-cookiecutter-starter#71 we need to synchronize the files used in tutorials and docs for all steps.

**Comment by stevepiercy** [comment]
To kill two birds use Python 3.8, and update the output for all tutorials.

**Comment by mmerickel** [comment]
It's probably time to do this, pending the open PRs to the cookiecutter get merged. I don't see anything bw-incompat or out of date in the cookiecutter other than the pending PRs.

**Comment by mmerickel** [comment]
Well - we need to do https://github.com/Pylons/pyramid/issues/3522. Do you want to do it or should I?

**Comment by stevepiercy** [comment]
I can have a look tonight, and if I get stuck, I'll hand it over to you.

**Comment by mmerickel** [comment]
Don’t forgo your holidays!

**Comment by stevepiercy** [comment]
- The Pyramid Issue #3522 was already addressed.
- Previously open PRs in pyramid-cookiecutter-starter have been merged.
- I've opened a new [PR to drop support for 3.4 and add for 3.8](https://github.com/Pylons/pyramid-cookiecutter-starter/pull/74). If it passes, I'll merge it, then start work on this issue.
