### ISSUE TITLE
Build fails with latest Black v19.10b0

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3526]
On Oct 28th, `19.10b0` was released, which integrated a handful of changes.  Travis builds now fail.

_Originally posted by @jvanasco in https://github.com/Pylons/pyramid/pull/3524#issuecomment-549991735_

**Comment by stevepiercy** [comment]
See PR #3525

**Comment by mmerickel** [comment]
fixed via #3525
