### ISSUE TITLE
Update authn/authz tutorial

### ISSUE THREAD

**Issue by luhn** [Pylons/pyramid#3548]
`docs/quick_tutorial/authentication.rst` and `docs/quick_tutorial/authorization.rst` need to be updated for the new security policy.

Shoutout to @merwok for bringing this to light.

**Comment by stevepiercy** [comment]
Also please check the two wiki tutorials for any necessary revisions.

- `docs/tutorials/wiki2/authentication.rst`
- `docs/tutorials/wiki2/authorization.rst`
- `docs/tutorials/wiki/authorization.rst`

**Comment by stevepiercy** [comment]
Are we not going to update `docs/tutorials/wiki/authorization.rst` in Pyramid 2.0? It would need a champion for the stuff that requires thought, but I can at least do the tedious grunt work of synching up files with narrative docs.

It actually needs someone to overhaul it to demonstrate traversal more effectively. Maybe we open a separate issue for the traversal/zodb wiki altogether?

**Comment by mmerickel** [comment]
Steve look at the checklist in the other PR I’m working on. 

- Michael
