### ISSUE TITLE
Documentation refers to adding route and view in the one add_route call.

### ISSUE THREAD

**Issue by arterrey** [Pylons/pyramid#3551]
Documentation states:

> Add a route configuration to the current configuration state, as well as possibly a view configuration to be used to specify a view callable that will be invoked when this route matches

(https://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator.add_route)

However there is no reference to any view configuration that can be passed into `add_route` Furthermore, a the comment (https://github.com/Pylons/pyramid/issues/2852#issuecomment-265649243) on another issue indicates that this functionality was removed.

**Comment by stevepiercy** [comment]
@arterrey checking [git blame of the docstrings](https://github.com/Pylons/pyramid/blame/323cfbb45e6ee4b7462bbea9dcaa4e8258dd74f6/src/pyramid/config/routes.py#L46-L53), and that there are no "*view-related* types", I would say you found an artifact in the docstrings that needs to be updated.

Would you please submit a PR against the `master` branch?

**Comment by merwok** [comment]
Fixed by https://github.com/Pylons/pyramid/commit/c1e150d765e33d92ad4d6d5912207ce3ba20991e
