### ISSUE TITLE
Reify decorator part of Py 3.8?

### ISSUE THREAD

**Issue by jenstroeger** [Pylons/pyramid#3564]
Perhaps more of a question than feature request.

It looks to me like Python 3.8’s [`@functools.cached_property`](https://docs.python.org/3/library/functools.html#functools.cached_property) is similar to Pyramid’s [`@reify` decorator](https://github.com/Pylons/pyramid/blob/master/src/pyramid/decorator.py)? It probably makes little sense, though, to use Python’s implementation at this point (if available)…

**Comment by mmerickel** [comment]
I don't think it's gonna be worthwhile to replace those few lines of code with a conditional import. Thanks for pointing it out though.

I looked at it and it also uses a lock which is pretty interesting that they chose to do that - very unnecessary in the context of Pyramid.
