### ISSUE TITLE
Customized Form Rendering

### ISSUE THREAD

**Issue by saiftyfirst** [Pylons/pyramid#3569]
I was looking into rendering forms in pyramid. There is a basic example in the documentation that shows to access fields in html and render them in a more customized manner. 

![Screenshot from 2020-04-01 16-48-29](https://user-images.githubusercontent.com/32745785/78156802-916fb400-743f-11ea-8a64-a099b5a0d3f2.png)

What is missing in the example is how in such a case, a button can be rendered. Say the form has the same schema as the example. In addition, I would like to add a submit button to the form. How can I render the button without rendering the entire form again ?

https://docs.pylonsproject.org/projects/deform/en/latest/retail.html

**Comment by saiftyfirst** [comment]
Sorry, I will post in the deform repo

**Comment by mmerickel** [comment]
I don't have an answer for you but please post it to the pylons-discuss mailing list instead of on the issue trackers for usage questions - there's a broader audience there.
