### ISSUE TITLE
Pyramid Docs Site 403 Forbidden from cloudflare

### ISSUE THREAD

**Issue by gcarothers** [Pylons/pyramid#3574]
## Bug Report

**Describe the bug**
403s from all of docs.pylonsproject.org

**To Reproduce**
1. Go to 'https://docs.pylonsproject.org/'
2. See Error :(

**Expected behavior**
See documentation.

**Screenshots**
If applicable, add screenshots to help explain the issue.
![image](https://user-images.githubusercontent.com/118299/80031542-b4214580-849e-11ea-85be-38e1bb4e0a75.png)

**Comment by stevepiercy** [comment]
That is a not a valid URL. You need to specify a project in the URL:
https://docs.pylonsproject.org/projects/pyramid/en/latest/

**Comment by mmerickel** [comment]
Steve, your valid URL is not working.

**Comment by zyd14** [comment]
I too am having issues accessing any pyramid docs from docs.pylonsproject.org, although this also seems to extend to any project hosted there as I'm getting 403s from the other projects linked here as well: 
https://pylonsproject.org/projects.html

**Comment by stevepiercy** [comment]
Disk usage on the Marketing server crept up again.

```bash
spiercy@marketing:/tmp$ sudo du -sh *
<snip>
7.0G    tmp

spiercy@marketing:/tmp$ sudo rm -Rf /tmp/logwatch.*

spiercy@marketing:/tmp$ sudo systemctl restart nginx
```

...and we're back. Cloudflare in the message was misleading, as we have no services with them, but I assume RTD uses it and was merely passing along the 403 from our Marketing server to the user.

**Comment by russellballestrini** [comment]
Strange, just verifying your work, I still get a 403 this morning.

**Comment by dantoac** [comment]
for the record: https://www.theregister.co.uk/2020/04/16/cloudflare_outage/

**Comment by fyfe** [comment]
Cloudflare has a [FAQ](https://support.cloudflare.com/hc/en-us/articles/115003014512-4xx-Client-Error#code_403) for it not sure if it's any help, in this case the second section applies as the 403 error has the Cloudflare branding.

**Comment by stevepiercy** [comment]
We're working on it. See https://twitter.com/PylonsProject/status/1253465539512393729 and follow on Twitter for latest updates.
