### ISSUE TITLE
Release 2.0 alpha?

### ISSUE THREAD

**Issue by merwok** [Pylons/pyramid#3584]
It would be great to have a prerelease available on PyPI, to test things without having to clone and build from github source.

**Comment by mmerickel** [comment]
Yeah, there's one lingering issue with the authenticated_identity stuff that is preventing me from doing a release but also haven't had time to get into. I'm really sorry for how long it's taking. :-(

**Comment by olemoign** [comment]
Any news on this?

**Comment by mmerickel** [comment]
2.0a0 is out now
