### ISSUE TITLE
Why was --pid-file removed from pserve since 1.8

### ISSUE THREAD

**Issue by robvdl** [Pylons/pyramid#3595]
Before Pyramid 1.8, pserve had a --pid-file option, I was using this to work out if my dev instance had started up yet so that I could run CI.

Now with pserve being included in Pyramid (since 1.8 it seems), it looks like the argument --pid-file has been removed, why?

I can still use gunicorn --paste --pid, sure, but why remove --pid-file from the pserve command, can it be bought back?

**Comment by stevepiercy** [comment]
[Pyramid Change History](https://docs.pylonsproject.org/projects/pyramid/en/latest/changes.html#id14) explains.
