### ISSUE TITLE
Application not serving with pserve when apply gevent patching

### ISSUE THREAD

**Issue by thoongnv** [Pylons/pyramid#3606]
I'm doing a gevent spawn in specific view and I need patch first in __init__.py

```python
from gevent import monkey; monkey.patch_all()
```
When doing it, the application stop serving, although it work if I start with uWSGI. Here is the log

```bash
pserve --reload development.ini
```
```
Gracefully killing the server.
Starting monitor for PID 26927.
```

Ah, just figure out that if I skip --reload param, it worked well

Is there something wrong with pserve script? I actually want to check if __init__.py before patch_all, if I started the application with uWSGI or pserve(waitress) to make the decision to patching.

**Comment by mmerickel** [comment]
You need to patch the process before importing your app and any pyramid code. To do this you can use a custom server runner with pserve. If you do it later then the threading module is used for theeadlocals before it’s patched properly to work with greenlets.

**Comment by thoongnv** [comment]
@mmerickel You mean I need to patch in pyramid/scripts/pserve.py?, I see some server runners in it

```bash
def wsgiref_server_runner(wsgi_app, global_conf, **kw):
def cherrypy_server_runner
```

**Comment by mmerickel** [comment]
Sorry I can’t get into all of the details right now but it’s don’t externally via a paste server runner. They are registered via entry points in Python and are the same way that `use = egg:waitress` works in pyramids default cookie cutter examples. Gunicorn used to have one that did the right thing but I’m not positive it exists any longer.
