### ISSUE TITLE
isort 5.5.x crashes on tox -e lint

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3613]
With the release of isort 5.5.x, the lint and format jobs will fail. Example:
https://github.com/Pylons/pyramid/runs/1180227019#step:5:12

I have opened an [issue with isort](https://github.com/PyCQA/isort/issues/1505) to track the matter. We could temporarily pin to isort 5.4.2 or wait a while. They are usually rapid responders.

Ping @mmerickel @bertjwregeer

**Comment by bertjwregeer** [comment]
Looks like it was fixed based upon the upstream ticket?! Awesome!
