### ISSUE TITLE
Black v20.8b1 causes failing builds

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3614]
Black v20.8b1 causes failing builds. It now changes docstring formatting, where it removes a leading space: `""" docstring` => `"""docstring`

Should I create a PR with just Blackification of the code base on both `master` and `1.10-branch`? I would not want to interfere with pending PRs that would require a rebase by the contributor.

**Comment by mmerickel** [comment]
I think it's ok if you want to re-blackify in a separate PR.

**Comment by stevepiercy** [comment]
OK, I'll wait till the next release of isort in a couple of days.

**Comment by stevepiercy** [comment]
The maintainer released a hotfix due to another issue, so I done did a blackify, but there was a minor issue. [I manually fixed it, but that was one of three options](https://github.com/Pylons/pyramid/pull/3616#issuecomment-701167223).
