### ISSUE TITLE
Feature Suggestion: pre-commit integration for black

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#3618]
Since black formatting is timely with their new release, and has been headaches in the past...

Would you be interested in a PR to integrate the `pre-commit` hook and black?  I can set it up and update docs in the contributing file.

We use it on SqlAlchemy. Basically you specify the black version in a yaml file (https://github.com/sqlalchemy/sqlalchemy/blob/master/.pre-commit-config.yaml) and tie it to the black version in `tox.ini`

As the name implies... if developers use pre-commit when contributing, it automatically runs the version of black in a git hook before generating the commit message.  This has really cut down on issues when the CI and PR-Author's versions of black differ.

**Comment by stevepiercy** [comment]
I'm -0 on this proposal.

If the version of Black is pinned, I might not know that there has been a new release of it. When CI uses the latest release, it helps reveal mistakes, such as not using `-r` when running tox before pushing a PR. It also helps remind us to update our tools before the next release.

**Comment by jvanasco** [comment]
No worries. I illustrated it in a quick 2minute PR, but it would require a deep dive into the CI to make it pass.

**Comment by bertjwregeer** [comment]
I use pre-commit on various projects myself, but have so far resisted introducing it to Pylons projects. Everyone has their won workflow.

Also, I am with Steve in that we have explicitly not pinned a version of black, knowing that we will likely have to update our codebase as failures happen.

Also by having it in pre-commit and in tox we risk having them go out of sync, so either we'd want tox to run pre-commit or have pre-commit run tox.
