### ISSUE TITLE
Link to license on repoze.org is dead

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3621]
https://github.com/Pylons/pyramid/blob/ee7ca28cc51cf40d1190144834704e287c9fc72d/setup.py#L96

repoze.org is dead. It shows up on PyPI. Accordingly we need to do some housecleaning in all Pylons Project repos. Should we put the license on pylonsproject.org and link to it there?

https://pylonsproject.org/license.html

See also https://github.com/Pylons/venusian/issues/70

**Comment by stevepiercy** [comment]
The Pyramid license is really confusing with 5 licenses. I'm not sure what to do here. Maybe have Pyramid's license hosted at https://trypyramid.com/license.html ?

**Comment by bertjwregeer** [comment]
We can change that line to `"BSD-derived (Repoze)"` and call it good.

There is no need for it to be a link to any particular document. There is a `LICENSE` file that is included with all of our distributables.

**Comment by stevepiercy** [comment]
Closed by #3623, #3624, #3625
