### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3622]
## Feature Request

I think we should start officially supporting Python 3.9. It was added to pyenv in early October 2020, so we can run it locally now.

If you agree, I can put together the PR for all the necessary changes to docs, tox, etc.

**Comment by mmerickel** [comment]
Go for it.

**Comment by stevepiercy** [comment]
Should I backport support for 3.9 to either the `1.10-branch` or `1.9-branch`, if feasible? I can't remember for sure if our policy allows adding support to an already released major version. I recall we do not drop support.

**Comment by mmerickel** [comment]
I don’t mind either way. If you do the work it’s fine to merge in my mind.

**Comment by stevepiercy** [comment]
Note that I did not bump coverage to py39 because it resulted in a single line getting missed in coverage.

```
src/pyramid/config/actions.py                                             217      1    99.54%   317
```

Here's the line in context.

https://github.com/stevepiercy/pyramid/blob/d18c1eb95e8d492e5a9e17b6e2a447e1637ba204/src/pyramid/config/actions.py#L317

I have no idea why this works in 3.8.0 but not 3.9.0 locally, so I reverted to 3.8. Can you try to reproduce it?

**Comment by mmerickel** [comment]
I do not see any clues immediately in the 3.9 changelog, but that's a line that might just warrant a pragma no cover.

**Comment by stevepiercy** [comment]
I dug through Python 3.9 changelog and bug tracker, but [only one thing came up](https://bugs.python.org/issue39114) that might be related to the line number that coverage reports as missing, but I doubt it. [This issue in coverage](https://github.com/nedbat/coveragepy/issues/1041) looks very similar to what would happen by bumping coverage to 3.9.

I wish we had added 3.9-dev as an allowed failure in Travis to have some history. 3.10-dev is now available, so I'll add that as an allowed failure.

**Comment by stevepiercy** [comment]
Nevermind. [GitHub Actions does not support allowed failures](https://github.com/actions/toolkit/issues/399) in a way that is similar to Travis.

**Comment by stevepiercy** [comment]
I'm debating whether to add Python 3.7+ support to `1.9-branch`, given 2.0 is around the corner and it did not go well for the cookiecutter https://github.com/Pylons/pyramid-cookiecutter-starter/pull/98. I think it would be a lot of effort for very little benefit to a small audience. What do y'all think?

**Comment by mmerickel** [comment]
I think it's fine to not touch 1.9 unless you just can't help yourself. I haven't been planning to cut a new release of it.

**Comment by stevepiercy** [comment]
OK. 3.9 support on 1.10 and master (2.0) is good enough and provides a sensible upgrade path. I got bigger fish to fry.
