### ISSUE TITLE
Extending the RouteMapper?

### ISSUE THREAD

**Issue by jvanasco** [Pylons/pyramid#3640]
I have a few projects with hundreds of routes configured via url_dispatch 

It looks like we hit a number of routes where there is some room for performance improvements due to implementation details of the router. 

The "problem" is a regex match happens for every route in the [RoutesMapper.routeslist](https://github.com/Pylons/pyramid/blob/master/src/pyramid/urldispatch.py#L83-L90).  

Compared to other sections of Pyramid's code, the overhead on routes here is fairly negligible -- however I'm trying to squeeze performance everywhere I can, and this route matching looks like a good candidate.

The two ideas I had:

* declare high-traffic routes earliest. this would solve most issues, but makes maintenance confusing and difficult

* extend the RoutesMapper to enable developers to optimize this 

The current Pyramid code allows for the entire RoutesMapper to be replaced via `config.registry.registerUtility(mapper, IRoutesMapper)` but I think that is a bit too dangerous for this purpose - as I just want to optimize a small bit of code.

A potential way to help people optimize this, would be to replace this line in RoutesMapper

    - for route in self.routelist:

with something like:

    + for route in self.routelist_optimized(path):

This would require extending the IRoutesMapper with an `routelist_optimized` method, which just returns all routes by default.  This could be overridden on the application's __init__ 

    mapper = config.registry.getUtility(IRoutesMapper)
    mapper.routelist_optimized = {{override}}

Admittedly, this is not a perfect solution - which is why I am bringing it up for discussion.

1. The RoutesMapper does not have a config/registry, so it can't invoke getUtility itself - which would have been better.
2. This doesn't allow for improving predicate matching

FWIW, the general usage case i profiled that led to improvements:

* on startup, batch routes into buckets based on the first path component
* `routelist_optimized(path)` returns only the routes within that first path component

On an application with over 500 routes, this made the route matching section of our application irrelevant.

Thoughts?

**Comment by mmerickel** [comment]
Pyramid has a pretty strict decision that routes are ordered by the application and not by the framework so this change would likely be breaking that assumption. Other than that, the RouteMapper is still a private API in Pyramid. At least at this time I don't feel like we should change anything to help with that until there's a robust, improved, version that we might want to crib features from or use wholesale in core. As you know you can replace it entirely in your apps, and that still seems like the right answer to me.

**Comment by jvanasco** [comment]
> As you know you can replace it entirely in your apps, and that still seems like the right answer to me.

Honestly, I did not think of that at all.  It seemed more like a dangerous side-effect of the registry system - not like a conscious design choice.

100% agreed this is the right approach. Thank you for your time and setting me straight!
