### ISSUE TITLE
Extra `**kw` in wiki tutorial?

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3647]
I'm not sure if this is an actual issue, but I'm opening it just in case. PyCharm issued a code inspection warning while I was working through the authentication and authorization steps in the wiki tutorial.

Under [Add ACL support](https://docs.pylonsproject.org/projects/pyramid/en/master/tutorials/wiki2/authorization.html#add-acl-support), there is a `**kw` parameter for both `remember` and `forget`.

```
    def remember(self, request, userid, **kw):
        return self.authtkt.remember(request, userid, **kw)

    def forget(self, request, **kw):
        return self.authtkt.forget(request, **kw)
```

However neither of these methods in the class `AuthTktCookieHelper` support arbitrary kwargs. https://github.com/Pylons/pyramid/blob/master/src/pyramid/authentication.py#L1116

I'm not absolutely sure, but I think we want to remove `**kw` from these methods. Please let me know.

**Comment by mmerickel** [comment]
Just stop forwarding the kwargs. Make it `self.authtkt.forget(request)`.

**Comment by stevepiercy** [comment]
Should I also remove them from the method signatures, resulting in the following?

```
    def remember(self, request, userid):
        return self.authtkt.remember(request, userid)

    def forget(self, request):
        return self.authtkt.forget(request)
```

**Comment by stevepiercy** [comment]
I don't see the usefulness of keeping kwargs in the signature when they are not used within the method. Is there a reason to keep them in the signature?

**Comment by mmerickel** [comment]
The only reason is if you want to accept stuff you don't support so that the user/library invoking it can be agnostic to which policy they are using. I don't care either way but technically the signature is `**kw` which is why I didn't change it in my suggested edits above.

**Comment by stevepiercy** [comment]
Thanks for the explanation. Agnosticism had not occurred to me, and that makes sense now. I've restored the kwargs in https://github.com/Pylons/pyramid/commit/b0dd658429367dd5e3cd99973bcc9a6763dcc5e7.

I'm still confused on one point though. To which signature do you refer? In the wiki app:

```
class MySecurityPolicy:
    def __init__(self, secret):
        self.authtkt = AuthTktCookieHelper(secret)

# snip

    def forget(self, request, **kw):
        return self.authtkt.forget(request, **kw)
```

...which I assumed was this method in the class `AuthTktCookieHelper` that does not have the kwargs:

https://github.com/Pylons/pyramid/blob/837358ee6be552fd2f990d1ed8d6ea9e1c98d583/src/pyramid/authentication.py#L1116-L1120

What did I miss?
