### ISSUE TITLE
Adaptation code structure to Pylince static analyze

### ISSUE THREAD

**Issue by SowingSadness** [Pylons/pyramid#3653]
I think static analyze is very important for development. I will be happy if Pylance can detecting at least main properties of framework.

https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/
![image](https://user-images.githubusercontent.com/576443/105639835-6b624700-5e8b-11eb-8b34-5f9cbaa14ac9.png)

**Comment by stevepiercy** [comment]
Is this issue already addressed in #2638?

**Comment by SowingSadness** [comment]
> Is this issue already addressed in #2638?
Both issue have same propose — type hinting. But this one do not require to drop Python 2 because Pylance can detect type as by annotation as by returned value using static analyze value of.
What way developers wish to use i don't know. May will they decide to use annotation way.

**Comment by bouillon** [comment]
+10 for this. 
Without type-hints pyramid has not future :-D

**Comment by mmerickel** [comment]
Hey I'm all for adding type hints but need someone with more experience there to support it than me! We have https://github.com/Pylons/pyramid/issues/2638 and don't support python 2 anymore so I'm closing this issue in favor of that one.
