### ISSUE TITLE
Sphinx doesn't like the reify decorator

### ISSUE THREAD

**Issue by Natim** [Pylons/pyramid#3655]
> Failed to get a method signature for kinto.core.resource.Resource.timestamp: <pyramid.decorator.reify object at 0x7f175ae45640> is not a callable object

If I understand correctly this is because the reify decorator doesn't pass along the function signature.

**Comment by luhn** [comment]
The problem here is that a reify'd property isn't callable—`@reify` has the same API as `@property`.  So Sphinx is looking for a callable object (not sure why, I don't know what your docs look like), but gets something that looks like a property.

**Comment by Natim** [comment]
Yes but it is missing some things that property is doing (__doc__, __annotation__, etc). If figured out a fix in #3656.
