### ISSUE TITLE
Missing HTTP Teapot response

### ISSUE THREAD

**Issue by jenstroeger** [Pylons/pyramid#3666]
I think this is not a bug per se, but kind of a missing feature: I noticed that the [httpexceptions](https://github.com/Pylons/pyramid/blob/master/src/pyramid/httpexceptions.py) module misses the [error response 418, I’m a Teapot](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418) and I’m curious why that is and whether you’d be open to adding it ☺️

**Comment by mmerickel** [comment]
Absolutely open to adding it. Sorry for ruining your April fools (maybe)!

**Comment by jenstroeger** [comment]
Great 👍🏼 Want a PR?

**Comment by mmerickel** [comment]
Yes please

**Comment by russellballestrini** [comment]
LMAO, do it!

**Comment by jenstroeger** [comment]
I’m looking forward to next year’s April. PR https://github.com/Pylons/pyramid/pull/3667.

**Comment by jenstroeger** [comment]
Closing, was merged.
