### ISSUE TITLE
threading.Thread.setDaemon has been deprecated in favor of setting daemon attribute directly in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [Pylons/pyramid#3676]
https://github.com/Pylons/pyramid/blob/8061fce297cc7117d3e6e2b39e47512c7db2904f/src/pyramid/scripts/pserve.py#L234

Ref : python/cpython#25174

**Comment by stevepiercy** [comment]
@tirkarthi thank you for the report. Would you please submit a PR with a fix? There are dozens of fixes linked to that issue to choose from.

**Comment by ztane** [comment]
`.setDaemon` is a Python 2.*5* compatibility thing. :D
