### ISSUE TITLE
How to create a custom permission

### ISSUE THREAD

**Issue by noahsalvadordenjo** [Pylons/pyramid#3682]
Hi https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#protecting-views explains how to use a permission, but how do we create the 'add' permission?

**Comment by mmerickel** [comment]
Please post usage questions to the mailing list at pylons-discuss@googlegroups.com.

The security policy above has a `permits()` method that receives the permission - it is the responsibility of this method to handle the permission and determine the access. Often this is abstracted using the ACLHelper. You'll see lots of examples of this in the tutorials.

**Comment by luhn** [comment]
You don’t need to “create” a permission, per se, you can use any arbitrary string and then update your `ISecurityPolicy.permits` method to Allow/Deny appropriately based on that permission.  See the next section:  https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#allowing-and-denying-access-with-a-security-policy <https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/security.html#allowing-and-denying-access-with-a-security-policy>

That method uses “read”, “write”, “delete”, but you could swap “add” in there as well.

(It is a bit confusing that we aren’t consistent with permission names throughout the tutorial…)

— Theron

**Comment by luhn** [comment]
Whoops, didn't even realize this was Github and not the mailing list...
