### ISSUE TITLE
Supported PyPy and Python versions in GitHub Actions

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid#3684]
On the `master` branch (and possibly other supported branches), we got a build failure.

https://github.com/Pylons/pyramid/pull/3683

The supported versions of Python and PyPy depend on which OS versions we want to test on. Here's our current testing matrix on `master`:

https://github.com/Pylons/pyramid/blob/8061fce297cc7117d3e6e2b39e47512c7db2904f/.github/workflows/ci-tests.yml#L16-L47

And here are available OSes:

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

We test using `<os>-latest`, but that label can shift when new OSes are released. That can result in versions of Python and PyPy that Pyramid supports getting dropped, such `macos-latest` dropping `pypy-3.6` by virtue of `pypy3` in the above PR.

To address this issue, I propose that we do the following in GHA:

1. When we make a major or minor release of Pyramid (1.10 and 2.0), we support only those versions of Python and PyPy that are available upon at that time for testing on GitHub Actions. We should avoid using `*-latest` in GHA and pin versions.
2. For `master`, we include `*-latest` to detect releases of new OSes, Python, and PyPY, as well as dropping of the same. When a Python or PyPy version that we want to support in an upcoming release is dropped from `*-latest`, then we add those specific dropped versions of Python and PyPy using a supported OS (such as `ubuntu-18.04`) in the matrix. Note that macOS currently uses the label `macos-latest` for `macos-10.15`, even though `macos-11` is available. This will allow us to more easily manage what we want to support when we cut a new release of Pyramid.

@mmerickel @bertjwregeer I'd appreciate your comments on these two implementation changes.

**Comment by stevepiercy** [comment]
p.s.:
- [Python 3.6 is EOL on 2021-12-23](https://devguide.python.org/#status-of-python-branches).
- [PyPy 3.6 stopped getting support on 2021-04-08](https://www.pypy.org/posts/2021/04/pypy-v734-release-of-python-27-and-37.html).

**Comment by mmerickel** [comment]
I have pinned macos-11, windows-2022, and ubuntu-20.04 in 1.10-branch, 2.0-branch, and master so we can mark this closed for now
