### ISSUE TITLE
getargspec and formatspec were removed in Python 3.11

### ISSUE THREAD

**Issue by tirkarthi** [Pylons/pyramid#3688]
https://github.com/Pylons/pyramid/blob/0b24ac16cc04746b25cf460f1497c157f6d3d6f4/docs/conf.py#L395-L398

https://docs.python.org/3.11/whatsnew/3.11.html#removed

> the getargspec function, deprecated since Python 3.0; use inspect.signature() or inspect.getfullargspec() instead.
> the formatargspec function, deprecated since Python 3.5; use the inspect.signature() function and Signature object directly.

**Comment by stevepiercy** [comment]
@tirkarthi thank you for the report. Would you please submit a pull request with a suggested change? The pull request should be made against both `master` and `2.0-branch`, as those are the versions that dropped Python 2 support.

**Comment by ztane** [comment]
@stevepiercy I guess this is something that could be easily compatted for previous version too.

**Comment by stevepiercy** [comment]
@ztane it could, but I think we avoid adding a new version of Python to support for already released versions of Python. I think it's at the discretion of @mmerickel.

At the other end, we have a policy against removing supported older versions of Python at https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/upgrading.html#python-support-policy. I think it would be good to include what we do about adding new versions of Python to support.

**Comment by mmerickel** [comment]
I don't think there's any compatibility concerns here because it only affects the docs. We can just make the switch as we expect the docs to only compile on python 3 at this point via our rtd config.
