### ISSUE TITLE
Pshell uses `!=` to figure out which objects are overridden in environment. `!=` does not work with every object and therefore `is not` is better

### ISSUE THREAD

**Issue by ztane** [Pylons/pyramid#3705]
I had a curious problem: I had thrown an object that was wrapped in a lazy object proxy added into the `pshell` environment. It had worked just recently but for some reason stopped working here merely due to updates in either Python version or some of the libraries. The error thrown was `AttributeError: __wrapped__` on this line.

I am not exactly sure how to minimally reproduce but [this pull request](https://github.com/Pylons/pyramid/pull/3704) fixed it. It is very unlikely that this would lead to a change in behaviour to the worse as it is not very likely that the user would override an object for which equality test would be true and identity test be false, **and** the user would **want to persist the docstring of the previous object and not use that of the override :D**

**Comment by LogiFarmer** [comment]
Nice tip
