### ISSUE TITLE
Logger for SQLAlchemy in `Quick Tutorial Chapter 19: Databases Using SQLAlchemy` seems to be wrong

### ISSUE THREAD

**Issue by ckaipf** [Pylons/pyramid#3706]
When I worked through the `Quick Tutorial Chapter 19: Databases Using SQLAlchemy`, I did not get the documented log information in the console when running `$VENV/bin/initialize_tutorial_db development.ini`.

Changing the logger from `sqlalchemy.engine.base.Engine` to `sqlalchemy.engine.Engine` in `development.ini` solved it for me.

**Comment by stevepiercy** [comment]
Nice catch! I can replicate the issue.

Would you like to submit a pull request with the changes? There are 3 places in `development.ini` where `sqlalchemy.engine.base.Engine` occurs, plus the documentation itself with an updated logging output.

**Comment by ckaipf** [comment]
Sure, it is my first, I hope I did everything right.
Thanks for the great tutorial!
