### ISSUE TITLE
Convert datetime objects in urlencode to ISO 8601

### ISSUE THREAD

**Issue by potkae** [Pylons/pyramid#3709]
## Bug Report

**Describe the bug**

When encoding URLs pyramid converts query parameters to strings: https://github.com/Pylons/pyramid/blob/1e439035e41da3767acbcae79689fb05dfdeb317/src/pyramid/encode.py#L73
If there is a datetime object in the query, the value is not outputted in ISO 8601 format. This produces validation issues when using with Openapi. 

**To Reproduce**

Try creating a url with datetime query parameter using urlencode method.
Or just try with python console: 
```
from datetime import datetime
date = datetime.fromisoformat("2019-01-01T00:10:00+00:00")
date
Out[4]: datetime.datetime(2019, 1, 1, 0, 10, tzinfo=datetime.timezone.utc)
datetime.isoformat(date)
Out[5]: '2019-01-01T00:10:00+00:00'
'%s' % date
Out[6]: '2019-01-01 00:10:00+00:00'
```

**Expected behavior**

Datetime values are converted to strings as ISO 8601 format.

**Comment by mmerickel** [comment]
urlencode is not attempting to encode arbitrary python objects. Only strings too url-safe strings. The most serialization it will do is invoke `str()`. If you want to serialize arbitrary objects you can define and supply your own quote_via arg to urlencode. Establishing a pattern of serializing arbitrary objects is a slippery slope that requires frameworking like what is supported by the JSON renderer’s add_adapter pattern. https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/renderers.html#using-the-add-adapter-method-of-a-custom-json-renderer
