### ISSUE TITLE
context matching in views and inheritance (traversal)

### ISSUE THREAD

**Issue by silenius** [Pylons/pyramid#3714]
Hello,

given 2 ressources and a @view_config:

```python
class A:
    ...

class B(A):
    ...

@view_config(context=A, name='foo')
def foo():
    ...
```

is there a way to match /someB/foo to A foo() if /someB/foo resolves to context B, but no @view_config(context=B, name='foo') has been defined (but as B is a child of A it could matches foo() registered on A) ?

Thanks

**Comment by mmerickel** [comment]
Your example should invoke the foo view for a context of your B and name=foo. Do you have a full example where it does not?

**Comment by silenius** [comment]
Sorry for late reply, you're right, it was a mistake on my side
