### ISSUE TITLE
License link to "Repoze Public License" seems dead in `README.rst`

### ISSUE THREAD

**Issue by sidkshatriya** [Pylons/pyramid#3716]
In `README.rst` of the https://github.com/Pylons/pyramid repo it says:

> Pyramid is offered under the BSD-derived [Repoze Public License](http://repoze.org/license.html).

The link does not seem accessible when I tried to access it.

Ideally whatever license pyramid is offered should be bundled with the repository and not an external link. 

There is a `LICENSE.txt` in the https://github.com/Pylons/pyramid repository but its not clear whether this is the same "Repoze Public License" mentioned in `README.rst`.

**Comment by bertjwregeer** [comment]
@mcdonc do you still own repoze.org? Should we add it to our existing list of domains? We can get a website setup for it as well if necessary?

**Comment by mcdonc** [comment]
I do own it. I can make sure that link resolves properly. I don't think there's a y reason to do more than that.

**Comment by mcdonc** [comment]
The link at http://repoze.org/license.html is now fixed.
