### ISSUE TITLE
Scaffolds are not W3C valid

### ISSUE THREAD

**Issue by pppierre** [Pylons/pyramid#373]
When you create a new application with "pcreate -t alchemy " command, you obtain a "mytemplate.pt" template which is not a XHTML 1.0 strict valid page. To do so, you have to encapsulate `<input>` tags in a `<div>` tag.

Similarly, the code added by pyramid_debugtoolbar is far from valid. In particular, it uses unknown `<h7>` tag.

I thing it would be a good think if all scaffolds and generated HTML pass the W3C validity test with success.

**Comment by stevepiercy** [comment]
All four scaffolds are now HTML5 compliant on master and 1.6-branch, per https://github.com/Pylons/pyramid_jinja2/commit/a77543a0083f8dc4fae6399468a1265f716cf8cc. I didn't try 1.5-branch. I did not validate debug_toolbar due to previous comments from @bertjwregeer. Closing.
