### ISSUE TITLE
view_page view in wiki tutorial too hard for newcomers to python

### ISSUE THREAD

**Issue by wichert** [Pylons/pyramid#410]
I have seen several people get completely stuck in the tutorial on the view_page view: the use of a subsitution function with a regular expression is something that many people do not understand, and they get stuck on that instead of looking at the pyramid bits.

I would suggest to either replace that with something completely trivial, or move the substitution code out to a helper function with a nice docstring that says 'dark magic here that is not pyramid-related' and keep the view function itself small and understandable.

**Comment by mmerickel** [comment]
I don't think the closure is an issue. Basic knowledge of Python is required by Pyramid one way or another. Please submit a PR with changes and we can re-evaluate then but until that time this has been open 2.5 years with no one interested in doing the work.
