### ISSUE TITLE
Improve SQLAlchemy tutorial (wiki2) according to paulo docs punchlist

### ISSUE THREAD

**Issue by mcdonc** [Pylons/pyramid#482]
Keeping track of sqlalchemy tutorial new user confusion issues at  https://docs.google.com/document/d/1u127sxnxBmQ7viOkjNeTP-yTlGs_0AmFUH8CKuGXLpc/edit?pli=1

**Comment by mmerickel** [comment]
I think the wiki2 tutorial updates in https://github.com/Pylons/pyramid/pull/2024 have drastically improved on this and addressed almost all of the comments.
