### ISSUE TITLE
Trim down the current set of docs to a more manageable length.

### ISSUE THREAD

**Issue by gjhiggins** [Pylons/pyramid#541]
Currently they weigh in at over 700 printed pages. Ideally they'd weigh in at about 500 or so. Those 500 pages would concentrate on very core concepts; more esoteric material would be relegated to other places (maybe the Cookbook or one or more other sets of supplemental documentation). Wordsmith core concepts documentation to be less didactic and easier to read.

**Comment by pauleveritt** [comment]
While I agree with the original goal, I think we've proven in the 3 years since the ticket opened that we're note going to do this all in one shot. We did, however, make a "Quick Tutorial" that gave a surface treatment on the major topics. Closing this.
