### ISSUE TITLE
Less minimal quick start application

### ISSUE THREAD

**Issue by gjhiggins** [Pylons/pyramid#548]
Lead off with a less minimal quick start application, and describe each component briefly while doing so. The current "firstapp.rst" chapter uses a very minimal application configured imperatively. Instead we should use a less minimal application configured using decorators. (MO: Please keep the hello app somewhere because the Pyramid/Pylons guide refers to it as an example of a minimal app.)

**Comment by pauleveritt** [comment]
While we don't "lead off" with it in the docs proper, the Quick Tutorial is a part of the docs proper, so let's consider this itch scratched.
