### ISSUE TITLE
Describe deployment strategies in a more concrete manner.

### ISSUE THREAD

**Issue by gjhiggins** [Pylons/pyramid#564]
For example, describe deploying with waitress, then describe deploying with gunicorn, then with mod_wsgi.

**Comment by pauleveritt** [comment]
I think we've proven (via 4 months of inaction) in this ticket the wisdom of not committing the official docs to *more* work. I'm closing this ticket. It can be re-opened as a new ticket in the Pyramid Cookbook repo.
