### ISSUE TITLE
For consideration: an API to start / teardown a request context

### ISSUE THREAD

**Issue by wichert** [Pylons/pyramid#596]
When writing console scripts you often need a configured pyramid, which is handled by pyramid.paster.bootstrap. Sometimes you need more than that though: you also need a fully configured request context. For example to get transaction handling or other things provided by tweens, or to have extra request properties setup. A possible API for that would be something like:

```python

environment = bootstrap(config_file)
with environment['request-context']:
    # Do my thing
```

where the request context would setup the tweens, issue INewRequest, etc. on `__enter__` and do all the necessary teardown on `__exit__`.

**Comment by mmerickel** [comment]
I just ran across this issue and it should be mostly solved at this point. The main feature is that request methods and properties are now attached properly which replaces most uses of the `NewRequest` event.

For a long-running script it's possible now to build a registry using the building blocks of bootstrap (bootstrap itself is coupled to a single request, but the building blocks are not).

```python
app = pyramid.paster.get_app(inipath)
registry = app.registry

for job in jobs:
    req = Request.blank(...)
    env = pyramid.scripting.prepare(registry=registry, request=request)
    env['closer']()
```

Using this method you can load the app once and re-use it across several dummy requests. You are still responsible for defining your own pipeline however, including invoking any events you care about and managing transactions.

If you really need to simulate a request with a full router lifecycle (tweens and events) then `prequest` is a good option or you can define your logic in a pyramid view, sending your request through the router.

```
def your_worker_view(request):
    # do some work

config = Configurator()
config.include(your_app)
config.add_view(your_worker_view, name='worker1234')
app = config.make_wsgi_app()

req = Request.blank('worker1234', ...)
response = req.get_response(app)
```
