### ISSUE TITLE
Confusion regarding @view_config return value usage

### ISSUE THREAD

**Issue by wichert** [Pylons/pyramid#666]
I have an existing view function that I am trying expose for another object as well. The original is defined like this:

``` !python
@view_config(route_name='celebrity-style-link-search', context=CelebrityStyle,
        renderer='json', permission='authenticated')
def link_search(context, request):
    ....
```

To expose it for a different class as well I tried to call view_config directly:

``` !python
magazine_link_search = (view_config(route_name='magazine-page-link-search',
        context=MagazinePage, renderer='json', permission='authenticated')
        (link_search))
```

That result in an error that the view conflicts with itself:

```
pyramid.exceptions.ConfigurationConflictError: Conflicting configuration actions
  For: ('view', <class 'customer.site.model.magazine.MagazinePage'>, '', None, <InterfaceClass pyramid.interfaces.IView>, None, None, None, 'magazine-page-link-search', None, False, None, None, None, None)
    ('/home/wichert/Work/customer.admin/src/customer/admin/ui/magazine.py', 149, '<module>', '(link_search))')
    ('/home/wichert/Work/customer.admin/src/customer/admin/ui/magazine.py', 149, '<module>', '(link_search))')
```

This appears to be due to the assignment. If I rewrite the code to remove the assignment to this:

``` !python
(view_config(route_name='magazine-page-link-search',
        context=MagazinePage, renderer='json', permission='authenticated')
        (link_search))
```

thinks work normally. I do not understand why this would break since I am only calling view_config once here. Is this a venusian bug?

**Comment by pauleveritt** [comment]
@wichert I'm doing some housecleaning, is this ticket still worth keeping open?

**Comment by wichert** [comment]
I do see some value in keeping this open, albeit at a very low priority.

**Comment by mmerickel** [comment]
If this is really an issue then it should be reported to venusian. If someone does this we can close the issue here.

**Comment by mcdonc** [comment]
With much trepidation and much shame, and little research, I close this issue due to the above comment four years ago.
