### ISSUE TITLE
Text highlight is broken in the PDF documentation

### ISSUE THREAD

**Issue by antoneliasson** [Pylons/pyramid#667]
In version 1.3.2 of http://media.readthedocs.org/pdf/pyramid/1.3-branch/pyramid.pdf, no text in the code boxes is highlighted. What should look like this (html version in Firefox 14.0.1): http://i.imgur.com/Wpdlm.png
looks like this (pdf in Evince 3.4.0 with libpoppler 0.18.4 in Ubuntu 12.04): http://i.imgur.com/1LJjx.png

**Comment by dietmarw** [comment]
> I've opened an issue there.
> https://bitbucket.org/birkenfeld/sphinx/issue/1238/support-emphasize-lines-in-pdf-output
This has now moved to https://github.com/sphinx-doc/sphinx/issues/1238

**Comment by stevepiercy** [comment]
@tseaver I want to keep this open, so I remember to resolve it when pygments, then sphinx, resolves it. I might need to make some adjustments.

**Comment by stevepiercy** [comment]
This was finally resolved 2017-12-11:
https://github.com/sphinx-doc/sphinx/issues/1238#event-1382285342

**Comment by stevepiercy** [comment]
Too soon. This was fixed in Sphinx 1.6.6, but RTD is still using 1.6.5, so reopening.

**Comment by stevepiercy** [comment]
Tracking the issue here: https://github.com/rtfd/readthedocs.org/issues/4015

**Comment by stevepiercy** [comment]
Closed by #3271
