### ISSUE TITLE
view_execution_permitted does not work with URL dispatch

### ISSUE THREAD

**Issue by rbu** [Pylons/pyramid#673]
I am using URL dispatch with a configuration similar to this:

``` py
...
    config.add_route('admin_main', '/admin')
...
@view_config(route_name='admin_main',
             permission='ADMIN',
             renderer='admin_main.jinja2')
class AdminMainView(object):
    ...

```

To test whether to show the admin link I have used the `view_execution_permitted` function like so:
`view_execution_permitted(request.context, request, 'admin_main')`

I am not using a resource tree, so context simply is a RootFactory instance.

Expected result:
- The function returns Denied when the authenticated user does not have the admin permission

Actual result:
- The function returns Allowed because the view is not found.

While this related to the Allowed/Denied default discussed in #299, this issue is about the fact that the view cannot be found. This view lookup works (in my setup):

``` py
        request_iface = reg.queryUtility(IRouteRequest, name=name)
        provides = [IViewClassifier, request_iface, providedBy(context)]
        view = reg.adapters.lookup(provides, ISecuredView, name='')
```

**Comment by tisdall** [comment]
@garyvdm - thanks for that code...  I'm still confused about what `name` is.

**Comment by mmerickel** [comment]
@tisdall You can almost always ignore name during url dispatch and expect it to be an empty string. It's the path segment after the context of the url in traversal. So the only time it may not be empty is if you have some custom `traverse=` arg to your route.
