### ISSUE TITLE
Development mode server kills itself on syntax errors

### ISSUE THREAD

**Issue by dwt** [Pylons/pyramid#681]
Hi there,

I've noticed an annoying feature of the development mode of pyramid, that is, it's server kills itself if it encounters a syntax error.

While that is certainly safe, what I think it should really do is just try again after the next file change (that usually fixes the syntax error....).

**Comment by domenkozar** [comment]
I've opened https://github.com/Pylons/pyramid/pull/2044 as a possible solution.
