### ISSUE TITLE
Enhance pshell to support the new ipython notebook interface

### ISSUE THREAD

**Issue by bassio** [Pylons/pyramid#690]
I wonder if it is possible to tweak the pshell so that it allows you to start it in an ipython notebook.

As someone who uses the pshell command frequently for debugging my app, it would be great to do this in the new ipython notebook, right there in my browser where I can go back and forth and change stuff around without limitations of a console.

Can be done?

**Comment by mmerickel** [comment]
Pyramid 1.6 has grown support for pshell entry points which may be useful here. Regardless notebook support won't be going into Pyramid core unless someone tries to integrate things in some way where core support is required so I'm going to close it.
