### ISSUE TITLE
xhr view predicate not behaving as documented

### ISSUE THREAD

**Issue by sbrauer** [Pylons/pyramid#729]
As I read the view config docs, if a view config doesn't explicitly set xhr to True, then (assuming the rest of the predicates are satisfied) that view should match a request without even checking if the request is an XMLHttpRequest.

I'm finding that XHR requests are only matching views where xhr=True.
Put another way, if the view config doesn't specify the xhr parameter, an XHR will never match.

If this is indeed a bug as I suspect, then one fix would be to change pyramid.config.predicates.XHRPredicate.**call**() to:

```
def __call__(self, context, request):
    if self.val:
        return bool(request.is_xhr)
    else:
        return True
```

One drawback of this proposed fix is that a view configured with xhr=False would match requests that are XHR requests, which behaves according to the docs (again, as I read them) but may not match developer expectations.
Maybe both the docs and behavior should change such that xhr can be None (the default, meaning XHR doesn't matter for the view config) or True or False (meaning that XHR does matter, and must be True or False). 

By the way, my use case is to configure some web service views using the accept predicate.  As long as the request accepts the mimetype I'm serving, I don't care whether the request was initiated via AJAX or some other means.  Currently to make this work I have to configure the view twice: once with xhr=True and again with xhr=False.

**Comment by iainctduncan** [comment]
Sorry to review an old thread, did this fix make it into a release? I seem to be having a similar issue but it's three years later now so I could be wrong here. thanks!
