### ISSUE TITLE
pserve --reload with --daemon

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid#912]
I'm not sure if this is supposed to work, but tizoc in #pyramid claimed it may be a problem. If this is supposed to work we should verify that it does. If it is not supposed to work (which I think would be fine) we should add an error message when trying to execute `pserve` with both options enabled.

**Comment by piotr-dobrogost** [comment]
From what I see --reload does not work with --daemon in Pyramid 1.4.5
What's preventing @mmerickel's fix from getting merged?

**Comment by mcdonc** [comment]
My $.02: I'd rather get rid of ``--daemon`` and ``--stop-daemon`` than trying to make ``pserve`` a full-blown process manager or add complexity to make daemon-stopping work with ``--monitor-restart``.  Very good process managers already exist and pserve doesn't really need to do their jobs.

That said, if @mmerickel wants to merge the patch, I'd be fine with it.

**Comment by mmerickel** [comment]
I'm a big fan of removing `--daemon` but it may be controversial.

Side note: my fix is something I would not consider production ready due to the infinite loop caused by saving a file with broken code while `--monitor-restart` is active.

**Comment by bertjwregeer** [comment]
I'd be all for removing `--daemon`. I never understood why we try to be everything with `pserve`. Then again, I run on top of `uWSGI`.
