### ISSUE TITLE
Support for function annotations in view functions

### ISSUE THREAD

**Issue by danielholmstrom** [Pylons/pyramid#977]
pyramid.config.util.takes_one_arg uses inspect.getargspec. This will fail if the callee has python3 function annotations. In that case inspect.getfullargspec should be used.

I have a patch, but it's missing tests since a test with function annotations will crash on python2.

Patch: danielholmstrom/pyramid@b63192f

pyramid.tests.test_config.test_util.Test_takes_one_arg test:

    def test_with_function_annotations(self):
        def foo(foo: 'annotation'):
            """ """
        self.assertTrue(self._callFUT(foo))

**Comment by mmerickel** [comment]
Closed by merging #1556.
